### ISSUE TITLE
Бага в ярости

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1003]
![image](https://user-images.githubusercontent.com/42086238/127905066-1cd51f3a-2c18-4fc5-beba-8e7b8db96ae3.png)
но не всегда

**Comment by bylins** [comment]
и почему-то удинение по раундам не работает

**Comment by vkhanayev** [comment]
Аффекты от умения ярость суммировались после каждого применения, после исправления аффекты суммироваться уже не будут.
Схожий эффект можно получить даже без релога (чтобы сбросить откат на применения ярости), просто по откату нажима ярость.
