### ISSUE TITLE
Расширение в квестах

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1005]
Билдеры просят сделать возможность давать квесты или с ограниченным временем выполнения, или ограничением времени на частоту выполнения.

**Comment by bylins** [comment]
Как я это вижу, делаем думми апплай APPLY_INQUEST
используем его поля нестандартно
af.modifier = будет уникальный номер квеста (ну например номерзоны+номермоба, чтоб незапутаться) это выставляет билдер, хардкод думаю ненужен
af.duration = соответственно нужную билдеру длительность.
Билдер всегда в триггере может проверить, сколько игроку осталось времени на выполнение, или когда он сможет взять квест заново.

**Comment by bylins** [comment]
Тут вижу правда одну тонкость, аффект без спелла спадать не умеет.
Хотя может и умеет, у нас 2 типа аффектов 
указывается в af.location, делал лет 6 назад подробности не помню

**Comment by bylins** [comment]
Хотя время, сколько еще висеть аффекту из триггеров узнать нельзя, только проверить наличие аффекта.

**Comment by vkhanayev** [comment]
походу изменений никаких вообще не нужно. Пример скрипта:

**wait 1
eval current_time %date.unix%

if !%actor.quested(6300)%
    say Привет, я вижу тебя первый раз
    %actor.setquest(6300 %current_time%)%
    halt
end

eval last_visit %actor.getquest(6300)%
eval time_diff (%current_time%-%last_visit%)
say Последний раз ты был у меня %time_diff% секунд(ы) назад
end**

**Comment by bylins** [comment]
перенесено в примеры в описании DG
