### ISSUE TITLE
Косяки с умениями чармисов

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#1039]
Некоторые умения чармисы не могут применять находясь в бою, например - **подножка, метнуть**
Причем вне боя нормально работает:
2031H 138M 34986465о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все подн холо
Странствующая воительница ловко подсекла усталого черниговского холопа, уронив его на землю.
Ладушки.
А **в бою** нет:
2031H 140M 34986465о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все уб хол
Усталый черниговский холоп поднялся.
Странствующая воительница ОЧЕНЬ БОЛЬНО рубанула усталого черниговского холопа.
Ладушки.
2031H 140M 34986407о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все подн холо
Ладушки.
2031H 140M 34986407о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все подн холо
Ладушки.
2031H 140M 34986407о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все подн холо
Ладушки.
2031H 140M 34986407о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все подн холо
Ладушки.
2031H 140M 34986407о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ> прик все подн холо

Удар усталого черниговского холопа прошел мимо странствующей воительницы.
Удар усталого черниговского холопа прошел мимо странствующей воительницы.
Странствующая воительница БОЛЬНО рубанула усталого черниговского холопа.
Странствующая воительница БОЛЬНО рубанула усталого черниговского холопа.
Странствующая воительница ОЧЕНЬ БОЛЬНО рубанула усталого черниговского холопа.
Странствующая воительница БОЛЬНО рубанула усталого черниговского холопа.
2031H 140M 34986196о Зауч:0 Пз:0 Пх:0 29L 294594G Вых:СВЮЗ>  
поковырявшись немного в коде умений, возможно не проходим проверку тут:
https://github.com/bylins/mud/blob/8af85135bc661836a160c08f3695299a4b438b6d/src/skills/chopoff.cpp#L152-L158
c метнуть дело то же:
https://github.com/bylins/mud/blob/8af85135bc661836a160c08f3695299a4b438b6d/src/skills/throw.cpp#L209-L217

вообще на некоторые умения захардкожено вот так, почему то:
```С++
	if (IS_NPC(ch) || !ch->get_skill(SKILL_MULTYPARRY)) {
		send_to_char("Вы не знаете как.\r\n", ch);
		return;
```
обидно как-то, иногда надо поуклоняться, или парри прожать играя в соло за кудеса...(если допустим моб к примеру !глуш и тому подобное)
https://github.com/bylins/mud/blob/8af85135bc661836a160c08f3695299a4b438b6d/src/skills/kick.cpp#L154-L157
https://github.com/bylins/mud/blob/ea5c6e723d0874d9ad58b5149247265383cd3e79/src/skills/styles.cpp#L95-L98
https://github.com/bylins/mud/blob/8af85135bc661836a160c08f3695299a4b438b6d/src/skills/protect.cpp#L22-L37

**Comment by vkhanayev** [comment]
подножка и метнуть должно уже работать.

насчет уклона и парирования для чармисов - мне кажется это перебор, тем более изменение затронет и купцов, а им и так хватит плюшек уже.

**Comment by hikopol** [comment]
да работает, и на этом спасибо.
