### ISSUE TITLE
Опять чармисы, глуш без двуруча и оружия

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1083]
гг Зурис прик всем оглуш каме
Вы сообщили группе : 'Зурис прик всем оглуш каме'

1475H 142M 515467948о Зауч:0 ОЗ:0 Пз:5 Пх:0 30L 191029G Вых:ВЮЗ>  

Зурис отдал приказ.
Удалой наемничек своим оглушающим ударом сбил каменного истукана с ног.
Удалой наемничек медленно появился из пустоты.
Каменный истукан медленно появился из пустоты.
Удалой наемничек СМЕРТЕЛЬНО ударил каменного истукана.

1475H 142M 515467948о Зауч:0 ОЗ:0 Пз:5 Пх:0 30L 191029G Вых:ВЮЗ>  

Зурис медленно появился из пустоты.
Меткий бросок Зуриса заставил каменного истукана застонать от боли.

1475H 142M 515467948о Зауч:0 ОЗ:0 Пз:5 Пх:0 30L 191029G Вых:ВЮЗ>  
0

Зурис ОЧЕНЬ БОЛЬНО сокрушил каменного истукана.
Удалой наемничек УБИЙСТВЕННО ударил каменного истукана.
Каменный истукан скончался мгновенно после сильнейшего удара удалого наемничка.
Каменный истукан мертв, его душа медленно подымается в небеса.
вз все все.труп
Ваш опыт повысился на 6399 очков.
Кровушка стынет в жилах от предсмертного крика каменного истукана.

1475H 142M 515461549о Зауч:0 ОЗ:0 Пз:5 Пх:0 30L 191029G Вых:ВЮЗ>  
0
Труп каменного истукана пуст.

1475H 142M 515461549о Зауч:0 ОЗ:0 Пз:5 Пх:0 30L 191029G Вых:ВЮЗ>  
см удалой
 * Он будет служить вам силой и честью...
Удалой наемничек невредим, стоит.

Удалой наемничек одет :
<правый указательный палец> кольцо посыльного *чармис* ..голубая аура!
<левый указательный палец>  кольцо могучего воина *чармис* ..голубая аура!
<на шее>                    зуб василиска *чармис* ..желтая аура!
<на груди>                  зуб василиска *3 хит 11 дам 10 здор чармис* ..голубая аура! ..желтая аура!
<на теле>                   доспех Безграничного Послушания *чармис* ..голубая аура!
<на голове>                 повязка Безграничного Послушания *чармис* ..голубая аура!
<на ногах>                  черные шипастые поножи *чармис* ..голубая аура!
<на ступнях>                сапоги Безграничного Послушания *чармис* ..голубая аура!
<на кистях>                 перчатки Безграничного Послушания *чармис* ..голубая аура!
<на руках>                  зеленые лесные наручи *чармис* ..голубая аура!
<на плечах>                 туманный панцирь предков *чармис* ..голубая аура!
<на поясе>                  фартук мясника *чармис* ..голубая аура!
<на правом запястье>        четки из слоновой кости *2 сила 3 хит 6 дам чармис* ..голубая аура! ..желтая аура!
<на левом запястье>         четки из слоновой кости *2 хит 8 дам 2 сила чармис* ..голубая аура! ..желтая аура!

**Comment by hikopol** [comment]
ну они же могут без оружия глушить, как мобы, хз бага или фича это?

**Comment by vkhanayev** [comment]
чармисы больше не смогут, т.к. это больше похоже на баг.
обычные мобы продолжат глушить как и раньше.
