### ISSUE TITLE
пропажа вещей из кланхрана[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#111]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Jan 10 06:23:09 :: Extracting obj сверкающие змеиные перчатки vnum == 91835 timer == 0  
а сообщения нету в кланлоге

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/111

**Comment by Svjatovit** [comment]
А точно есть баг?

**Comment by bylins** [comment]
не жаловались болдьшще
