### ISSUE TITLE
не срабатывают триггеры на мобов

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1117]
из того что заметил: command и speech триггеры не срабатывают, если их пытается активировать моб. возможно есть еще какие-то, но я не знаю.

**Comment by Svjatovit** [comment]
В большинстве случаев они и не должны срабатывать. Как правило, билдеры ставят в начале проверку на внум (-1), т.е. работает толко для игрока. Уверен, что в том триггере такого нет и не срабатывает именно на уровне кода?
