### ISSUE TITLE
Косяк с базаром

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1134]
562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> инв
Вы несете:
костяное кольцо лучника  <великолепно> 
кожаный заплечный короб  <великолепно>  (пуст)
переметная сума  <великолепно>  (есть содержимое)

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> 

Аукцион : лот 0(трактат о невыносимом ужасе пустоты), 100000 кун, ЧЕТЫРЕ!!!!

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б выст коль 500
Вы выставили на базар костяное кольцо лучника (лот 898) за 500 кун.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б пред мои
 Лот     Предмет                                                     Цена  Состояние
--------------------------------------------------------------------------------------------
[  16]   сердце молодого разбойничка                                  200  скоро сломается

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б инф 898
Лот 898. Цена 500
Предмет "костяное кольцо лучника",  тип БРОНЯ
Можно надеть на палец.
Состояние: нерушимо.

Вы не сможете пользоваться этой вещью.
Продавец 

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б куп 898
Это же ваш лот. Воспользуйтесь командой 'базар снять <лот>'

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> 

Сильный ветер.
Дождь утих.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> 

Минул час.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> 

Аукцион : лот 0(трактат о невыносимом ужасе пустоты), 100000 кун, ПЯТЬ!!!!!

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б снять 898
Вы сняли костяное кольцо лучника с базара.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б выст коль 500
Вы выставили на базар костяное кольцо лучника (лот 898) за 500 кун.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б пред мои
 Лот     Предмет                                                     Цена  Состояние
--------------------------------------------------------------------------------------------
[  16]   сердце молодого разбойничка                                  200  скоро сломается

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б фильтр нет
Новый фильтр пуст.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> б пред мои
 Лот     Предмет                                                     Цена  Состояние
--------------------------------------------------------------------------------------------
[  16]   сердце молодого разбойничка                                  200  скоро сломается

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> 

Аукцион : лот 0(трактат о невыносимом ужасе пустоты), 100000 кун - ПРОДАНО.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ> 
[system] Ошибка: Некорректный набор параметров. [#savelog]
[system] Лог 1(1).html сохранен.

На востоке показались первые солнечные лучи.
Умеренный ветер.

562H 271M 6602372о Зауч:0 ОЗ:0 Пх:0 Уд:0 27L 5390G Вых:СВЮЗ>

**Comment by Zhadan87** [comment]
Кроме того, что не отображаются мои новые лоты, не могу снять старые( 16 в данном случае) - пишет, что не мой лот. Этого перса недавно пересоздал, с таким же именем. Может базарные лоты старого перса как-то не удалились? И из-за этого новые мне не показываются

**Comment by bylins** [comment]
Новый чар с тем же именем не равен старому, и это правильно. Старые лоты рассыпятся по таймеру 2 недели.

**Comment by Svjatovit** [comment]
Привязка лотов по идее не по имени должна идти, а по иду чара.
