### ISSUE TITLE
очень странный баг

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1155]
load mob 100
load mob 100
атак ск
убить ск
Вы попытались ударить скелета - неудачно.
[скелет:Невредим] > Вы обратили скелета в прах! Взглядом! Одним!
attach wtr 99831 199
атак ск
убить ск

Trigger 99831 (подавляем выход из игры, ренту и врата) attached to room 199.

Вы попытались ударить скелета - неудачно.
[скелет:Невредим] > Вы не можете это сделать в бою.
и вот это выдается на каждую команду с подсоединенным триггером, вот текст:
Name: 'подавляем выход из игры, ренту и врата',  VNum: [99831], RNum: [ 8493]
Trigger Intended Assignment: Rooms
Trigger Type: Command, Numeric Arg: 100, Arg list: *
Commands:
   eval cm %cmd.mudcommand%
   if %cm% == конец || %cm% == quit || %cm% == постой || %cm% == rent || %cm% == предложение || %cm% == offer || %cm% == поселиться || %cm% == settle
     %send% %actor% куда это вы собрались? сначала покиньте арену, так то!
   elseif %cm% == врата
     %send% %actor% вы попытались открыть врата, но не смогли.
     %echoaround% %actor%   %actor.name% попытал%actor.u% открыть врата, но ничего из этого путного не вышло.
   else
     return 0
   end
и проблема скорее всего связана именно с триггером, так как если использовать имскую невидимость, то баг пропадает.

**Comment by Daniil-Gusev** [comment]
скорее всего это как-то связано с * в аргументе, так как когда в arguments я поставил не *, а что-то другое, обновил зону, и все заработало корректно в бою.

**Comment by bylins** [comment]
короче если висит такой триггер на комнате с аргументом * в бою чара клинит
работает только иммкоманда invis
причем введеная полностью, после этого естественно расклинивает
