### ISSUE TITLE
str.words str.car str.cdr

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1174]
посмотреть максимальное количество обрабатываемых символов, указать в учебнике по dg_script

**Comment by bylins** [comment]
car cdr принимают
unsigned char: 0...255

**Comment by bylins** [comment]
half_chop обрезает до MAX_INPUT_LENGTH непонятно зачем ведь там можно sizeoff делать  
```
	} else if (!str_cmp(field, "words")) {
		int n = 0;
		// Подсчет количества слов или получение слова
		char buf1[MAX_TRGLINE_LENGTH];
		char buf2[MAX_TRGLINE_LENGTH];
		buf1[0] = 0;
		strcpy(buf2, vd->value);
		if (*subfield) {
			for (n = atoi(subfield); n; --n) {
				half_chop(buf2, buf1, buf2);
			}
			strcpy(str, buf1);
		} else {
			while (buf2[0] != 0) {
				half_chop(buf2, buf1, buf2);
				++n;
			}
			sprintf(str, "%d", n);
		}

```

**Comment by vkhanayev** [comment]
Никаких ограничений не нашел. В теории car и cdr могут работать со строками произвольной длины (ограничено тока размером size_t, но все равно это очень много). Да и строки такой длины скорее и не нужны, т.к. они явно больше ограничения на вывод и максимальной длины строки в триггере.

**Comment by bylins** [comment]
Вова я исправил закрываю

**Comment by bylins** [comment]
там веселуха в  half_chop
