### ISSUE TITLE
дополнение счета

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1181]

**Comment by Daniil-Gusev** [comment]
сделать вариант комады счет, которая будет выводить статистику персонажа списком а не таблицей.

**Comment by bylins** [comment]
Вых:СВЮЗ> сч спи
Вы Верий, русич, волшебник, язычник, уровень 30, перевоплощений 29.
Ваша возраст: 252, размер: 50(50), рост: 180(180), вес 128(128).
Вы можете выдержать 1585(2269) единиц повреждений, и пройти 142(142) версты по ровной местности.
Ваша сила: 39(39), ловкость: 38(38), телосложение: 42(48), ум: 51(63), мудрость: 54(50), обаяние: 45(59).
Попадание: -3, повреждение: 28, запоминание: 595, успех колдовства: 389, удача: 29.
Сопротивление: огню: 25, воздуху: 35, воде: 50, земле: 5, тьме: 34, живучесть: 30, разум: 30, иммунитет: 30.
Спас броски: воля: 173, здоровье: 58, стойкость: 255, реакция: 273, маг.резист: 15, физ.резист 15, отчар.резист: 0.
Восстановление: жизни: +60% (+104), сил: +0% (+32).
Броня: 78, защита: -15, поглощение 0.
Вы имеете кун: на руках: 124363, на счету 15711319. Гривны: 130, опыт: 1879999999, ДСУ: 1.
Ваша позиция: Вы стоите.
Вы можете быть призваны.
Голоден: нет, жажда: нет.
Вы поставили рунную метку в комнате: 'В думной гридне', она продержится еще 30 часов
