### ISSUE TITLE
новое событие в dg

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1183]
каст на комнату
в комнате использовали заклинание, направленное на комнату.

**Comment by bylins** [comment]
Andrey Стрибог, [06.11.2021 22:48]
Ямщик отдыхает здесь. 

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> колд !молн! ямщи
Вы произнесли заклинание "молния".
Бабабабах!!!

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю>

----------------------------------------------------------------------------

Andrey Стрибог, [06.11.2021 22:49]
962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> колд !метеор до
Вы произнесли заклинание "метеоритный дождь".
Повинуясь вашей воле несшиеся в неизмеримой дали громовые камни обрушились на землю.

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> 

Раскаленные громовые камни рушатся с небес!
Бабабабах!!!

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> 

Раскаленные громовые камни рушатся с небес!
Бабабабах!!!

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> 

Раскаленные громовые камни рушатся с небес!
Бабабабах!!!

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> 

Последний громовой камень грянул в землю и все стихло.

962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю>


-----------------------------------------------

Andrey Стрибог, [06.11.2021 22:49]
962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> колд !суд бого
Вы произнесли заклинание "суд богов".
Вы сплели руки в замысловатом жесте, и все потускнело!
Бабабабах!!!

---------------------------------------------------

Andrey Стрибог, [06.11.2021 22:51]
962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> колд !chai l! ямщ
Вы произнесли заклинание "цепь молний".
Вы подняли руки к небу и оно осветилось яркими вспышками!
Бабабабах!!!
Макс. целей: 9, Каст: 76, Уровень заклинания: 29.

----------------------------------------

Andrey Стрибог, [06.11.2021 22:52]
return 1
962H 179M ??? Зауч:0 ОЗ:0 34L 57136313G Вых:Ю> колд !chai l! ямщ
Вы произнесли заклинание "цепь молний".
Вы подняли руки к небу и оно осветилось яркими вспышками!
Бабабабах!!!
Ямщик поднялся.
Одна из ваших молний не оставила и следа от ямщика.
Ямщик мертв, его душа медленно подымается в небеса.

**Comment by Daniil-Gusev** [comment]
с такой реализацией походу и не особо нужно новое событие, закрываю.
