### ISSUE TITLE
странное в стат чара

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1187]
stat дремир
Защитн.аффекты: [Para:-175/Breath:-145/Spell:-268/Basic:-265], Поглощ: [70], Стойк: [348], Реакц: [313], Воля: [209]
выводится не все и почему савинги больше -100 ??
какой-то бред

**Comment by bylins** [comment]
stat верий
Защитн.аффекты: [Para:-180/Breath:-60/Spell:-268/Basic:-327], Поглощ: [0], Стойк: [306], Реакц: [355], Воля: [241]

**Comment by Svjatovit** [comment]
Настакали как-то?

**Comment by bylins** [comment]
этго починили
