### ISSUE TITLE
Бага в тортилле? или в былинах

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1190]
коцеп ра; кледя раз
----------^ пробел
1752H 93M 199121о Зауч:0 ОЗ:0 Пз:6 Пх:0 Вр:10 6L 17754G Вых:ВЮ> 
колд !оцепе! ра
 кледя раз
Вы произнесли заклинание "оцепенение".
Вы занесли заклинание "оцепенение" в свои резы.
Сумасшедший разбойник замер на месте!
1752H 94M 199121о Зауч:0:02 ОЗ:0 Пз:6 Пх:0 Вр:10 6L 17754G Вых:ВЮ> 
Чаво?
1752H 94M 199121о Зауч:0:00 ОЗ:0 Пз:6 Пх:0 Вр:10 6L 17754G Вых:ВЮ> 
--------------------------------------------------------------------------------------------------------------------------------------------
коцеп ра;кледя раз  - без пробела
1752H 94M 199121о Зауч:0 ОЗ:0 Пз:6 Пх:0 Вр:10 6L 17754G Вых:ВЮ> 
колд !оцепе! ра
колд !ледя прик! раз
Вы произнесли заклинание "оцепенение".
Вы занесли заклинание "оцепенение" в свои резы.
Ваши потуги оказались напрасными.
1752H 94M 199121о Зауч:0:02 ОЗ:0 Пз:6 Пх:0 Вр:10 6L 17754G Вых:ВЮ> 
Вы произнесли заклинание "ледяное прикосновение".
Вы занесли заклинание "ледяное прикосновение" в свои резы.
Сумасшедший разбойник вскрикнул от боли, когда вы прикоснулись к нему.
----------------------------------------------------------
или все таки у нас skipspace не работает????

**Comment by bylins** [comment]
чурюпаха явно не развернуло макрос

**Comment by garkins** [comment]
да на самом деле черепаха все прально сделала. ведь алиас с пробелом и без пробела разные вещи

**Comment by bylins** [comment]
Абсолютно не согласен
1. жаба не понимает если после ; нет пробела.
2. после точки с запятой это новая команда введеная якобы в промте, т.е. skipspace никто не отменял.
3. а разве можно забиндить алиас у которого первый символ пробел?
PS прикольно. реально можно, пробел знаковый в промте. Будем считать фичей.

**Comment by bylins** [comment]
но все таки первые пробелы немного не согласованы с мадами.
мад скипает все пробелы в начале строки команды, это делают все, а не только былины, ты больше путаешь игрока такой возможностью, а вот алиас с первым символом пробел и его необходимость крайне спорна. Приведешь пример заткнусь.

**Comment by gmax79** [comment]
пробел в алиасе есть, так что он и будет подставлен. на то он и алиас, клиенту невозможно корректно решить - нужен пробел или не нужен. не нужен пробел уберите его после точки с запятой.... и похоже мад не скипает пробелы в начале, но это уже сам сервер решает, как ему нужно

**Comment by bylins** [comment]
каждый arg в интерпретер скипает пробелы в начале строки, заботится о телнете?
пробела в алисе нет, жаба требует после ; пробел иначе проигнорирует. это въелось в подкорку.
3 еще раз вопрос, придумай нужный алиас с пробелом в начале строки.
у тебя твой промт съест
![image](https://user-images.githubusercontent.com/42086238/140989972-a0d3676b-6b30-4fda-bf1b-6ca6d0127465.png)

![image](https://user-images.githubusercontent.com/42086238/140990059-924281e0-4d4c-4291-8487-767146d4752e.png)

**Comment by bylins** [comment]
мад убрал, зачем ты незначащие пробелы оставляешь знаковыми не знаю

**Comment by bylins** [comment]
мне то все равно, но возможно это одна из причин почему перенесенный из жабы тригги не пашут

**Comment by bylins** [comment]
PS skipspace функция циркуля, не былин, съедает все пробелы в начале строки.
думаю во всех мадах такое.

**Comment by gmax79** [comment]
черепаха не убирает алиас, т.к она не знает что хочет игрок... может ему нужен пробел, и мад такой... по логике сам сервер должен заботится об этом...  игрок то в момент игры может и руками пробелы нажимать без алиасов

**Comment by bylins** [comment]
мы говорим про вариант после ;
это мад не обрабатывает, только клиент

**Comment by bylins** [comment]
см лог выше, первый, твой клиент не смог распарсить алиас

**Comment by bylins** [comment]
беспредметный разговор. я у себ проблему решил.
но жаба требует пробела после ; иначе вообще не воспринимает

**Comment by bylins** [comment]
Любой мадсервер удаляет незначащие пробелы в начале строки при получении команды. Можно не спорить, наверно для исключения команд от корявых клиентов.
Т.е. то что ты при отсылке команды и ее интерпретации их оставляешь - ошибка., нагружающая сервер на парс строк.

**Comment by bylins** [comment]
см skip_spaces в  коде сервера и ее использование.

**Comment by bylins** [comment]
void skip_spaces(T string) {
	for (; **string && isspace(**string); (*string)++);
}
превессти?
