### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1198]
=================================================================
==250738==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x55a0b5d63fa7 in operator new(unsigned long) (/home/stribog/mud/build/circle+0x107dfa7)
    #1 0x55a0b60e8197 in determineFeaturesSpecification() /home/stribog/mud/src/feats.cpp:608
    #2 0x55a0b5ea40f9 in boot_db() /home/stribog/mud/src/db.cpp:2285
    #3 0x55a0b5da970a in stop_game(unsigned short) /home/stribog/mud/src/comm.cpp:783
    #4 0x55a0b5da95ab in main_function(int, char**) /home/stribog/mud/src/comm.cpp:757
    #5 0x55a0b5da81c1 in main /home/stribog/mud/src/main.cpp:4
    #6 0x7f862c2bd0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x55a0b5d63fa7 in operator new(unsigned long) (/home/stribog/mud/build/circle+0x107dfa7)
    #1 0x55a0b60e8299 in determineFeaturesSpecification() /home/stribog/mud/src/feats.cpp:616
    #2 0x55a0b5ea40f9 in boot_db() /home/stribog/mud/src/db.cpp:2285
    #3 0x55a0b5da970a in stop_game(unsigned short) /home/stribog/mud/src/comm.cpp:783
    #4 0x55a0b5da95ab in main_function(int, char**) /home/stribog/mud/src/comm.cpp:757
    #5 0x55a0b5da81c1 in main /home/stribog/mud/src/main.cpp:4
    #6 0x7f862c2bd0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x55a0b5d63fa7 in operator new(unsigned long) (/home/stribog/mud/build/circle+0x107dfa7)
    #1 0x55a0b60e86dd in determineFeaturesSpecification() /home/stribog/mud/src/feats.cpp:653
    #2 0x55a0b5ea40f9 in boot_db() /home/stribog/mud/src/db.cpp:2285
    #3 0x55a0b5da970a in stop_game(unsigned short) /home/stribog/mud/src/comm.cpp:783
    #4 0x55a0b5da95ab in main_function(int, char**) /home/stribog/mud/src/comm.cpp:757
    #5 0x55a0b5da81c1 in main /home/stribog/mud/src/main.cpp:4
    #6 0x7f862c2bd0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x55a0b5d63fa7 in operator new(unsigned long) (/home/stribog/mud/build/circle+0x107dfa7)
    #1 0x55a0b60e85db in determineFeaturesSpecification() /home/stribog/mud/src/feats.cpp:646
    #2 0x55a0b5ea40f9 in boot_db() /home/stribog/mud/src/db.cpp:2285
    #3 0x55a0b5da970a in stop_game(unsigned short) /home/stribog/mud/src/comm.cpp:783
    #4 0x55a0b5da95ab in main_function(int, char**) /home/stribog/mud/src/comm.cpp:757
    #5 0x55a0b5da81c1 in main /home/stribog/mud/src/main.cpp:4
    #6 0x7f862c2bd0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 52 byte(s) in 1 object(s) allocated from:
    #0 0x55a0b5d629f8 in realloc (/home/stribog/mud/build/circle+0x107c9f8)
    #1 0x7f862c8bb5e6  (/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4+0x3e5e6)

**Comment by Svjatovit** [comment]
Хм... там создаются "наборы предметов" с которыми можно выполнить скилл (в данном случае - бросок". Видимо, накосячил. Не сильно страшно, оно один раз при старте мада вызывается, но надо пофиксить.

**Comment by Svjatovit** [comment]
Исправлено.
