### ISSUE TITLE
Какой-то говнокод

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1202]
Nov 18 14:54:50 :: SYSERR: Format error in trg file 33.trg near trg #-1
Nov 18 14:54:50 :: SYSERR: ... offending line: '~'

dg_olc.cpp  2952 какой-то говнокод
![image](https://user-images.githubusercontent.com/42086238/142411973-cab30d01-cabe-4d16-aee5-ab6a5fc59844.png)
как результат
![image](https://user-images.githubusercontent.com/42086238/142412022-7c696125-176f-435f-b228-494af571739b.png)

**Comment by bylins** [comment]
Чо он делает и почему строки * Empty script нет?

**Comment by bylins** [comment]
без перевода строки ошибка и мад не грузится

**Comment by vkhanayev** [comment]
@bylins 
Надо поправить содержимое 33.trg в world.test.tgz на "$~"

Верхняя тильда с текущем варианте (как на скриншоте) явно лишняя, похоже она осталось от предыдущего триггера который не до конца вырезали.
Проблем в коде на нашел - думаю сам файл в примерах неправильный.
