### ISSUE TITLE
Арена доминирование

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1212]
тут пишем недостатки и баги

**Comment by bylins** [comment]
в персхран нельзя положить именную шмотку

**Comment by bylins** [comment]
Увеличить перхран

**Comment by bylins** [comment]
Не пересчитывается MAX_HIT при адвансе до 30 левела
копать
void check_max_hp(CHAR_DATA *ch) {

**Comment by hikopol** [comment]
1. при повторном входе на арену (рестарт арены) сохраняються временные заклинания полученые раннее, соответсвенно их можна применять.
2. знамя не пуржит сданые останник, соответвенно они забивают ему инвентарь.
3. проблема с чармисами невозможно сагрить чужого чармиса (умка, наемник и тд.) - тут скорее всего проблема с боевой системой, ибо их нельзя сагрить и не на арене...
4.  кудесу скелиться магия до 1000% соответвсенно, перк хозяин животных создает дисбаланс (либо максить магию / умения участвующих - до сответвстия 20 морта)

**Comment by bylins** [comment]
> * при повторном входе на арену (рестарт арены) сохраняються временные заклинания полученые раннее, соответсвенно их можна применять.
ну рестарт арены это нерасчитанная ситуация
> * знамя не пуржит сданые останник, соответвенно они забивают ему инвентарь.
> * проблема с чармисами невозможно сагрить чужого чармиса (умка, наемник и тд.) - тут скорее всего проблема с боевой системой, ибо их нельзя сагрить и не на арене...
по полному имени агрятся, кто-то просил и сделали
> * кудесу скелиться магия до 1000% соответвсенно, перк хозяин животных создает дисбаланс (либо максить магию / умения участвующих - до сответвстия 20 морта)
или поправь свой говнокод :)

**Comment by hikopol** [comment]
> > * при повторном входе на арену (рестарт арены) сохраняються временные заклинания полученые раннее, соответсвенно их можна применять.
> >   ну рестарт арены это нерасчитанная ситуация
> > * знамя не пуржит сданые останник, соответвенно они забивают ему инвентарь.
> > * проблема с чармисами невозможно сагрить чужого чармиса (умка, наемник и тд.) - тут скорее всего проблема с боевой системой, ибо их нельзя сагрить и не на арене...
> >   по полному имени агрятся, кто-то просил и сделали
> > * кудесу скелиться магия до 1000% соответвсенно, перк хозяин животных создает дисбаланс (либо максить магию / умения участвующих - до сответвстия 20 морта)
> >   или поправь свой говнокод :)

ну а смыл давать все умения по 1000% если всех уравняли до 20 морта, тогда и выдать всем умешки-магию соответвсенно..
Ну способность нормально работает расчитана же на магию а не на морты, ток в реальносте ты никогда не будешь иметь 1000% да и даже близкие значения к 350 крайне редки, что то я не вижу кудесов 50 мортов пока)

**Comment by bylins** [comment]
> ну а смыл давать все умения по 1000% если всех уравняли до 20 морта, тогда и выдать всем умешки-магию соответвсенно..
> Ну способность нормально работает расчитана же на магию а не на морты, ток в реальносте ты никогда не будешь иметь 1000% да и даже близкие значения к 350 крайне редки, что то я не вижу кудесов 50 мортов пока)

а если ты с 50го морта опускал? вообще-то там должен сработать кап по максумению и мудрости. Почему у тебя не срабатывает смотри, не ту функцию взял

**Comment by Daniil-Gusev** [comment]
знамя не пуржит сданые останник, соответвенно они забивают ему инвентарь.
там пуржило, но не все. щас вроде исправил.

**Comment by bylins** [comment]
[01-12-21 20:09:01][ WARNING: Unset out of slots feature 'привычка к яду' for character 'Ухмыл'! ]
[01-12-21 20:09:01][ WARNING: Unset out of slots feature 'любимое оружие: голые руки' for character 'Ухмыл'! ]
[01-12-21 20:09:01][ WARNING: Unset out of slots feature 'держать строй' for character 'Ухмыл'! ]

**Comment by bylins** [comment]
[01-12-21 20:17:05][ SCRIPT LOG (Room: 15000, trig: 15071): Unknown world cmd: 'гов проходим на юг, раздеваемся до гола, вещи все оставляем.' ]
[01-12-21 20:17:05][ SCRIPT LOG (Room: 15000, trig: 15071): Unknown world cmd: 'гов потом возвращаемся сюды и дуем на запад.' ]
[01-12-21 20:17:05][ SCRIPT LOG (Room: 15000, trig: 15071): Unknown world cmd: 'гов всем все ясно?' ]
[01-12-21 20:17:05][ SCRIPT LOG (Room: 15000, trig: 15071): Unknown world cmd:

**Comment by vadimka2k** [comment]
хп у знамени когда его бьеш не снижатся 766H 127M 988868653о Зауч:0:00 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] > 
Вы выучили заклинание "каменное проклятие".
Наконец ваши занятия окончены. Вы с улыбкой захлопнули свой часослов.

767H 127M 988868653о Зауч:0 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] > 
к !кам прок!  знамя
Вы приготовились применить заклинание 'каменное проклятие' на синее знамя.


768H 128M 988868653о Зауч:0 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] > 

Вы произнесли заклинание "каменное проклятие".
Вы дописали заклинание "каменное проклятие" в свой часослов.
Вы наложили каменное проклятие на синее знамя. Оно страдает.
Ваша рука не достигла синего знамени - нужно было лучше тренироваться.
Вы сильно подстрелили синее знамя.
Ухмыл СМЕРТЕЛЬНО ударил синее знамя.
Ухмыл СМЕРТЕЛЬНО ударил синее знамя.
Костяной дракон чрезвычайно сильно ободрал синее знамя.
Костяной дракон БОЛЬНО ободрал синее знамя.

768H 128M 988868653о Зауч:0:00 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] > 
Вы выучили заклинание "каменное проклятие".
Наконец ваши занятия окончены. Вы с улыбкой захлопнули свой часослов.

**Comment by vadimka2k** [comment]
после завершения соревнования зашел снова в клетку НОВЫЙ ДИВНЫЙ МИР и не выйти....
Дивный новый мир
   Отсюда открывается удивительный вид. Перед вашими глазами возникла огромная скала,
а недалеко от нее подготовлен здоровенный котлован, в котором парят какие-то размытые тени. 
Вероятно, именно туда вам предстоит попасть.  
[ Exits: e ]
Узорчатая табличка покачивается прямо в воздухе.
Бесовский Ухмыл (воевода ДНЗ) стоит здесь. 
*Костяной дракон летает здесь. 
Крылатый тарпан (под седлом) летает здесь. 

848H 100M 48868653о Зауч:0 Пз:0 Пх:0 28L 193106G Вых:В> 
восток
вы уже распределены в команду, куда вам теперь идти то? ждите.

848H 100M 48868653о Зауч:0 Пз:0 Пх:0 28L 193106G Вых:В> 
восток
восток
восток
вы уже распределены в команду, куда вам теперь идти то? ждите.
восток

848H 101M 48868653о Зауч:0 Пз:0 Пх:0 28L 193106G Вых:В> 
вы уже распределены в команду, куда вам теперь идти то? ждите.

848H 101M 48868653о Зауч:0 Пз:0 Пх:0 28L 193106G Вых:В> 
вы уже распределены в команду, куда вам теперь идти то? ждите.

**Comment by Daniil-Gusev** [comment]
хп у знамени когда его бьеш не снижатся 766H 127M 988868653о Зауч:0:00 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] >
снижается, оно просто проставляется выше максимального, поэтому кажется, что не падает.

**Comment by Daniil-Gusev** [comment]
после завершения соревнования зашел снова в клетку НОВЫЙ ДИВНЫЙ МИР и не выйти....
я думаю над тем, как дать возможность вылетевшим раньше конца выйти с арены, будет исправлено.

**Comment by GhostLamb** [comment]
Предмет "чугунный афедрон с двумя ручками", тип : ОРУЖИЕ
Принадлежит к классу "двуручники".
Можно взять в обе руки (требуется 50 силы).
Вес: 50, Цена: 0, Рента: 0(0)
Материал : БУЛАТ, макс.прочность : 100, тек.прочность : 100
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: !рента,рассыпется вне зоны,!обезоружить,!рассыпется,рассыпется на репоп
Наносимые повреждения '11D6' среднее 38.5.
Накладывает на вас аффекты: инфравидение,доблесть,настороженность,не.сбежать,медлительность
Дополнительные свойства :
   сила улучшает на 12
   удача улучшает на 24
   повреждение улучшает на 36
   макс.жизнь улучшает на 150

**Comment by GhostLamb** [comment]
при 20 проставленых мортах, у всех файтеров сразу не хватит сил одеть двуручник или лук т.к 20-25 силы родной
получается файтеры вобще не смогут одеть оружие, если у него нету напарника мага, что ставит их в заведомо более плохие условия для участия
Предмет "чугунный афедрон с двумя ручками", тип : ОРУЖИЕ
Принадлежит к классу "двуручники".
Можно взять в обе руки (требуется 50 силы).
Вес: 50, Цена: 0, Рента: 0(0)
Материал : БУЛАТ, макс.прочность : 100, тек.прочность : 100
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: !рента,рассыпется вне зоны,!обезоружить,!рассыпется,рассыпется на репоп
Наносимые повреждения '11D6' среднее 38.5.
Накладывает на вас аффекты: инфравидение,доблесть,настороженность,не.сбежать,медлительность
Дополнительные свойства :
   сила улучшает на 12
   удача улучшает на 24
   повреждение улучшает на 36
   макс.жизнь улучшает на 150

Предмет "крупнокалиберная станковая праща", тип : ОРУЖИЕ
Принадлежит к классу "луки".
Можно взять в обе руки (требуется 49 силы).
Вес: 49, Цена: 0, Рента: 0(0)
Материал : ПРОЧНОЕ.ДЕРЕВО, макс.прочность : 100, тек.прочность : 100
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: !рента,рассыпется вне зоны,!обезоружить,!рассыпется,рассыпется на репоп
Наносимые повреждения '10D6' среднее 35.0.
Накладывает на вас аффекты: опр.невидимости,не.сбежать,медлительность
Дополнительные свойства :
   сила улучшает на 20
   ловкость ухудшает на 5
   повреждение улучшает на 30
   реакция ухудшает на 30
   макс.жизнь улучшает на 150
   защита.от.чар улучшает на 10

**Comment by bylins** [comment]
> хп у знамени когда его бьеш не снижатся 766H 127M 988868653о Зауч:0:00 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] >

поправлю

**Comment by GhostLamb** [comment]
макс.прочность : 100, тек.прочность : 100
у всего оружие маленькая прочность, кузнецом чинил пару раз оружие что бы не сломалось, у других проф такой возможности нету! Файтеров ущемляют на арене!

**Comment by GhostLamb** [comment]
ум
Вы владеете следующими умениями:
      оглушить                 (совершенно) 200 (177) 
      сражение верхом          (совершенно) 200 (177) 
      перековать               (совершенно) 200 (177) 
      лидерство                (совершенно) 200 (177) 
[  1] опознание                (недостижимо) 1000 (177) 
      укрепить                 (совершенно) 200 (177) 
[-!-] опохмелиться             (совершенно) 200 (177) 
      сбить                    (совершенно) 200 (177) 
      пнуть                    (совершенно) 200 (177) 
      кулачный бой             (недостижимо) 1000 (177) 
      спасти                   (недостижимо) 1000 (177) 
      выследить                (недостижимо) 1000 (177) 
      палицы и дубины          (недостижимо) 1000 (177) 
      секиры                   (недостижимо) 1000 (177) 
      длинные лезвия           (недостижимо) 1000 (177) 
      короткие лезвия          (недостижимо) 1000 (177) 
      иное оружие              (недостижимо) 1000 (177) 
      двуручники               (недостижимо) 1000 (177) 
      проникающее оружие       (недостижимо) 1000 (177) 
      копья и рогатины         (недостижимо) 1000 (177) 
      атака левой рукой        (совершенно) 200 (177) 
      обезоружить              (совершенно) 200 (177) 
[-!-] ремонт                   (совершенно) 200 (177) 
      заточить                 (совершенно) 200 (177) 
[-!-] ярость                   (недостижимо) 1000 (177) 
      ювелир                   (совершенно) 200 (177) 
      железный ветер           (недостижимо) 1000 (177) 

ярость даёт дамролы в зависимости от прокачки, от оружейки вроде тоже что то насыпает так что 1000 значение это перебор надо сделать что бы 200 было тоже

**Comment by hikopol** [comment]
после выхода с арены у персонажа остаються временные заклы купленые на арене, на время правда, но все же, можна купить круг или Кп с арены и бегать с ним еще пару часиков,  имхо думаю что это не порядок.
|<.T......> воздушный щит                  [47]  
1709H 130M 906501о Зауч:0 Пз:2 Пх:0 24L 42768G Вых:СЮ> кол ! возд щ !
Вы произнесли заклинание "воздушный щит".
Вы занесли заклинание "воздушный щит" в свои резы.
Вас окутал воздушный щит.

**Comment by bylins** [comment]
> после выхода с арены у персонажа остаються временные заклы купленые на арене, на время правда, но все же, можна купить круг или Кп с арены и бегать с ним еще пару часиков, имхо думаю что это не порядок.

на 2 часа при тесте, и что время пройдет исходи слюной если постоянки не было

**Comment by bylins** [comment]
> ярость даёт дамролы в зависимости от прокачки, от оружейки вроде тоже что то насыпает так что 1000 значение это перебор надо сделать что бы 200 было тоже

поправлю

**Comment by Daniil-Gusev** [comment]
у всего оружие маленькая прочность, кузнецом чинил пару раз оружие что бы не сломалось, у других проф такой возможности нету! Файтеров ущемляют на арене!
увеличил в 2.5 раза

**Comment by Daniil-Gusev** [comment]
при 20 проставленых мортах, у всех файтеров сразу не хватит сил одеть двуручник или лук т.к 20-25 силы родной
исправил

**Comment by Daniil-Gusev** [comment]
после завершения соревнования зашел снова в клетку НОВЫЙ ДИВНЫЙ МИР и не выйти....
исправлено

**Comment by Daniil-Gusev** [comment]
холд после смерти сократил в два раза, теперь 5 секунд.

**Comment by Daniil-Gusev** [comment]
Вы заметили : 'сделал респ без холда, но с восстановлением только до половины хп, если хп при этом меньше половины'

**Comment by Daniil-Gusev** [comment]
хп у знамени когда его бьеш не снижатся 766H 127M 988868653о Зауч:0:00 Пз:0 Пх:0 [Боголюб:Ранен] [Ухмыл:Ранен] [синее знамя:Невредимо] >
исправили, теперь будет отображаться.

**Comment by bylins** [comment]
в триггерах сделать поле linkdrop

**Comment by bylins** [comment]
см #1235
