### ISSUE TITLE
фляга с водой с водой

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1219]
скажем есть у нас емкость под названием фляга, наполненная жидкостью вода. в падежах прописываем в олц слово фляга и склоняем его, сохраняем. вроде все хорошо: фляга с водой. но вдруг нам понадобилось сменить таймер фляги. открываем олц и в падежах видим уже не фляга, а фляга с водой. если мы сохраним в таком варианте, то получим флягу с водой с водой. баг.

**Comment by bylins** [comment]
Это не фляга с водой а с магическим зельем. такое не багрепортили потому не правилось

**Comment by bylins** [comment]
[13433] бочонок с водкой  <великолепно> (наполнен меньше, чем на четверть зеленой жидкостью)
962H 179M ??? Зауч:0 ОЗ:0 34L 57136173G Вых:СВЮv> oedit 13433
-- Предмет : [13433]
1) Синонимы : бочка
2) Именительный (это ЧТО)             : бочонок
3) Родительный  (нету ЧЕГО)           : бочонка

**Comment by bylins** [comment]
962H 179M ??? Зауч:0 ОЗ:0 34L 57136173G Вых:СВЮv>  oedit 149
-- Предмет : [149]
1) Синонимы : бочонок
2) Именительный (это ЧТО)             : бочонок
3) Родительный  (нету ЧЕГО)           : бочонка
4) Дательный    (прикрепить к ЧЕМУ)   : бочонку
5) Винительный  (держать ЧТО)         : бочонок
---------------
962H 179M ??? Зауч:0 ОЗ:0 34L 57136173G Вых:СВЮv> load obj 149
Вы создали бочонок с черным колдовским зельем.

**Comment by bylins** [comment]
решено 6e40a48
