### ISSUE TITLE
новый крешь

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1220]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff75e9859 in __GI_abort () at abort.c:79
#2  0x000055555663088d in std::__replacement_assert (__file=0x5555578dcd80 "/usr/include/c++/11/array", __line=188,
    __function=0x5555578e3c00 "constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = unsigned char; long unsigned int _Nm = 354; std::array<_Tp, _Nm>::reference = "..., __condition=0x5555578dcc00 "__n < this->size()") at /usr/include/x86_64-linux-gnu/c++/11/bits/c++config.h:504
#3  0x000055555676ed8d in std::array<unsigned char, 354ul>::operator[] (this=0x61f005602e08, __n=354) at /usr/include/c++/11/array:188
#4  0x000055555673d9ff in clear_char_skills (ch=0x61f005602880) at /home/stribog/mud/src/db.cpp:4985
#5  0x0000555556d48a43 in spell_angel (ch=0x6210042f1900) at /home/stribog/mud/src/magic/spells.cpp:2190
#6  0x0000555556d01eab in mag_manual (level=30, caster=0x6210042f1900, cvict=0x0, ovict=0x0, spellnum=155) at /home/stribog/mud/src/magic/magic.cpp:3724
#7  0x0000555556d02e63 in mag_single_target (level=30, caster=0x6210042f1900, cvict=0x0, ovict=0x0, spellnum=155, savetype=2) at /home/stribog/mud/src/magic/magic.cpp:3842
#8  0x0000555556d2ef19 in call_magic (caster=0x6210042f1900, cvict=0x0, ovict=0x0, rvict=0x61400098e440, spellnum=155, level=30) at /home/stribog/mud/src/magic/magic_utils.cpp:413
#9  0x0000555556d319bd in cast_spell (ch=0x6210042f1900, tch=0x0, tobj=0x0, troom=0x61400098e440, spellnum=155, spell_subst=155) at /home/stribog/mud/src/magic/magic_utils.cpp:691
#10 0x0000555557742dff in do_cast (ch=0x6210042f1900, argument=0x7fffffffdd74 " ") at /home/stribog/mud/src/cmd/cast.cpp:169
#11 0x0000555556c9eb8d in command_interpreter (ch=0x6210042f1900, argument=0x7fffffffdd70 "колд ") at /home/stribog/mud/src/interpreter.cpp:1311
#12 0x0000555556637527 in process_io (epoll=13, mother_desc=11, events=0x6270008b5900) at /home/stribog/mud/src/comm.cpp:1282
#13 0x000055555661c7d6 in game_loop (epoll=13, mother_desc=11) at /home/stribog/mud/src/comm.cpp:1490
#14 0x000055555661ab93 in stop_game (port=5555) at /home/stribog/mud/src/comm.cpp:816
#15 0x000055555661a5ac in main_function (argc=2, argv=0x7fffffffeaf8) at /home/stribog/mud/src/comm.cpp:757
#16 0x00005555566191c2 in main (argc=2, argv=0x7fffffffeaf8) at /home/stribog/mud/src/main.cpp:4
(gdb)

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/143993947-4a6b05f8-1366-45b4-91a6-9ec0ce902cd5.png)
какой нафиг SPELLS_COUNT + 1 если он указывает на последний спелл
	SPELL_QUEST = 353,
	SPELLS_COUNT = SPELL_QUEST //last

**Comment by bylins** [comment]
for (int i = 0; i <= SPELLS_COUNT + 1; i++) {
		if (PRF_FLAGGED(ch, PRF_AUTOMEM) && ch->real_abils.SplMem[i]) {
и таких мест много

**Comment by vkhanayev** [comment]
Конструкции вида "unsigned char cnt[SPELLS_COUNT + 1]" оставляем - т.к. нумерация с 0 и +1 нужно чтобы вместить все варианты.

А вот в обработке циклов +1 явно лишнее, т.к. используется <=
