### ISSUE TITLE
Глуш чармиса 2 раунда подряд

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1221]
![image](https://user-images.githubusercontent.com/42086238/144035069-3d7dcf1f-cade-4f61-964a-4c3c4246351d.png)

**Comment by hikopol** [comment]
да и кузнецы так могут кстате, тут ничего такого нет

**Comment by vkhanayev** [comment]
С глушем действительно перебор был. Для атакующего лаг 1 раунд, а для цели 3 (даже при минимальном виде глуша).
Сделал минимальный лаг для глуша в 2 раунда (для атакующего).
Молот остался без изменений т.к. минимальный вариант молота дает лаг по 1 раунду как атакующему, так и цели.
