### ISSUE TITLE
Новая Арена

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1235]

**Comment by bylins** [comment]
1: сделать выдачу стартовой шмотки или ногат.
2: исправить баг запуска ранудов боев
3: увеличить количество загружаемого мусорного стафа.
4: починить загрузку алтаря.
5: починить ловушки
6: сделать диспел при смерти на арене

**Comment by hikopol** [comment]
1 .при попадании на арену (когда всех раскидывает по командам), не очишаються текущие чармисы , т.е я оказался в такой ситуации что меня телепортнуло из комнаты подготовки а чармисы остались в ней.
2. можна было почармить продавца магазина
3. не появлялись обычные мобы с которых падают нагаты
4. !холд не слетал после смерти, возможно !сон! тоже не слетит хз
 5. переделать предмет    4)     Навалом  обуревший божок                                    300 - он теперь бесполезный (ибо автозб забрали :)

**Comment by Daniil-Gusev** [comment]
11. у ЛДшников не проставляется комната возврата. Сделать моба проставляющего в 1рд принудительно
12. сделано, внум триггера 15073.

**Comment by Osyka82** [comment]
1. Если холд не спадает, то надо все спеллы проверять, возможно так работает сон, молча и тд. Так же если витязь точканет из строя, + круг пустоты не знаю есть он на арене или нет, + кп у черноков.
2. В первой части мобы не давали нагаты, только за убийство чаров.
3. Знамя очень долго принимает останки, можно это без задержек сделать? Был момент что на руках было больше 20 останков, и приходилось сидеть там и сдавать.
4. В какой-то момент пропал магазин, причина не ясна.

**Comment by Daniil-Gusev** [comment]
2. можна было почармить продавца магазина
 исправлено.
 5. переделать предмет 4) Навалом обуревший божок 300 - он теперь бесполезный (ибо автозб забрали :)
 переделал предмет.

**Comment by Daniil-Gusev** [comment]
В первой части мобы не давали нагаты, только за убийство чаров.
там дело в том, что триггер загрузки мобов не запустился. вы били в начале вспомогательных мобов.
Знамя очень долго принимает останки, можно это без задержек сделать? Был момент что на руках было больше 20 останков, и приходилось сидеть там и сдавать.
нельзя, иначе может возникнуть ситуация, что игроки поддаются друг другу, чтоб по-быстрому ногат срубить.

**Comment by GhostLamb** [comment]
1.проставить все скилы по 200
оружейные задирают дамролы очень сильно
железный ветер           (недостижимо) 1000 (180) - дает вихрь по 4-и мува в раунд, хотя при 200 скиле это в районе 20 мувов в раунд
что бы не повторятся что может еще у кого то скиллы останутся влияющие всё по 200 проставить просто, а не каждый который найдешь только
2.  убрать на стафе такое количество дамролов, и каста - т.к сейвов нету на арене, то после покупки 2-3 стафин, в холд встаешь всегда от кастера, ну и в лаг от файтера тоже встаешь всегда поэтому файтеры между собой тоже кто проспамил 1-ый тот и победил
3.  добавить всевид за ногаты 3-5 там, а то кастеры имеют преимущество в начале если берут инвиз ты их не можешь ударить, в часности кудесы могут бить чармисами спокойно, а ты их не видишь и просто умираешь
4.  добавить чж бутылочкой тоже, ибо его вобще нету на стафе, тати наемы сникают и трипают а ты ничего не можешь сделать им, купец тоже сможет агрить всегда первый из хайда
5. добавить дешевый вариант оружки за 15-20 ногат для начала без статсов просто 10 в прайм и 15ср обе руки, и рукавички 8 весу что то такое

**Comment by bylins** [comment]
при смерти буду снимать:
{SPELL_SLEEP, SPELL_POISON, SPELL_WEAKNESS, SPELL_CURSE, SPELL_PLAQUE, SPELL_SILENCE, SPELL_BLINDNESS, SPELL_HAEMORRAGIA, SPELL_HOLD, SPELL_PEACEFUL,  SPELL_CONE_OF_COLD, SPELL_DEAFNESS, SPELL_BATTLE};
все что умеет умение лечить

**Comment by Daniil-Gusev** [comment]
5: починить ловушки
протестировал ловушки, все работают корректно, по тексту триггеров тоже ошибок не вижу. потребует наблюдений, пока вроде все в порядке.

**Comment by Daniil-Gusev** [comment]
3: увеличить количество загружаемого мусорного стафа.
увеличил, теперь на старте грузится по 3*количество участников единицы оружия, брони и волшебных предметов, потом каждые 12 секунд проверка: если 1D100 <= количество участников, то грузим еще набор по 1 оружие, броня и волшебный предмет. думаю должно хватить.

**Comment by bylins** [comment]
В персхран не лезет школьный сет и как пример сумка осина

**Comment by Daniil-Gusev** [comment]
2: исправить баг запуска ранудов боев
распределил рандом триггеры-активаторы по разным комнатам, так надежнее и должно быть без багов.

**Comment by Daniil-Gusev** [comment]
10: починить отображение рун в магазине
ошибку нашел и починил. не тестировалось.

**Comment by Daniil-Gusev** [comment]
1: сделать выдачу стартовой шмотки или ногат.
сделал. файтерам- оружка, батырам- шмотка на кисти, магам- 30 ногат. купу отнес к файтерам.

**Comment by Daniil-Gusev** [comment]
2. убрать на стафе такое количество дамролов, и каста - т.к сейвов нету на арене, то после покупки 2-3 стафин, в холд встаешь всегда от кастера, ну и в лаг от файтера тоже встаешь всегда поэтому файтеры между собой тоже кто проспамил 1-ый тот и победил
3. сделано.

**Comment by Daniil-Gusev** [comment]
сделал пурж чармисов игрока в начале подготовки.

**Comment by Daniil-Gusev** [comment]
7: сделать фонтан с мувами.
8: положить еду, мувы и алкашку на базы.
мувы добавил в тот же прудик, где и сытость. положил прудик и источник водки на базы.

**Comment by GhostLamb** [comment]
щас пошел зонить и увидел что у меня умение ярость сбросилось до 200 оказывается и начало качаться 
[  1] ярость                   (хорошо) 204 (253)
в логах посмотрел это случилось после арены, значит на арене когда проставили 200 скилл он не вернулся к максимальным значениям когда закончился тест

**Comment by bylins** [comment]
см #1240
