### ISSUE TITLE
Что-то странное в DG

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1239]
![image](https://user-images.githubusercontent.com/42086238/145045829-10612332-7bb0-4051-b3dc-715f159c7b59.png)
[07-12-21 16:38:11][ SCRIPT LOG (Trigger: Бьют ключника, VNum: 20217) : calcuid target not found vnum: 20215, count: 1. ]
[07-12-21 16:38:11][ SCRIPT LOG (Trigger: Бьют ключника, VNum: 20217) : attach: нет или ошибка в аргументе 2: 'attach 20204 ' ]
[07-12-21 16:38:11][ SCRIPT LOG (Trigger: Бьют ключника, VNum: 20217) : run invalid id arg(1): 'exec 20204 ' ]
куда делся моб?
Dec  7 16:38:17 :: Load mob #20215 by старик-ключник (mload)
попытка его загрузки через 6 секунд, это как? лагом не объяснить

**Comment by hikopol** [comment]
а что там в 20204 тригере, его же тут екзекютят, мб там какие-то приколюхи

**Comment by bylins** [comment]
см внимательно, моб загружается потом его калкуид
но моб загрузился по какой-то причине  через 6 секунд

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/145056280-cfa1e9b8-e0dc-4b9a-91ac-ec30c2c16a2f.png)

**Comment by bylins** [comment]
такое ощущение что mload команда была пропущена а сработала уже на следующий вызов триггера
там damage т.е. на каждый нанесенный дамаг
но!если был бы в лаге, то приостанавливается выполнение, а не пропускаются команды.

**Comment by bylins** [comment]
962H 179M ??? Зауч:0 ОЗ:0 34L 57136173G Вых:СВЮv> tstat 20204
Name: 'Помошь пришедших по зову',  VNum: [20204], RNum: [ 2063]
Trigger Intended Assignment: Mobiles
Trigger Type: Auto, Numeric Arg: 100, Arg list: None
Commands:
   wait 1
   set Target %random.pc%
   mecho Прибежавший на подмогу воин закричал - Сдохни %Target.name% !
   attack %Target.name%

**Comment by bylins** [comment]
exec То тоже не выполнился

**Comment by bylins** [comment]
моб в лаге
