### ISSUE TITLE
Арена доминирование 7.12.2021

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1240]
пишем баги тут
1. наем стаб ваншот насмерть?
2. скилл лечить хиляет знамя полностью
3. дубль сообщений если на чаре аура
Нанна насмерть сокрушена Родовитом.
Нанна насмерть сокрушена Родовитом. (*)

**Comment by hikopol** [comment]
1. на старте дали 30 ногат. кудесу хватило купить подчинить разум за 25 и купить инвиз за 3, на детект не хватило... либо вернуть 50 кроме этого не знаю скок там круг и кп стоит, но чарующий узор за 177 чето дороговато имхо.
2. Витязи грят коней не нашли на арене, ну мб плохо искали,? - мб добавить какой-то типо медальён в магазин за ногаты
3. Как по мне слишком много мусорного стафа, + непонятно что он дает, куда пялить, с названия не особо понятно.

**Comment by Daniil-Gusev** [comment]
наем стаб ваншот насмерть?
поставил знаменам роли боссов, теперь должна пропасть возможность ваншота. так же поставил !убить.точным.стилем
скилл лечить хиляет знамя полностью
сделал триггерный запрет на это.
на старте дали 30 ногат. кудесу хватило купить подчинить разум за 25 и купить инвиз за 3, на детект не хватило... либо вернуть 50 кроме этого не знаю скок там круг и кп стоит, но чарующий узор за 177 чето дороговато имхо.
ну и достаточно, это самый старт, что всю арену будешь делать?
Витязи грят коней не нашли на арене, ну мб плохо искали,? - мб добавить какой-то типо медальён в магазин за ногаты
а название ездовой хмырь не о чем не говорит? это и есть лошади, которых еще купцы могут нанимать.

**Comment by Daniil-Gusev** [comment]
Как по мне слишком много мусорного стафа, + непонятно что он дает, куда пялить, с названия не особо понятно.
количество загружаемого мусорного стафа уменьшил. в магазине можно за 5 ногат купить свиток познания, так же у некоторых профессий есть умение. все это должно решать проблему непонятности, куда и что надевать.

**Comment by Daniil-Gusev** [comment]
еще мне задачки:
1: сделать респаун игрока не на базе, а на рандом клетке: база и 4 клетки крепи вокруг нее.
2: сделать спаун мобов не по углам, а в рандом клетке: угол и клетки вокруг него.

**Comment by Daniil-Gusev** [comment]
1: сделать респаун игрока не на базе, а на рандом клетке: база и 4 клетки крепи вокруг нее.
сделано
2: сделать спаун мобов не по углам, а в рандом клетке: угол и клетки вокруг него.
сделано.

**Comment by GhostLamb** [comment]
Предлагаю сделать задержку перед возможностью воскрешения 5-10секунд
сейчас такой нету, вот кусочек лога Нанна через батл раунд воскресает это слишком быстро

69H 19M 675613807о ОЗ:0 [Родовит:О.тяжело ранен] [белое знамя:Ранено] > 

Вы ИЗУВЕРСКИ пнули белое знамя. Теперь ему наложат гипс.
Вы ИЗУВЕРСКИ ударили белое знамя.
Вы ИЗУВЕРСКИ ударили белое знамя.
Вы ИЗУВЕРСКИ ударили белое знамя.
Вы УЖАСНО пырнули белое знамя.
Вы пошатнулись, задетые магической стрелой белого знамени. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Вы пошатнулись, задетые магической стрелой белого знамени. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Вы пошатнулись, задетые магической стрелой белого знамени. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Магическая стрела, пущенная белым знаменем, пронзила вас. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Вы избежали попытки белого знамени хлестнуть вас.
54H 2M 675613807о ОЗ:1 Пн:2 [Родовит:О.тяжело ранен] [белое знамя:Ранено] >
 
Нанна взглянула на Осина и произнесла : 'Умри!'.
Густая тень вокруг Осина жадно поглотила магию Нанны.
Нанна медленно появилась из пустоты.
Нанна насмерть сокрушена Осином. (*)
Нанна мертва, ее душа медленно подымается в небеса.
Ваше деяние никто не оценил.
Кровушка стынет в жилах от предсмертного крика Нанны.
61H 4M 675613807о ОЗ:1 Пн:2 [Родовит:О.тяжело ранен] [белое знамя:Ранено] > 

Вы слишком устали.
Вы ИЗУВЕРСКИ ударили белое знамя.
Вы НЕВЫНОСИМО БОЛЬНО пырнули белое знамя.
Вы пошатнулись, задетые магической стрелой белого знамени. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Магическая стрела, пущенная белым знаменем, пронзила вас. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Вы пошатнулись, задетые магической стрелой белого знамени. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Вы пошатнулись, задетые магической стрелой белого знамени. (*)
 Вы желаете, чтобы ваши раны не кровоточили так сильно! 
Белое знамя попыталось хлестнуть вас, но промахнулось.
53H 4M 675613807о ОЗ:0 Пн:1 [Родовит:О.тяжело ранен] [белое знамя:Ранено] > 

Осин своим оглушающим ударом сбил Нанну с ног.
Нанна медленно появилась из пустоты.
Нанна насмерть сокрушена Осином.
Нанна мертва, ее душа медленно подымается в небеса.
Ваше деяние никто не оценил.
Кровушка стынет в жилах от предсмертного крика Нанны.

**Comment by bylins** [comment]
Ну лаг на чара после рипа сам бог велел
