### ISSUE TITLE
Арена доминирования 9.12.2021

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1245]

**Comment by EsteryBylins** [comment]
Лаги, просто бессмысленно что-либо делать, если будут такие дикие лаги, особенно перед стартом раунда, в конце вообще зависало секунд по 10
После второго раунда есть все, что можно получить по большому счету, игра сводится к убийству знамени, а это бесконечный процесс, респаун игроков надо делать хотя бы секунд 30 иначе мясорубка бесконечная, или увеличивать время респа с каждой смертью или с каждым заработанным ногатом, чем богаче, тем дольше респ
Одеться чтобы бить пятую волну нереально, мобы побеждают, плюс лаги не дают нормально с ними справляться, да и бить их уже особо незачем
Сдавать останки это гемор какой-то, особенно если играешь группой, намного лучше было бы сразу получать монетки за убийство, ну или снять капы на сдачу
Время между волнами, особенно первыми точно можно сокращать, пока не закупился особо смысла нет воевать, потому что за войну нет ногатов, останки запихиваются вяло

**Comment by bylins** [comment]
Захардкожу что лечить можно только PC или чармиса

**Comment by bylins** [comment]
Сделать событие на комнату, сдох игрок

**Comment by bylins** [comment]
проверить преймущества боссов, откуда взялся отхил?

**Comment by Daniil-Gusev** [comment]
сделал выдачу ногат сразу за убийство игрока:
[10:25] Вы заметили : 'если ногаты жертвы/10 >= 3 то даем получившееся количество убийце, у жертвы забираем. если ногат у жертвы меньше 3, то забираем их все и передаем убийце, если ногат нету, то убийца ничего не получает'
После второго раунда есть все, что можно получить по большому счету, игра сводится к убийству знамени, а это бесконечный процесс, респаун игроков надо делать хотя бы секунд 30 иначе мясорубка бесконечная, или увеличивать время респа с каждой смертью или с каждым заработанным ногатом, чем богаче, тем дольше респ
пока установлен респаун 20 секунд, плюс теперь после смерти от рук игрока потеря 10 проц своих ногат, поэтому будут аккуратнее.
Одеться чтобы бить пятую волну нереально, мобы побеждают, плюс лаги не дают нормально с ними справляться, да и бить их уже особо незачем.
забрал дышки у 5 волны, они оказывается только у 5 и 9 есть, теперь должно упроститься значительно.
Сдавать останки это гемор какой-то, особенно если играешь группой, намного лучше было бы сразу получать монетки за убийство, ну или снять капы на сдачу
расписал чуть выше, теперь зарабатывать ногаты с игроков удобнее.
Время между волнами, особенно первыми точно можно сокращать, пока не закупился особо смысла нет воевать, потому что за войну нет ногатов, останки запихиваются вяло.
там пауза зависит от количества участников: 420 -(количество участников*5) секунд и пауза там стандартная для всех раундов, пока трогать не буду.

**Comment by hikopol** [comment]
> Захардкожу что лечить можно только PC или чармиса

если не ошибаюсь то лечить качаеться только ели ты его применяешь к НПС
зачем ламать что-то что-бы реализовать что-то, мб проще каким-то флагом сделать чем ломать механику умения и отхила у витязей. Например флагом !исцелить.

**Comment by bylins** [comment]
> если не ошибаюсь то лечить качаеться только ели ты его применяешь к НПС
> зачем ламать что-то что-бы реализовать что-то, мб проще каким-то флагом сделать чем ломать механику умения и отхила у витязей. Например флагом !исцелить.

ктож так качает то... Это больше на абуз похоже.

**Comment by bylins** [comment]
Убрать ваншот со стаба у наемов и отказаться от боссов

**Comment by hikopol** [comment]
1. Убийство врагов чармисами не давало ногат.
2. Снимали чето сильно много ногат за смерть : пример - до смерти
 баланс 27, после смерти 0.

**Comment by Daniil-Gusev** [comment]
Снимали чето сильно много ногат за смерть : пример - до смерти
исправлено
