### ISSUE TITLE
Арена доминирования 11.12.2021

### ISSUE THREAD

**Issue by EsteryBylins** [bylins/mud#1249]
Стало веселее, лаги такие же
На земле стало валяться слишком много хлама, оделся с первых пяти клеток, далее до самого конца смысла подбирать особо ничего нет
Качаться теперь реально надо до пятого раунда включительно, только там уже можно закупиться
Надо чтобы писалось Ухмыл был убит Эстери 10 раз!
Было бы круто видеть вообще видеть стату по килам, по дамаге, кто кого сколько раз убил
Лаг после рипа надо как-то "украсить", чтобы таймер видно было например, ну или просто двигаться можно было, но нельзя выйти, а то кажется, что упал, хочется реконнект, а это уже дисквал..

**Comment by Daniil-Gusev** [comment]
На земле стало валяться слишком много хлама, оделся с первых пяти клеток, далее до самого конца смысла подбирать особо ничего нет
еще уменьшил хлама в несколько раз.
Надо чтобы писалось Ухмыл был убит Эстери 10 раз!
это достаточно трудно реализуемо, пока просто сделал счетчик убийств, если замочил чара- он прибавится. Вася убит Петей! всего убийств: 17!

**Comment by bylins** [comment]
перенесли в 10.12
