### ISSUE TITLE
Лабиринты

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1253]
если клетка nomapper то отрубить и показ миникарты

**Comment by joopel** [comment]
помимо флага nomapper нужен еще флаг novnum. 

Поясню у нас может быть тип зоны, где надо скрыть только номерка клеток, чтоб по ним нельзя было идентифицировать где находишься. (Например та же генерация зон, чтоб игроки не могли ориентироваться по номерам как хлебным крошкам) Но отображение самой карты при этом остается как есть.

**Comment by bylins** [comment]
делай некоторые места без флага номаппер. чтоб игрок мог сориентироваться, и будет тебе счастье.
