### ISSUE TITLE
Арена доминирования 11.12.2021

### ISSUE THREAD

**Issue by EsteryBylins** [bylins/mud#1254]

**Comment by EsteryBylins** [comment]
Снимать ногаты за рип не стоит, только давать, потерял время с тьмой из свитка и все, второй раунд мобов пропустил, а дальше не набрать 300, чтобы купить круг, так как за рип снимают больше, чем успеваешь набить, а с четвертого раунда если не оделся прилично фармить уже нереально
Время респа должно как-то увеличиваться с раундами, а вначале быть минимальным, 5 10 15 20 25 сек и тд
Если на стартовых шмотках есть детект инвиза, то почему нет сенсы? Пускай все в равных условиях бегают, а не только тати, было бы логичнее вообще убрать детект со стафа и автоинвиз

**Comment by EsteryBylins** [comment]
Мобы после 4 раунда слишком сильные, их уже никто толком не бьет, слишком больно, а ногатов не хватает, это конкретно замедляет динамику игры, только кудес счастлив

**Comment by hikopol** [comment]
1. За убийство игрока чармисом не дает нагат, так же не идет в счетчик убийств.
2. "Чарующий узор" не работает с ингром что на арене, подозреваю что проблема в том что VNUM итема разные.
3. С "обоянием" думаю ситуация аналогичная п.2

**Comment by hikopol** [comment]
> 

ну я хз кто как бьет мобов, мб уже на такой волне надо бить в 3 рыла, не брать 3 татя-наема в гопу, а брать волхва, клера, что бы можна было бить мобов и зароблять ногаты не только убийством игроков...
мы вот били вместе мобов с 4 волны, да в одиночку это не реально сделать, но если подумать башкой то возможно.

**Comment by Daniil-Gusev** [comment]
Снимать ногаты за рип не стоит, только давать, потерял время с тьмой из свитка и все, второй раунд мобов пропустил, а дальше не набрать 300, чтобы купить круг, так как за рип снимают больше, чем успеваешь набить, а с четвертого раунда если не оделся прилично фармить уже нереально
а чьи это проблемы? сам протупил, а теперь ему не стоит. там я не ввожу в арену новые ногаты, вы уже набитые между собой распределяете, кто-то конечно будет обделен. 
Время респа должно как-то увеличиваться с раундами, а вначале быть минимальным, 5 10 15 20 25 сек и тд
сделал, респаун теперь раунд*5 секунд. раунд сейчас выведу на табличку. 
Если на стартовых шмотках есть детект инвиза, то почему нет сенсы? Пускай все в равных условиях бегают, а не только тати, было бы логичнее вообще убрать детект со стафа и автоинвиз
убрал автоинвиз на стартовом шмоте.
Мобы после 4 раунда слишком сильные, их уже никто толком не бьет, слишком больно, а ногатов не хватает, это конкретно замедляет динамику игры, только кудес счастлив
бьют то больно, но ногаты нужны. а кому сейчас легко?
