### ISSUE TITLE
арена доминирование 13.12.2021

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1259]
пишем тут

**Comment by bylins** [comment]
шмот который с мобов надо сделать флаг рассыпется на земле
и подумать с трупами, а то там несколько экранов

**Comment by hikopol** [comment]
**1. сегодня не по части багов но по части юзабилити**
 горы, море мусора на земле и в мобах, пачками однотипного по сути не ценного , (ценное только вначале) ито до раунда 2го.
=> что предлагаю не лоадить так много стафа с мобов, \ просто так на землю {не вкурсе как это сделано}
=> сделать что-то вроде сундучков которые появляються-лоадяться , рандомно в зонах (1-2 сундука) на волну со стафом уровня этой волны. например где-то в углах, сундуков поставить охранять мобов посильнее и агресивных!. 
=>срезать сильно лоад шмоток с мобов, но если упала шмотка то она бы была хорошой (явно ценной) (для этой волны)
**2. ну это мои пожелание** : не делать один магазин с кучей позиций. Очень легко запутаться что ты хочешь купить или на что ты копишь на номер 23 или 24, ибо чтобы например найти: харю или мудру +каст надо либо учить на изусть всю таблицу, либо запоминать номеры, либо постоянно лорить стаф (сделать 2 магазы = 1ой файтерский , 2ой кастерский, 3-ий доп штуки - свитки, бомбы, зелья, мины... итд.)
**3. Я так и не понял куда (а главное почему??) свапнулись знамя после 8раунда**, с базы исчезло зеленое знамя, найти не могли, в то время как его атаковали, нашли в углу карты в низу.... это так задумано???

**Comment by garkins** [comment]
1) переделать механику ожидания респавна - например сидеть в той же клетке или другой но уметь разговаривать и тд. Ужасно бесит! Думаешь что в лаге
2) не до конца понял куда пропадают ногаты
3) чуть тупанул с закупом - третья или четвертая волна убивала меня без шансов
4) как познать те горы шмото-свитков????

**Comment by Daniil-Gusev** [comment]
горы, море мусора на земле и в мобах, пачками однотипного по сути не ценного , (ценное только вначале) ито до раунда 2го.
максимально прибрал лоад мусора, значительно снизил шанс на выпадение шмота с мобов.
=> сделать что-то вроде сундучков которые появляються-лоадяться , рандомно в зонах (1-2 сундука) на волну со стафом уровня этой волны. например где-то в углах, сундуков поставить охранять мобов посильнее и агресивных!.
сейчас в дропе с мобов лежит 30 шмоток, там не расчитано по волнам, просто разный шанс на их выпадение, поэтому сундучки выглядят малореализуемыми без ребаланса и переделки всего аренного шмота. 
=>срезать сильно лоад шмоток с мобов, но если упала шмотка то она бы была хорошой (явно ценной) (для этой волны)
см выше, сделано.

**Comment by Daniil-Gusev** [comment]
2. ну это мои пожелание : не делать один магазин с кучей позиций. Очень легко запутаться что ты хочешь купить или на что ты копишь на номер 23 или 24, ибо чтобы например найти: харю или мудру +каст надо либо учить на изусть всю таблицу, либо запоминать номеры, либо постоянно лорить стаф (сделать 2 магазы = 1ой файтерский , 2ой кастерский, 3-ий доп штуки - свитки, бомбы, зелья, мины... итд.)
3. маловозможно, так как под базу выделяется только одна клетка, а на ней для исключения багов и путаницы может стоять только один продавец.
3. Я так и не понял куда (а главное почему??) свапнулись знамя после 8раунда, с базы исчезло зеленое знамя, найти не могли, в то время как его атаковали, нашли в углу карты в низу.... это так задумано???
4. больше конкретики: что и как произошло?
4. Ну да солидарен с другими лаг можна заменить, невозможностью использовать тригер выйти, а то висеть в лаге и не иметь даже возможности прокоментировать что-то, оч печально.
 
сделано, теперь просто не выпускает из комнаты контуженых, если не прошел таймер респа, но лаг не ставит.

**Comment by Daniil-Gusev** [comment]
переделать механику ожидания респавна - например сидеть в той же клетке или другой но уметь разговаривать и тд. Ужасно бесит! Думаешь что в лаге
см выше, сделано.
не до конца понял куда пропадают ногаты
если тебя убил игрок, то ты теряешь 1/10 своего кошелька ногат, они отдаются в пользу победителя.
чуть тупанул с закупом - третья или четвертая волна убивала меня без шансов
а чьи это проблемы?
как познать те горы шмото-свитков????
ну теперь должны быть не горы, снизил количество мусора. в магазине у тролленка есть свитки познания, их можешь использовать.

**Comment by hikopol** [comment]
> 4\. Я так и не понял куда (а главное почему??) свапнулись знамя после 8раунда, с базы исчезло зеленое знамя, найти не могли, в то время как его атаковали, нашли в углу карты в низу.... это так задумано??

вобщем после какой точно не скажу волны - вроде бы 7+
произошла ситуация - кощиха случайно сагрил знамя своим чармисом, в то время я вишу во фризе(в комнате ожидания) просит срескать или убить чармиса его... я выхожу с комнаты, как обычно в районе нашей базы, захожу в клетку с знаменем, а его там попросту нет... начинаю искать его по всей карте , нашлось в углу карты в самом нижнем уровне.

**Comment by garkins** [comment]
> > 4. Я так и не понял куда (а главное почему??) свапнулись знамя после 8раунда, с базы исчезло зеленое знамя, найти не могли, в то время как его атаковали, нашли в углу карты в низу.... это так задумано??
> 
> вобщем после какой точно не скажу волны - вроде бы 7+ произошла ситуация - кощиха случайно сагрил знамя своим чармисом, в то время я вишу во фризе(в комнате ожидания) просит срескать или убить чармиса его... я выхожу с комнаты, как обычно в районе нашей базы, захожу в клетку с знаменем, а его там попросту нет... начинаю искать его по всей карте , нашлось в углу карты в самом нижнем уровне.

КВ опять читерят :)))

**Comment by garkins** [comment]
Да и еще хотелось бы что-то отменяющее все аффекты. Притом бесплатно в комнате респавна. Какой-то командой. Так как есть негативные свитки палки. И бывает ты их пробнул и считай проиграл. Бесплатно потому что можно попасть в эту тему сразу

**Comment by Daniil-Gusev** [comment]
Да и еще хотелось бы что-то отменяющее все аффекты. Притом бесплатно в комнате респавна. Какой-то командой. Так как есть негативные свитки палки. И бывает ты их пробнул и считай проиграл. Бесплатно потому что можно попасть в эту тему сразу
а попку вам не подтереть еще? ты совал в рот всякую бяку, отравился, чьи это проблемы? буду на базе за 10 ногат продавать напиток, 3 раза кастующий развеять магию 50 левла.

**Comment by Daniil-Gusev** [comment]
сделать разделение по гопе ногат, полученных через триггеры.

**Comment by garkins** [comment]
Магазин может быть продублирован в комнате респавна. Сидишь ждешь респавна и думаешь как победить. Тратишь ногаты. Логично имх
