### ISSUE TITLE
арена доминирования 15.12.2021

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1263]
субж

**Comment by bylins** [comment]
с чармисами и мобами всегда делаю останки, и они не могут вернуться на ренту они мобы, они висят в нигде
при входе на арену кастерам кидаются ногаты, но ведь теперь триггерное add_nogata делится на группу

**Comment by hikopol** [comment]
- Бытует мнение что знамя могут перемещаться, с г следуй, но делают это не всегда)

**Comment by bylins** [comment]
предположительно следует за лидером если погрупить как согрупника, но это какой-то бред.
подтвердите

**Comment by bylins** [comment]
MOB флаги: !ходит,
но если его погрупить ходит. перемещения запретить триггерами не удается они если знамя полагали не работают

**Comment by bylins** [comment]
MOB_SENTINEL ==!ходит
в коде нахрен вырезана проверка

**Comment by bylins** [comment]
сделал
char.point_nogata
добавляет только цели и не делит на группу

**Comment by bylins** [comment]
все триггтелепорты переносят чармисов клонов хранов
правило чармиса
моб и лидер игрок и (нанят или  очарован)
если что-то не переносится ставьте в прототипы мобу.
