### ISSUE TITLE
арена доминирование 17.12.2021

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1266]
пишем сюда

**Comment by Daniil-Gusev** [comment]
поправить уровни мобам для подъема черноками нормальных мобов.

**Comment by Daniil-Gusev** [comment]
поправить уровни мобам для подъема черноками нормальных мобов.
сделано

**Comment by Daniil-Gusev** [comment]
по просьбам игроков повысил шанс дропа стафа с мобов.

**Comment by Daniil-Gusev** [comment]
изменил прочность для всего оружия.

**Comment by Daniil-Gusev** [comment]
[21:10] Вилогар сказал вам : 'очепятка. Ухмыл дал много ногаты Бельверусу.'

**Comment by Daniil-Gusev** [comment]
у тролленка можно чинить вещи за куны.

**Comment by Daniil-Gusev** [comment]
знамена продолжают ходить.

**Comment by Daniil-Gusev** [comment]
осмотр таблички с разной инфой на арене сильно тормозит, надо что-то сделать.

**Comment by EsteryBylins** [comment]
первый раунд, "наем" убил всех мобов за 30 секунд на тригерах (условно), дальше непонятно что делать в ожидании второго раунда, файтеры закупились стафом, а ты ничего не купил, потому что надо спеллы, а накопить на них естественно не получилось, будешь драться, тот же наем тебя будет тыкать по кд, потеряешь вообще все ногаты, которые удалось получить, в итоге за два раунда нет фарма, нет спеллов, нет шмоток, третий раунд мобы еще убиваются, но уже тяжело, на выходе у тебя полтора спелла к четвертому раунду и одна шмотка, драться с четвертой волной уже нереально, если в пати нет хила
это я пишу от лица колда
чернок вообще неиграбельная профа на арене 
в общем весь баланс сводится к тому, что надо брать двух кузнецов и клера писать скрипты на фарм первых волн
и стоять далее на чужом респе не давая выйти врагам)

**Comment by Daniil-Gusev** [comment]
первый раунд, "наем" убил всех мобов за 30 секунд на тригерах (условно), дальше непонятно что делать в ожидании второго раунда, файтеры закупились стафом, а ты ничего не купил, потому что надо спеллы, а накопить на них естественно не получилось, будешь драться, тот же наем тебя будет тыкать по кд, потеряешь вообще все ногаты, которые удалось получить, в итоге за два раунда нет фарма, нет спеллов, нет шмоток, третий раунд мобы еще убиваются, но уже тяжело, на выходе у тебя полтора спелла к четвертому раунду и одна шмотка, драться с четвертой волной уже нереально, если в пати нет хила
это я пишу от лица колда
чернок вообще неиграбельная профа на арене
в общем весь баланс сводится к тому, что надо брать двух кузнецов и клера писать скрипты на фарм первых волн
 я бы предпочел увидеть возможные пути решение проблем все же. уже сделана загрузка мобов в рандомной клетке, чего еще не хватает?

**Comment by hikopol** [comment]
- если предполгались хмыри чармисами то надо проверить - ибо Желтого смог почармить , синего же нет - устойчив (!чарм флаг), так же проверить у них умения  , у синего есть стаб, у желтого глуш - привести всех к одному списку умений например у всех хмырей есть - стаб,молот,глуш, реск, скрытый, подножка.
- так же проверить флаг у всех хмырей !нанимаеться ?

**Comment by Daniil-Gusev** [comment]
если предполгались хмыри чармисами то надо проверить - ибо Желтого смог почармить , синего же нет - устойчив (!чарм флаг), так же проверить у них умения , у синего есть стаб, у желтого глуш - привести всех к одному списку умений например у всех хмырей есть - стаб,молот,глуш, реск, скрытый, подножка.
недостающие флаги проставил, умения менять не буду, пусть различия останутся.
заклинания "обояние" нет в списке заклов на покупку
исправлено.
так же проверить флаг у всех хмырей !нанимаеться ? , вообще купцы были на арене??!
проверил, везде стоит где нужно.

**Comment by FariseyMeles** [comment]
По чернокам.

**Comment by hikopol** [comment]
- когда наступает 6-7а волна физически нельзя почармить мобов уже, если твои погибли по каким-то причинам
у всех мобиков около 10к хп и куча дамаги - что на прямую влияет на возможность почармить их кудесом...
тоесть если твоего чармиса убили враги -  де факто ты остаешся без чармиса.. а ковырять палкой мобов или знамя, ну уж извольте

**Comment by FariseyMeles** [comment]
Поразмыслив, считаю правильным на 8 и 9 раунде не делать мобов сильнее, чем на 7. Причина - 8 и 9 раунд это уже по сути должно быть ПВП между игроками, захват баз и так далее.
     Предлагаю следующую логику 8 и 9 раундов.
   8 раунд - это должна быть тотальная зачистка мобов игроками, с покупкой недостающих предметов, заклинаний и так далее. То есть к концу 8 раунда потенциально все потребности в заклах/стафе должны быть закрыты, мобов нет или практически нет, ничто не ограничивает применение массовых заклинаний (сейчас мас касты ограничены люлями от мобов).
   9 раунд - мобы должны быть жирными и с них должно падать много ногат (очень много!). Ввести в магазины на базах что-то оверное из шмота, что будет стоить дорого (очень дорого! настолько дорого, что купить его можно только лишь убив кого-то из жирнющих мобов 9 раунда). Таким образом, 9 раунд может стать решающим - будет выбор либо в нормальном закупе пвпшится и пытаться убить знамена, либо потратить время на поиск и убийство жирных по хп и дропу мобов 9 раунда, позволяющим переломить исход боя, купив овершмот за много-много ногат.
     Ну и, естественно, на 8 и 9 раунде должны быть мобы, подходящие на роль чармиса чернокам/кудесам/купцам. Поскольку масс-фраги после тотальной зачистки мобов на 8 раунде станут пригодны к использованию, то чармисы будут умирать (никуда не денутся), а значит мобы, пригодные для почарма, должны быть легко доступны, и может быть лоадиться как-то периодически (в таком случае с них не должно быть ногат).
     Сколько делать жирных имба-мобов на 9 раунде? Думаю, из расчета 1 или 2 моба на команду (можно начать с 1, далее надо тестить). Лоадятся на уровни, на которых находились побежденные к 9 раунду команды или на нейтральные уровни (смысл - чтобы командам, которые еще в игре, приходилось уходить от своего знамени в поисках этих жирных мобов, чтобы заработать много ногат, но рискуя знаменем). С 1 моба должно быть столько ногат, чтобы на них можно было купить овер-шмотку 1/3 части команды.
     Возможные статы овершмота: +800 хп, +100 каждого из сейвов (реакция, воля, стойкость), +ЛЩ/ОЩ/ВЩ, +50 здоровье, +100 инициатива, +15 физ и маг резист, +10 всех статов.

**Comment by shevelev** [comment]
Так дошла и моя очередь, напишу по колдунам, так как я участвовал почти во всех турнирах и выходил на топ 1, и один раз на 2 место, то готов сказать, что арена более менее сбалансирована, но люди не понимают тактику для выигрыша, все вот пишут. что им не хватало ногат. вот статистика за вчерашний турнир по моей группе:
Раунд 1: добыто 137 ногат, взяли их за пару тиков, потом 3-6 тиков тупо бегать бить игроков или ныкаться.
Раунд 2: добыто 176 ногат, так же взяты за пару тиков. потом ныкаться
Раунд 3: добыто 53, тут я афканул на ужин.
Раунд 4: добыто 86 ногат, из-за пред афка мобов уже всех подрезали. опять же нычимся.
Раунд 5: добыто 112 ногат, нычимся
Раунд 6: добыто 88 ногат, нычимся
Раунд 7: добыто 149 ногат, тут решили все таки бить гопой всех мобов и стараться не умирать на бельверусе+ко
Раунд 8: добыто 168 ногат. Основной закуп по стафу+заклам сделан.
Раунд 9: добыто 499 ногат, тут уже били всех мобов. танчил чармис, тут уже оделись в стаф. (Бельверус убил желтое)
Раунд 10: добыто 550 ногат, спущено на стаф, листья ну и итогом:  -красное - зеленое - белое

Люди не понима, что нужно вначале вфармить на 1-5 раундах, чтобы был хоть какой-то стаф на них, я на 7-8 раундах оглядывал людей в комнате ожидания, ОНИ ВСЕ ГОЛЫЕ. поэтому у них дальше пути развития 0, они не убьют никого на 8-9 волне.

Так же с 1 по 7 раунд, мобов быстро выкашивают и по сути в каждом раунде тупо афкаешь или ныкаешься по 3-7 тиков (6-15 минут) что не дает никакой мотивации для продолжения. Тут нужно или новые волны в разрезе раунда кидать, или запускать сразу новый раунд после убийства всех мобов в раунде.
Было бы конечно неплохо с 1 по 5 раунд к примеру, чтобы в отведенное для раунда время мобы постоянно лоадились и народ мог одеться уже на этапе 2-7, чем на этапе 6-10, и уже в этот момент убивать чужие знамена.

**Comment by hikopol** [comment]
- нет дешевых вещей + харя просто в магазе
- есть палка херовимов в офф но цена зашквар, поясок с магаза норм но только +10
- на фоне того что есть шмот +50 мудры, думаю как то не справедливо
- рандом харю с мобов не считаю ибо если не повезло/ не зафармил мобов вначале все эти бантики/чурбаны не выпали - то ты сосеш соску с 36 родных хари, а с таким к-вом токлько носильщиков под корсой и чармить :)) а не мобов с 6-7 волны

**Comment by Daniil-Gusev** [comment]
загружать новую волну сразу после убийства предыдущей заманчиво, но в данном случае достаточно трудно реализуемо. сейчас у пауза между раундами =420 -(количество участников*5) секунд. возможно ты сможешь предложить какую-либо более оптимальную формулу?

**Comment by Daniil-Gusev** [comment]
странно, не сохранилось сообщение. я сделал кол-во атак как предлагала кощиха, поставил где можно каст и харю шмоту, снял !очар и !поднять с мобов, разрешил чармить и поднимать хмырей. задумка кощихи вряд ли будет реализована, так как по шмоту у меня другие мысли: сделать по 3 комплекта вещей файтерам и магам со всеми нужными статами: мусорный, дроповый и магазинный. так же сделать магазинные и возможно дроповые кольца, браслеты и амулеты на разные статы. комплекты будут состоять из 5 шмоток предварительно. оружие тоже хотелось бы изменить.

**Comment by shevelev** [comment]
> загружать новую волну сразу после убийства предыдущей заманчиво, но в данном случае достаточно трудно реализуемо. сейчас у пауза между раундами =420 -(количество участников*5) секунд. возможно ты сможешь предложить какую-либо более оптимальную формулу?

тогда может быть с 1 по 5 раунд, повторять волны ? 1 повторить там 5 раз, вторую 4 раза, третью 3 раза, четвертую 2 раза и пятую два раза?

**Comment by Daniil-Gusev** [comment]
тогда может быть с 1 по 5 раунд, повторять волны ? 1 повторить там 5 раз, вторую 4 раза, третью 3 раза, четвертую 2 раза и пятую два раза?
такое себе решение, там в плане именно технической реализации тоже оч неудобно. может я просто буду грузить побольше мобов 1-6 волны?

**Comment by shevelev** [comment]
тогда их нужно грузить раза в 3 больше.

**Comment by Daniil-Gusev** [comment]
тогда их нужно грузить раза в 3 больше.
изменил формулу:
нум =количество участников
1 волна нумх3
2 волна нумх2
3 волна нум
4 волна (нум/2)+1
5 волна (нум/2.5)+1
6 волна (нум/3)+1
7 волна (нум/4)+1
8 волна (нум/5)+1
9 волна (нум/6)+1
