### ISSUE TITLE
арена доминирование 18.12.2021

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1268]

**Comment by hikopol** [comment]
|| Киллы арене доминирования   1, смерти на арене   1                               ||
что-то не работает явно

**Comment by GhostLamb** [comment]
1. фикс коня на арене
Зеленый ездовой хмырь УБИЙСТВЕННО ударил косолапого мишку.
Зеленый ездовой хмырь УБИЙСТВЕННО ударил косолапого мишку.
Зеленый ездовой хмырь УЖАСНО ударил косолапого мишку.
первое что нашел когда бил коняжка, однозначно надо фиксить его дамаг
2. нельзя сагрить чармиса директом чару
устая тень вокруг костяка велета жадно поглотила магию красного знамени.
Попытка красного знамени хлестнуть костяк велета оказалась неудачной.
Костяк велета НЕВЫНОСИМО БОЛЬНО рубанул красное знамя.
1376H 491M 640463894о ОЗ:0 30L 30170G Вых:С> 
оглуш велет
Для исключения незапланированной агрессии введите имя жертвы полностью.

оглуш костяк
Для исключения незапланированной агрессии введите имя жертвы полностью.
3. в бою с чармисом нельзя спасти знамя
спас знамя
Вы пытаетесь спасти чужого противника.
может быть это вытекает из пункта 2. но это требует проверки
4. статистка по моя стат не работает, хотя у меня было 65 килов и 0 рипов но статистика всё равно врет
 || Киллы арене доминирования   0, смерти на арене   0

**Comment by hikopol** [comment]
раунды волн почему-то сбились

**Comment by hikopol** [comment]
каки-то образом на клетке появился чармис - удалой наемничек,(без флага чармис (*)) мб это произошло
 после смерти купца(или описание не поправили хмырю) скорее всего

**Comment by GhostLamb** [comment]
в логе поискал про удалого, его позвал хмырь
1800H 491M 640463894о ОЗ:2 [Родовит:Ранен] [Весторн:Ранен] > 
Зеленый ездовой хмырь воззвал : "На помощь, мои верные соратники!"
Удалой наемничек прибыл на зов и вступил в битву на стороне зеленого ездового хмыря.
Ваша мощная атака оглушила Весторна.
оглуш
Вы ИЗУВЕРСКИ сокрушили Весторна.
Весторн сумел избежать удара удалого наемничка.
От удара удалого наемничка Весторн отправился в мир теней.
вск
Весторн мертв, его душа медленно подымается в небеса.
Весторн погиб смертью храбрых.
Кровушка стынет в жилах от предсмертного крика Весторна.
Вы переключили внимание на желтого ездового хмыря.
Кудояр отдал приказ.
Вам нужно набраться сил.

**Comment by Daniil-Gusev** [comment]
первое что нашел когда бил коняжка, однозначно надо фиксить его дамаг
хмыри перестали быть лошадками, я сделал отдельного коня внум 1600, который вызывается из свистка, который можно будет купить в магазине за ногаты.
раунды волн почему-то сбились
исправлено, я на это надеюсь :) 
каки-то образом на клетке появился чармис - удалой наемничек,(без флага чармис (*)) мб это произошло
исправлено.

**Comment by garkins** [comment]
1) знамена ходили опять )
2) лагов почти не было - такое считается лагов не было )
3) в волнах все время были малоногатные мобы? так задумано?
4) захват алтаря начался только триггером - так и задумано?
5) не считался счет...

вроде бы все из того с чем столкнулся

**Comment by Daniil-Gusev** [comment]
в волнах все время были малоногатные мобы? так задумано?
почему-то волны с определенного момента сбиваются. я отследить это не смог, но какие ошибки увидел- поправил. надеюсь исправил.
захват алтаря начался только триггером - так и задумано?
да, захват начинается только триггером, все верно.
