### ISSUE TITLE
Арена 24/12/2021

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1284]
пишем тут

**Comment by hikopol** [comment]
вобщем такое:
Вы сказали : 'следуй'
Красное знамя начало следовать за вами.
Красное знамя принято в члены вашего кружка (тьфу-ты, группы :).
915H 142M 554458554о Зауч:0 Пз:0 Пх:0 30L 20822G Вых:(С)> гр все
Все, кто за вами следуют, уже включены в вашу группу.
915H 142M 554458554о Зауч:0 Пз:0 Пх:0 30L 20822G Вых:(С)> группа
Ваша группа состоит из:
Персонаж            | Здоровье |Энергия|Рядом|Учить| Аффект | Кто | Держит строй | Положение 
Кудояр              | Невредим | Полон | Да  |     |   Н    |Лидер| Нет          | Стоит
Красное знамя       | Невредим | Да  |        |Стоит          
Лерина              | Невредим |Отдохн.| Да  |     |   Н    |     | Нет          | Стоит
======
проходит пару минут====
![Знімок екрана 2021-12-24 194738](https://user-images.githubusercontent.com/61746291/147367579-8b70d4ab-5056-427a-af41-d1504ee59dd5.png)

**Comment by garkins** [comment]
1) фляжки должны быть с черным это очевидно. красное неочевидно
2) ногаты за рипы фиксом не должны приходить. только как процент от тех что были у того кого убил.
3) стартовых ногат стало хватать только на шаровую молнию... так и нужно?
а в остальном. не меняйте механики. оттестируйте те что есть. откуда новые лаги? почему меняют цены? зачем давать за килы ногаты? оттестируйте то что есть!!!

**Comment by garkins** [comment]
а да и вопрос с прославлеными игроками. их пролитые статы должны тоже как-то убираться. вместе с мортами мб флагом этим аренным (который от хоругви).

**Comment by garkins** [comment]
мне в какой-то момент Мизуро дал 1000 ногат которые залутал с Лерины. и это на третьей минуте арены

**Comment by Daniil-Gusev** [comment]
а да и вопрос с прославлеными игроками. их пролитые статы должны тоже как-то убираться. вместе с мортами мб флагом этим аренным (который от хоругви).
а разве не убираются? стриб делал вроде. 
мне в какой-то момент Мизуро дал 1000 ногат которые залутал с Лерины. и это на третьей минуте арены
мне в телеге предложили давать фиксированно кроме процента с кошелька ногаты с игроков, чтоб пвп было нужнее еще. я добавил в качестве эксперимента. 1000 ногат это из-за бага с ядом, там куча ногат из воздуха производилось. фиксированные ногаты отключил. цены надо менять, так как они был несбалансированными. я пока делаю это, как умею, но помощников что-то не видно.

**Comment by Daniil-Gusev** [comment]
Еще такое, просто стоиш и смотриш, ибо ты задел одного моба а втыкнулись еще 20-30.... надо чутку убрать флаг ассистит, хотя бы у половины мобиков, а то выходит побоище
в качестве эксперимента убрал ассист с аренных мобов.
фляжки должны быть с черным это очевидно. красное неочевидно
сделано.

**Comment by bylins** [comment]
> а да и вопрос с прославлеными игроками. их пролитые статы должны тоже как-то убираться. вместе с мортами мб флагом этим аренным (который от хоругви).

слава вся снимается, чар нормализуется после этого, оставались хиты выше макса но при входе на арену и они должны скидываться на 30 лев и 20 морт

**Comment by bylins** [comment]
лечить и получается рип на арене не снимает кровотеччение от точки и яды с наемовского отравить
