### ISSUE TITLE
статусная строка на предмет задержки умений

### ISSUE THREAD

**Issue by kartozar** [bylins/mud#1285]
На некоторые умения в статусной строке отображается задержка. Например: Бм:2 богатырский молот, Пн:3 пнуть, Ог:1 оглушить ну и так дальше. На сколько реально добавить в статусную строку задержку от умения перехватить атаку?

**Comment by bylins** [comment]
а зачем выводить в статус умения у которых кулдаун 1 раунд, считай что его нет
если не смог прикрыть, у тебя глобальный кулдаун покажет

**Comment by bylins** [comment]
как вариант сделать вывод если глобальный кулдаун больше чем у скилла выводить его

**Comment by bylins** [comment]
А, тут речь о перехватить, а там вообще не выставляются кулдауны, только лаги.

**Comment by kartozar** [comment]
тут все неоднозначно. оно атаку и если не перехватывает то всеравно задержек нету. ну и статусная строка то не помешало б выводить задержки. вот лог боя с мобом который тоже перехватывает атаки. моб перехватывает, а я дальше могу бить. в данном эксперименте не использовался ни молот ни пинок, а просто руками.
https://pastebin.com/Q4iaZvyK
https://pastebin.com/Q4iaZvyK
