### ISSUE TITLE
Виртуальная комната

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1288]
![image](https://user-images.githubusercontent.com/42086238/148356915-df2d982d-dadd-4498-87c0-90cbc2952b68.png)
а чо там ингры делают?

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/148357044-5bab1f89-2b5b-4d17-b392-df10afca8409.png)

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/148357909-a6e19f81-621d-4090-aa15-1a6e1076314e.png)
это с какого перепуга оно начало конечной клеткой виртуалку давать?
кто паламал?

**Comment by bylins** [comment]
да не дает она последней виртуалку 
%echo% last %self.lastvnum%
в 1 зоне

Last 186

**Comment by bylins** [comment]
Вова помойму тебе проще дебаггером глянуть.

**Comment by bylins** [comment]
```
void im_reset_room(ROOM_DATA *room, int level, int type) {
	OBJ_DATA *o, *next;
	int i, indx;
	im_memb *after, *before;
	int pow, lev = level;
	// 40 * level / MAX_ZONE_LEVEL;

	for (o = room->contents; o; o = next) {
		next = o->get_next_content();
		if (GET_OBJ_TYPE(o) == OBJ_DATA::ITEM_MING) {
			extract_obj(o);
		}
	}

```
не заходит в виртуалку эта процедура, вон чистит лежащие ингры при репопе, а их там вон 70

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/148430870-5a405d6e-14cf-4046-9840-67da6f7aa55b.png)
а это хозяйка медной горы, чо там ландыши делают

**Comment by bylins** [comment]
и там же
![image](https://user-images.githubusercontent.com/42086238/148431048-dd6e26bb-3ea4-4e42-a8b5-2bbea2082cd6.png)
т.е. зима идет снег в пещере то!!! там нет погоды
и летние ингры

**Comment by bylins** [comment]
голову сломал сдаюсь

**Comment by vkhanayev** [comment]
Вместе с фиксом для #1287 должно стать лучше

**Comment by Svjatovit** [comment]
Некоторые ингры появляются в определенный сезон. Если ингр появился, а потом сезон сменился - его по идее кинет в виртуалку, не?

**Comment by bylins** [comment]
нет конечно, но это явно был сбой циркуля, память потекла, данные патчи не могут устранить это, оно само после ребута исчезло и не повторяется.
