### ISSUE TITLE
Изменить "держать строй", чтобы не прикрывала от стаба.

### ISSUE THREAD

**Issue by joopel** [bylins/mud#1296]
В виду того что мобы-стаберы стали абсолютно бесполезны, думаю надо вернуть возможность стабать, то есть при применении умения заколоть, игнорируется держать строй всех членов группы, работают только прикрывашки богатырей.

**Comment by bylins** [comment]
тараканы в том, что сначала выбирается цель, и только потом мад решает какую атаку на нее применить.
вот в выборе цели как раз и участвует строй. Единственный костыльный вариант, стаб стоит первой в выборе лучших атак, так что если есть умение будет применять его сначала. Так что можно проверить, если у моба есть скилл стаб, пусть игнорирует строй.

**Comment by joopel** [comment]
да, нормальный вариант, то что надо

**Comment by vkhanayev** [comment]
чо-то мне кажется что это стремное предложение, зачем усложнять игру не для топово одетых кастеров?
которых даже в средних зонах будут выность со стаба (от которого как раз стиль и должен был защитить).
рано или поздно этих флагов наставят почти всем стаберам и начнется треш.

если и делать подвижки в это сторону, то можно сделать стиль зависимым от профы (к примеру дружинники будут всё ловить, т.к. это и есть их прямое назначение), а другие профы будут пропускать стаб и т.п.

**Comment by bylins** [comment]
20 лет без строя играли и не жужжали, а тут якобы подвижки. Да и сильно сомневаюсь что это приобреттет массовый размах из-за лени.
Правда, Ярило просит меня сконвертить мобов, и все у кого есть стаб выдать игнор строя. я то сделал, но не конвертил. Жду вашего решения.

**Comment by vkhanayev** [comment]
Если и выдавать флаг, то только вручную и не всем подряд.
Силу мобов в зонах время от времени поднимают и в текущих реалиях без держать строй у кастеров шансов на выживание почти нет.
15 лет назад стаберы не убивали всех подяд со стаба, а сейчас даже танка в прадубе/р2 до красного могут стабнуть.

Тот же прадуб и Р2 сейчас далеко не топ зоны, а у нас там после стаба выживает только танк или батыр.
Если файтеров по 15 мортов в гривносетах со стаба выносят, чтоб уже про остальных говорить.

А насчет того что стаберы не опасны - не согласен. Любая ошибка (зайти в клетку без танка, флик) к стаберу - верная смерть.

Да и я за то, чтобы стиль танка защищал от всех атак, иначе какой в нем спысл? стабать много кто умеет из мобов.

**Comment by bylins** [comment]
я уже писал, что узнать какое умение будет применено нельзя. Правда никто не мешает чутку модифицировать attack_best и прогонять перед расчетом строя, чтоб узнать кака атака будет.

**Comment by vkhanayev** [comment]
Ага, но мне кажется конвертить всех мобов это перебор.
Думаю нужно дальше обсуждать варианты, чтобы не слишком усложнять игру.
Я к тому что играть можно даже минигруппой, а не комплектоваться батырами для каждого кастера.

И мне кажется изменение больше затронет "средний класс" - игроков которые не имеют 3к хп, пачку батыров и топовый стафф.
Я бы предлжить продумывать изменения, которые наоборот облегчат жизнь "среднему классу" и новичкам, но усложнят жизнь для топов.

Мобов-стаберов частенько рескают, и даже печать от них спасать не будет.
И в этом случае (даже если чар пережил стаб) в него впишется моб-файтер после того как сраскает моба-стабера, что еще уменьшит шанс выживания.

**Comment by joopel** [comment]
> Если и выдавать флаг, то только вручную и не всем подряд. Силу мобов в зонах время от времени поднимают и в текущих реалиях без держать строй у кастеров шансов на выживание почти нет. 15 лет назад стаберы не убивали всех подяд со стаба, а сейчас даже танка в прадубе/р2 до красного могут стабнуть.
> 
> Тот же прадуб и Р2 сейчас далеко не топ зоны, а у нас там после стаба выживает только танк или батыр. Если файтеров по 15 мортов в гривносетах со стаба выносят, чтоб уже про остальных говорить.
> 
> А насчет того что стаберы не опасны - не согласен. Любая ошибка (зайти в клетку без танка, флик) к стаберу - верная смерть.
> 
> Да и я за то, чтобы стиль танка защищал от всех атак, иначе какой в нем спысл? стабать много кто умеет из мобов.

Ну что за бред. Выживут танк и батыр, значит не доводи до того чтоб им выживать пришлось, у богатырей есть прикрыть - они прикроют кастеров. Сейчас группу действует двойная защита Друж кроет всю группу, богатыри кастеров. В результате про то что у нас в хай зонах мобы вообще кого-то колят можно забыть. Я специально тестил со стабающими мобами, Результат 0 из 100.  

Строй ввели, но заколотить убили. Расставлять автоматом всем мобам надо, у нас столько хай морт контента, что руками это можно проставлять неделю, либо нужна будет выгрузка по всем мобам мира, начиная с хай зон.

**Comment by vkhanayev** [comment]
В игре есть не только топ кланы, а еще и другие игроки, которые не в состоянии пережить стаб даже в средних зонах.
Да что там про стаб говорить, если их даже с руки за пару раундов выносят.

Хочень усложнить игру - начни с хай морт контента куда мид кланы и не ходят.
А выдача флага игнор строй всем подряд - затронет и мид контент. Причем усложнит до невозможности проход мид зон мид кланами, и при этом хай морт кланы и не заметят этого нововедения.

**Comment by joopel** [comment]
Я зонил лоу морт зоны когда еще строя не было и все ок былою. Мы накосячили со строем забыв про стаб. Спасибо за твое мнение и пруфы по мид зонам и мид кланам, весомый вклад.  /s

**Comment by vkhanayev** [comment]
Лоу морт зоны это наподобие загробы?
Когда строя небыло там и стабали на 300-400хп, а сейчас на 1к+ легко может залететь.

**Comment by vkhanayev** [comment]
И насчет пруфов - Миролис тать около 18 мортов. В ТТ сете в загробе со стаба от скелета сдох.
Норм так лоу морт зона и как кастерам там быть?

**Comment by joopel** [comment]
> Лоу морт зоны это наподобие загробы? Когда строя небыло там и стабали на 300-400хп, а сейчас на 1к+ легко может залететь.

с каких пор загроба стала лоу морт зоной? если там мутанты солят, это не значит что лоуморту надо.
-> Когда строя небыло там и стабали на 300-400хп, а сейчас на 1к+ легко может залететь. - КАКИМ ОБРАЗОМ если стаб не менялся? )

Понимаю, что вам казуальщики, лишь бы мобов шинковать

**Comment by joopel** [comment]
> И насчет пруфов - Миролис тать около 18 мортов. В ТТ сете в загробе со стаба от скелета сдох. Норм так лоу морт зона и как кастерам там быть?

еще раз. С каких пор в твоем понимании загроба лоу морт зона. Что там кастеру делать одному, пусть берет богатыря и тот прикрывает, как зонили всегда
