### ISSUE TITLE
Вывод уровня заклинания по "заклинания все".

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#1302]
[12] 09:45 03-12-2021 (Ревар) :: 

Такое вот.
Помоему былобы удобно при написании закл все. Увидить какие заклы, с каким уровнем открываються. Также как с способ все.
---
Глянуть, мб можно сделать малой кровью.

**Comment by bylins** [comment]
легко но будет некрасиво

**Comment by bylins** [comment]
и это всеж интрига, а когда же у тебя на новом морте закл откроется

**Comment by Svjatovit** [comment]
Способности показываются, когда откроются. Не вижу, почему бы и спеллы не показывать.

**Comment by Svjatovit** [comment]
Дубликат #1306  , закрываю.
