### ISSUE TITLE
Добавить в dg событие для предметов "раунд боя".

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1304]
срабатывает в бою: запускать каждый боевой раунд. желательно через нарг реализовать 1: шмотка в экипе, 2: шмотка в инве.

**Comment by Svjatovit** [comment]
Сделал.
1. Надо перенести обработку до начала атаки персонажа.
2. Возвращаемое значение интерпретировать как "будет ли персонаж атаковать в этом раунде".

Тоггда можно будет сделать, к примеру, предмет, который периодически заменяет атаки лечением или фрагами. Завтра доделаю.

**Comment by Svjatovit** [comment]
Готово.
