### ISSUE TITLE
Stat не статает вещи в персхране

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1311]

**Comment by bylins** [comment]
Заодно привести в порядок иммское где
962H 179M ??? Зауч:0 ОЗ:0 34L 62111073G Вых:СВЮv> где тайн.рун
 1. [1002336] посох Тайных Рун  - надет на ******[-1] в комнате [12510]
 2. [1002337] корзно Тайных Рун - надет на ******[-1] в комнате [12510]
 3. [1002339] сапоги Тайных Рун - надет на ******[-1] в комнате [12510]
 4. [1002338] перстень Тайных Рун - надет на ******[-1] в комнате [12510]
 5. [1002340] кольцо Тайных Рун - надет на ******[-1] в комнате [12510]
корзно Тайных Рун находится в хранилище дружины '******'. Vnum предмета: 2337
перстень Тайных Рун находится в хранилище дружины '******'. Vnum предмета: 2338
кольцо Тайных Рун находится в хранилище дружины '******'. Vnum предмета: 1002340
сапоги Тайных Рун находятся в хранилище дружины '******'. Vnum предмета: 2339
O  6. посох Тайных Рун  - находится в персональном хранилище (******).
O  7. корзно Тайных Рун - находится в персональном хранилище (******).
-------------------
как зря выводится

**Comment by bylins** [comment]
Вова см название тикета, ты стат забыл починить :)

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/151240980-c854728e-b533-4cf4-9e4a-a9170bc7b6c6.png)
бардак не устранен

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/151305472-60c0d246-971a-4870-adc4-6f4d6f96680f.png)
а это еще где

**Comment by Svjatovit** [comment]
Сделано.
