### ISSUE TITLE
новое поле для dg char.apply_value

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1320]
char.apply_value(str)
возвращает модификатор апплая str (если на чаре аффект +5 к силе то char.apply_value(сила) должно вернуть 5)

**Comment by Svjatovit** [comment]
Эээ.. во-первых, зачем? Там и так возвращается отдельно родная сила и с учетом надетой/обкаста. Во-вторых, апплай - это просто эффект. В теории можно его хоть к "полету" привесить. Т.е. надо все аффекты проверять и суммировать. Да и вообе, по-хорошемиу в подавляющем большинстве случаев надо тупо брать силу с учетом обкаста и надетого. Если можно надеть  накастовать гору силы - это проблема баланса в целом, а неконкретной зоны. В общем, что-то сомнительное. Зачем оно потребовалось?

**Comment by bylins** [comment]
У нас в триггерах нигде не возвращается, только есть или нет апплай, и есть ли например таже сила в сумме.
Сколько набафано неизвестно.

**Comment by Daniil-Gusev** [comment]
зачем использую я: чтоб сделать на арене свиток, который при каждом использовании будет повышать бонус ко всем умениям на 10, что решит проблему у меня преимущества файтеров при уравнивании. 
как использовать более глобально? можно будет навешивать стакающиеся дебаффы в баттлтриггах для каждого чара: если чар уже собрал 3 стака и в итоке имеет -6 силы апплаем например, то ему еще снизим больше, а если чар только впервые попал под дебафф, то ему вычтется несколько единичек.

**Comment by bylins** [comment]
Жалоб нет закрываю
