### ISSUE TITLE
Добавление школ магии волхвам

### ISSUE THREAD

**Issue by pilaty** [bylins/mud#1326]
Добавить школы магии:
- света
- жизни
- разума

**Comment by pilaty** [comment]
if (i->get_trained_skill(SKILL_DARK_MAGIC) > 0)
		strcat(aura_txt, "...сферы всех магий кружатся над головой");		
	else if (i->get_trained_skill(SKILL_LIGHT_MAGIC) > 0)
		strcat(aura_txt, "...сферы шести магий кружатся над головой");	
	else if (i->get_trained_skill(SKILL_AIR_MAGIC) > 0)
		strcat(aura_txt, "...сферы пяти магий кружатся над головой");	
	else if (i->get_trained_skill(SKILL_EARTH_MAGIC) > 0)
		strcat(aura_txt, "...сферы четырех магий кружатся над головой");	
	else if (i->get_trained_skill(SKILL_WATER_MAGIC) > 0)
		strcat(aura_txt, "...сферы трех магий кружатся над головой");	
	else if (i->get_trained_skill(SKILL_FIRE_MAGIC) > 0)
		strcat(aura_txt, "...сферы двух магий кружатся над головой");	
	else if (i->get_trained_skill(SKILL_LIFE_MAGIC) > 0)
		strcat(aura_txt, "...сфера жизни кружит над головой");

**Comment by Svjatovit** [comment]
Так сикллы через конфиг доабвляются. Или у волхвов не учиытваются сами скиллы?

**Comment by bylins** [comment]
там последовательность выдачи, типа школу огня не получить если ты не выучил школы жизни.
в коде костылями

**Comment by Svjatovit** [comment]
> там последовательность выдачи, типа школу огня не получить если ты не выучил школы жизни. в коде костылями

Я такой дичи точно не делал. Кто и зачем это сделал, спрашивается?

**Comment by bylins** [comment]
делал я, было обсуждение, мне выдано ТЗ
где-то в закрытых ветках тут, если не лениво ищи под названием АП волхва, или по коммиту тамм ссылка будет на тикет

**Comment by Svjatovit** [comment]
В общемю. Ограничений на изучение скиллов магии я что-то в коде не вижу. Или как-то хитро обернули. Доступные скиллы прописываются в конфиге, а не в коде. А отображение скиллов у волхва посторонник я вырезал, нечего палить статистику чужого персонажа.
