### ISSUE TITLE
Добавить в ДГ возможность проверки, ID чего именно находится в перменной.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#1327]
В некоторых случаях (например, при поиске по имени) в переменную может попасть неизветсный объект - предмет или персонаж. Хочется иметь способ проверить, что именно находится в переменной. Можно либо добавить всем трем типам объектов поля is_char, is_object, is_room, которые возвращают true только если соответствующая переменная указывает на орбъект соответствующего типа. Другой вариант - функция а-ля %what(%id%)%, которая возвращает строку char, obj или room. Но это влечет сравнение результата со сторокой, что медленней.

**Comment by bylins** [comment]
Нифига там не влечет, первый символ смотрится
