### ISSUE TITLE
Сопротивления

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1334]
```
	CASE("Resistances") {
		auto array_string = split_string(value);
		if (array_string.size() < 7 || array_string.size() > MAX_NUMBER_RESISTANCE) {
			log("SYSERROR : Excepted format <# # # # # # # #> for RESISTANCES in MOB #%d", i);
			return;
		}
		for (unsigned kk = 0; kk < array_string.size(); kk++) {
			GET_RESIST(mob_proto + i, kk) = MIN(300, MAX(-1000, atoi(array_string[kk].c_str())));
		}

```

**Comment by bylins** [comment]
сделать кап 100% переделать calculate_resistance_coeff в расчете на новый кап, поправить олц на новый кап, но и сконвертировать резисты мобов поделив на 3

**Comment by joopel** [comment]
только живучесть + надо продумать что делать с точкой, так как живучесть порежем, и витязи будут пылесосить мобов в 3 раза сильнее.

![image](https://user-images.githubusercontent.com/25629791/150420180-ba0939b6-8169-491d-8780-3aa6f13d849d.png)
Дагомир топ дамагер, войкан - лоу морт витязь, то 5 дамага
+ проблема витязя как вижу, в овердамаге при зонинге и при пк - один щелбан и даже самый толстый танк - покойник.
Создам, наверное, другое issue

**Comment by Svjatovit** [comment]
Про ауры не забудьте. Они некисло рехисты повышают.

**Comment by bylins** [comment]
ауры я отдельным тикетом заведу и переведу не на левел а на скил магии

**Comment by bylins** [comment]
вроде все работает ждем изменение справки и закрываем

**Comment by Svjatovit** [comment]
> ауры я отдельным тикетом заведу и переведу не на левел а на скил магии

Да епрст.. не надо ничего "заводить на левел". Вот вообще ничего. Скиллы магии для того и были введены.
