### ISSUE TITLE
перехватить атаку в продолжение. показываю логи.

### ISSUE THREAD

**Issue by kartozar** [bylins/mud#1337]
в статусной строке при фейле не выдается сообщение типа пр:3, и нету сообщения вам не удалось перехватить атаку. показываю логи и в них же коментирую. комент начинается на +++
Чтоб тут не мусорить, и уважать общество, на лог даю ссылку. кому надо будет, тот откроет.
https://pastebin.com/nfGSngYp

**Comment by kartozar** [comment]
кроме того, обнаружилось, что на перехватить атаку, и на прикрыть, используются одни и те ж две буквы, тоесть пр:
Думаю, что оно может как-то мешать.

**Comment by kartozar** [comment]
сегодня я тестировал то ничего не изменилось. дело в том, что ни буквы на перехват ни задержки не изменились. Я незнаю. то новый лог подавать или как поступить?

**Comment by bylins** [comment]
Буквы остались таки еже, изменились у прикрыть, задержки тоже не менялись, зачем менять то что и так работает
