### ISSUE TITLE
найм у купца. минимальная цена и морты для найма.

### ISSUE THREAD

**Issue by garkins** [bylins/mud#1340]
Цель если у жертвы больше мортов чем у нанимателя - неудача.
И чтобы стоимость часа найма не была меньше чем золота в прототипе моба.
------- это то что мы там обсуждали про прототип
int min_price = MAX(m_dr / 300 * GET_REAL_LEVEL(victim), GET_REAL_LEVEL(victim) * 5));
int min_price = МАХ(min_price, mob_proto[GET_MOB_RNUM(victim)].get_gold());

----- а про морты мы не обсуждали ))))

**Comment by garkins** [comment]
src/cmd/hire.cpp - 225я строчка туда что-то типа
Roman Sunko, [22.01.2022 7:48]
вот нам сюда надо вставить

Roman Sunko, [22.01.2022 7:49]
типа else if (GET_REMORT(ch) < GET_REMORT(helpee))

Roman Sunko, [22.01.2022 7:50]
send_to_char("Подрасти бы тебе!\r\n",ch)

**Comment by Timeofgod** [comment]
Предлагаю сделать завязку от 30 уровня(поскольку большинство топ-чармисов именно с этого уровня начинаются) сделать чтоб нанималось только с аналогичным или большим числом мортов, уровню чармиса то есть - GET_REAL_REMORT(ch) < GET_LEVEL(helpee)

**Comment by garkins** [comment]
> Предлагаю сделать завязку от 30 уровня(поскольку большинство топ-чармисов именно с этого уровня начинаются) сделать чтоб нанималось только с аналогичным или большим числом мортов, уровню чармиса то есть - GET_REAL_REMORT(ch) < GET_LEVEL(helpee), это отбросит лоуморт купцов от найма мегачармисов, плюс отвяжет билдинг от усиления чармисов тех же самых(поскольку у нас уровни мобов проставляются кодом), еще я бы сделал на 30 именно уровне требования по мортам GET_REAL_REMORT(ch)/2 - по скольку там не такие матерые чармисы как выше и таки надо как то купцам все же выживать...

пфффф. тут не про это ведь.
1) сравниваем морты купы и морты наемника если у купы меньше - нельзя нанять
2) уровни автоматически? да нет....
цель этой движухи ограничить лоуморт купцов от хайморт чармисов и иметь возможность управлять минимальной ценой все через олц

**Comment by bylins** [comment]
Мобы кодом проставляются левела если ему установлен уровень 0.
Если уровень указан берется значение.

**Comment by Timeofgod** [comment]
> > Предлагаю сделать завязку от 30 уровня(поскольку большинство топ-чармисов именно с этого уровня начинаются) сделать чтоб нанималось только с аналогичным или большим числом мортов, уровню чармиса то есть - GET_REAL_REMORT(ch) < GET_LEVEL(helpee), это отбросит лоуморт купцов от найма мегачармисов, плюс отвяжет билдинг от усиления чармисов тех же самых(поскольку у нас уровни мобов проставляются кодом), еще я бы сделал на 30 именно уровне требования по мортам GET_REAL_REMORT(ch)/2 - по скольку там не такие матерые чармисы как выше и таки надо как то купцам все же выживать...
> 
> пфффф. тут не про это ведь.
> 
> 1. сравниваем морты купы и морты наемника если у купы меньше - нельзя нанять
> 2. уровни автоматически? да нет....
>    цель этой движухи ограничить лоуморт купцов от хайморт чармисов и иметь возможность управлять минимальной ценой все через олц

минимальной ценой через олц - флаг в зубы, а вот ограничение хаймортов - я именно это и предложил так то! Читай чего написано!

**Comment by bylins** [comment]
так и сделано уже, проснись :)
