### ISSUE TITLE
посмотреть, можно ли на арене вне боя длительность холда, слепи итп изменить. 

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1344]
субж

**Comment by Svjatovit** [comment]
В каком смысле? Сечас аффекты (некоторые) по-разному тикают, если персонаж в бою и вне его. Можно сделать какой-то особый режим, если персонаж вне боя, но на клетке "арена". Правда тут сразу потенциальные абьюзы, типа пришел в город и забежал на арену. 

Но в любом случае вопрос, что нужно от длителньости аффектов?

**Comment by bylins** [comment]
это на арене доминирования, я прикидывал, не сложно, у нас пульс в бою и вне боя разные процедуры считает время то.
