### ISSUE TITLE
Новая арена доминирование

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1345]
i5 962H 179M ??? Зауч:0 ОЗ:0 34L 62111073G Вых:Ю> tstat 15033
Name: 'раунды загрузки мобов на арену',  VNum: [15033], RNum: [ 1866]
Trigger Intended Assignment: Rooms
Trigger Type: Auto, Numeric Arg: 100, Arg list: None
Commands:
   context 150
   eval time %date.unix%
   if %battle%
     detach 15082 %world.room(15001)%
     eval chars %team1.cdr% %team2.cdr% %team3.cdr% %team4.cdr% %team5.cdr% %team6.cdr%
     eval chars %chars.trim%
     eval num %chars.words%
     eval tmp %num%*2
     eval tmp2 %num%*3/2
     eval tmp3 %num%
     eval tmp4 (%num%/2)+1
     eval tmp5 (%num%/3)+1
     eval tmp6 (%num%/4)+1
     eval tmp7 (%num%/5)+1
     eval tmp8 (%num%/6)+1
     eval tmp9 (%num%/7)+1
     eval count %tmp% %tmp2% %tmp3% %tmp4% %tmp5% %tmp6% %tmp7% %tmp8% %tmp9%
     eval hares 15010 15020 15030 15040 15050 15060 15070 15080 15090
     eval falcons 15011 15021 15031 15041 15051 15061 15071 15081 15091
     eval bears 15012 15022 15032 15042 15052 15062 15072 15082 15092
     eval lions 15013 15023 15033 15043 15053 15063 15073 15083 15093
     eval wolves 15014 15024 15034 15044 15054 15064 15074 15084 15094
     eval lynxes 15015 15025 15035 15045 15055 15065 15075 15085 15095
     eval bulls 15016 15026 15036 15046 15056 15066 15076 15086 15096
     eval snakes 15017 15027 15037 15047 15057 15067 15077 15087 15097
     eval room1 15031 15032 15035 15057
     eval room2 15021 15022 15030 15043
     eval room3 15024 15023 15025 15046
     eval room4 15027 15026 15028 15049
     eval room5 15081 15080 15082 15039
     eval room6 15084 15042 15075 15083
     eval room7 15076 15067 15071 15072
     eval room8 15078 15036 15077 15079
     while %round% <= 9
       %zoneecho% 15000 раунд %round%!!!
       eval count1 %count.words(%round%)%
       eval count2 %count1%
       eval count3 %count1%
       eval count4 %count1%
       eval count5 %count1%
       eval count6 %count1%
       eval count7 %count1%
       eval count8 %count1%
       wait 5
       while %count1% > 0
         %at% %array.item(%room1%, %random.4%)% %load% mob %array.item(%hares%,%round%)%
         eval count1 %count1% -1
       done
       eval c1 %c1%+1
       worlds c1
       wait 5
       while %count2% > 0
         %at% %array.item(%room2%, %random.4%)% %load% mob %array.item(%falcons%,%round%)%
         eval count2 %count2% -1
       done
       eval c2 %c2%+1
       worlds c2
       wait 5
       while %count3% > 0
         %at% %array.item(%room3%, %random.4%)% %load% mob %array.item(%bears%,%round%)%
         eval count3 %count3% -1
       done
       eval c3 %c3%+1
       worlds c3
       wait 5
       while %count4% > 0
         %at% %array.item(%room4%, %random.4%)% %load% mob %array.item(%lions%,%round%)%
         eval count4 %count4% -1
       done
       eval c4 %c4%+1
       worlds c4
       wait 5
       while %count5% > 0
         %at% %array.item(%room5%, %random.4%)% %load% mob %array.item(%wolves%,%round%)%
         eval count5 %count5% -1
       done
       eval c5 %c5%+1
       worlds c5
       wait 5
       while %count6% > 0
         %at% %array.item(%room6%, %random.4%)% %load% mob %array.item(%lynxes%,%round%)%
         eval count6 %count6% -1
       done
       eval c6 %c6%+1
       worlds c6
       wait 5
       while %count7% > 0
         %at% %array.item(%room7%, %random.4%)% %load% mob %array.item(%bulls%,%round%)%
         eval count7 %count7% -1
       done
       eval c7 %c7%+1
       worlds c7
       wait 5
       while %count8% > 0
         %at% %array.item(%room8%, %random.4%)% %load% mob %array.item(%snakes%,%round%)%
         eval count8 %count8% -1
       done
       eval c8 %c8% +1

Листать : <RETURN>, Q<К>онец, R<П>овтор, B<Н>азад, или номер страницы (1/2).
       worlds c8
       eval num 240 +(%array.item(%chars%)%*6)
       wait %num%s
       eval round %round% +1
       worlds round
     done
   end
   eval time2 %date.unix%-%time%
   worlds time2

**Comment by bylins** [comment]
Милий, все переменные загоним в worlds, переложить на хардкод читая переменные из контекста, названия переменных константа.
т.е. после каждого eval его в worlds объявим

этот триггер почему-то обнуляется с переменными в DG,

**Comment by bylins** [comment]
```
eval tmp %num%*2
eval tmp2 %num%*3/2
eval tmp3 %num%
eval tmp4 (%num%/2)+1
eval tmp5 (%num%/3)+1
eval tmp6 (%num%/4)+1
eval tmp7 (%num%/5)+1
eval tmp8 (%num%/6)+1
eval tmp9 (%num%/7)+1
eval count %tmp% %tmp2% %tmp3% %tmp4% %tmp5% %tmp6% %tmp7% %tmp8% %tmp9%
```
ну и этот треш бы в формулу

**Comment by bylins** [comment]
грубо начиная с while %count1% > 0
ессно никаких вайтов

**Comment by garkins** [comment]
1) как и говорил зачем столько сетов? и один не соберешь
2) зачем в покупных вещах за твои ногаты нефлик? пока разберешься где он.

имхо - нужны обычные шмотки +- как были. хотите сеты - добавляйте пусть 2 3 одетых вещи активятся как-то. кузей комфортно играть но после третьей волны уже мобы круче тебя. кастерам хоругвь должна больше хп давать сразу. рулят чармисы и кузнецы. чармисы супер имбаланс.

**Comment by vkhanayev** [comment]
пример скрипта для теста


context 150
eval hares 15010 15020 15030 15040 15050 15060 15070 15080 15090
eval falcons 15011 15021 15031 15041 15051 15061 15071 15081 15091
eval bears 15012 15022 15032 15042 15052 15062 15072 15082 15092
eval lions 15013 15023 15033 15043 15053 15063 15073 15083 15093
eval wolves 15014 15024 15034 15044 15054 15064 15074 15084 15094
eval lynxes 15015 15025 15035 15045 15055 15065 15075 15085 15095
eval bulls 15016 15026 15036 15046 15056 15066 15076 15086 15096
eval snakes 15017 15027 15037 15047 15057 15067 15077 15087 15097

eval hares_rooms 15031 15032 15035 15057
eval falcons_rooms 15021 15022 15030 15043
eval bears_rooms 15024 15023 15025 15046
eval lions_rooms 15027 15026 15028 15049
eval wolves_rooms 15081 15080 15082 15039
eval lynxes_rooms 15084 15042 15075 15083
eval bulls_rooms 15076 15067 15071 15072
eval snakes_rooms 15078 15036 15077 15079

eval mobs_count 2 3 4 5 6 7 8 9 10

eval debug_messages 1

arena_round 3
wait 100
arena_round 7
