### ISSUE TITLE
 show triggers

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1347]
чтоб писало список какие триггера сейчас на выполнении

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/150693060-7426915f-068b-483a-97b6-4d5d4d07980d.png)
чищу стату и все равно через 3-5 секунд опять триггера более секунды

**Comment by Daniil-Gusev** [comment]
хорошо бы еще указывать obj/mob/room триггер и на внуме какого обжа/моба/комнаты прикреплен.

**Comment by bylins** [comment]
он пока нужен для другого, хватит внума и названия пока

**Comment by bylins** [comment]
потестирую пока не закрываю
