### ISSUE TITLE
Игнор лист для игроков

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#1362]
Что думаете есть ли сделать что-то типо личного игнор листа 
что бы работало как то так :
добавить игнор Пилатий
вы игнорируете личные сообщение, болтать, офтоп, гс, гд для данного игрока
удалить игнор Пилатий 
вы больше не игнорируете все сообщения данного игрока

Я думаю такое нововведение упростило бы жизнь многим.

**Comment by bylins** [comment]
а чем это отличается от команды
игнор добавить пилатий все
 ?

**Comment by Svjatovit** [comment]
Игнор уже есть. Или в нем не хватает каких-то функий?

**Comment by bylins** [comment]
Это кудо глючит :)))))
