### ISSUE TITLE
Античит в oedit

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1364]
сделать и для оффлайн шмота по аналогии с
#1363

**Comment by Svjatovit** [comment]
ИМХО, если у челвоека ОЛЦ, то при наличии хоть пары извилин он что угодно начитит, нигде не спаливашись. Делать по этому поводу костыли в ОЛЦ бесполезно, только читать перслог ну и не выдавать кому попало.

**Comment by bylins** [comment]
Там немного для другого сделано, чтоб изменения объектов применялись во всем мире.
Сейчас не трогает ренту, но там сделать легко, пример есть

**Comment by bylins** [comment]
Хотя брешу что легко, ведь кроме таймера поля предмета в ренте не доступны
