### ISSUE TITLE
Проверка на правильность предтитула по УКБ

### ISSUE THREAD

**Issue by shevelev** [bylins/mud#1380]
Для того, чтобы не тратить времени богов + игроков на правильность установки предтитула (только первое слово с большой буквы, остальные с маленькой) и возможности получить нелепую 1 неделю ада, предлагаю в файле https://github.com/bylins/mud/blob/master/src/title.cpp внести правки:
1. или сразу в функции установки предитула воткнуть вторую часть чтобы предтитул с 1 символа по последний были маленькими, сейчас же только принудительно 1 буква предтитула идет большой.
2. дополнить или создать новую мелкую функцию, на входе в которую будет предтитул, внутри он бьется на массив с разделителем пробел и принудительно каждый итем массива опускаем в нижний регистр, потом соединть массив в одну строку и отдать ее обратно для сохранение в аккаунт.

**Comment by Svjatovit** [comment]
Это все проще делается. И функции для снижения регистра и капитализация первого символа в коде есть. То есть тупо весь предтитул прогоняем через нижний регистр, потом первый символ ставим прописной.

**Comment by garkins** [comment]
там надо возможно УКБ менять. некоторые титулы просят заюзать большую букву

**Comment by bylins** [comment]
изменится УКБ менять код?
