### ISSUE TITLE
по  перехвату в продолжение

### ISSUE THREAD

**Issue by kartozar** [bylins/mud#1390]
на данный момент исправлены буквы в статусе на Пх:, соответственно опохмелиться, на Опх:. и все ббы было хорошо, но с задержками там не все так гладко. часто есть так, что ни фейла нету, и молот блокируется до успешного перехвата.
Хочу показать лог файл, который лежит вот тут:
https://pastebin.com/zt9t1MpJ

**Comment by bylins** [comment]
бред

**Comment by bylins** [comment]
все как и положено, если по тебе не попали, перехватить продолжает работать, и не работать молот.
Как попадут, флаг что ты стоишь перехватываешь снимется.
Никакие кулдауны тут не причем и в статусе появляться ничего не должно
```
		for (const auto vict : people) {
			if (dam < 0) {
				break;
			}

			hit_touching(ch, vict, &dam);
		}

```
