### ISSUE TITLE
и что это в дг было?

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1412]
создаем random room триггер, прикрепляем к руме 100:
eval list элемент1 элемент2 элемент3 элемент4 элемент5
foreach i %list%
eval tmp %i%
wait 60s
done
ждем пока тригг запустится и встанет на паузу, статнем комнату, и в переменных триггера увидим такое:
i{18B3D8D1-240E-4D60-AEAB-6748580CA460}:  элемент1 элемент2 элемент3 элемент4 элемент5

**Comment by vkhanayev** [comment]
Всё ок, это вывод внутрего состояния foreach.
Чуть улучшил читаемость вывода. Если будет мешать - можно просто отключить вывод внутренних переменных состояния.
