### ISSUE TITLE
Изменить работу dg-команды arena_round

### ISSUE THREAD

**Issue by vkhanayev** [bylins/mud#1419]
короче в mobs_count я буду давать не количество загружаемых мобов каждого вида, а суммарное количество загружаемых мобов. ну тоесть если первым словом в mobs_count идет число 96, то в 1 раунде грузим 96 мобов суммарно. нужно в с++ части уже завести переменную, которая будет содержать количество загружаемых мобов каждого вида, получать в нее значение надо целочисленным делением mobs_count/8
далее когда загрузил по mobs_count/8 мобов каждого вида создаешь еще переменную и в нее записываешь результат остатка от деления mobs_count/8
если остаток будет больше 0, то крутишь цикл пока эта переменная не станет 0, при этом на каждой итерации случайным образом выбирай массив мобов (bears, hares, volves итп, всего 8 массивов) и из выбранного грузи моба, который находится на round позиции в массиве. ну тоесть допустим выбрал массив с волками, и если щас раунд 3, то берешь третее слово из массива volves и грузишь этого моба в рандомную клетку из его списка: для волков volves_rooms.

**Comment by Daniil-Gusev** [comment]
[26-02-22 22:04:55][ SCRIPT LOG (Trigger: раунды загрузки мобов на арену, VNum: 15233) : Неверный счетчик мобов в переменной mobs count: 32 ]
