### ISSUE TITLE
Почему-то кривое значение из таблиц

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1429]
int app = 25 real int = 35
int app = 15 real int = 25
int app = 22 real int = 32
это int_app[GET_REAL_INT(ch)].to_skilluse

таблица якобы

а берет -10 от инты

constants.cpp
struct IntApplies int_app[] =
.....
{95, 7, 135, 0, 10, 7},
    {95, 8, 140, 0, 10, 7},
    {95, 8, 145, 0, 10, 7},
    {95, 8, 150, 0, 10, 7},
    {96, 9, 150, 0, 11, 8},    // int = 35
второй это скилюз

**Comment by Svjatovit** [comment]
Значения берутся из файла basic.lst Значения, которые прописаны в коде, используются, если файл не удалось прочитать.
