### ISSUE TITLE
Лаги в маде 2[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#143]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Первоначально достигли того что хотели, тиковые лаги пропали, ну и сильно разгрузили мад это продолжение see #117

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/143

=======COMMENTS=======

Date: 2018-03-14T06:49:52Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

кстати на зеркале тряпочка не спамит

Date: 2018-03-14T06:19:58Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

видимо при otransform 35916 удаляется, но вопрос, почему тогда не спамит сухая тряпка так же?

Date: 2018-03-14T06:10:31Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

```
#!c++

Trigger Intended Assignment: Objects
Trigger Type: Random,Auto, Numeric Arg: 0, Arg list: None
Commands:
   if (%self.vnum% == 35916)
     otransform 35917
   else
     otransform 35916
   end
```
35917 сухая трапочка

Date: 2018-03-14T06:08:16Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Мать хозяина хутора прекратила использовать сухую тряпочку.  
Мать хозяина хутора дала сухую тряпочку старухе.  
  
i25 3308H 179M ??? Зауч:0 34L 9741963G Вых:З>   
  
Старуха заботливо смочила тряпочку в тазике с водой.  
  
i25 3308H 179M ??? Зауч:0 34L 9741963G Вых:З>   
  
Старуха дала мокрую тряпочку матери хозяина хутора.  
  
i25 3308H 179M ??? Зауч:0 34L 9741963G Вых:З>   
  
Мать хозяина хутора водрузила мокрую тряпочку на голову.  
Мать хозяина хутора с хрипом вздохнула и закашлялась.

Date: 2018-03-14T06:01:42Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Могу предположить, что при ресете сначала ресетится мать хозяина хутора, соответственно держатель тряпочке становится null, а потом сама тряпочка

Date: 2018-03-14T05:58:33Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Понятия не имею, но когда я это делал, некоторые вещи при ресете зоны не определялись где они

Date: 2018-03-14T05:55:40Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

а почему она room 0  
O  1. мокрая тряпочка           - надет на мать хозяина хутора[35901] в комнате [35988] Vnum предмета: 35916

Date: 2018-03-13T22:08:10Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Ох уж эта мокрая тряпочка vnum == 35916 room = 0, весь мад лагает )

Date: 2018-03-13T18:18:24Z

*Original comment by* **Anton Gorev (Bitbucket: [kvirund](https://bitbucket.org/kvirund), GitHub: [kvirund](https://github.com/kvirund))**

----------------------------------------

Attachment contains output of

```
#!text
$ cat syslog | grep -e 'Missed\|Long-running' -C 2 > temp
```

**Comment by Svjatovit** [comment]
Вроде бы уже не актуально.
