### ISSUE TITLE
ch->get_level()

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1434]
GET_LEVEL поменяно на GET_REAL_LEVEL а вот ch->get_level() не весь

**Comment by bylins** [comment]
int GetRealLevel(const CharData *ch)

**Comment by Svjatovit** [comment]
А зачем его мнять? Я наоборот везде макросы убираю.

**Comment by bylins** [comment]
ch->GetRealLevel() там должно быть

**Comment by bylins** [comment]
везде кроме записи в пфайл
