### ISSUE TITLE
с аффектом доминирование выпадает оружие из рук при сохранении чара

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1444]
когда в ручном и автоматическом режиме чар сохраняется, то у него из рук выпадает оружие в случае, описанном ниже, доказано.
заходим на чара с маленькой силой, например тот же колд. создаем оружие с таким весом, чтоб с текущими параметрами чар не смог им вооружиться, но смог бы с аффектом доминирование. надеваем шмотку с аффектом доминирование и вооружаемся тем оружием, пишем "сохранить". как результат: оружие падает из рук. при ручном сохранении этого вроде бы не происходит, но еще на автосейв есть подозрение в том, что если чар заучил под доминированием закл, который ему в без доминирования не доступен, то при сохранении он исчезнет из мема.

**Comment by bylins** [comment]
афф доминирования не добавляет силу, уточни что значит "создаем оружие с таким весом, чтоб с текущими параметрами чар не смог им вооружиться, но смог бы с аффектом доминирование"

**Comment by Daniil-Gusev** [comment]
доминирование не дает силу, но ее дают морты, которые дает доминирование, если морты чара без доминирования меньше 20.

**Comment by bylins** [comment]
в save_char
    while (!affected.empty()) {
      affect_remove(affected.begin());
все снимается и принудительно пересчитывается affect_total
присутствует комментарий зачем
		 * remove the affections so that the raw values are stored; otherwise the
		 * effects are doubled when the char logs back in.
