### ISSUE TITLE
Неправильный расчет магдамаги

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1450]
dam += dam * (1 + ch->get_skill(skill_id))) / 500.0);
так же для мудрости

**Comment by bylins** [comment]
увеличивает маг. урон на 10%
находится тут
int Damage::Process(CharData *ch, CharData *victim) {

**Comment by Daniil-Gusev** [comment]
в догонку: сделать для шмота апплаи увеличение физ урона и увеличение маг урона в процентах, сейчас есть только на сетах.

**Comment by Daniil-Gusev** [comment]
для физ урона в процентах уже есть апплай "дополнительный бонус повреждений", надо переименовать.
