### ISSUE TITLE
Добавить новые апплаи

### ISSUE THREAD

**Issue by Maksuckan** [bylins/mud#1458]
Создать apply на умения: лидерство +10

Возможно добавить:
                                           магия.воды +10
                                           магия.воздуха +10
                                           магия.земли +10 
                                           ...... etc

**Comment by Daniil-Gusev** [comment]
ну значение указывать вряд ли надо, просто апплаи, прибавляющие указанные умения, а значение уже можно будет проставить.

**Comment by Svjatovit** [comment]
Угу. И на каждое умение по аплаю. У предметов уже есть поле "увеличивает умение".

**Comment by Maksuckan** [comment]
Мне не нужны все, нужны только магии и лидерка, навесить апплаями на камни ювелира. Да и скорее всего сейчас не актуально станет, бо Стриб зашел с другой стороны, дает присваивать скиллы.

**Comment by bylins** [comment]
переделал вплавить, можно паять новый параметр "умение"
