### ISSUE TITLE
Новые варнинги

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1473]
/home/mud/mud/src/cmd/flee.cpp: In function 'void go_flee(CharData*)':
/home/mud/mud/src/cmd/flee.cpp:54:87: warning: arithmetic between floating-point type 'double' and enumeration type 'EDirection' is deprecated [-Wdeprecated-enum-float-conversion]
   54 |                 && !bernoulli_trial(std::pow((1.0 - static_cast<double>(correct_dirs) / EDirection::kMaxDirNum), EDirection::kMaxDirNum))) {

/home/mud/mud/src/act_movement.cpp: In function 'int calcDrunkDirection(CharData*, int, bool)':
/home/mud/mud/src/act_movement.cpp:587:95: warning: arithmetic between floating-point type 'double' and enumeration type 'EDirection' is deprecated [-Wdeprecated-enum-float-conversion]
  587 |                         && !bernoulli_trial(std::pow((1.0 - static_cast<double>(correct_dirs) / EDirection::kMaxDirNum), EDirection::kMaxDirNum))) {

**Comment by bylins** [comment]
вспом болт сломалас

**Comment by Svjatovit** [comment]
Сделано.
