### ISSUE TITLE
дополнить счет все и счет список

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1482]
вывести в счет все и счет список дополнительный бонус опыта и волшебное уклонение.

**Comment by Daniil-Gusev** [comment]
для счет список
из строчки
Попадание: 14, повреждение: 51, запоминание: 20, успех колдовства: 0, удача: 38, инициатива: 15, маг.урон: 0, физ. урон: 0.
убираем процентные бонусы
Попадание: 14, повреждение: 51, запоминание: 20, успех колдовства: 0, удача: 38, инициатива: 15.
и после этой строки выводим еще одну
Бонусы в процентах: маг.урон: 0, физ.урон: 0, опыт: 0.

**Comment by bylins** [comment]
готово
