### ISSUE TITLE
способность врачеватель

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1505]
сделать новую способность врачеватель, снижающую кулдаун скилла лечить.

**Comment by Daniil-Gusev** [comment]
в игре уже имеется способность целитель, переименовать ее в "врачеватель" и выдать всем профам, у которых есть скилл лечить. снизить от использования умения лечить со способностью кулдаун вдвое и увеличить со способностью скорость развития умения.

**Comment by dr-hools** [comment]
Можно добавить способность на подобии врачевателя, но которая будет увеличивать полезность бинтов 
Например больше хп от возможности свитка, или дополнительно снимать плохой аффект

**Comment by bylins** [comment]
способность врачаватель есть, делит кулдаун на 2
плюшки от нее спорно

**Comment by Daniil-Gusev** [comment]
как вариант со способностью врачеватель сделать возможность использовать фит на цель, у которой любое количество хп, а не 30% и меньше.
