### ISSUE TITLE
каменное_проклятие vs круг_пустоты[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#151]
*Originally reported by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Допустим 90 визды, 30 лвл

Каменное проклятие: Урон: 18d90+16 (34...1636) в случае удачи и 12d90+30 (42...1110) в случае неудачи. Шанс оглушения: 25% (без учета резистов). Длительность оглушения: 16 раундов.

Круг пустоты: Урон: 40d80+17 (57...3217) всегда (без учета двойного урона от способности колдунов). Шанс оглушения: 50% (без учета резистов). Длительность оглушения: 17 раундов.

Почему в этом маде все для колдунов?

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/151

=======COMMENTS=======

Date: 2018-05-20T06:34:46Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Я лишь сравнил 2 очень схожих заклинания, показав огромную разница в уроне/шансе каста.

Date: 2018-05-18T08:10:48Z

*Original comment by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

Все для колдунов ? 
В текущем состоянии колдуны явяются топ 1 дамага в лоу/мидл зонах в зонах высокого уровня они мас лагеры но не дамага.
Про остальные кастерские професии молчу поскольку они чуть ниже спины в темноте.
Баланс по профам отсутствует.  Поэтому сравнивать дамагу колдуна и чернока = разговори не о чем. Просто проведте мониторинг професий
После мониторнга зададим вопрос почему все для ....

Date: 2018-04-10T15:36:10Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Это началось в 2001 году когда я взял провальную профу колдунов, именно тогда я сначала добавил увеличенный дамаг кастами по сидящим\башанным, потом увеличил дамаг в 2 раза.  Никто не хотел играть ими. Потом продолжили видимо. Режь нафиг как считаешь нужным, колдуны официально под моим присмотром, согласовывать изменения ни с кем не надо.

**Comment by Svjatovit** [comment]
Обсуждения - на форум. Вопли "господи, дай мне знаком по тыковке" - тоже,
