### ISSUE TITLE
Удача

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1510]
case ELuckTestResult::kLuckTestCriticalSuccess:
				base_percent = CalcSkillHardCap(ch, skill);
				break;
критудача в реморт кап скилла а должна в абсолютный

**Comment by bylins** [comment]
задно добавить вывод в лог тестера

**Comment by Daniil-Gusev** [comment]
щас крит удача не оч понятно как считается, предлагаю
если max(1,удача-50) <= number(1,1000)
игнорим при ударе броню, поглот, санку, призму. так будет смысл удачи выше 50.

**Comment by dr-hools** [comment]
Но тогда какой максимум удачи будет?

**Comment by Daniil-Gusev** [comment]
Но тогда какой максимум удачи будет?
а, в предыдущем сообщении забыл указать: кап удачи установить в 150.

**Comment by Daniil-Gusev** [comment]
чуть лучше вник в код, предлагается такой вариант:
const int bonus_limit = MIN(150, luck * 10);
критудача максимум 15%, и чтоб была максимальная критудача надо 15 удачи собрать.
 тогда нужно кап оставить в 15%, но убрать халяву и сделать
bonus_limit =min(150,max(1,150-(200-luck)))
таким образом критудача при удаче 200 будет 15% и выше не поднимется. если удача будет ниже 52, то шанс критудачи будет 0.1%

**Comment by Svjatovit** [comment]
Забудьте уже про существование макросов MIN и MAX. Я задолбался их из кода вычищать.

**Comment by Daniil-Gusev** [comment]
для автоатак с критудачей добавить игнор щитов.
