### ISSUE TITLE
Баги нового обновления

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1520]
Ферстах воззвал к богам с сообщением : 'Сегодня вы уже получали гривны за выполнение этого задания.'

630H 179M ??? Зауч:0 ОЗ:0 34L 50929818G Вых:СВЮv> 

Ферстах воззвал к богам с сообщением : 'У вас на руках 25367 кун и 0 гривен '
-----------------------------------
13-05-2022 20:04:39 Лирана сказал вам: только что дали гривны за квест, проверил

**Comment by bylins** [comment]
Не работают руны
2056H 202M 25000з 8230200о ОЗ:0 Пз:0 Опх:0 30L 144867G Вых:СЮЗ> колд !созд воду
Рано еще вам бросаться такими словами!
-------------------------
1880H 202M 25000з 8230200о ОЗ:0 Пз:0 Опх:0 30L 144867G Вых:СЮЗ> закл все
  Вам доступна следующая магия :
В настоящее время магия вам недоступна!
1885H 202M 25000з 8230200о ОЗ:0 Пз:0 Опх:0 30L 144867G Вых:СЮЗ> закл
  Вам доступна следующая магия :
В настоящее время магия вам недоступна!

**Comment by Daniil-Gusev** [comment]
на 12 левле моему чару открыты все доступные ему слоты способок.

**Comment by Daniil-Gusev** [comment]
видимо при смене класом сетом и при создании нового не проставляются руны в genchar
волхв нэргарод сказал, что у него касты по команде заклинания не показываются.

**Comment by Daniil-Gusev** [comment]
заклы у влохва не отображаются, но кастить их можно. нужно посмотреть, что сломалось в отображении.

**Comment by Daniil-Gusev** [comment]
имму 33 показываются сообщения канала оффтоп, но по вспомнить оффтоп историю получить не получается и писать в канал тоже нельзя с имма. вроде бы отображаться не должно.
