### ISSUE TITLE
закл все

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1534]
![image](https://user-images.githubusercontent.com/42086238/169344641-bee64cf8-d600-424e-b1a3-a7c08204ac96.png)
~~едет таблица~~
исправлено

**Comment by shevelev** [comment]
туда же
![qwe](https://user-images.githubusercontent.com/5988586/169347539-26053d52-4b4d-4461-a6fa-c42c8a0e0135.png)
.

**Comment by bylins** [comment]
это не туда, максслот класса у свента глючит, могу убрать костылем, а надо править причину
