### ISSUE TITLE
Знаки зачарования с молчей[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#154]
*Originally reported by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Периодически на знак зачарования вешается аффект молчание (с чем связано не знаю).

Это явно ошибка, т.к. если предполагалось, что аффект должен перейти на шмотку, то нет, он просто не дает колдуну кастить, если он держит в левой.
Если предполагалось, что должен кастить волхв, то он не может вешать доп.аффекты, т.к. у него нет умения магия света.

Убрать молчание со знаков или дать возможно кастить колдунам в левой с этими знаками, но при этом рассматривать молчу как один из аффектов (или всегда) при переносе на шмотку?

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/154

=======COMMENTS=======

Date: 2018-04-12T12:02:34Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Да Полель просто забил доделать, вот и обозвал фичей :)

Date: 2018-04-12T11:51:02Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Ну порежьте % выпадения, зачем нужны знаки с молчей, в чем смысл )

Date: 2018-04-12T11:42:07Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Х3, но автор зачарования считает это фичей :)

Date: 2018-04-12T11:35:58Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

как вариант, но сейчас полный бред

Date: 2018-04-12T10:53:56Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

или для знаков сделать другую таблицу апплаев, на которых нет отрицательных аффектов

**Comment by aryabenkiy** [comment]
а то что там в таблице есть слепь ? или есть холд ? я с самого начала обсуждал и было решенно что негативные аффекты должны быть. проблема по большей мере в том что это все на знаке и когда колдун берет его в руку оно переходит на колдуна. сдругой стороны если убрать навешивание  на колдуна от знаков зачарования когда он берет их в руку. тогда афект перейдет на стаф. после этого будут експеременты как с ядом. есть стаф с ядом. если его одеть и потом выпить серую колбу то яд уйдет. 

Если хотите править вперед. но не должны знаки быть только с +.

**Comment by lrdx** [comment]
Никто не против того, чтобы там были негативные аффекты (но они не должны быть на самом знаке, чтобы их можно было закастовать). На данный момент негативные аффекты рандомно накладываются при зачаровании, 25% если не ошибаюсь.
