### ISSUE TITLE
Успех колдовства[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#156]
*Originally reported by* **Urik_SH (Bitbucket: [Urik_SH](https://bitbucket.org/Urik_SH), GitHub: Unknown)**

----------------------------------------

Добавлять "успех колдовства" +1 стат, при перевоплощении всем магическим профессиям(чернокнижник, волшебник, колдун, кудесник, волхв, лекарь, купец, витязь)

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/156

**Comment by Svjatovit** [comment]
Не нужно. Если уж такая блажь выдавать халявный каст за морты, то надо привязываться к скиллам магии.
