### ISSUE TITLE
агр цветных последователей

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1560]
агр любых последователей происходит по полному любому слову из имени моба, но если имя моба цветное, то не сработает.

**Comment by Daniil-Gusev** [comment]
проверить на мобе с именем например
&RКрасное знамя&n
у меня не работало.

**Comment by bylins** [comment]
//Проверка, является ли строка arg полным именем ch
int name_cmp(CharData *ch, const char *arg) {
	char opp_name_part[200] = "\0", opp_name[200] = "\0", *opp_name_remain;
	strcpy(opp_name, GET_NAME(ch));
