### ISSUE TITLE
Креш от команды "дать денег"

### ISSUE THREAD

**Issue by prool** [bylins/mud#1572]
При попытке выполнить команду

дать 100 кун паук

происходит креш в файле currencies.cpp:200

предположительно отсутствуют падежи слова "куна"

----

Thread 1 "circle" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e13f54 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7e13f54 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555563cfd81 in currencies::CurrencyInfo::GetObjName[abi:cxx11](long, ECase) const (this=0x555556b3c9c0, quantity=100, gram_case=kAcc)
    at /home/prool/0-z/orig/mud/src/game_economics/currencies.cpp:200
#2  0x00005555563d090b in currencies::CurrencyInfo::GetObjCName (this=0x555556b3c9c0, quantity=100, gram_case=kAcc)
    at /home/prool/0-z/orig/mud/src/game_economics/currencies.cpp:239
#3  0x000055555636b819 in perform_give_gold (ch=0x555556b2ba40, vict=0x555556d3ab30, amount=100) at /home/prool/0-z/orig/mud/src/cmd/give.cpp:100
#4  0x000055555636bec0 in do_give (ch=0x555556b2ba40, argument=0x7fffffffd5bc " \320\301\325", <incomplete sequence \313>)
    at /home/prool/0-z/orig/mud/src/cmd/give.cpp:167
#5  0x000055555616420b in command_interpreter (ch=0x555556b2ba40, 
    argument=0x7fffffffd5b0 "\304\301\324\330 100 \313\325\316 \320\301\325", <incomplete sequence \313>)
    at /home/prool/0-z/orig/mud/src/interpreter.cpp:1297
#6  0x0000555555d513e6 in process_io (epoll=14, mother_desc=12, events=0x555556d51120) at /home/prool/0-z/orig/mud/src/comm.cpp:1284
#7  0x0000555555d439d5 in game_loop (epoll=14, mother_desc=12) at /home/prool/0-z/orig/mud/src/comm.cpp:1494
#8  0x0000555555d42b2d in stop_game (port=5555) at /home/prool/0-z/orig/mud/src/comm.cpp:818
#9  0x0000555555d4286e in main_function (argc=2, argv=0x7fffffffdf68) at /home/prool/0-z/orig/mud/src/comm.cpp:759
#10 0x0000555555d41dad in main (argc=2, argv=0x7fffffffdf68) at /home/prool/0-z/orig/mud/src/main.cpp:4
(gdb)

**Comment by Svjatovit** [comment]
Конфига валют нет просто, забыл выложить. В следующем апдейте будет.
