### ISSUE TITLE
БАГ- в аргументах триггеров имеет значение большая или маленькая буква.

### ISSUE THREAD

**Issue by garkins** [bylins/mud#1594]
там где не работало я починил. ну там где встретил
1) не работает в тригах вида if !%arg.contains(Ворота)%
  wsend %actor% Ну, и куда жмем-с ?
  halt

2) и там где это просто аргумент без кода

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/174601977-1f77878f-9509-4b8b-b5ef-dae99371642d.png)
там все гораздо хуже, если в аргументе с большой буквы вообще никак не работает
