### ISSUE TITLE
длительность аффектов на арене доминирование (можно и к обычной араене кстати)

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1624]
ускорить снятие негативных эффектов в 16 раз, список ниже:
оцепенение длительное_оцепенение массовое_оцепенение сон слепота полная_слепота массовая_слепота молчание длительное_молчание массовое_молчание глухота длительная_глухота массовая_глухота проклятие слабость безумие сеть шок повреждение_разума медлительность массовая_медлительность лихорадка
проверить скилл лечить, возможно там чего-то из негативного не хватает.

**Comment by bylins** [comment]
inline ESpell GetRemovableSpellId(int num) {
	static const ESpell spell[MAX_FIRSTAID_REMOVE] = {ESpell::kSleep, ESpell::kPoison, ESpell::kWeaknes, ESpell::kCurse,
		ESpell::kFever, ESpell::kSilence, ESpell::kBlindness, ESpell::kHaemorrhage,
		ESpell::kHold, ESpell::kPeaceful, ESpell::kColdWind, ESpell::kDeafness,
		ESpell::kBattle};

**Comment by Daniil-Gusev** [comment]
лечить не снимает kMindless и kSlowdown. так же не снимает kMadness и kWeb.

**Comment by bylins** [comment]
в лечить сейчас 13 аффектов
просматривается с конца, но снимаются только те, на сколько хватит скилл / 10.
например, при скилле 100 снимется афф только из первого десятка, если он выше, напишет "не хватило скилла".

**Comment by Daniil-Gusev** [comment]
предлагаю такой список для лечилки, сначала самый треш, в конце самое серьезное:
яд безумие сеть слабость медлительность повреждение_разума ледяной_ветер лихорадка проклятие глухота молчание слепота сон оцепенение кровотечение !получил в бою!
