### ISSUE TITLE
Увлечение свента переименовкой

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1625]
kPeaceful
это флаг комнаты
апплай
аффект
название одинаково, из разных енумов
но как пример - смирение это тоже kPeaceful а по идее должно быть kHumility

**Comment by Svjatovit** [comment]
Enum, если это enum class, пишется полностью. То есть, EAffect::kPeaceful. Поэтому наличие в разных перечислениях константы с одинаковым именем не мешает и не путается.

**Comment by bylins** [comment]
путает еще как, так как перед двоеточьем абракадабра и надо или по памяти помнить или поиском
