### ISSUE TITLE
телепорт всех чаров в комнате в дг на лошадках

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1635]
при телепорте
%teleport% allchar %vnum% horse
чары перемещаются без лошадок если таковые есть, но при возвращении в комнату, из которой они были перемещены, персонажи автоматически станут всадниками без дополнительного вскакивания.

**Comment by bylins** [comment]
для влд триггера готово

**Comment by bylins** [comment]
для всех вариантов готово, проверяйте и комментируйте
