### ISSUE TITLE
запретить купцам и кудесникам приводить мобов из тестовых зон, арен и прочих имбалансных зон

### ISSUE THREAD

**Issue by garkins** [bylins/mud#1655]
запретить купцам и кудесникам приводить мобов из тестовых зон, арен и прочих имбалансных зон

**Comment by bylins** [comment]
if (NPC_FLAGGED(mob, ENpcFlag::kNoMercList)) {
			SendMsgToChar(ch, "%s показал большую дулю и свалил от вас подальше.\r\n", mob->get_name());
			ExtractChar(mob));
		}
