### ISSUE TITLE
тригтелепорты (изменить телепорт по умолчанию портить всех)

### ISSUE THREAD

**Issue by garkins** [bylins/mud#1668]
1) по дефолту телепортом без аргументов телепортить всех и чармисов и лошадей
2) сделать аргументы вида nohorse nofollowers

то есть у нас сейчас чтобы телепортнуть всю разношерстную группу нужно дописывать horse followers
хочется чтоб по дефолту портило всех. а если извращенцу нужно без кого-то пусть пишет nohorse nofollowers

**Comment by bylins** [comment]
1 сделано
2 делать не буду, надо без лошадей верни их в триггере
