### ISSUE TITLE
косяки в mob триггерах[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#167]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

не работает Entry триггер, для Income добавить бы переменную room - уид клетки куда зашел моб

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/167

**Comment by Svjatovit** [comment]
Проверить и если все ок - закрыть.

**Comment by bylins** [comment]
никому не нужно
