### ISSUE TITLE
баги кудесовских чармисов

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1738]
1: чармисы, почармленные хозяином животных, могут носить экипировку. следует запретить это и разрешить экипировать только служебные предметы (когти, шкуры). кстати с названиями этих когтей и шкур есть несколько багов
1.1: когда лежат в инве чара, выглядят стопкой, даже если там двое когтей и шкур например и нормальные названия появляются, если предметы одного вида убрать из стопки.
1.2: после ребутов вроде шкуры и когти со зверей попадают в инв к кудесу и от этих предметов очень трудно избавиться, а они служебные и вообще у игрока не должны находиться.
2: если чармис чармится хозяином животных, то он может использовать старые умения, которые были до преобразований. следует это исправить, как вариант - чистить при почарме хозяином животных умения чармиса перед выставлением скиллов от хозяина животных.

**Comment by bylins** [comment]
Кому: Стрибог
   От: Белун
 
 Мобы, тип животные, почармленные кудесником, и если у них стоит флаг, одеваются, они
 могут одеваться, и они уже чит! надо это исправить чтоб не могли после почарма.
 Второе, если моб например глушит, а кудесник при почарме почармил стабера, то моб
 также стабает и глушит, надо сделать чтоб предыдущие умелки отрубались. Если надо
 подробности, то к белуну.
 Баги нашел актавиан, надо ему накинуть славы за то что не использовал а сдал.

**Comment by Daniil-Gusev** [comment]
за одно убрать скрытый удар у всех профилей и способки танцующая тень и воровской удар. железный ветер у кого есть тоже убрать, все равно не работает. проверить начисление МР, АР и ФР, если все же начисляется, то давать бонус не с 12+ морта а так же как и игрокам, вроде с 20+.

**Comment by bylins** [comment]
> 1.1: когда лежат в инве чара, выглядят стопкой, даже если там двое когтей и шкур например и нормальные названия появляются, если предметы одного вида убрать из стопки.
> 1.2: после ребутов вроде шкуры и когти со зверей попадают в инв к кудесу и от этих предметов очень трудно избавиться, а они служебные и вообще у игрока не должны находиться.

Это требует уточнений

**Comment by bylins** [comment]
флаг !бросить убрал с когтей и тыпы

**Comment by bylins** [comment]
молчат, закрываю
