### ISSUE TITLE
метка предметов.

### ISSUE THREAD

**Issue by shevelev** [bylins/mud#1755]
Суть, что метка предмета не срабатывает для применения.
Берем кольцо с гх для примера (тонкое серебряное колечко *нанна.гх*)

Вых:СВЮЗ> вз гх сум
Вы взяли тонкое серебряное колечко из сумы Незабытой Магии.
Вых:СВЮЗ> дер гх
Вы взяли тонкое серебряное колечко в левую руку.
Вых:СВЮЗ> примен гх
Возьмите в руку 'гх' перед применением!
Вых:СВЮЗ> э
<в левой руке>              тонкое серебряное колечко *нанна.гх*  <великолепно>

**Comment by bylins** [comment]
в чОм прикол?

**Comment by shevelev** [comment]
метка не срабатывает если писать применить предмет, если писать применить тонк.сереб то гх происходит.
Кольцо тип палочка с гх.

**Comment by bylins** [comment]
в мелкие баги пиши, просто не берется правильно текст

**Comment by bylins** [comment]
кстати по метке вообще поиска нет
