### ISSUE TITLE
что-то не так в голове у моба

### ISSUE THREAD

**Issue by bylins** [bylins/mud#1777]
Чернокнижник опустил руки, и земля задрожала!
Путника повалило на землю.
Путник зашатался, пытаясь удержать равновесие.
От удара чернокнижника путник отправился в мир теней.
Путник мертв, его душа медленно подымается в небеса.
Кровушка стынет в жилах от предсмертного крика путника.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник засветился таинственным светом.
Чернокнижник взял маленькую горстку кун из трупа путника.
Чернокнижник поднял труп путника.
Чернокнижник бросил труп путника.
Костяной дракон появился из клубов голубого дыма!
Костяной дракон начал следовать за чернокнижником.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник ударил костяного дракона.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник отдал приказ.
Костяной дракон ударил себя, и громко завопил 'Мамочка, больно ведь...'
Чернокнижник взглянул на костяного дракона и бросил : 'сон'.
Чернокнижник сильно ударил костяного дракона.
Костяной дракон БОЛЬНО ободрал чернокнижника.
Костяной дракон чрезвычайно сильно ободрал чернокнижника.

**Comment by bylins** [comment]
коротко комната 34203
стоит чернок, к нему зашел путник, чернок его прибил, поднял дракона и начал бить дракона

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/194006181-9e7f30e2-4ea6-4f52-9f7e-68c1c647580f.png)
просто еще раз проходил мимо :)

**Comment by bylins** [comment]
[34203] На обочине [ничего]
   Поле простирается вокруг. Несколько деревьев видны на севере. Широкий торговый тракт лежит на юге.
[ Exits: s w ]
Путник сражается с чернокнижником! 
Чернокнижник сражается с путником! 

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник БОЛЬНО ударил путника.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник взглянул на путника и бросил : 'землетрясение'.
Чернокнижник опустил руки, и земля задрожала!
Путника повалило на землю.
Путник зашатался, пытаясь удержать равновесие.
От удара чернокнижника путник отправился в мир теней.
Путник мертв, его душа медленно подымается в небеса.
Кровушка стынет в жилах от предсмертного крика путника.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник засветился таинственным светом.
Чернокнижник взял маленькую горстку кун из трупа путника.
Чернокнижник поднял труп путника.
Чернокнижник бросил труп путника.
Костяной дракон появился из клубов голубого дыма!
Костяной дракон начал следовать за чернокнижником.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник ударил костяного дракона.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:ЮЗ> 

Чернокнижник отдал приказ.
Костяной дракон ударил себя, и громко завопил 'Мамочка, больно ведь...'
Чернокнижник взглянул на костяного дракона и бросил : 'сон'.
Чернокнижник сильно ударил костяного дракона.
Костяной дракон БОЛЬНО ободрал чернокнижника.
Костяной дракон чрезвычайно сильно ободрал чернокнижника.

**Comment by bylins** [comment]
[34201] Тракт [ничего]
[ Exits: n e s w ]
*Костяной дракон сражается с чернокнижником! 
Чернокнижник сражается с костяным драконом! 

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:СВЮЗ> 

Чернокнижник взглянул на костяного дракона и бросил : 'массовое молчание'.
Костяной дракон прикусил язык!
Чернокнижник очень сильно ударил костяного дракона.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:СВЮЗ> 

Чернокнижник засветился таинственным светом.

630H 179M ??? Зауч:0 ОЗ:0 Бк:6 Из:3 34L 50955318G Вых:СВЮЗ> 

Костяной дракон сумел избежать удара чернокнижника.

**Comment by Daniil-Gusev** [comment]
создавали чернока в редакторе видимо и проставили ему там алигн -1000. в олц столько не поставишь, там от -600 до +600. у костяного дракона в прототипе стоит -600. агромобы агрятся если разница алигна с другим мобом 10+. ставлю черноку алигн -600 и закрываю.
