### ISSUE TITLE
Компиляция и запуск под CygWin'ом[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#181]
*Originally reported by* **Anton Gorev (Bitbucket: [kvirund](https://bitbucket.org/kvirund), GitHub: [kvirund](https://github.com/kvirund))**

----------------------------------------

В настоящее время работают не все Unit-тесты. В частности, отрабатывает нормально при следующем фильтре: `--gtest_filter=-Bonus_Command_Parser.*:MSDP_Builder.*:Bonus_Command_Parser_Negative.*:Boards_Changelog.*`

Нужно понять, что не так с кодом в этим тестах и устранить ошибку.

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/181

=======COMMENTS=======

Date: 2018-07-20T06:49:41Z

*Original comment by* **Anton Gorev (Bitbucket: [kvirund](https://bitbucket.org/kvirund), GitHub: [kvirund](https://github.com/kvirund))**

----------------------------------------

Под студией должно работать. Тут всё верно. Почему виснет - я хз. Надо отлаживать. Попробуй запустить из студии, но выставить текущую директорию в то место, откуда запускаешь .exe файл. Тесты требуют определённого расположения файлов, которые будут считаны (тестовые данные досок, например). При запуске .exe файла директория может оказаться другой, чем когда ты запускал под студией. Эта разница в запуске может давать разницу в результатах.

Проблема только с CygWin'ом. Вот с ним не понятно что происходит. И стек всё время дурной какой-то получается. Так что не отладишь.

Date: 2018-07-20T06:37:53Z

*Original comment by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Может я что-то делаю не так, но у меня все проходит (запускаю из студии). Если запустить отдельно .exe файл, то виснет почему-то но fight.penlaties в каком-то бесконечном цикле, но у меня это давно, я доверял запуску из студии )

**Comment by Svjatovit** [comment]
А надо ли продолжать поддержку сигвина? Это примочка времен, когда организовать свой сервер или хотя бы полноценную виртуалку у себя на компе было большой проблемой. Сейчас такой проблемы и близко нет. Можно под винду собрать, можно под виндой от 10 и выше виртуалку сделать, ниже 10 - поставить виртуалбокс и в него какой угодно линух.

**Comment by bylins** [comment]
В текущей версии цигвина все работает.
