### ISSUE TITLE
Не одобренные имена не отображаются у иммов[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#183]
*Originally reported by* **bodrich (Bitbucket: [bodrich](https://bitbucket.org/bodrich), GitHub: [bodrich](https://github.com/bodrich))**

----------------------------------------

Падежи: Тешигор/Тешигора/Тешигору/Тешигора/Тешигором/Тешигоре Имя никем не одобрено!

836H 252M ??? Зауч:0 33L 3682585G Вых:СВЮv> имя

имя - вывод списка имен, ждущих одобрения, если они есть
имя <игрок> одобрить - одобрить имя данного игрока
имя <игрок> запретить - запретить имя данного игрока
имя <игрок> удалить - удалить данное имя из списка без запрета или одобрения
836H 252M ??? Зауч:0 33L 3682585G Вых:СВЮv>

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/183

=======COMMENTS=======

Date: 2018-08-03T13:17:51Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

должны выводиться по "кто -и" но да, я как то видел забагованного игрока

**Comment by Svjatovit** [comment]
Вроде бы, сейчас все нормально отображается, не видел такого бага. Будет повторяться - переоткроем.
