### ISSUE TITLE
Починить применение палок на объекте[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#186]
*Originally reported by* **bodrich (Bitbucket: [bodrich](https://bitbucket.org/bodrich), GitHub: [bodrich](https://github.com/bodrich))**

----------------------------------------

Есть палка с доблестью (объект 33106), нужно сделать, чтобы была возможность применять на другие объекты (доблить их)

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/186

=======COMMENTS=======

Date: 2018-08-03T13:12:15Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

А почему доблесть не кастуется?

**Comment by Svjatovit** [comment]
Это не ошибка. Названный предмет - посох, а заклинания с посохов всегда массовые. Массовая доблесть, естественно, к предметам не применяется. Заклинания с палочек применяются к предметам как и положено. Задачу закрываю.
