### ISSUE TITLE
сбросы умелок заклов после реморта[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#187]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

пересмотреть уровни

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/187

**Comment by Svjatovit** [comment]
Куда пересмотреть? Зачем пересмотреть? Походу, кто-то перепутал доску задач с записной книжкой...
