### ISSUE TITLE
нерф способки хозяин животных

### ISSUE THREAD

**Issue by Daniil-Gusev** [bylins/mud#1877]
убрать очень мощные стабы у чармисов, почармленных хозяином животных. убрать у них же скрытый удар.

**Comment by bylins** [comment]
Сделал чармиса уникальным в наборе
сделал атаку с умения по приказу убить

**Comment by hikopol** [comment]
1.сделать что бы при вхождении в бой с процедуры attack_best проверялась валидность применения умений чармисов.
а то пока что чармис может стабнуть пальцем, глушить с кулака, или башить без щита. Я уже не говорю про заколоть с лука или молотнуть с двуручем в руках.
2. в do_bash , где-то стоит кривая проверка на чармисов, т.е. даже имея щит и умение сбить - чармис не применяет его по приказу хозяина
3. добавить в attack_best пинок как умение с самым низким приоритетом.

**Comment by hikopol** [comment]
Проблема при атаке чармисом с заколоть и перком воровской удар, если уже кто-то сражаеться с целью, он вступает с простой атаки
![image](https://user-images.githubusercontent.com/61746291/213885903-14d34bcc-b816-4f24-8f69-c0e230886971.png)
при простой команде заколоть цель , проблема не возникает:
![image](https://user-images.githubusercontent.com/61746291/213885940-d9ad32bf-7a63-4398-b0eb-a7880c2bee3f.png)

**Comment by Daniil-Gusev** [comment]
так вроде решили убирать татенаемовские способки у чармисов. или я пропустил что-то?

**Comment by hikopol** [comment]
Сделали что нельзя реролить профу чармиса , и нельзя иметь повторные профы чармисов.
т.е макс 1 го типа (нельзя всех стаберов, или всех глушеров и т.д.)

**Comment by Daniil-Gusev** [comment]
а как реализован запрет реролла? любопытно посмотреть.

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/213923740-2ac3a1ac-ac92-4271-b611-64a6fa1acb76.png)

**Comment by bylins** [comment]
```
				std::vector<int> rndcharmice = {1, 2, 3, 4, 5, 6, 7, 8};
				struct FollowerType *k, *k_next;
				for (k = ch->followers; k; k = k_next) {
					k_next = k->next;
					if (IS_CHARMICE(k->follower) && k->follower->get_type_charmice() > 0) {
						rndcharmice.erase(rndcharmice.begin() + k->follower->get_type_charmice() - 1);
					}
				}
				int rnd = number(0, rndcharmice.size() - 1);
				type_mob = rndcharmice.at(rnd);
			}

```

**Comment by bylins** [comment]
при перечарме можно получить несколько одинаковых чармисов

**Comment by hikopol** [comment]
https://github.com/bylins/mud/blob/0ca099b262f15e0470c3c47376f0b476e1fb941e/src/game_magic/spells.cpp#L1220
тут забыли

**Comment by bylins** [comment]
вот правка
```
			// выбираем тип бойца - рандомно из 8 вариантов
			int type_mob;
			std::vector<int> rndcharmice = {1, 2, 3, 4, 5, 6, 7, 8};
			struct FollowerType *k, *k_next;
			for (k = ch->followers; k; k = k_next) {
				k_next = k->next;
				if (IS_CHARMICE(k->follower) && k->follower->get_type_charmice() > 0) {
					rndcharmice.erase(rndcharmice.begin() + k->follower->get_type_charmice() - 1);
				}
			}
			int rnd = number(0, rndcharmice.size() - 1);
			if (rndcharmice.find(victim->get_type_charmice()) != rndcharmice.end())
				type_mob = victim->get_type_charmice();
			else
				type_mob = rndcharmice.at(rnd);
        		victim->set_type_charmice(type_mob);
			switch (type_mob)

```

**Comment by hikopol** [comment]
проверять наличие пушки в do_mode а то чармис выбирает использование молота вместо глуша, если даже вооружен пушкой
