### ISSUE TITLE
Про резисты[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#19]
*Originally reported by* **bodrich (Bitbucket: [bodrich](https://bitbucket.org/bodrich), GitHub: [bodrich](https://github.com/bodrich))**

----------------------------------------

Насчет воли, стойкости, реакции и тому подобного.
Предлагаю, чтобы от стафа бонус от одетых резистов уменьшался.
На -1 до 3 за каждые одетые 10 единиц.
Т.е. если человек напялит на себя 50 воли, то у него бонус будет 
10 + 9 + 8 + 7 + 6 = 40 воли

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/19

=======COMMENTS=======

Date: 2017-10-01T10:31:56Z

*Original comment by* **Sventovit (Bitbucket: [Sventovit](https://bitbucket.org/Sventovit), GitHub: [Sventovit](https://github.com/Sventovit))**

----------------------------------------

Живучесть - защита от критов и крит. эффектов спеллов.
Иммунитет - от яда и планировалось болезни и всякие там тому подобные клялки ввести но так и не сделали.

Date: 2017-06-08T09:09:05Z

*Original comment by* **bylins (Bitbucket: [bylins](https://bitbucket.org/bylins), GitHub: [bylins](https://github.com/bylins))**

----------------------------------------

FIRE_RESISTANCE  Огонь  
AIR_RESISTANCE   Воздух  
WATER_RESISTANCE   Вода  
EARTH_RESISTANCE  Земля  
MIND_RESISTANCE  Разум  
VITALITY_RESISTANCE Живучесть  
IMMUNITY_RESISTANCE Иммунитет  
На что 2 последних влияет я  не в курсе

Date: 2017-06-08T08:59:50Z

*Original comment by* **bylins (Bitbucket: [bylins](https://bitbucket.org/bylins), GitHub: [bylins](https://github.com/bylins))**

----------------------------------------

SAVING_WILL       Воля  
SAVING_CRITICAL Здоровье    
SAVING_STABILITY  Стойкость  
SAVING_REFLEX     Реакция

Date: 2017-06-07T18:32:08Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

+ названия савинг - алиас на русском
+ название резиста - алиас на русском

Date: 2017-06-07T17:08:02Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

хотя бы места в коде где расчитываются резисты, кроме как general_saving_trow

**Comment by Svjatovit** [comment]
Смешались в кучу кони, люди... резисты - не сейвы, а сейвы - не резисты. Странные костыльные формулы урезания надетого тоже не нужны, нужен баланс и внятные параметры стафа. Закрываю.
