### ISSUE TITLE
переделать ядовитый туман

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#1916]
переделать ядовитый туман в что нибуть более полезное
напрмер туман смерти =
вешает разные аффекты + дрын вконце

**Comment by Svjatovit** [comment]
Не надо его переделывать ни в какие попсовые "туманы смерти". Просто проверить механику и доработать. Еще, кстати, там тупо во всех комнатах аж отдельное поле, сколько яда в комнате. Зачем, спрашивается, если можно значение хранить в самом аффекте? 

Другое дело, что надо доработать саму механику аффектов на коаннату. Надо в аффект писать рейтинг каста, который считается от скилла и ключевого параметра. И если другой персонаж пытается наложить такой же аффект, то если он союзник, более сильный аффект заменяет более слабый. Если не союзник - делается противостоящий бросок. Ну и туманы и все такое с комнаты должны слетать, если персонаж убит или вышел из комнаты. Во избежание.
