### ISSUE TITLE
иммское где

### ISSUE THREAD

**Issue by bylins** [bylins/mud#192]
2772H 179M ??? Зауч:0 34L 9747363G Вых:Ю> где калантарь
O  1. калантарь с клеймом Китовраса - лежит в переметной суме, который находится 
                                - затарено имя [-1] в комнате [номеррумы] Vnum предмета: 2192
почему показывает внум сумки (2192) а не у кого лежит, правилось же....

**Comment by lrdx** [comment]
Так пишет же, у кого этот контейнер, внум контейнера и комната где владелец контейнера. А как должно быть?

**Comment by bylins** [comment]
дык внум предмета нужен, а не контейнера
