### ISSUE TITLE
не работает в олц О) Ингредиенты:

### ISSUE THREAD

**Issue by bylins** [bylins/mud#197]
или непонятно как добавить, так же не указывается сила ингра

**Comment by Svjatovit** [comment]
И не должно работать. Ингредиенты давно лоадятся автоматически. Комнатные - от типа зоны, с мобов - от расы моба.  Тут наоборот, надо простановку ингредиентов через ОЛЦ вырезать, где не вырезано.

**Comment by bylins** [comment]
Должно, у нас формат моб файла поддерживает загрузку объектов и ингредиентов при смерти моба, аналогично загрузки из триггеров.

**Comment by Svjatovit** [comment]
Не должно. Вырезать это надо, а не "чинить". Нефиг дублировать сущности.

**Comment by Svjatovit** [comment]
Сделано, но после накатывания патча надо пересохранить через OLC все *.wld и *.mob файлы, а затем вырезать из boot.data.files.cpp парсинг в мобах и комнатах строк, начинающихся с "I ".

**Comment by bylins** [comment]
зря время потратил, давно сделано
