### ISSUE TITLE
ап со знаками зачарования

### ISSUE THREAD

**Issue by Avseek** [bylins/mud#199]
Некоторое вермя назад стало часто случаться так, что после апа со знаком почему-то в результате получается шмотка с проклой, хотя на знаке ее не было.

**Знак**
Предмет "знак великолепного зачарования", тип : ДРУГОЕ
Можно взять в левую руку (требуется 1 сила).
Вес: 1, Цена: 1, Рента: 1(1)
Материал : НЕИЗВЕСТЕН
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: ничего
Накладывает на вас аффекты: ничего
Дополнительные свойства :
   сила улучшает на 2

**Предмет который апаем**
Предмет "коготь гаврана", тип : ОРУЖИЕ
Принадлежит к классу "иное оружие".
Можно надеть на шею.
Можно взять в правую руку (требуется 1 сила).
Можно взять в левую руку (требуется 1 сила).
Вес: 1, Цена: 100, Рента: 100(10)
Материал : ОРГАНИКА
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: ничего
Наносимые повреждения '4D4' среднее 10.0.
Накладывает на вас аффекты: ничего
Дополнительные свойства :
   сила улучшает на 1

**Результат**
Предмет "коготь гаврана", тип : ОРУЖИЕ
Принадлежит к классу "иное оружие".
Можно надеть на шею.
Можно взять в правую руку (требуется 1 сила).
Можно взять в левую руку (требуется 1 сила).
Вес: 1, Цена: 100, Рента: 100(10)
Материал : ОРГАНИКА
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: магический
Наносимые повреждения '4D4' среднее 10.0.
Накладывает на вас аффекты: **проклятие**
Дополнительные свойства :
   повреждение ухудшает на 2
   сила улучшает на 2

Надо бы разобраться почему так происходит...

**Comment by lrdx** [comment]
Это фича, а не баг (с)

**Comment by Avseek** [comment]
Имхо фичей было то что попятся знаки сразу с молчей или проклой. Это было всем известно. Но такого чтобы аффекты рандомно появлялись не было...
Или в этом и состояло изменение о котором не написали?

**Comment by lrdx** [comment]
Да, т.к. получать знак с молчей с фридропа было бредом. С другой стороны делать зачарование со знаком только из плюсов это чересчур как по мне, компромиссом было принято решение вешать в 25% случаев при касте со знаком на шмотку негативный аффект из тех, что раньше могли быть на знаке изначально.
Если есть идеи, можно обсудить

**Comment by aryabenkiy** [comment]
Короткая предыстория. 
был ап +2 +2. поскольку вещей которые ают намного лучше чем апнутое валом апом никто не пользовался.
Игроки пожаловались богам что необходимо что-то сделать. 
Посоветовавшитьс с старшими богами я сделал что ап зависит от прокачки школы магии и парально сделал знаки зачарования.
Значи зачарования падали рандомно и в зависимости от фридропа имели разную силу.
при этом на знаки накладывали негативные афекты. 
Дальше все зависило от колдующего. хотел он перенести часть с знака (тогда колдовать должен был не прокачаный колдун) или все (тогда магия света 160+) переносилось на предмет + к этому еще был рандом от первого части апа по повреждению и попаданию.
Знаки которые были с негативными афектами можно использовать (берешь в руку и оно все тебе плюсуеться) поэтому молчу или что там еще выпадало я и не убирал.
В текущих реалиях получаем что игрок найдя (купив) знак молжет получить опять же негативный аффект и заклинания с управляеммого(предсказуемого) превращается в неконтролируемый рандом. как результат заклинанием не будут пользоваться.

Если вы хотите дать возможность игрокам управлять процесом зачарования тогда возможно стоит  убрать учитывание аффектов когда держишь знак зачарования в руке но полный перенос.
Как первоначальный автор знаков я бы настаивал на паком развитии событий.

**Comment by bylins** [comment]
пусть остается пока как есть
