### ISSUE TITLE
не удаляется world trigger в OLC

### ISSUE THREAD

**Issue by garkins** [bylins/mud#2088]
увидеть пример можно в зоне 976 и 978
![photo_2023-10-25_20-16-57](https://github.com/bylins/mud/assets/26000120/6374a220-e510-495a-ba1a-a7669fdc8fed)
![photo_2023-10-25_20-17-02](https://github.com/bylins/mud/assets/26000120/6da1fa4c-f54a-4634-b77e-75d45c797ac3)

**Comment by bylins** [comment]
там структура при загрузке мада создается owner_to_triggers_map_t
tlist ее использует, а олц не правит.
т.е. глючит именно тлист а не олц
