### ISSUE TITLE
олц у тестеров

### ISSUE THREAD

**Issue by bylins** [bylins/mud#2201]
~сделать чтоб на тестовую зону работали vstat и stat~

**Comment by hikopol** [comment]
так же бывает ситуации что итем / квест итем подикеил, т.к. таймер вещей 30минут
дать load obj - (только из этой зоны естественно), для возможности залоадить квест итем / Поглядеть характеристики вещей.
Ну продавать или пользовать вне зоны не выйдет т.к таймер и !продать

**Comment by bylins** [comment]
zreset

**Comment by bylins** [comment]
запретить гривну

**Comment by hikopol** [comment]
show worlds
show all - показывает все доступные спец команды списком

**Comment by hikopol** [comment]
Andrey Стрибог, [27.04.2024 17:01]
он сейчас только с номером будет

Andrey Стрибог, [27.04.2024 17:03]
tlist без номера
номер зоны указанный в аргументе == 0
я кстати в сегодняшних командах этот вариант учел

Andrey Стрибог, [27.04.2024 17:03]
надо будет переписать давнее

Andrey Стрибог, [27.04.2024 17:03]
закинь в иссуе 2201 я поправлю
