### ISSUE TITLE
Добавить в DGscript

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#2202]
дать возможность работать с следующими параметрами объекта
Доп. аффекты(EApply), Увеличение %умения (?)
если возможно по аналогии с obj.value
например: 
obj.ea.1 -> проверим аплай к силе, если есть то значение если нет то "нулл" или 0
obj.ae.25(+100) -> установить аплай "хп реген" в плюс 100
obj.ae.19(-2) -> уменьшиьб аплай "дамрол" на -2 ( если было например 10 , то должно стать 8)

obj.skills(подножка) -> проверим есть ли модификатор %умения "подножка" , выводит наприер "200" , если нет то "0"
obj.skills(осторожный стиль, 10) -> установить увеличение %умения "осторожный стиль" на 10

**Comment by bylins** [comment]
сделать только на одеваемое, типа оружие - броня

**Comment by bylins** [comment]
Andrey Стрибог, [26.04.2024 16:22]
у нас есть еще такое
#define GET_OBJ_SKILL(obj) ((obj)->get_skill())
только для оружия, это то что прокачивает

Andrey Стрибог, [26.04.2024 16:22]
а я использую мля int get_skill(ESkill skill_num) const;
