### ISSUE TITLE
Баг в воровской гильдии

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#221]
Привозишь с собой коня, агришь его, охранники выходят из хайда и ассистят. Считаем за баг или фичу?

**Comment by il--ya** [comment]
А что тут можно считать багом? Что моб ассистит кому попало?
По-моему, багом является то, что прячущийся моб может каким-то образом "не пускать" - но это уже, видимо, стало фичей.

**Comment by bylins** [comment]
Ну это конечно обход игровой механики, но думаю фича. Никто не мешает кастануть сенс или позвать охота
