### ISSUE TITLE
новое с лд и сумоном

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#2210]
Чар упал в лд, с групой не следует.
при попытке призвать его, призываеться (но строчки что кто-то прибыл нету), есть строчка что прибыл чармис за хозяином.
![image](https://github.com/bylins/mud/assets/61746291/25651a06-18a5-4b7f-aa57-903d5192eda4)
раньше был фейл, как попытка призвать кого-то в лд

**Comment by bylins** [comment]
сделал запрет на суммон игроков в лд
