### ISSUE TITLE
Улутшение в DGscript

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#2241]
сделать mdamage по аналогии с odamage где можна определить  параментром тип наносимого урона 
physical / magical 
чтот по типу 
mdamage %target% 777 physical <--- физ урон
mdamage %target% 777 <--- cтарая версия
mdamage %target% 777 magical <--- маг урон
з.ы. в душе не чаю что за poison но в описание к odamage тоже фигурирует

**Comment by hikopol** [comment]
добавить возможность проверять общие сейвы char (врожденные + добавочные)
воля, стойкость, реакция ... Выводить желательно в положительных значениях
например:
char.will > 200 (воля)
char.reflex> 150 (реакция)
char.critical > 60 (живучесть)
char.stability > 150 (стойкость)

**Comment by bylins** [comment]
готово
