### ISSUE TITLE
C++20

### ISSUE THREAD

**Issue by 1vanK** [bylins/mud#2313]
[Тут](https://github.com/bylins/mud/blob/master/CONTRIBUTING.md) написано, что проект использует C++17, но по факту он использует C++20.

Тут забыли версию стандарта поменять на 20: <https://github.com/bylins/mud/blob/master/CMakeLists.txt#L741>.
Это одно из препятствий сборки проекта в Visual Studio.

В GCC13 уже есть поддержка std::format, можно и подмодуль ftm выбросить.

В старых версиях Убунты GCC13 можно поставить:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update -y
sudo apt install gcc-13 g++-13 -y
```

Кстати в CMakeLists.txt версия два раза указана: <https://github.com/bylins/mud/blob/master/CMakeLists.txt#L1-L2>.

**Comment by bylins** [comment]
у нас gcc 11.3 
и бетта 20 модель, хотя по факту на ней пишем.

**Comment by bylins** [comment]
кстати в мсвц 2021 другой не было под рукой собирается без вопросов

**Comment by bylins** [comment]
if (UNIX AND NOT CYGWIN)
	#add_definitions("--std=gnu++17")
	add_definitions("-std=c++2a")

решетка это коммент

**Comment by 1vanK** [comment]
> решетка это коммент

Это понятно, там для студии работает ветка
```
set_target_properties(circle.library PROPERTIES CXX_STANDARD 14)
```

**Comment by 1vanK** [comment]
> кстати в мсвц 2021 другой не было под рукой собирается без вопросов

Это какая? Была 2019, после нее 2022 ) Вот в 2022 сыпет кучу ошибок

**Comment by bylins** [comment]
да, 2022 но я ее под wsl настроил

**Comment by bylins** [comment]
я под gcc 13 собрал мад ради эксперимента, но переводят пусть профессионалы, вон Свентовит например
