### ISSUE TITLE
zMUD/CMUD полноценная поддержка буквы я

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#238]
В zMud [начиная с версии 6.39a](https://www.zuggsoft.com/zmud/version.htm) и в CMUD (новое название zMud)  реализована поддержка буквы 'я', но криво. При получении поледовательности IAC IAC клиент отображает букву я, но сдвигает указатель во входном буфере только на один байт. В результате следующие две буквы воспринимаются как управляющая последовательность Telnet IAC+CommandCode, т.е. еще один байт проглатывается. Это довольно легко можно обойти, заменяя 'я' на последовательность из *трёх* байт: "\xFF\xFFz". Я предварительно потестил в zMud 6.62, 7.21 и CMUD 3.34 - работает.
В былинах сейчас реализована поддержка буквы "я" для zMud при приёме данных от клиента, но кодировка на передачу осталась старой - 'я' заменяется на 'z'. Я предлагаю добавить полноценную поддержку zMUD/СMUD (старую оставить для совместимости). 
Я понимаю, что CMUD уже 7 лет не поддерживается, но, по-моему, это по прежнему один из лучших клиентов для Windows, один из немногих со встроенным маппером и огромным количеством разных полезных фич.

**Comment by lrdx** [comment]
А как определять клиент, версию? Или просто добавить еще один пункт в выборе кодировки?

**Comment by il--ya** [comment]
Да, просто ещё один пункт. Была мысль, для облегчения выбора кодировки какую-нибудь короткую тестовую фразу на русском выводить в соответствующей кодировке - но решил, что будет неэстетично. В конце концов кодировка подбирается один раз при первом использовании, а на мусор придется потом смотреть при каждом соединении.
Еще, чтобы сильно не засорять, можно в основном меню сделать UTF-8 первым пунктом, Windows-1251 вторым и KOI8-R третьим, а остальные нестандартные убрать в пункт "другое" и на следующем шаге уже выбирать всякую нестандартную экзотику.
Можно пытаться использовать Telnet Charset Option ([RFC2066](https://tools.ietf.org/html/rfc2066)),  но:
1) довольно много работы 
2) ручные опции всё равно останутся для клиентов, которые автоопределение не поддерживают, или поддерживают криво как zMUD.

**Comment by bylins** [comment]
делай поддержку змуд, а они отпарсят кодировку при коннекте

**Comment by il--ya** [comment]
Предлагаю сделать так. Старое меню оставлю почти без изменений:

> Using keytable
>   0) Koi-8
>   1) Alt
>   2) Windows(JMC,MMC)
>   3) Windows(zMUD)
>   4) Windows(zMUD 'z')
>   5) UTF-8
>   6) More...
> Select one : 

Но пункт 3 теперь будет полноценной поддержкой 'я' для новых версий. Поддержку старых версий zMud из основного меню убрал - по-моему, пора. Пункт 4 останется как сейчас, с заменой я на z в обоих направлениях для версий 6.39+ - он нужен на случай, если кто-то хочет продолжать играть с z потому что у него уже сделана так карта и настроены триггеры. Соответственно переименовал его, чтобы понятно было в чем отличие от пункта 3. Вообще конечно можно было в zMud делать subst 'z' на 'я', но может кто не догадался и 15 лет так и играл с z вместо я, и по-другому не может :)

Добавил расширенное меню последним пунктом. В нём будут все те же самые пункты плюс поддержка старого zMUD, и после каждого пункта справа будет выводиться строка "Тестовая строка" (или любой другой текст - ваши предложения? Условие, чтобы в нём была маленькая "я") в соответствующей кодировке, чтобы игрок мог сразу визуально определить, что подойдёт для его клиента.

Мнения?

**Comment by kvirund** [comment]
А почему расширенную версию нельзя показать сразу?

Тестовые строки сразу выводить для всех пунктов, мне кажется, не стоит, т. к. каждый вход на эти тесты смотреть никому не нужно. Лучше сделать что-то типа команды "показать тест для опции N". Например "тест 1", либо "тест все".

**Comment by kvirund** [comment]
> Во-первых, чтобы не сбивать народ (ньюбов особенно) с толку.

А два меню понятнее? :)

> Вообще интересно было бы собрать статистику сначала, но я подозреваю что в 90% случаев используют UTF-8 или Window.

Чем бы она помогла? Она будет только за конкретный промежуток времени. И она бы не сказала о том, есть ли где-то игрок, который во время сбора статистики не подключался, но использует какую-нибудь экзотику.

> Слишком сложно, особенно учитывая что мы ограничины английским языком (по крайней мере английским алфавитом).

Сложно в каком плане? Запрограммировать или понять?

```
 Using keytable
   0) Koi-8
   1) Alt
   2) Windows(JMC,MMC)
   3) Windows(zMUD)
   4) Windows(zMUD 'z')
   5) UTF-8
 Select one (type "test <choice>" to see test string or type "test all" to test all keytables) : 
```

ИМХО, не так уж сложно. Ещё вариант: Попросить пользователя ввести некоторую строку: например "Мама мыла раму". Циркуль получит её в кодировке пользователя. И, соответственно, вообще автоматом её определит. Хотя вот эти различные версии zMUD'ов, возможно, станут проблемой (я просто хз как там всё это происходит).

**Comment by kvirund** [comment]
Хотя, не совсем понятно как попросить пользователя ввести эту строку. Но это уже отдельная задача. Например, можно дать ссылку на web-страницу с нужной строкой. Или тупо попросить ввести все буквы русского алфавита. Это можно и по-английски описать.

**Comment by il--ya** [comment]
> А два меню понятнее? :)
А нечего во второе лезть, если с первым не разобрался! :)
В первом меню ограничен выбор на наиболее вероятные подходящие опции, чтобы меньше перебирать. Я бы и Alt с zMud оттуда убрал, но не хочу менять последовательность номеров пунктов и ломать сильно людям автоконнект.
>Сложно в каком плане? Запрограммировать или понять?
>ИМХО, не так уж сложно. 
Сложно в смысле "много букав", да ещё латиницей, да, прости господи, на английском. Пугает условного ньюба, который первый раз подключился к русскоязычному (!) маду. Одно слово "More" или "Other" - ещё куда ни шло, и многоточие намекает. А там уже глядишь и буквы знакомые проглядывают, и что-то даже прочитать можно.
А тому, кто подключается не первый раз, не очень-то и нужно.

> Ещё вариант: Попросить пользователя ввести некоторую строку: например "Мама мыла раму".
Просить придётся по-английски или транслитом. Работы для пользователя больше, чем узнать знакомые буквы и набрать одну цифру.

Автоопределение надо делать через телнет опции, не надо пользователя мучать. Тот же zMud его поддерживает. Но ручной выбор должен сохраняться как fallback.

**Comment by kvirund** [comment]
Вот я, вроде, не нуб, а две менюшки меня уже пугают и сбивают с толку. Возникают всякие вопросы, типа: а чем кодировки во втором меню отличаются от первого? Они лучше/правильней? Что мне больше подходит? Из первого меню или из второго? А они точно одинаковые?

Менять последовательность или состав я бы тоже не стал. С этим согласен.

Что more, что other пугают не меньше. Многоточие намекает только опытному пользователю, а не нубу. А опытный, вероятно, слышал про гугл-транслейт или ещё какой переводчик.

> Просить придётся по-английски или транслитом. Работы для пользователя больше, чем узнать знакомые буквы и набрать одну цифру.

Не одну, а две, раз менюшек две. Причём во вторую менюшку таки надо попасть переведя английский текст. Те же требования, только с дублированием пунктов.

> Автоопределение надо делать через телнет опции, не надо пользователя мучать. Тот же zMud его поддерживает. Но ручной выбор должен сохраняться как fallback.

Автоопределение клиент ещё должен поддерживать. А вариант с вводом строки универсален. Плюс да, ручной выбор как fallback - это второй вариант. И ввод заранее определённой строки для автоопределения кодировки - это третий вариант. Причём ни один из них не исключает другой.

Впрочем, я хз как ты представляешь второе меню. Возможно, мы говорим об одном и том же. :) Просто я это "подменю" вижу не как подменю, а как точно то же самое меню, но просто с подсказками. Т. е., например, вместо команды "test all" - этот пункт "More...":

```
 Using keytable
   0) Koi-8
   1) Alt
   2) Windows(JMC,MMC)
   3) Windows(zMUD)
   4) Windows(zMUD 'z')
   5) UTF-8
   6) Test
 Select one : 6

 Using keytable
   0) бНОПНЯ
   1) ??????
   2) Выбери меня
   3) ...
   4) Выбери менz
   5) <какие-то иероглифы>
   6) Test
 Select one :
```

P.S. Если уж говорить про пугающие английские буквы: "Select one" дословно - "Выбери один". Т. е. то ли выбрать надо что-то одно, то ли ввести 1. Тут бы лучше подошло "Your choice". :) Ну и три пункта с Windows тоже не вносят ясности: как нуб я мог вообще не слышать про разные клиенты: У меня, может, Тортилла, а её тут вообще нет.

**Comment by il--ya** [comment]
ОК, мне нравится вариант с Test (только всё ж с многоточием) - короткое, понятное, почти русское слово (может даже "TECT" ?). Но второе меню без указания кодировок не годится - некоторые могут выглядеть идентично, причём оптимальный выбор, но работать по-разному. Без дополнительной информации непонятно, что тыкать.
Select one - тоже об этом думал, но это не я придумал... Ладно, нуб!=идиот, всё-таки. 

>    2) Выбери меня

Остроумно, но увы, нужно чтобы после 'я' в тестовой фразе были ещё буквы. Чтобы было заметно, что zMud их проглотил.

> Вот я, вроде, не нуб, а две менюшки меня уже пугают и сбивают с толку. Возникают всякие вопросы, типа: а чем кодировки во втором меню отличаются от первого? Они лучше/правильней? Что мне больше подходит? Из первого меню или из второго? А они точно одинаковые?

Вот потому и возникают вопросы, что не нуб. А у нуба вопросов не возникнет - работает хоть как-то - и слава богам! Главное, чтобы человек минимальными усилиями смог законектиться и начать играть.

> Ну и три пункта с Windows тоже не вносят ясности:
Да, причём Windows не исключает UTF-8.. Но тогда "тут всю систему менять надо" :)

**Comment by il--ya** [comment]
>Тут фигня в том, что для того же zMUD, как я понимаю, кодировка будет одна и та же. Просто с небольшими вариациями. Наверное, ты имел ввиду кодировку плюс какие-то её особенности.

Да, кодировка + workarounds на приёме и передаче, чтобы нормально текст отображался и принимался. Строго говоря это не кодировка, конечно.
Если второе меню будет просто тестом, тогда старый zMud придётся оставить в первом. Но я все же перенесу его в конец списка.

Вот так будет выглядеть из windows-1251:
```
 Using keytable
   0) Koi-8
   1) Alt
   2) Windows(JMC,MMC)
   3) Windows(zMUD)
   4) Windows(zMUD 'z')
   5) UTF-8
   6) Windows(zMUD <6.39)
   9) TECT...
 Select one : 9

 Using keytable
   0) Koi-8               тХУУЛБС БЪВХЛБ: "БВЧ...ЬАС".
   1) Alt                 ђгббЄ п  §ЎгЄ : " Ўў...ноп".
   2) Windows(JMC,MMC)    Русская азбука: "абв...эюя".
   3) Windows(zMUD)       Русскаяz азбука: "абв...эюяz".
   4) Windows(zMUD 'z')   Русскаz азбука: "абв...эюz".
   5) UTF-8               Р СѓСЃСЃРєР°СЏ Р°Р·Р±СѓРєР°: "Р°Р±РІ...СЌСЋСЏ".
   6) Windows(zMUD <6.39) Русскаz азбука: "абв...эюz".
 Select one : 
 ```
Из UTF-8:
```
 Using keytable
   0) Koi-8               󖔓́ϠṌ: "ծ..݀Ϣ.
   1) Alt                 䢡ª �§¡㪠: " ¡¢...".
   2) Windows(JMC,MMC)    ѳ򲫠�랺 "ᢢ...�
   3) Windows(zMUD)       ѳ򲫠�� "ᢢ...�
   4) Windows(zMUD 'z')   ѳ򲫠z ᨡ� "ᢢ...�
   5) UTF-8               Русская азбука: "абв...эюя".
   6) Windows(zMUD <6.39) ѳ򲫠z ᨡ� "ᢢ...�
 Select one : 
```
Из KOI8-R:
```
 Using keytable
   0) Koi-8               Русская азбука: "абв...эюя".
   1) Alt                 ░ЦАА╙═О ═╖║Ц╙═: "═║╒...МНО".
   2) Windows(JMC,MMC)    пСЯЯЙЮЪ ЮГАСЙЮ: "ЮАБ...ЩЧЪ".
   3) Windows(zMUD)       пСЯЯЙЮЪz ЮГАСЙЮ: "ЮАБ...ЩЧЪz".
   4) Windows(zMUD 'z')   пСЯЯЙЮz ЮГАСЙЮ: "ЮАБ...ЩЧz".
   5) UTF-8               п═я┐я│я│п╨п╟я▐ п╟п╥п╠я┐п╨п╟: "п╟п╠п╡...я█я▌я▐".
   6) Windows(zMUD <6.39) пСЯЯЙЮz ЮГАСЙЮ: "ЮАБ...ЩЧz".
 Select one : 
```

**Comment by il--ya** [comment]
Можно даже так:
```
Using keytable            TECT. CTPOKA
   0) Koi-8               тХУУЛБС БЪВХЛБ: "БВЧ...ЬАС".
   1) Alt                 ђгббЄ п  §ЎгЄ : " Ўў...ноп".
   2) Windows(JMC,MMC)    Русская азбука: "абв...эюя".
   3) Windows(zMUD)       Русскаяz азбука: "абв...эюяz".
   4) Windows(zMUD 'z')   Русскаz азбука: "абв...эюz".
   5) UTF-8               Р СѓСЃСЃРєР°СЏ Р°Р·Р±СѓРєР°: "Р°Р±РІ...СЌСЋСЏ".
   6) Windows(zMUD <6.39) Русскаz азбука: "абв...эюz".
 Select one : 
 ```

**Comment by il--ya** [comment]
>P.S. Если уж говорить про пугающие английские буквы: "Select one" дословно - "Выбери один". Т. е. то ли выбрать надо что-то одно, то ли ввести 1. Тут бы лучше подошло "Your choice". :) 

Как насчет
```
KAKOE nuCAHbE ECTb BEPHOE, PA3yMEEMOE HA PyccKOM? BBEguTE TYT HOMEP:
```

Или это перебор? :)

**Comment by kvirund** [comment]
Ну, мне нравится. Но, думаю, это решение должно быть не за мной.

**Comment by il--ya** [comment]
Сделал у себя в тестовом на ftp.cputick.net:4000

**Comment by bylins** [comment]
а вообще где UTF8 используется? под юниксами?

**Comment by il--ya** [comment]
Не знаю.. я в putty тестирую. TinTin вроде на putty основан, может там можно, сейчас посмотрю.

**Comment by il--ya** [comment]
Да, TinTin по умолчанию UTF-8. А вообще любой более-менее современный клиент должен поддерживать.
В википедии есть [табличка](https://en.wikipedia.org/wiki/MUD_client#Protocol_support), в последнем столбце поддержка UNICODE.
