### ISSUE TITLE
"Свет" и "Тьма"

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#239]
Думаю заклинания "свет" и "тьма" должны работать аналогично паре "освящение" и "призматическая аура" - то есть если на чаре есть тьма, то первое заклинание "свет" её отменяет, а уже второе вешает свет. Сейчас их можно повесить одновременно, и свет имеет приоритет.

**Comment by bylins** [comment]
я впилил флаг для комнаты "всегда светло" а так да, у каждого заклинания есть параметр сила света (санк свет тьма, источник света, день ночь,  помойму ауры) вот сумма их и влияет
