### ISSUE TITLE
Чармисы не атакуют некоторых мобов по "прик все уб"

### ISSUE THREAD

**Issue by dshchedr** [bylins/mud#2441]
некоторых мобов чармис не хочет атаковать по "прик все уб"
![image_2024-10-24_23-28-54](https://github.com/user-attachments/assets/95d5911e-d477-4d90-8771-15f97af2c47a)

 только через "оглуш" начинает бой

**Comment by bylins** [comment]
![image](https://github.com/user-attachments/assets/03abbcfc-0257-4cf7-bade-e7b18fe59f47)

**Comment by bylins** [comment]
![image](https://github.com/user-attachments/assets/15bcb555-1860-48b5-900b-de797af6d7e7)

**Comment by dshchedr** [comment]
похоже вываливается т.к. в FindVictim() мы ищем по первому слову в имени моба, а у ливонского рыцаря в синонимах нет слова "ливонский" в первой строке

```
#89901
патрульный рыцарь ливонец~
ливонский рыцарь~
ливонского рыцаря~
ливонскому рыцарю~
ливонского рыцаря~
ливонским рыцарем~
ливонском рыцаре~
Ливонский рыцарь дышит свежим воздухом, гуляя по лагерю.
..
```

если в attack_best заменить GET_NAME на GET_PC_NAME - чармис атакует нормально:

do_stupor(ch, str_dup(GET_PC_NAME(victim)), 0, 0);
