### ISSUE TITLE
Внезапная смена противника

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#247]
Где выделено, происходит неожиданная смена противника.
> [ Exits: e ]
> Вы просто увязаете в грязи.
> Старый, покрытый седой шерстью лис притаился здесь.
> Старый лис хотел завалить вас, но, не рассчитав сил, упал сам.
> 
> 399H 111M 158318о Зауч:0:49 [XXXXXX:Невредим] [старый лис:Невредим] >
> Лисенок пришел с востока.
> Лисенок вступил в битву на стороне старого лиса.
> Лисенок попытался укусить вас, но лишь громко клацнул зубами.
> 
> 399H 111M 158318о Зауч:0:49 [XXXXXX:Невредим] [старый лис:Невредим] > у лис
> 
> Вы БОЛЬНО сокрушили старого лиса. 56..96
> Лисенок попытался укусить вас, но поймал зубами лишь воздух.
> Лисенок попытался укусить вас, но лишь громко клацнул зубами.
> Старый лис попытался укусить вас, но поймал зубами лишь воздух.
> Старый лис попытался укусить вас, но поймал зубами лишь воздух.
> 
> **399H 112M 158162о Зауч:0:48 [XXXXXX:Невредим] [старый лис:Ранен] >
> 399H 112M 158162о Зауч:0:48 [XXXXXX:Невредим] [лисенок:Невредим] >**
> Вы БОЛЬНО сокрушили лисенка. 56..96
> Лисенок попытался укусить вас, но поймал зубами лишь воздух.
> Лисенок легонько укусил вас. 1..5
> Старый лис легонько укусил вас. 1..5
> На мгновение вы исчезли из поля зрения противника.
> Старый лис попытался укусить вас, но поймал зубами лишь воздух.
>

**Comment by lrdx** [comment]
Вроде просто переключение на цель командой "убить" ?
399H 111M 158318о Зауч:0:49 [XXXXXX:Невредим] [старый лис:Невредим] > у лис

**Comment by il--ya** [comment]
Ясно, спасибо.. не знал, что так можно.
