### ISSUE TITLE
Школы магии у "полной слепоты" и "страха"

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#249]
По справке !полная слепота! - заклинание тьмы (логично, и аналогично !слепота! - у них и раздел в справке один на двоих).
Но по команде "закл" она подсвечивается сиреневым, как заклинание разума.
Надо либо код поправить:
https://github.com/bylins/mud/blob/012e5b10dc53a145ffd62939e65d2bc4f7d3c645/src/spell_parser.cpp#L4848-L4851
Либо справку поправить тут:
https://github.com/bylins/mud/blob/012e5b10dc53a145ffd62939e65d2bc4f7d3c645/lib.template/text/help/spells.hlp#L1375-L1385
убрать тут:
https://github.com/bylins/mud/blob/012e5b10dc53a145ffd62939e65d2bc4f7d3c645/lib.template/text/help/skills.hlp#L1336-L1338
и добавить тут:
https://github.com/bylins/mud/blob/012e5b10dc53a145ffd62939e65d2bc4f7d3c645/lib.template/text/help/skills.hlp#L1366-L1369

Ещё мне кажется странным, что страх и масс.страх - это заклинания школы тьмы, а не разума. Но тут хотя бы справка не расходится с подсветкой. Они и должны быть в школе тьмы?

**Comment by bylins** [comment]
по идее заклинания лекаря которые несут отрицательный эффект школа тьмы, слепоту сделал тьмой
