### ISSUE TITLE
При наличии у NPC флага !север и проч. можно проехать на лошади

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#260]
У моба флаг !сбежать, и я не могу от него сбегать. Но если я на коне, конь меня выносит из боя (ну да, конь-то с мобом не сражается).
Фича или баг?

UPD: понял, это не про флик, а про флаги "не пущать <направление>". Вопрос остаётся - по-моему, баг.

**Comment by lrdx** [comment]
Фича

**Comment by il--ya** [comment]
Что-то я вообще не понимаю, как так получается, что конкретно от этого моба сбежать нельзя. Вроде такого и флага-то нет у мобов, чтобы от них сбежать нельзя было. Что-то тут не так.

**Comment by lrdx** [comment]
Там есть флаг !север, !юг и т.д., моб не пускает в конкретном направлении, следовательно и сбежать в ту сторону не получается. На лошади этот флаг игнорируется

**Comment by il--ya** [comment]
Хм, действительно. Вот тут всадники явным образом исключены.
https://github.com/bylins/mud/blob/5784982ee290365beae318e68d45cd59cac7320a/src/act.movement.cpp#L642
Имхо, очень странно, что стоит вскочить на лошадь, моб тебя пропускает.

**Comment by il--ya** [comment]
И потом, даже если это фича, при флике надо сообщение, из-за чего паникуем? Сейчас его нет. У игрока вообще никаких шансов понять, почему флик то работает, то вдруг не работает.

> 408H 140M 11047361о Зауч:2:20 [Ладник:Легко ранен] [главарь ватаги:О.тяжело ранен] > беж
> Главарь ватаги встал на ноги.
> Вы легонько ударили главаря ватаги. 1..5
> Главарь ватаги хотел завалить вас, но, не рассчитав сил, упал сам.
> Главарь ватаги слегка ударил вас. 6..11
> Главарь ватаги промазал, когда хотел ударить вас.
> 405H 140M 11047359о Зауч:2:19 [Ладник:Легко ранен] [главарь ватаги:О.тяжело ранен] > 
> ПАНИКА ОВЛАДЕЛА ВАМИ. Вы не смогли сбежать!

**Comment by lrdx** [comment]
> Хм, действительно. Вот тут всадники явным образом исключены.
> [mud/src/act.movement.cpp](https://github.com/bylins/mud/blob/5784982ee290365beae318e68d45cd59cac7320a/src/act.movement.cpp#L642)
> 
> Line 642 in [5784982](/bylins/mud/commit/5784982ee290365beae318e68d45cd59cac7320a)
> 
>  && !on_horse(ch)) 
> 
> Имхо, очень странно, что стоит вскочить на лошадь, моб тебя пропускает.

Ну мне тоже было странно, но сказали, что это фича и так должно быть.



> И потом, даже если это фича, при флике надо сообщение, из-за чего паникуем? Сейчас его нет. У игрока вообще никаких шансов понять, почему флик то работает, то вдруг не работает.
> 
> > 408H 140M 11047361о Зауч:2:20 [Игрок:Легко ранен] [главарь ватаги:О.тяжело ранен] > беж
> > Главарь ватаги встал на ноги.
> > Вы легонько ударили главаря ватаги. 1..5
> > Главарь ватаги хотел завалить вас, но, не рассчитав сил, упал сам.
> > Главарь ватаги слегка ударил вас. 6..11
> > Главарь ватаги промазал, когда хотел ударить вас.
> > 405H 140M 11047359о Зауч:2:19 [Игрок:Легко ранен] [главарь ватаги:О.тяжело ранен] >
> > ПАНИКА ОВЛАДЕЛА ВАМИ. Вы не смогли сбежать!

Можно добавить, думаю это хорошая идея.

**Comment by il--ya** [comment]
>Можно добавить, думаю это хорошая идея.
Хотел по-быстрому сделать, да смотрю надо для начала по-нормальному выносить все внешние функции в act.movement.hpp, иначе придётся плодить magic numbers. Мне интересно, есть какая-то веская причина, почему код так странно организован, без хедеров? Просто спешка и лень?

**Comment by bylins** [comment]
фишка в том, что на лошади сбежать 100%, а вот то что можно сбежать в клетку куда моб не пускает, явно бага, влегкую могу представить как можно проабузить

**Comment by bylins** [comment]
короче признано багой, надо править

**Comment by il--ya** [comment]
Как именно исправлять?
1) Запретить сбегать туда, куда моб не пускает, даже если на лошади
2) Запретить ходить туда, куда моб не пускает, даже если на лошади
или и то и другое?

**Comment by bylins** [comment]
решено
