### ISSUE TITLE
Trigger types: Command не возвращает аргумент

### ISSUE THREAD

**Issue by bylins** [bylins/mud#266]

**Comment by bylins** [comment]
2772H 179M ??? Зауч:0 34L 14742313G Вых:СВЮv> trigedit 100
Trigger Editor [100]

1) Name         : перемещение
2) Intended for : Rooms
3) Trigger types: Command
4) Numberic Arg : 100
5) Arguments    : шаг
6) Commands:
%echo%  arg 1
%echo%  %arg% 2
%echo%  %arg%

Q) Quit
Enter Choice :q

2772H 179M ??? Зауч:0 34L 14742313G Вых:СВЮv> шаг
Arg 1
%echo%  %arg% 2
%echo%  %arg%
Q) Quit
Enter Choice :q

**Comment by bylins** [comment]
2772H 179M ??? Зауч:0 34L 14742313G Вых:СВЮv> шаг
Arg 1
2
[14-10-18 14:42:16][ SCRIPT LOG (Room: 100, trig: 100): wecho called with no args ]

**Comment by bylins** [comment]
кто сломал непонятно, на объекте таже фигня, судя по описанию обязанно быть

**Comment by bylins** [comment]
завтра уже покажу там первую букву у объекта съедает

**Comment by kvirund** [comment]
Про съедание говорили много раз уже. Нельзя объекты просто выводить. Там первым символом идёт тип переменной "объект". Поэтому выводить можно "имя" объекта, например. Но не сам объект.

**Comment by bylins** [comment]
аргумент не работает так как первую буковку ест

**Comment by kvirund** [comment]
Что именно не работает? Если вывод аргумента, который является объектом - так и должно быть. Сам-то аргумент возвращает объект как и положено? Или я чего-то не понимаю?

**Comment by il--ya** [comment]
```
6) Commands:
%echo% arg 1
%echo% %arg% 2
%echo% %arg%

Q) Quit
Enter Choice :Q

669H 82M ??? Зауч:0 34L 1752609G Вых:СЮv> шаг блабла
Arg 1
Блабла 2
Блабла
```
В 1-й строке "arg" не выводится. Это проблема?

**Comment by bylins** [comment]
я конечно сам найду, просто не было времени, но кто-то нагадил недавно

**Comment by kvirund** [comment]
Ну, если теряет первую букву у *обычной* строки - то это, конечно, ошибка. Но надо это как-то воспроизвести сначала.
