### ISSUE TITLE
При аварийном завершении теряются последние строки в логе

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#267]
Нужно добавить какой-то log_flush, чтобы принудительно флашить сообщения в определённых ситуациях, в частности перед exit().
Обсуждалось [тут](https://github.com/bylins/mud/commit/1c272776d98b173e715ca73c22f58f8d1d096b8a#commitcomment-30892855).

**Comment by il--ya** [comment]
>лучше зависон почините при ребуте
одно другому не мешает ))

**Comment by kvirund** [comment]
Всё гораздо проще. При `exit`-е вызываются деструкторы статических объектов. А тред для вывода как раз управляется статическим объектом. Но:

```
	while (!m_destroying)
	{
		message_t message;
		if (m_output_queue.pop(message))
		{
			if (!runtime_config.log_stderr().empty())
			{
				const auto syslog_converter = runtime_config.syslog_converter();
				if (syslog_converter)
				{
					syslog_converter(message.first.get(), static_cast<int>(message.second));
				}
			}

			output_message(message.first.get(), logfile);
		}
	}
```

Т. е. при выставлении флага `m_destroying` в деструкторе, очередь остаётся как есть. Вместо этого можно сделать что-то типа:

```
	while (!m_destroying || !m_output_queue.empty())
	{
	  ...
	}
```

Вопросы, предложения, критика?

**Comment by il--ya** [comment]
Меня смущает что это будет делаться всегда и для всех сообщений. В итоге exit может подвиснуть и реально важное никуда не попадёт. Может использовать log_error где критично и дублировать его в отдельный файл без очереди? Так будет надёжнее.

**Comment by il--ya** [comment]
хотя одно другому не мешает, можно и очередь сбрасывать, и в отдельный файл писать все SYSERR:

**Comment by il--ya** [comment]
Не, большого смысла нет. exit() всё равно не будет флашить буферы, пока деструктор не отработает, так что если он подвиснет в деструкторе - всё равно ничего не узнаем. Пусть будет как ты предлагаешь.

**Comment by il--ya** [comment]
Только надо ещё проверять m_destroying и не принимать новые сообщения, если он выставлен. Иначе можно долго ждать.

**Comment by il--ya** [comment]
не, посылать новые сообщения будет некому, т.к. основной тред ждёт. В общем да, можно обойтись просто добавлением while (!m_destroying **|| !m_output_queue.empty()**)

**Comment by bylins** [comment]
не починено?

**Comment by kvirund** [comment]
Должно быть починено.

**Comment by kvirund** [comment]
Да, ты прав. Раньше при непустой очереди `pop` не вызывался и, следовательно, не мог давать зависания. Это я проглядел. Надо `pop` тоже поправить, заменив `if (m_destroying)` на `if (m_queue.empty())`. Оно и натуральней будет.
