### ISSUE TITLE
int general_savingthrow(CHAR_DATA *killer, CHAR_DATA *victim, int type, int ext_apply)

### ISSUE THREAD

**Issue by bylins** [bylins/mud#272]
save += GET_SAVE(victim, type);	// одежда   
	save += ext_apply;	// внешний модификатор

почему одежда виктима идет не в минус? имх это тупая опечатка

**Comment by bylins** [comment]
все нормально, оно минусовое

**Comment by bylins** [comment]
int general_savingthrow(CHAR_DATA *killer, CHAR_DATA *victim, int type, int ext_apply)
{
	int temp_save_stat = 0, temp_awake_mod = 0;

	if (- GET_SAVE(victim, type) / 10 > number(1, 100))
	{
		return 1;
	}
вот это не понимаю пока смысл

**Comment by il--ya** [comment]
Коммит 0331c43c390c4fa07fbcbce3ba9b949f83ba6504. Пока я только понимаю, что должно быть  number(0, 99) , иначе save -19 будет неотличим от save 0.

**Comment by il--ya** [comment]
Ну и лучше бы разрешение увеличить, как-то так
GET_SAVE(victim, type)  > number(0, 999)

**Comment by bylins** [comment]
я так понимаю это абсолютное прохождение или фэйл, типа была проверка на савинги, добавили на резисты

**Comment by Svjatovit** [comment]
Весь этот бордель с сейвами и тыпы надо переписывать на новые формулы. Не вижу смысла тут это мусолить.
