### ISSUE TITLE
Старые сеты

### ISSUE THREAD

**Issue by bylins** [bylins/mud#273]
Не можем перевести сет для кудеса на новую систему в олц, так как нельзя поставить флаг: "одевают чармисы". Сделано для меня непонятно
#17 ;Доспех верного наемника
<------>Name: Доспех верного наемника
<------>Alis: вн,верногонаемника
<------>Vnum: 1268 ;доспех верного наемника
<------><------>Oqty: 3
<------><------><------>Clss: 42
причем тут класс 42 и чармисы не врублюсь :(

**Comment by aryabenkiy** [comment]
При загрузке таблицы сетов по старому формату проставляется для какого типа она активится
 i = Clss: 42   NUM_PLAYER_CLASSES = 14   NUM_KIN = 3
if (i < 0 || i > NUM_PLAYER_CLASSES * NUM_KIN)
