### ISSUE TITLE
Ингредиенты, компоненты и материалы

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#276]
Ингредиенты и компоненты - все наоборот при фильтрации в магазине. по Тингр даёт компоненты. А ингредиенты - только по Трун. Кроме того, вещи для умения "смастерить" тоже почему-то стали магическими ингредиентами ("ветвь черного дерева"). Надо как-то разгрести это.

**Comment by aryabenkiy** [comment]
материалы (смастерить) и материалы (сшить) имеют разный тип. магические компоненты (для складывания рун) и магические компоненты (для смастерить лук) являются магическими ингридиентами. поэтому в магазине при фильтрации Трун = фильтрация магические компоненты. а Вот если сделать фильтр по Тматериал ты получишь то что необходимо для сшить. разделить первые вещи нужно было бы но это старые компоненты и на них много завязанно.

**Comment by Svjatovit** [comment]
Вообще, старый смастерить лук выпилить бы.... Но это все та же тема с недоделанным крафтом. Тему видимо закрываю, при переделке крафта этот косяк сам собой исчезнет, а править это сейчас и иметь кучу головняков не вижу смысла.
