### ISSUE TITLE
printf-подобные функции нужно объявлять с __attribute__((format(printf,m,n)))

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#284]
Чтобы компилятор выдавал предупреждения по ошибкам формата, все printf-подобные функции нужно объявить с атрибутом [`__attribute__((format(printf,m,n)))`](http://www.unixwiz.net/techtips/gnu-c-attributes.html).
В sysdep.h уже есть общий define для `__attribute__`:
https://github.com/bylins/mud/blob/9f9be3c31e9cc838ff9cabd98c61ba2104e9a570/src/sysdep.h#L244-L246
Т.е. нужно убедиться, что хедер включает sysdep.h прямо или через structs.h, и можно смело добавлять `__attribute__((format(printf,2,3)))` здесь, например:
https://github.com/bylins/mud/blob/9f9be3c31e9cc838ff9cabd98c61ba2104e9a570/src/comm.h#L32

Попробовал для начала с send_to_char(), вывалилось куча всего...

**Comment by bylins** [comment]
все так плохо? вроде 99.99% выводится

**Comment by il--ya** [comment]
Список функций в которые нужно добавить: 

comm.h:void send_to_char(const CHAR_DATA* ch, const char *messg, ...);
depot.cpp:void depot_log(const char *format, ...)
diskio.h:int fbprintf(FBFILE * fbfl, const char *format, ...);
file_crc.cpp:void add_message(const char *text, ...)
glory_const.hpp:void transfer_log(const char *format, ...);
logger.hpp:void shop_log(const char *format, ...);
logger.hpp:void olc_log(const char *format, ...);
logger.hpp:void imm_log(const char *format, ...);
logger.hpp:void err_log(const char *format, ...);
parcel.cpp:void parcel_log(const char *format, ...)
utils.h:void pers_log(CHAR_DATA *ch, const char *format, ...);

В этих уже есть:
logger.hpp:void log(const char *format, ...) __attribute__((format(printf, 1, 2)));
logger.hpp:     virtual void operator()(const char* format, ...) __attribute__((format(printf, 2, 3))) = 0;
logger.hpp:     void operator()(const char* format, ...) override __attribute__((format(printf, 2, 3)));
msdp.parser.hpp:        void log(const char* format, ...) __attribute__((format(printf, 1, 2)));
msdp.parser.hpp:        void debug_log(const char* format, ...) __attribute__((format(printf, 1, 2)));

**Comment by il--ya** [comment]
сделано
