### ISSUE TITLE
Включить по дефолту реж цвет полный для всех состояний

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#288]
сабж, чтобы можно было использовать цвета при создании чара и чтобы не было такой фигни:
`при уходе на постой:
Сила последних велетов Кпокинула вас и вы стали прежним.
Сила последних велетов Кпокинула вас и вы стали прежним.
Сила последних велетов Кпокинула вас и вы стали прежним.
Сила последних велетов Кпокинула вас и вы стали прежним.
Сила последних велетов Кпокинула вас и вы стали прежним.`

**Comment by bylins** [comment]
такое иссуе есть, чуть ниже
