### ISSUE TITLE
Недоступные вещи в магазине

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#292]
По-моему, вещи с флагом "недоступно" не должны продаваться персонажу, которому они недоступны. Сейчас вещь продаётся, и беззвучно падает на пол. Можно, конечно, возразить в духе "бачили очі, що купували" - можно ведь и "рассмотреть" предмет перед покупкой. Но я большого смысла не вижу в этой подлянке :)
Хочу сделать, чтобы продавец говорил  что-то типа "Э, Василий, ты же лекарь, эта вещь явно не для тебя." и не продавал предметы с флагом "недоступен" (по аналогии как сейчас не продаётся, если забит инвентарь).
Возражения, замечания?

**Comment by bylins** [comment]
Это сделано специально, для того в магазе есть опознание предмета. По аналогии надо тогда делать все такое на аукционе и на базаре. Не стоит автоматизировать процесс до ничегонедумания
