### ISSUE TITLE
Bug Report Стаб Тать/Наем

### ISSUE THREAD

**Issue by Jonikster** [bylins/mud#301]
Есть 2 чара. Тать и наем.
С самого создания и получения скила стаба, если наем норм бьет и даже криты проходят, то тать мажет. Практически постоянно.
Если брать 15 левел, у татя стаб под 20, у наема чуть выше из-за большего колва мудры, точно уже не скажу, так как наема делетнул, с ловкой 35, то в нубозоне бобры тать также мажет, а наем практически ни разу.
У наема и татя все способности врожденные, кроме любимого оружия.
Скайп volibor4444. Если требуется, предоставлю логи, еще с наема остались. И другую доп инфу, если нужно.

**Comment by il--ya** [comment]
Кстати, `features.lst` в исходниках на гитхабе не соответствуют тому, что на bylins.su
Не вижу "воровской удар" (`THIEVES_STRIKE_FEAT`) у татя   и "танцующая тень" (`SHADOW_STRIKE_FEAT`) у наёмника. Это же не секретная инфа, любой может посмотреть по команде "способности все". Обновите плз файл, у кого доступ есть.

**Comment by bylins** [comment]
Я то обновлю, но lib.template сделан для тестового сбора движка а не для игры, и информация туда добавлена минимальная и не поддерживается особо. Кодерам я выдаю оригинальный миск и служебные зоны

**Comment by bylins** [comment]
Сравнение тать vs наем не показало различий (Канаон) тем более код у стаба используется одинаковый

**Comment by kvirund** [comment]
lib.template должно быть шаблоном lib'а. Т. е. минимальным миром со `всеми` фичами, но без зон, триггеров, игроков. Всё остальное там должно быть актуальным.

Поэтому было предложение разбить этот lib/lib.template на две части: открытую и закрытую. Чтобы  открытая обновлялась и шла вместе с исходниками, а закрытая - только из закрытого репозитория.

Т. е. проблема-то в том, что есть две копии одного и того же. И одна копия поддерживается, т. к. активно используется, а другая - нет. Хотя эта другая должна быть базой.

**Comment by bylins** [comment]
реально это сделать только скриптом который определенные файлы из lib автоматом переносит в lib.template по крону например. Просто иначе тривиальное исправление опечатки 1 буквы в хелпе приводит к куче действий, которые для тестового движка ну вообще не актуальны. 
типа
cp /home/mud/mud/lib/text/help/* /home/mud/mud/lib.template/text/help/

**Comment by bylins** [comment]
commit -a -m

**Comment by bylins** [comment]
push

**Comment by il--ya** [comment]
> код у стаба используется одинаковый

Там несколько проверок на уникальные скилы татя и наёма THIEVES_STRIKE_FEAT и SHADOW_STRIKE_FEAT, так что по сути код и стаб разный. Вполне могли один из них сломать.

**Comment by il--ya** [comment]
> скриптом который определенные файлы из lib автоматом переносит в lib.template по крону например

А почему не наоборот, копировать из lib.template в lib? Код и справка должны обновляться вместе. Изменили фичу - тут же обновили хелп. То же по возможности с конфигами. А тривиальные исправления теперь можно делать прямо на гитхабе.

**Comment by kvirund** [comment]
Вообще, сделать какую-то цель, типа "deploy", которая разворачивала бы циркуль и lib.template в некоторую директорию (за исключением тестовых зон). В эту же директорию делать clone недостающей (секретной) части мира.

Тогда сборка была бы а-ля `cmake --build. --target deploy`.

**Comment by bylins** [comment]
> > код у стаба используется одинаковый
> 
> Там несколько проверок на уникальные скилы татя и наёма THIEVES_STRIKE_FEAT и SHADOW_STRIKE_FEAT, так что по сути код и стаб разный. Вполне могли один из них сломать.
это различия для проверки кто стабает, тать например в бою может стабать, потому крит у него реже, но может ваншот. Формула прохождения в go_backstab и она едина без этих проверок
аналогично в skills.cpp
	case SKILL_BACKSTAB:	//заколоть
нет различий в бонусах от статов.
Проверки на врожденные умения делаются чтоб напрямую не проверять класс игрока, почему так х3, принято давно не мною.

**Comment by bylins** [comment]
> > скриптом который определенные файлы из lib автоматом переносит в lib.template по крону например
> 
> А почему не наоборот, копировать из lib.template в lib? Код и справка должны обновляться вместе. Изменили фичу - тут же обновили хелп. То же с частью конфигов как файлы скилов и способностей. А тривиальные исправления теперь можно делать прямо на гитхабе.

просто более трудоемко и никому не нужно, да и оригинальный misc не лежит на гитхабе, у нас есть world на приватном bitbacket так как там приватные репы бесплатны, но это все равно уровень доступа имма 34

**Comment by bylins** [comment]
> Вообще, сделать какую-то цель, типа "deploy", которая разворачивала бы циркуль и lib.template в некоторую директорию (за исключением тестовых зон). В эту же директорию делать clone недостающей (секретной) части мира.
> 
> Тогда сборка была бы а-ля `cmake --build . --target deploy`.

у кого надо все есть нужное и это главное

**Comment by bylins** [comment]
> А почему не наоборот, копировать из lib.template в lib? Код и справка должны обновляться вместе. Изменили фичу - тут же обновили хелп. То же с частью конфигов как файлы скилов и способностей. А тривиальные исправления теперь можно делать прямо на гитхабе.

потому что 99% изменений в lib делаю я и мне неудобно туда сюда скакать :)

**Comment by kvirund** [comment]
Если рассуждать в таком ключе - то `lib.template` вообще не нужен, т. к. он в конечном счёте будет не рабочий. Но вместе с этим и сам циркуль будет бесполезен. А тогда и выкладывать исходники, по большому счёту, смысла нет, раз они будут нерабочими без секретного мира.

**Comment by bylins** [comment]
> Если рассуждать в таком ключе - то `lib.template` вообще не нужен, т. к. он в конечном счёте будет не рабочий. Но вместе с этим и сам циркуль будет бесполезен. А тогда и выкладывать исходники, по большому счёту, смысла нет, раз они будут нерабочими без секретного мира.

он и не нужен, я все равно каждый раз готовлю сборку для билдеров заново, просто чуть сокращает время так как не надо вспоминать список файлов для очищения

**Comment by bylins** [comment]
Тоха, билдеру не важно что расставлено в misc у профы он может это сделать и проставить иммом
важна работоспособность движка. Потому я особо не синхронизирую, если и так позволяет загрузиться виндовой версии мада

**Comment by il--ya** [comment]
> потому что 99% изменений в lib делаю я и мне неудобно туда сюда скакать :) + в lib секретная инфа, так что публиковать кое что нельзя

Ну ладно, дело хозяйское. Но, по моему, ты наоборот, добавляешь себе работы. Например поддержку help вполне можно было бы делегировать, а сейчас всё завязано на тебя.

**Comment by bylins** [comment]
на мне 90% работы делегировано, если не больше, лучше буду делать сам...

**Comment by Jonikster** [comment]
Так а со стабом что? Я предлагаю запустить в тест 2 чара, могу даже роскачать наема до того левла, что тать, чтобы дать точные параметры чара. Я не верю, что то такая вероятность.

**Comment by kvirund** [comment]
Нужно собрать статистику по этим стабам. Я хз, есть ли она уже или нет (Стрибог подскажет). Смысл должен быть следующим: для каждого стаба добавлять запись (ключ, успех/неуспех). Ключ - всевозможные параметры влияющие на вероятность стаба: т. е. класс, скилл, уровни навыков, влияющие на это. Ну а затем можно проверить и уже поотлаживать.

Если нет - то надо реализовать сбор этой статистики.

**Comment by bylins** [comment]
Все это уже делалось, стаб НОРМАЛЕН

**Comment by kvirund** [comment]
Ок. Тогда чем объясняется эта разница? Или это так и задумано?

**Comment by bylins** [comment]
Нет там разницы, субъективное впечатление

**Comment by lrdx** [comment]
Попробуем прислушаться к игрокам (да, они тоже иногда бывают правы). И о чудо! Что мы видим? То что в функции go_backstab есть проверка на способность наемника SHADOW_STRIKE_FEAT, после которой шанс промахнуться стабом ==0.
И да, это сильно нивелируется мортами.
https://github.com/bylins/mud/blob/082a8e1fda8bfc18a49389b69ec5f186f4c285ca/src/act.offensive.cpp#L556

**Comment by bylins** [comment]
| Персонаж не получает штрафа к попаданию при сражении в осторожном стиле.     |
| Осторожный стиль добавочно увеличивает спас-броски персонажа.   
причем здесь стаб? это чья-то диверсия что так подняли наему стаб.

**Comment by lrdx** [comment]
> | Персонаж не получает штрафа к попаданию при сражении в осторожном стиле. |
> | Осторожный стиль добавочно увеличивает спас-броски персонажа.
> причем здесь стаб? это чья-то диверсия что так подняли наему стаб.

Грубо говоря, умение наемника SHADOW_STRIKE_FEAT и умение татя THIEVES_STRIKE_FEAT используется по всему коду как разделение одинаковых скилов на татей и наемов. Зачем так сделано - без понятия, но это нормальная практика в коде.

**Comment by Jonikster** [comment]
Хорошо, вот 2 лога на минимальном левле в мадшколе с минимально раскаченым стабом.
[Лог.txt](https://github.com/bylins/mud/files/2537819/default.txt)

**Comment by bylins** [comment]
Это понятно, но 1. не дописано в справке 2. зачем тогда вообще % в умении, если оно всегда max_percent. Явно диверсия и похоже бодрича.
--------- его слова:
помнится, что я что-то такое там делал
но точно не 100%
процентов 70-80%

**Comment by lrdx** [comment]
Ну там дальше конечно есть проверка мисов на хитролах, но она ничтожна как и при ударе обычной рукой )

**Comment by bylins** [comment]
Наверно еще в те времена когда он бонус подножки х3 от ловки сделал, я как-то пропустил этот коммит. Убираю это условие нафиг, пусть наем будет как все, качает умения

**Comment by il--ya** [comment]
Представляю как Jonikster теперь волосы на себе рвёт... Насыпь хоть славы человеку в утешение. :)

**Comment by bylins** [comment]
ну да, 100 за абуз, но я его ник в игре не знаю :)

**Comment by Jonikster** [comment]
Персы на мыле leon.belov04@gmail.com
Го на златоведа

**Comment by Jonikster** [comment]
Благодарю за реакцию
