### ISSUE TITLE
Сделать приоритет имм.команд выше, чем у триггеров

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#304]
Чтобы не было такого:
707H 252M ??? Зауч:0 34L 1006309G Вых:З> уда
707H 252M ??? Зауч:0 34L 1006309G Вых:З> 

Что это Вы собрались уда ?
707H 252M ??? Зауч:0 34L 1006309G Вых:З> удалить 12322
707H 252M ??? Зауч:0 34L 1006309G Вых:З> 

Что это Вы собрались удалить ?

**Comment by il--ya** [comment]
Надо просто добавить синоним odelete (object delete)

**Comment by il--ya** [comment]
Сделал чтобы invis всегда работал, pull request #327
