### ISSUE TITLE
Одетый актив не соответствует справке

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#306]
---------------------------------------------------------------------------
Парные молнии богов прави
---------------------------------------------------------------------------
Суммарные свойства набора: 
Профессии : дружинник, витязь
 + Аффекты : доблесть,полет,мигание,медлительность,ускорение
 + Свойства :
 +    сила улучшает на 5
 +    телосложение улучшает на 6
 +    попадание улучшает на 6
 +    воля улучшает на 15
 +    реакция улучшает на 15
 +    инициатива улучшает на 10
 +    разум улучшает на 10
 +    защита.от.чар улучшает на 3
 + Меняет умения :
 +    веерная защита улучшает на 50%
---------------------------------------------------------------------------
черная молния
Наносимые повреждения '10D5' среднее 30.0
Вес : 30
Аффекты : мигание
Свойства :
   сила улучшает на 2
Предметов для активации: 2
Листать : <RETURN>, Q<К>онец, R<П>овтор, B<Н>азад, или номер страницы (1/3).
 + Профессии : дружинник витязь
 + Аффекты : доблесть,медлительность
 + Свойства :
 +    телосложение улучшает на 4
 +    попадание улучшает на 6
 +    инициатива улучшает на 10
 +    защита.от.чар улучшает на 3
 + Устанавливает наносимые повреждения '7D6' среднее 24.5
 + Меняет умения :
 +    веерная защита улучшает на 25%
---------------------------------------------------------------------------
белая молния
Наносимые повреждения '6D5' среднее 18.0
Вес : 21
Аффекты : ускорение
Свойства :
   телосложение улучшает на 2
Предметов для активации: 2
 + Профессии : дружинник витязь
 + Аффекты : полет,ускорение
 + Свойства :
 +    сила улучшает на 3
 +    воля улучшает на 15
 +    разум улучшает на 10
 +    реакция улучшает на 15
Листать : <RETURN>, Q<К>онец, R<П>овтор, B<Н>азад, или номер страницы (2/3).
 + Устанавливает наносимые повреждения '7D6' среднее 24.5
 + Меняет умения :
 +    веерная защита улучшает на 25%

**Comment by bodrich** [comment]
Телосложние дает  +4, а не +6
Силы +3, а не +5
В целом, похоже, что при активе шмотки, статы которые висят на самих шмотках - исчезают

**Comment by bylins** [comment]
вот что в них прописано:
#0 ; Парные молнии богов прави
    Name: Парные молнии богов прави
    Vnum: 79913
        Oqty: 2
            Clss: 5 9
                Amsg: &W$o0 ярко засверкала в ваших руках.&n
                Dmsg: &W$o0 вспыхнула и угасла.&n
                Ramg: &W$o0 $n1 ярко засверкала.&n
                Rdmg: &W$o0 $n1 вспыхнула и угасла.&n
                Affs: p0C0
                Afcn: 5 4
                Afcn: 18 6
                Afcn: 42 10
  Afcn: 51 3
                Dice: 6 7
  Skll: 12 25
    Vnum: 79914
        Oqty: 2
            Clss: 5 9
                Amsg: &W$o0 ярко засверкала в ваших руках.&n
                Dmsg: &W$o0 вспыхнула и угасла.&n
                Ramg: &W$o0 $n1 ярко засверкала.&n
                Rdmg: &W$o0 $n1 вспыхнула и угасла.&n
                Affs: t0D0
                Afcn: 1 3
                Afcn: 20 -15
                Afcn: 49 10
  Afcn: 39 -15
                Dice: 6 7
  Skll: 12 25

**Comment by bylins** [comment]
Magni Magnifiko, [02.11.18 12:57]
в справке учитывает в общем активе

Magni Magnifiko, [02.11.18 12:57]
поэтому и не соответствие

**Comment by bodrich** [comment]
> телосложение улучшает на 2
> сила улучшает на 2
Где вообще это прописывается?

**Comment by bylins** [comment]
setstuf.lst

**Comment by bodrich** [comment]
Проблема остается. Если на шмотке висели какие-то статы, то при активе сета - эти статы не учитываются.

**Comment by il--ya** [comment]
А как понял, что не учитывается? По "счет все"?

**Comment by bodrich** [comment]
Ага. Но иссуе можно закрывать, ибо старые сеты мы не поддерживаем и этот сет надо перенести на новую систему (на которой сделаны миники)

**Comment by Svjatovit** [comment]
Закрывать так закрывать...
