### ISSUE TITLE
Павла воззвала к богам с сообщением : 'Вы взяли сообщите богам если увидите этот предмет из трупа Павлы.'

### ISSUE THREAD

**Issue by bylins** [bylins/mud#309]
предмет 100 vnum

**Comment by bylins** [comment]
при смерти какой-то предмет становится первый по рнум в мире?

**Comment by bylins** [comment]
я кусок жаренного мяса с внум 100 так переименовал

**Comment by il--ya** [comment]
Знать бы, что у Павла было до смерти.

**Comment by il--ya** [comment]
Можно как-то в тестовом маде загрузить игрока? Сбросить ему руками пароль и зайти. Не факт конечно что у него после постоя шмот не сменился

**Comment by il--ya** [comment]
Нашёл:

https://github.com/bylins/mud/blob/e07b2659807aa7f8ebfbc4018a827392daef3dcf/src/fight_stuff.cpp#L712-L723

Павла из своего трупа брала, поэтому не обжигало.

**Comment by bylins** [comment]
Бодрого застрелить, свитки решили не делать, а  я в массе патча это пропустил.
Удалить все гавно. свитки при смерти делать не стали, в продажу выложили.
