### ISSUE TITLE
какой-то небольшой косяк с setall[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#31]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

frozen off не выводит из ада (хотя фриз сняло)      
а frozen 0 вывело

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/31

=======COMMENTS=======

Date: 2017-06-28T14:52:47Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

```
#!c++

			sprintf(buf, "Freeze OFF by %s", GET_NAME(ch));
			add_karma(vict, buf, reason);
			if (IN_ROOM(vict) != NOWHERE)
			{
				act("$n выпущен$a из темницы!", FALSE, vict, 0, 0, TO_ROOM);

```
так понимаю цель в ЛД не будет выпущена, стоит добавить сообщение что она не будет выпущена из ада

**Comment by Svjatovit** [comment]
Всю дорогу так было. Фриз оф просто расфриживает, из ада надо выпускать отдельно. Сделанов вроде бы чтобы не выкидывало из ада тех, кого отдельно за какие-то заслуги посадили.
