### ISSUE TITLE
Некорректно работает AFF_FLAGS().set.

### ISSUE THREAD

**Issue by bylins** [bylins/mud#322]
Дополнят попозже

**Comment by bodrich** [comment]
Там раньше была проверка на npc, я ее убрал так как аффекты, когда моб снимал миник не исчезали, поэтому пришлось их сбрасывать. Правильнее было бы при снимании сетины, проверять аффекты, которые исчезают при деактивации миника, но я так и не нашел как это сделать.

**Comment by kvirund** [comment]
Там проблема в том, что есть два механизма установки аффектов:

1. `AFF_FLAGS` - какое-то поле поля поля какого-то поля `CHAR_DATA`;
2. `CHAR_DATA::affected` - список аффектов

Соответственно, механизм (2) главнее. Т. е. в какой-то момент аффекты (1) переставляются на основании аффектов в (2). За исключением пары, которая фильтруется.

Ну так вот, AFF_FLAGS().set надо просто запретить и там, где компилироваться перестанет - переделать на механизм (2). В идеале - вообще оставить только один механизм. Возможно, какой-то комбинированный.

**Comment by il--ya** [comment]
Я не знаю, связано это или нет, пока дополню тут.
Если у моба в аффектах стоит "прячется","маскировка", то проверка CAN_SEE() на него возвращает false даже во время боя, когда он уже не прячется и не маскируется. 
В CAN_SEE() проверяется AFF_FLAGGED(obj, EAffectFlag::AFF_HIDE) && !AFF_FLAGGED(obj, EAffectFlag::AFF_CAMOUFLAGE)
То есть видимо эти флаги остаются установленными. Что-то тут не так.

**Comment by aryabenkiy** [comment]
поскольку правка данного флага [https://github.com/bylins/mud/commit/f21f7ea15ba9813fd8f61da2cdefd459ac80dd12](url) порадила новые баги [https://github.com/bylins/mud/issues/337](url) предлагаю откатить код в части обнуления.

Для большей ясности у вызваных последователей прототипы (которые используются в качестве базы) не обладают многими аффектами. + при почарме чармерами у чармисов уходят некоторые аффекты (поидее СЗ должно уходить у лихо при почарме купцом но как сейчас не проверял).

**Comment by aryabenkiy** [comment]
> Там проблема в том, что есть два механизма установки аффектов:
> 
>     1. `AFF_FLAGS` - какое-то поле поля поля какого-то поля `CHAR_DATA`;
> 
>     2. `CHAR_DATA::affected` - список аффектов

Давайте разберемся в 2х таблицах

**Comment by kvirund** [comment]
Ну так вот, пункт 2.а как раз и устанавливает эту связь ежду механизмами. Т. е. в какой-то момент надо снять с `affected_by` аффекты, назначенные из `affected`.

Т. е., грубо говоря, исчезает аффект из `affected` - надо убирать его из `affected_by`. При этом возникает вопрос: откуда появился этот аффект в `affected`: был он установлен только аффектом из `affected_by` или как флаг оно тоже было? Т. е. появляется неоднозначность: удалять или нет?

Другой момент: как и когда синхронизировать `affected` с `affected_by`? Сейчас это делается вручную после добавления аффекта в `affected_by`, путём вызова специальной функции. Эта функция проходитя по списку и перевыставляет `affected`. При этом, разумеется, если какой-то аффект из списка пропал - он удалён не будет (это делалось только для `!IS_NPC`). Т. е. f21f7ea15ba9813fd8f61da2cdefd459ac80dd12 (Пофиксил, когда аффекты с мобов не спадали): теперь перед выставлением аффектов в `affected` из `affected_by`, `affected` предварительно очищается с запоминанием старых флагов.

Т. е. f21f7ea15ba9813fd8f61da2cdefd459ac80dd12 по сути, просто расширяет сброс аффектов в этом механизме "синхронизации" и на мобов тоже. Далее, как работает сама эта синхронизация.

  1. Все флаги сбрасываются в дефолтовые: для игроков это `clear_flags`, для моба - флаги из его прототипа;
  2. Из старых флагов сохраняются те, которые в списке `char_saved_aff`;
  3. Происходит накатывание флагов из `affected_by`.

Т. е. имеем: флаги, которые надо сохранить, дефолтовые флаги и то, что накатывается из `affected_by`. Если множества флагов `affected` и `affected_by` не пересекаются - то этот механизм работает правильно: ну, т. е. если что-то на тике сбрасывается - значит его нет в списке `char_saved_aff`.

Без f21f7ea15ba9813fd8f61da2cdefd459ac80dd12 для мобов в синхронизации будет отсутствовать пункт (1). Т. е. это просто откинет нас обратно к другой проблеме и ничего не даст.

Итого,

  * #337 починится добавлением нужных аффектов в `char_saved_aff`.
  * откатывать f21f7ea15ba9813fd8f61da2cdefd459ac80dd12 смысла не вижу: оно приводит механизм к какому-то универсальному виду.
  * Нужно убедиться, что множеста флагов в `affected` и `affected_by` не пересекаются. Иначе получаем неоднозначность при удалении флагов. Но это уже приводит нас к другому выводу: если эти флаги не пересекаются - зачем их связывать? Почему не иметь множество "простых аффектов, хранящихся в `affected`" и множество "какое-то другое название для другого типа аффектов, хранящихся в `affected_by`". Т. е. если это разные механизмы - то и работать с ними по отдельности. С другой стороны, если оба этих механизма дают какой-то третий набор флагов: объединение флагов `affected` и `affected_by` - то это уже должен быть третий набор флагов, а не солянка в одной из первых двух механизмов. Т. е., например, можно было бы сделать какой-то геттер `bool CHAR_DATA::has_affect(enum ThirdClassAffect affect) const;`, который бы определял откуда может идти аффект `affect` и проверял только либо первый механизм, либо второй.
  * Если же множества флагов `affected` и `affected_by` пересекаются  - то геттер из предыдущего механизма просто опрашивал бы обе структуры. Но в любом случае, когда выставляется тот или иной аффект должно быть чётко понятно, какой именно механизм нужно использовать. Т. е. сеттеров должно быть два: `void CHAR_DATA::set_affect_flag(enum FirstClassAffect affect);` и `void CHAR_DATA::add_special_affect(const SecondClassAffect& affect);`

**Comment by kvirund** [comment]
> А что, оно может быть ни к чему не привязанным флагом? Должен же быть какой-то источник - заклинание, экипировка и тд.

`affected_by` - это просто битовый набор флагов. Эти аффекты не имеют источника. Точнее, он не хранится.

> Я не думаю, что такой геттер делать разумно - это будет жутко неэффективно. Флаги на то и флаги, что они проверяются абсолютно везде и много. Просто при обновлении нужно учитывать все возможные источники аффекта.

Вряд ли это будет хуже полного прохода по всему списку аффектов и пересинхронизация по любому чиху. Проверка битового поля - константное время. Проверка в списке - тоже могла бы быть константной, если бы это был `unordered_map`. Это константно как сумма. Если будет проседать - можно и кэшировать.

Но тут проблема-то не столько в производительности, сколько в том, чтобы отделить мух от котлет: там два механизма выставления аффектов. И одна невнятная попытка впихнуть более широкий механизм (список структур `affects` с источниками и т. п.) в старый механизм `affected_by`  (простой набор битов без какой-либо информации). В результате кто-то выставляет аффекты по-старому и они теряются, а кто-то по новому и они не затираются. Я уж не говорю о том, что в коде вообще просто каша нечитабельная получается из всего этого.

Немного конкретики:

```cpp
inline FLAG_DATA& AFF_FLAGS(CHAR_DATA* ch) { return ch->char_specials.saved.affected_by; }
```

где `affected_by`:

```cpp
FLAG_DATA affected_by;
```

А `FLAG_DATA`, по сути, набор функций над:

```cpp
std::array<uint32_t, PLANES_NUMBER> m_flags;
```

В то время как `affected`:

```cpp
using char_affects_list_t = std::list<AFFECT_DATA<EApplyLocation>::shared_ptr>;
...
char_affects_list_t affected;	// affected by what spells
```

А `AFFECT_DATA` - структура с широким набором свойств (которая, кстати, тоже не только для аффектов используется: одна структура на аффекты персонажа и на аффекты комнаты).

А вот тут механизм, который вихивает невпихуемое:

```cpp
// This updates a character by subtracting everything he is affected by
// restoring original abilities, and then affecting all again
void affect_total(CHAR_DATA * ch)
```

Поэтому я и говорю: если более широкий механизм - не пересекается с старым - то это два разных механизма и их нужно разделять. Если один список вычисляется из двух разных механизмов - то результирующий список - это третья структура. Ну и если старый механизм покрывается новым, более широким - то старый надо выкинуть и сделать его "только чтение" с автоматическим обновлением при добавлении/удалении аффекта в новой структуре.

**Comment by il--ya** [comment]
В общем прежде чем что-то менять, нужно либо найти документ, по которому это делалось, либо самим его писать. И начать надо с определения, что же такое "аффект", а то сейчас несколько довольно разных понятий под этим понимаются, по крайней мере если судить по коду.

**Comment by aryabenkiy** [comment]
Мы кодим не для того чтобы кодить а для того чтобы люди играли. сейчас имеется проблема с мобами после наших правок. При этом правки не решают проблему которые должны решить, поэтому предлагаю откатить правки и делать правильное решение.

**Comment by bylins** [comment]
Но заведомо кодить с ошибками просто нельзя.

**Comment by bylins** [comment]
Так кто возьмется разобраться с этим? а то чармисы работают некорректно

**Comment by aryabenkiy** [comment]
добавлять char_saved_aff все афекты не есть хорошо по причине того что в #337 мы видим волша. а он своим последователям (защитница, огнехраны) вешает куча обкастов, что равносильно добавление всех этих кастов в список.
Если все будут с этим согласны тогда я могу добавить в список все эти аффекты.

**Comment by kvirund** [comment]
> Мы кодим не для того чтобы кодить а для того чтобы люди играли. сейчас имеется проблема с мобами после наших правок. При этом правки не решают проблему которые должны решить, поэтому предлагаю откатить правки и делать правильное решение.

Как бы, тут вопрос в том, какая из ошибок хуже: если та, которая появилась после - то ок, нужно откатить. Но при этом создать отдельную ветку, куда перенакатить этот патч и не закрывать ветку, пока патч не будет доведён до ума.

> добавлять char_saved_aff все афекты не есть хорошо по причине того что в #337 мы видим волша. а он своим последователям (защитница, огнехраны) вешает куча обкастов, что равносильно добавление всех этих кастов в список.

Если эти аффекты не могут прийти из списка `affected` (и, следовательно, при удалении из него не должны очищаться в `affected_by`) - то ничего страшного: раз их все нужно сохранять - значит они все должны быть в этом `char_saved_aff`. А вот если могут - то это как раз та неоднозначность о которой я говорил и тут уже *необходимо* явное разделение механизмов.

**Comment by kvirund** [comment]
> Так кто возьмется разобраться с этим? а то чармисы работают некорректно

У меня сейчас четыре выходных с завтрашнего дня. Могу попробовать за это время управиться, думаю. Только опишите, пожалуйста, кто знает, как конкретно воспроизвести ошибку и проверить что вот она, присутствует. Т. е. и ошибку с пропаданием и ошибку с несниманием (вдруг там что-то ещё замешано, кроме этого механизма, который мы тут обсуждаем).

**Comment by aryabenkiy** [comment]
Афекты из affected в affected_by  как минимум невидимость. но в отличии от невидимости полноценной (на стафе) при пропадании из affected она пропадает и из affected_by (начало боя или команда появиться).
для повторение #337 достаточно произнести заклинания ангел или огненый защитник. .если ангел произнесен с обаятельностью большей 30 то небесная защитница будет с аффектом ...светится ярким сиянием в таблице affected_by будет запись освящение а в таблице affected будет. Заклинание : освящение             (18 часов) . повторить 
Проблему которую решала правка f21f7ea  я не знаю как повторить.

**Comment by aryabenkiy** [comment]
насчет таблиц affected_by и affected могу сказать что не все записи affected попадают в affected_by, но есть еще записи которые при наличии в affected_by не попадают в affected (призматическая аура против освящения, верхом против полета : ) ) если необходимо какие-то списки предоставить или разъяснения по обоим таблицам могу помочь.

**Comment by bylins** [comment]
одеваем 30 хари
колд !ангел
см
[  108] (летит) Небесная защитница летает тут.
...светится ярким сиянием 
Минул час.
см

**Comment by kvirund** [comment]
Спасибо.

> но есть еще записи которые при наличии в affected_by не попадают в affected

Тут интереснее пересечение множеств этих аффектов. Т. е. какие аффекты одновременно могут быть назначены прямо в `affected_by` и какие могут прийти из `affected`. Судя по всему, `невидимость` - как раз такой аффект. Поэтому с ним и проблемы. Потому добавление его в `char_saved_aff`, вероятнее всего, не починит проблему, а просто именит её вид: т. е. он просто не будет сниматься, когда пришёл из `affected`.

**Comment by kvirund** [comment]
Что я хочу сделать:

  1. Ограничить доступ к `affected_by`;
  2. Добавить производное поле с аффектами персонажа;
  3. `AFF_FLAGS` оставить только ту, которая возвращает константные аффекты. Возвращать там теперь это производное поле;
  4. Добавить сеттер для `affected_by`, который автоматом будет обновлять и производное поле: т. е. чистить, копировать туда `affected_by` и накатывать на него же содержимое `affects` (по сути - вызов `affect_total`);
  5. Те места, где компилироваться перестанет, поменять на использование сеттера (4), за исключением функции `affect_total`.
  6. В функции `affect_total` обновлять не поле `affected_by`, на производное. Перед обновлением накатывать на него в том числе и `affected_by`.

Что это даст: будет два явных источника аффектов, на основании которых будет формироваться результирующее множество аффектов персонажа. Т. к. код не будет иметь способов изенить это поле, кроме как в функции `affecy_total`, то никто не сможет по ошибке изменить это поле и будет вынужден выбирать либо первый механизм работы с аффектами, либо второй. Плюс, т. к. механизмы будут явно разделены - то первый не сможет нарушить данные во втором и наоборот.

**Comment by kvirund** [comment]
Добавление мудрости:

`oedit 110; r; 0; 6; +50; 0; q; y; load obj 110; дер нож`

**Comment by aryabenkiy** [comment]
надо обояние

**Comment by kvirund** [comment]
> надо обояние

Да, я сделал обаяние, но почему-то написал "мудрости". :)

**Comment by aryabenkiy** [comment]
надо записать зону

**Comment by kvirund** [comment]
Оно в памяти уже меняет. Этого достаточно для воспроизведения.

**Comment by aryabenkiy** [comment]
1 там еще посде r и я не ставлю +50 а ставлю 50

**Comment by aryabenkiy** [comment]
кстати если на ангела бросить освящение то оно не пропадет.

**Comment by kvirund** [comment]
Возможно, оно работает через `affects`.

**Comment by kvirund** [comment]
Ну вот, видимо, потому, что он в `affects` добавляется - то после сброса его в `affected_by` он там снова восстанавливается из `affects`.

**Comment by bodrich** [comment]
Разве в void affect_from_char(CHAR_DATA * ch, int type)
ch->affect_remove(affect_i);
не надо заменить на что-то другое?

**Comment by kvirund** [comment]
Может быть. Объясни, пожалуйста, почему ты так думаешь и на что именно нужно заменить?

**Comment by il--ya** [comment]
Я не знаю, в этом ли проблема сейчас с аффектами, но методом пристального взгляда нашёл вот это:

https://github.com/bylins/mud/blob/fbde1461b01067e70f6d4958399e71e88aff2220/src/char.cpp#L2423-L2427

clear_flags - это пустой битсет
https://github.com/bylins/mud/blob/fbde1461b01067e70f6d4958399e71e88aff2220/src/db.cpp#L158

+= определено так:
https://github.com/bylins/mud/blob/fbde1461b01067e70f6d4958399e71e88aff2220/src/structs.h#L1319-L1327

То есть  `m_affected_by += clear_flags;` нифига не очищает.

**Comment by kvirund** [comment]
А ему и не надо. Это мёртвый код. Я его удалил уже, просто запушить не успел ещё. Там несколькими строчками выше:

```cpp
m_affected_by = char_specials.saved.active_affects;
```

Т. е. теукщие аффекты просто принимаются за постоянные. А потом на текущие дополнительно накатываются пульсовые.

**Comment by il--ya** [comment]
Но у PC не должно быть никаких постоянных, если я всё правильно понимаю. Это у моба может быть неспадающая слепота.

**Comment by kvirund** [comment]
Запостоянные аффекты принимаются врождённые и наложенные шмотками.

**Comment by kvirund** [comment]
Как-то вот так:

![image](https://user-images.githubusercontent.com/674287/49562266-5ce9f780-f8e0-11e8-9542-a357a63db133.png)

**Comment by kvirund** [comment]
А вот так это было до моего патча:

![image](https://user-images.githubusercontent.com/674287/49562281-7428e500-f8e0-11e8-867a-84124bf6222b.png)

**Comment by kvirund** [comment]
Я уже сейчас думаю, а почему там просто при любом изменении в любом источнике аффектов не перевычислять их заново. А то я в этом огороде уже сам вконец запутался.

**Comment by kvirund** [comment]
Собственно, именно это и происходит при добавлении/удалении эпплая. Не так только при надевании снимании вещи.

**Comment by il--ya** [comment]
Там дальше по коду после этой недо-очистки которую я исправил а ты вообще удалил, идёт повторный накат аффектов со шмоток и фитов. То есть по смыслу всё правильно, нужно очищать

**Comment by kvirund** [comment]
Тогда очищать надо не в ветке `else`, а прямо в начале функции:

```cpp
	const auto saved = m_affected_by;

	m_affected_by.clear();
```

Но это всё равно не могло быть ошибкой. Два раза накатить флаги - получим те же самые флаги.

**Comment by kvirund** [comment]
Кстати, а где там накатываются врождённые аффекты? Что-то не могу найти.

**Comment by il--ya** [comment]
и кстати вот эта строка в remove_pulse_affect() вообще смысла не имеет
https://github.com/bylins/mud/blob/fbde1461b01067e70f6d4958399e71e88aff2220/src/char.cpp#L304
потому что после неё идёт 
https://github.com/bylins/mud/blob/fbde1461b01067e70f6d4958399e71e88aff2220/src/char.cpp#L322
А update_active_affects() херит m_affected_by. Зачем-то правда сохраняет копию в saved, но ничего с этой копией не делает.

**Comment by il--ya** [comment]
> Тогда очищать надо не в ветке `else`, а прямо в начале функции:
> 
> ```c++
> 	const auto saved = m_affected_by;
> 
> 	m_affected_by.clear();
> ```
Для мобов же не очищается. У них могут быть врождённые флаги. Типа постоянно летает, просто так, без причины.

**Comment by il--ya** [comment]
Ну вот фиты накладываются, там же в update_active_affects()
https://github.com/bylins/mud/blob/fbde1461b01067e70f6d4958399e71e88aff2220/src/char.cpp#L2464-L2474

> А то я в этом огороде уже сам вконец запутался.

Не мудрено, это не огород, а авдиевы конюшни. :)

**Comment by kvirund** [comment]
> и кстати вот эта строка в remove_pulse_affect() вообще смысла не имеет

Возможно. Но я старался не менять порядок вызовов и механизмы. Собственно, оно так и было раньше (см. f3128981ab23a0af5db6cbe99677d85c73c139f7):

```cpp
	affect_modify(this, af->location, af->modifier, static_cast<EAffectFlag>(af->bitvector), FALSE);
	if (af->type == SPELL_ABSTINENT)
	{
		if (player_specials)
		{
			GET_DRUNK_STATE(this) = GET_COND(this, DRUNK) = MIN(GET_COND(this, DRUNK), CHAR_DRUNKED - 1);
		} else
		{
			log("SYSERR: player_specials is not set.");
		}
	}
	if (af->type == SPELL_DRUNKED && af->duration == 0)
	{
		set_abstinent();
	}

	affected.erase(affect_i);

	affect_total(this);
```

> А update_active_affects() херит m_affected_by. Зачем-то правда сохраняет копию в saved, но ничего с этой копией не делает.

Делает:

```cpp
		// Check if any stealth affect has been turned off
		for (const auto& i : char_stealth_aff)
		{
			if (saved.get(i)
				&& !active_affects().get(i))
			{
				CHECK_AGRO(this) = TRUE;
			}
		}
```

Этот хитрый флаг хитро контролирует агро на персонажа в снике.

**Comment by aryabenkiy** [comment]
могу помочь с структурой если есть необходимость.

**Comment by kvirund** [comment]
Да, конечно. Было бы весьма неплохо: https://github.com/bylins/mud/wiki/%D0%90%D1%84%D1%84%D0%B5%D0%BA%D1%82%D1%8B.

**Comment by il--ya** [comment]
> Собственно, началось-то всё с того, что возникла такая проблема: в коде понадобилось выставить персонажу некоторый аффект. 
Аффект или флаг аффекта? Давайте всё же различать.
Аффект - это результат применения заклинания, спелла, умения, способности. Он может модифицировать статы и выставлять флаг аффекта.
Флаг без спелла, насколько я понимаю, бывает только у мобов. У чаров такого быть не должно. По-хорошему и у мобов не должно, но это очень хлопотно менять.

**Comment by kvirund** [comment]
Флаг аффекта.

У чаров тоже могут быть: `AFF_HORSE`, `AFF_SNEAK`, `AFF_CAMOUFLAGE`, возможно что-то ещё. Обнуление `m_affected_by` в начале `update_active_affects` равносильно отмене постоянных аффектов (постоянных флагов аффектов). Поэтому проще было мой патч откатить. Получили бы то же самое.

**Comment by il--ya** [comment]
> У чаров тоже могут быть: AFF_HORSE, AFF_SNEAK, AFF_CAMOUFLAGE

А.. сейчас `char_saved_aff` вообще не используется. Т.е. `AFF_HORSE` и `AFF_GROUP` будет слетать.
Проблема в том, что affected_by в прототипе имеет совсем другой смысл, чем affected_by в чаре, и нужен только для мобов (у чаров прототипа нет).

**Comment by kvirund** [comment]
> > Поэтому проще было мой патч откатить.
> 
> Какой именно?

Все. И начинать сначала просто. Как бы, понятно, что мой патч только внёс всякого шуму и сейчас чтобы от него избавиться пришлось просто отключить то, ради чего патч делался. Т. е. все патчи из веток `issue.322*` нужно просто выкинуть.

**Comment by il--ya** [comment]
Я всё же за то, чтобы оставить. AFF_HORSE и AFF_GROUP нужно восстанавливать, а так вроде почти рабочее.

**Comment by kvirund** [comment]
Так с предварительной очисткой эти постоянные аффекты становятся ненужными: они же всё равно очищаются.

**Comment by kvirund** [comment]
Я к тому, что в результате они не сделали код лучше, а только ещё больше запутали. При весьма сомнительной пользе (я её уже не вижу, честно говоря). В общем, сейчас, думаю, стоит откатить. Когда будет готов дизайн - можно будет откатить откат и снова на это посмотреть.

**Comment by il--ya** [comment]
Польза в том, что сейчас код читабельнее, и в нём можно хоть что-то понять

**Comment by kvirund** [comment]
> Да, конечно. Было бы весьма неплохо: https://github.com/bylins/mud/wiki/affects

Добавил то, что сам знал. Просьба тех, кто хоть что-то знает и понимает - сделать ревью и дополнить. Примеры кода, описание подводных камней, багов и сложностей приветствуются в соответствующих секциях.

**Comment by il--ya** [comment]
Не могу понять как исправить, потому что трудно понять что было сломано, и как должно было работать. **Согласен, надо откатить.** Дизайна дожидаться необязательно, нужно мелкими шажками рефакторить и менять, а там глядишь будет понятно что к чему.
У меня уже сейчас гораздо лучше понимание, буду помогать хотя бы ревью.

По поводу дока - замечание по терминологии.

Возьмём заклинание "защита богов". Оно состоит из трёх частей: улучшает на 10 сэйвы APPLY_SAVING_STABILITY, APPLY_SAVING_WILL, APPLY_SAVING_REFLEX, и устанавливает флаг аффекта AFF_SHIELD вместе с каждой такой частью (см. [тут](https://github.com/bylins/mud/blob/e022b5be0bab51b3b1688cc6939c407afc25875c/src/magic.cpp#L3029)). Как называть эти "части"? Ты называешь их apply, но существующий код устанавливает эти "части" вызовом функции affect_to_char(), передавая ей параметр типа AFFECT_DATA, которая затем вызывает affect_modify для собственно добавления или удаления аффекта. Логично называть аффектом именно это: изменение стата и/или установку флага. 
Ещё одно соображение против apply: это слово выражает действие, не очень подходит для обозначения сущности. Хотя вообще, конечно, affect - это тоже глагол (существительное только в очень узком смысле). А "воздействие" - это effect. Ну да ладно, после `SKILL_SHIT` я готов уж потерперь affect вместо effect. :smile:

Ну а устанавливаемый флаг называть называть "флаг аффекта". Модификатор параметра - ну пусть будет apply, хотя он вне аффекта никак не существует.

**Comment by bylins** [comment]
> Логично называть аффектом именно это: изменение стата и/или установку флага.
Вообще-то они изначально назывались apply affect

**Comment by il--ya** [comment]
> > Логично называть аффектом именно это: изменение стата и/или установку флага.
> 
> Вообще-то они изначально назывались apply affect

Ну уж хотя бы AffectApplication тогда

**Comment by kvirund** [comment]
Да, терминология там хромает. Я сам часто забываю, что к чему. В общем-то, я предлагаю заодно в дизайн-документе с этим определиться.

**Comment by kvirund** [comment]
Дело в том, что не все эпплаи накладывают аффекты. Только некоторые. Что делают остальные - я вообще не знаю. Поэтому я даже не пытался править названия.

**Comment by kvirund** [comment]
Кстати, эффекты там тоже есть какие-то. :)

**Comment by il--ya** [comment]
Это всё effects - воздействия. Какие-то воздействия модифицируют статы, какие-то флаги, какие-то и то, и другое. Один спелл или умение может наложить несколько воздействий, с разной силой и временем действия. Вообще механизм и идея хорошая, не глючило бы ещё...

**Comment by il--ya** [comment]
Надо вернуть рефакторинг, который ты делал, с переносом функций из handler.cpp в методы CHAR_DATA и спрятать affected_by в сеттер-геттерг. Я бы назвал их get/set_affect_flag а не get/set_affect.

**Comment by il--ya** [comment]
По поводу ДТ на будущее если тестировать, там две ветки в зависимости от RENTABLE() (боевые действия). В одной вызывается `die()`, который затем вызывает `raw_kill()`, а в нём происходит `reset_apply_affects()`. В другой вызывается `extract_char()`, который аффекты не трогает. Возможно, из-за этого у некоторых чаров воспроизводилось, а у некоторых нет.
https://github.com/bylins/mud/blob/0671de25abf285a51ddbf0b528d82c71fc04f962/src/deathtrap.cpp#L204-L210

**Comment by il--ya** [comment]
> Кстати, эффекты там тоже есть какие-то. :)

Ну да, "ярость", "предсмертная ярость", "испуг" и "плач" - это стопудово аффективные состояния. :)

**Comment by il--ya** [comment]
Я пришёл к выводу, что сейчас всё сделано более-менее правильно с аффектами, как ни странно.
#337 нужно исправлять нормальной установкой аффекта (а не только флага, как сейчас) - тогда ничего не будет слетать. duration ставить равным времени почарма.
