### ISSUE TITLE
в money.txt пишется бред, точнее строки сислога вместо нужных сообщений

### ISSUE THREAD

**Issue by bylins** [bylins/mud#325]
подробнее тут
https://github.com/bylins/mud/pull/324

**Comment by il--ya** [comment]
Вот тут лажа:

https://github.com/bylins/mud/blob/74fd2a5890c47e6d0e6cead85e8c26bd4ba3e872/src/logger.cpp#L101-L104

Делается подмена logfile в основном треде, а реальная запись в лог идёт в другом треде. Понятно что в итоге пишется куда попало. Сислог попадает в другие логи, и наоборот.

**Comment by kvirund** [comment]
Согласен. Мой косяк. Значит пропавшие записи должны были попасть в MSDP лог.

Создал pull request с решением.

**Comment by kvirund** [comment]
Хотя нет. Есть ещё один косяк:

```cpp
		logfile = runtime_config.logs(channel).handle();
		log("%s", str);
		logfile = runtime_config.logs(SYSLOG).handle();
```

**Comment by kvirund** [comment]
См. pull request: https://github.com/bylins/mud/pull/326

**Comment by il--ya** [comment]
Я так понимаю output_thread общий для всех stream, в нём запись в файл делается так:
			output_message(message.first.get(), logfile);
Нужно либо кидать сообщения в отдельные output queue для разных файлов, либо в самом сообщении указывать, в какой файл класть сообщение.

**Comment by kvirund** [comment]
> Я так понимаю output_thread общий для всех stream, в нём запись в файл делается так:
output_message(message.first.get(), logfile);

Да, но logfile всегда связан с syslog'ом только. Поэтому буферизация предполагалась только для него. Т. е. неявно output_thread только для syslog'а.

> Нужно либо кидать сообщения в отдельные output queue для разных файлов, либо в самом сообщении указывать, в какой файл класть сообщение.

Да, если расширять для остальных файлов.

**Comment by kvirund** [comment]
> Я так понимаю output_thread общий для всех stream, в нём запись в файл делается так:
> output_message(message.first.get(), logfile);

Да, ты прав. Я понял в чём косяк.

**Comment by il--ya** [comment]
Починилось?

**Comment by kvirund** [comment]
Я хз. Я проверял только что компилируется. Стрибог должен был проверить работу.

**Comment by il--ya** [comment]
Ну я @bylins и спрашиваю. Если починилось пусть закрывает )

**Comment by bylins** [comment]
починилось, закрываю
