### ISSUE TITLE
Сделать суммон чармисов заклинанием !призвать!

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#33]
*Originally reported by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

дать возможность кудесам призывать чармисов
по соло спелам дать возможность кастить груп (дышать водой, детекты, бв кк) по аналогии с силой защитой полетом

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/33

=======COMMENTS=======

Date: 2017-07-08T09:01:37Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Merged in issue.33 (pull request #31)

see #33

**Comment by Svjatovit** [comment]
Сделано. Для черноков тоже работает.
