### ISSUE TITLE
Оформление кода

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#332]
Пара мыслей по правилам оформления кода, главным образом для @kvirund как автора [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) и единственного, похоже, человека, которого это вообще беспокоит :)

1.
>Тела конструкций if, if ... else for, while, do ... while всегда должны быть
заключены в символы '{', '}'.

Может всё же сделать исключение для совсем простых конструкций if, if...else, for и while? При условии, что часть после оператора в скобках занимает одну строку и тело состоит из одной команды на одной строке (для if...else *обе* части из одной команды и на одной строке).
Иначе получается, что на две полезных строки мы добавляем ещё две неинформативные строки со скобками, тем самым не улучшая, а ухудшая читабельность.

2.
>Символы '\*' и '&' при описании типа данных не должны иметь пробелов слева, но должны иметь хотя бы один пробел справа.
Например:
const char* message = "blah-blah-blah";
const auto& message_ref = message;

Звездочка (*) считается префиксным оператором, в том числе в объявлениях. То есть * относится не к тому, что слева, а к тому, что справа.
Примеры, когда такой гайдлайн не очень работает:
char *foo = "foo-str", *bar = "bar-str";
int (*foo)(); // указатель на функцию, которая возвращает int
Про это довольно подробно написано в [википедии](https://en.wikipedia.org/wiki/Const_(computer_programming)#C++_convention)
"Attaching the pointer symbol to the type is tricky, as it strongly suggests a pointer type, which isn't the case."

По этому пункту мне, вообще, без разницы. Просто я (не без причины) привык сдвигать вправо или как компромисс ставить пробелы с обоих сторон, и хотел бы просто уточнить - для кого-то это имеет значение? Если да, то попробую переучиться :)

3.
В правилах не описано, как именовать функции, методы, члены классов и так далее. Я имею в виду CamelCase/snake_case, с заглавной/с маленькой/все заглавными, префиксы и тд. Какие-то вещи очевидны типа m_ перед членами класса, но их всё равно лучше упомянуть. Какие-то вещи менее очевидны, например как именовать классы. Я вот не очень понимаю, приходится выбирать стиль по аналогии, как привык или наобум.
Я не к тому, что давайте сейчас будем всё переименовывать. Просто для нового кода и при рефакторинге нужен какой-то ориентир.

**Comment by kvirund** [comment]
> Может всё же сделать исключение для совсем простых конструкций if, if...else, for и while?

Я это писал больше из практических соображений: код Былин изобилует всякими макросами. Поэтому обязательное наличие скобок защитило бы от чего-то вроде:

```cpp
#define SOME_MACROS(x, y) x = 5; y = 6
...
if (some_condition)
  SOME_MACROS(a, b);
```

Но вообще, мне вовсе не принципиально, кто как пишет. Просто чем меньше правил - тем проще им следовать. Исключения добавляют мыслей, а-ля "а можно ли вот тут не следовать правилу" и только отвлекают. :)

> Звездочка (*) считается префиксным оператором, в том числе в объявлениях. То есть * относится не к тому, что слева, а к тому, что справа.

Да, согласен. Мне тоже больше нравится когда оно прижато к правой стороне. Просто пока это никого не волновало - я написал так, как принято у меня на работе, чтобы не переучиваться/путаться.

Что касается примеров:

```cpp
char *foo = "foo-str", *bar = "bar-str";
```

Так делать не хорошо, т. к. противоречит принципу "одна строка - одна команда" (считая объявление (особенно, с инициализацией) за одну команду).  А если переписать - то получится вполне сносно:

```cpp
const char* foo = "foo-str";
const char* bar = "bar-str";
```

> хотел бы просто уточнить - для кого-то это имеет значение?

Для меня имеет значение. Но только в том смысле, что надо взять одно и ему следовать. Т. е. чтобы код одного проекта не пестрил разными стилями. Сейчас это, конечно, далеко не так, но я искренне верю, что если достаточно упорно следовать принципу неусугубления - то можно сделать конфетку из чего угодно.

> В правилах не описано, как именовать функции, методы, члены классов и так далее. Я имею в виду CamelCase/snake_case, с заглавной/с маленькой/все заглавными, префиксы и тд. Какие-то вещи очевидны типа m_ перед членами класса, но их всё равно лучше упомянуть. Какие-то вещи менее очевидны, например как именовать классы. Я вот не очень понимаю, приходится выбирать стиль по аналогии, как привык или наобум.

Тут сложно. Я даже хз, что выбирать. Мне, например, нравится для классов/enum'ов использовать CamelCase с первой заглавной. Методы/функции/локальные переменные/формальные параметры - snake_case. `m_` префикс для обычных полей, `s_` для статических полей, CAPITAL для констант/макросов/элементов перечислений. Элементы перечисления именовать без всяких префиксов (на работе приняли префиксы в виде первых букв CamelCase'а, типа `enum ECamelCase { ECC_ITEM1, ECC_ITEM2}` - такая фигня нечитабельная).

Префиксы классов тоже. Я там некоторые создавал а-ля `CPrototype` (т. е. с использованием префиксов C/E/T) - уродство. Сейчас я бы с удовольствием это переименовал назад. суффикс `_t` для алиасов типов в сочетании с snake_case, а-ля `using some_type_t = std::vector<int>;` мне пока кажется нормальным.

В общем, смотри сам. Можешь сделать свои правки и pull-request на них. Дальше обсудим конкретные изменения. Я не вдавался в детали по coding-style ещё и затем, чтобы не вписывать девелоперов в жёсткие рамки. Как бы, с одной стороны это хорошо, когда код выглядит в одном стиле, но над Былинами работают люди, которым интересен не столько код с его чистотой, сколько наполнение самой игры. И, наверное, тут я обязан принять их сторону, в том плане, что в Былинах лучше криво написанная новая фича, чем идеальное ничто. Поправить эту фичу и привести код в порядок я могу и сам. Но, т. к. в сами Былины я уже давно не играю (да и вообще я нуб там :)) и плохо представляю, что творится в самой игре - я просто описал некоторые рекомендации. Если им будут следовать - отлично. Нет - ну, пофиг, поправлю, когда руки дойдут. Лишь бы работало. А очевидно-неработающие вещи Стрибог выпиливает в два счёта.

Сейчас вот надо с утечками подразобраться. :)

**Comment by kvirund** [comment]
Но вообще, я считаю, мы уже далеко продвинулись. Если не с оформлением кода, то хотя бы с workflow. Так, я помню когда код каждый коммитил в единственную ветку master. Вместо системы сборки были Makefile'ы и невнятный проект для студии, которые работали в лучшем случае, только на тех серверах, где последний раз использовались. А вывод компилятора больше напоминал блевотину в которой иногда можно было разобрать, собственно, саму команду на запуск компилятора.

Правда, сейчас что-то под CygWin'ом сборка не работает толком. Но у меня есть сильное подозрение, что там получается какой-то кривой линк. Т. к. ошибки совершенно бредовые (например, см. мои попытки починить их вот тут 6bcf2c0320d72e0c5a5f49dc2c2d6425aa2cdb0d: я хз как этот коммит вообще может хоть что-то починить, однако, после него был прогресс). Удалось найти несколько unit-тестов, которые кордампят, но я вообще хз, что там может не работать: там всё проще палки.

**Comment by il--ya** [comment]
> Я не вдавался в детали по coding-style ещё и затем, чтобы не вписывать девелоперов в жёсткие рамки. 

Ну жёсткость рамок определяется не правилами, а строгостью надзора за их выполнением.
Пусть будет не столько policy сколько guideline, чтобы хотя бы в порядке добровольного следования был ориентир.

> Правда, сейчас что-то под CygWin'ом сборка не работает толком.

А он сильно нужен, тот cygwin?

**Comment by aryabenkiy** [comment]
Буду тешить что мой комент породил у Ладника необходимость таких правок : ))
но в общем согласен с необходимостью причесывать.
Насчет кто-то пишет под Cygwin'ом, опять таки наверное это был я. Но уже сижу плотно на Ubuntu.
И опять мои привычки доводять людей до бешенства : ) поскольку в IDE системе что я использую или криво настроены (виноват постараюсь исправится) или так работают отступы в начале кода.
Бросте сюда кто-то последнюю правку требований к исходному коду (помню отступ 4 пробела, с++ 17 версии и все : (  ).

**Comment by kvirund** [comment]
Вот эта пока последняя версия: https://github.com/bylins/mud/blob/master/CONTRIBUTING.md

**Comment by il--ya** [comment]
Предлагаю использовать [гайд Гугла](https://google.github.io/styleguide/cppguide.html#Naming), чтобы не изобретать колесо.

**Comment by kvirund** [comment]
Я не против.

**Comment by Svjatovit** [comment]
В общем, по возможности придерживаемся при оформлении кода, нейминге и всем таком прочем стандарта Google:
https://google.github.io/styleguide/cppguide.html
Единственное исключение - там прописана длина строки 80 символов, что по нынешним временам излишнее ретроградство. Потому использовать ограничение в 120 символов. Clion знает стандарт гугла (ставится в настройках редактора) и может автоматически форматировать под него код.
