### ISSUE TITLE
Лидерство - бонус к попаданию или защите?

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#342]
Справка по лидерству говорит что оно даёт бонус к AC (-2). Однако судя по коду там бонус к хитролам. То ли справка неправильная/устарела, то ли код неправильный?

https://github.com/bylins/mud/blob/627367952e10ea8e0b314928074fabea637d9c7d/src/fight_hit.cpp#L3391-L3393

**Comment by bylins** [comment]
Посмотрел сорцы 2001 года, тоже самое, видимо еще сквиз намудрил (или справкописатель не правильно прочел), но зачем лидеру хитроллы? надо привести код в  соответствие к справке

**Comment by Svjatovit** [comment]
А точно надо? Смысл этого явно был в том, что если лидерка высокая, то это добавляет защиты. Но сейчас у нас есть десяцкий и держать строй. Лучше эту тему развовать имхо, в плане повышения защиты от лидерки, а не тупо АС растить.

**Comment by Svjatovit** [comment]
Исправлено. Хоть вся механика там и кривая напрочь...
