### ISSUE TITLE
Неполадки со статистикой ипи

### ISSUE THREAD

**Issue by bylins** [bylins/mud#343]
Создан: [25-11-2017] Последний вход: [21-11-2018] Играл: [4899h 39m] Возраст: [47]

Персонаж заходил с IP-адресов:
  82.208.126.238    20 07:09:56  1 Декабря 2017 года 
   93.183.73.231    23 10:18:47 31 Июля 2018 года 
  82.208.126.229    74 09:40:03 13 Декабря 2017 года 
   79.126.43.151    33 14:39:26 20 Декабря 2017 года 
  82.208.101.247    37 11:43:55 31 Декабря 2017 года 
  109.184.53.207    10 09:46:07  4 Января 2018 года 
   79.126.51.125    50 21:24:19 16 Января 2018 года 
   82.208.124.22    15 14:33:46 27 Января 2018 года 
    109.184.0.80     1 03:42:19 28 Января 2018 года 
  109.184.29.193     1 05:23:33 28 Января 2018 года 
  109.184.55.244     8 19:02:24 29 Января 2018 года 
    79.126.57.69     1 21:58:29 29 Января 2018 года 
  109.184.90.143     3 07:12:35 30 Января 2018 года 
  82.208.124.211     1 09:46:19 30 Января 2018 года 
    79.126.46.52    16 14:11:37  4 Февраля 2018 года 
  82.208.124.169    44 09:54:11  6 Марта 2018 года 
   82.208.127.57    39 09:17:27 22 Марта 2018 года 
   82.208.124.67     4 17:59:36 24 Марта 2018 года 
  82.208.126.213     9 21:25:29  1 Апреля 2018 года 
   82.208.127.43    15 19:20:35  5 Августа 2018 года 
   82.208.127.73     9 23:13:20 15 Августа 2018 года 
   82.208.127.48     5 08:11:20 17 Августа 2018 года 
   82.208.127.56    12 07:29:53 22 Августа 2018 года 
  82.208.127.118     2 11:22:04 23 Августа 2018 года 
   109.184.63.71    48 12:11:56 22 Сентября 2018 года 
  82.208.127.245    16 01:06:50  2 Октября 2018 года 
  82.208.126.100     1 16:35:50  3 Октября 2018 года 
   82.208.126.87     5 08:30:16  6 Октября 2018 года 
  82.208.126.119     1 15:31:36  6 Октября 2018 года 
   82.208.126.35     2 18:35:22  7 Октября 2018 года 
    82.208.124.3     2 09:15:22  9 Октября 2018 года 
 109.184.107.137     6 21:48:05 16 Октября 2018 года 
   109.184.19.95    57 20:20:01 15 Ноября 2018 года 
 109.184.103.210    12 17:43:45 21 Ноября 2018 года 

Ладно сортировка через жопу (надо поправить) почему в стате нет первого входа в игру

**Comment by lrdx** [comment]
Статистика формируется следующим образом: Ip -> кол-во заходов -> Последний заход.
На данный момент сортировка идет по времени первого добавления Ip адреса в список, т.е. первый ip это как раз тот, который использовался при создании чара, просто после этого с этого айп зашли суммарно 20 раз и последний 1 Декабря 2017 года.
В связи с этим и сортировка не по дате, т.к. чаром заходили со старого ip, но гораздо позже.

Предлагаю сделать так: сортировать по дате захода, но при этом указывать дополнительно около ip, с которого был создан чар (в данном случае верхний).

**Comment by bylins** [comment]
да, нормальное решение
