### ISSUE TITLE
Правки по гривнам

### ISSUE THREAD

**Issue by lrdx** [bylins/mud#364]
В коммите https://github.com/bylins/mud/commit/946e96936f6d269b8b7d058bcb9fa59a1ebe49a7 производится проверка на уровни мобов и затем идет присваивание переменной самой себе 
```
			int value = x.reward + number(1, 3);
			if ((zone_table[world[this->in_room]->zone].mob_level > 24) 
				|| (zone_table[world[this->in_room]->zone].mob_level > (GET_LEVEL(this) + GET_REMORT(this)/5)))
			{
				value = value;
			}
			else
			{
				value /= 2;
			}
```
Не знаю, что там хотели сделать, но так точно быть не должно.

**Comment by kvirund** [comment]
> На самом деле не угадаешь) может ошибка и value должно при этом меняться

Оно же менялось на то же самое значение: `value = value;`.

**Comment by lrdx** [comment]
Тут есть 2 варианта:
1. Сделано специально и value не должно меняться.
2. Ошибка и value должно было меняться.
Хотелось бы услышать автора коммита @bylins, чтобы было понятно как править.

**Comment by bylins** [comment]
value не должно меняться, да и не я это делал, я закоммитил
