### ISSUE TITLE
Какая то проблема с act

### ISSUE THREAD

**Issue by bylins** [bylins/mud#372]
![image](https://user-images.githubusercontent.com/42086238/49599148-52d40180-f991-11e8-9384-206349b9d92b.png)

**Comment by bylins** [comment]
что очень странно
		act("Вы прекратили следовать за $N4.", FALSE, ch, 0, ch->get_master(), TO_CHAR);
		act("$n прекратил$g следовать за $N4.", TRUE, ch, 0, ch->get_master(), TO_NOTVICT | TO_ARENA_LISTEN);
		act("$n прекратил$g следовать за вами.", TRUE, ch, 0, ch->get_master(), TO_VICT);

**Comment by il--ya** [comment]
+ Проявляется при отсоединении по неактивности. Со стороны выглядит нормально.

**Comment by bylins** [comment]
без коня тоже самое, и это явно дремучая бага (на основе повторяется)
![image](https://user-images.githubusercontent.com/42086238/49608352-799e3200-f9a9-11e8-842f-745c00213985.png)
но вот чо интересно, как может глючить надпись конь, моб то в игре, а не уведен в странную комнату.

**Comment by bylins** [comment]
```
		if (*orig == '$')
		{
			switch (*(++orig))
			{
			case 'n':
				if (*(orig + 1) < '0' || *(orig + 1) > '5')
				{
					snprintf(nbuf, sizeof(nbuf), "&q%s&Q", (!IS_NPC(ch) && (IS_IMMORTAL(ch) || GET_INVIS_LEV(ch))) ? GET_NAME(ch) : APERS(ch, to, 0, arena));
					i = nbuf;
				}
				else
				{
					padis = *(++orig) - '0';
					snprintf(nbuf, sizeof(nbuf), "&q%s&Q", (!IS_NPC(ch) && (IS_IMMORTAL(ch) || GET_INVIS_LEV(ch))) ? GET_PAD(ch, padis) : APERS(ch, to, padis, arena));
					i = nbuf;
				}
				break;

```

**Comment by bylins** [comment]
типа выставление цвета должно быть, но в самом perform_act
```
			if (cap)
			{
				if (*i == '&')
				{
					*buf = *(i++);
					buf++;
					*buf = *(i++);
					buf++;
				}
				*buf = a_ucc(*i);
				i++;
				buf++;
				cap = 0;
			}

```
зачем-то смещается в непонятном случае буфер на 1

**Comment by bylins** [comment]
Квирунд пишет:
В общем, я подозреваю, что проблема вот тут:
if ((t->character) && (pos = proc_color(i, (clr(t->character, C_NRM)))))
Тут если t->character == nullptr - то вторая часть выполняться не будет.
Для персонажа, которого отключают - это вполне возможно.
Т. е. к моменту вывода уже не ясно, поддерживает ли персонаж полноцветный режим или у него цвета отключена.
*отключены
Хотя буфер-то уже сформирован с &q и &Q.
Просто настройки цвета должны быть настройкой дескриптора соединения, а не настройкой персонажа.
Ну, т. е. вывод осуществляется не только когда есть персонаж, а как только появляется соединение. 
Просто у персонажа может быть какая-то настройка, которая включала бы цвета в соединении.
Стрибог пишет:
Я давно предлагал отменить при создании персонажа выбор цвета, сейчас нет клиентов его не поддерживающих даже у слепых поддерживается

**Comment by il--ya** [comment]
А если кого-то не устраивают дефолтные цвета и он делает свою раскраску?

**Comment by bylins** [comment]
сабст воспринимает строки а не цвет, будет работать и в режиме полном

**Comment by il--ya** [comment]
Добавить цвета сабстом можно, а вот убрать уже гораздо сложнее.

**Comment by bylins** [comment]
Клиенты для subst передают строку без управляющих ANSI последовательностей, так что не вижу проблем

**Comment by bylins** [comment]
реж призыв поломали
вместо него срабатывает реж контроль

**Comment by bylins** [comment]
интересно, а где вообще проверяется PRF_COLOR при выводе текста, не нахожу, давно чтоль убрали?

**Comment by bylins** [comment]
нашел, там полный мрак

**Comment by il--ya** [comment]
Я не очень понимаю зачем выпиливать фичу которая 20 лет работала и ещё 20 проработает. Она нужна. Может, не всем, но я точно знаю, что не все любят когда мад расцвечен как новогодняя ёлка.

Проблему, которая в  этом реквесте, выпиливание не решает.

**Comment by bylins** [comment]
у нас "цвет нет" тривиально не работает, так как в тех же зонах и в половине кода используется аддон easy color который плюет на этот режим (такие определения как &R &n)
