### ISSUE TITLE
Необрабатываемые применения аффектов в логе

### ISSUE THREAD

**Issue by il--ya** [bylins/mud#374]
```
Dec  7 16:47:28 :: SYSERR: Unknown apply adjust 61 attempt (/home/mud/mud/src/handler.cpp, affect_modify).
Dec  7 13:16:55 :: SYSERR: Unknown apply adjust 58 attempt (/home/mud/mud/src/handler.cpp, affect_modify).
```
58 это `APPLY_BONUS_EXP`
61 это `APPLY_MADNESS`

Бонус экспы не добавляет ничего к статам, а используется как абсолютное значение, поэтому не попал в affect_modify() - он по сути ничего не модифицирует, а используется напрямую.
```C++
if (aff->location == APPLY_BONUS_EXP) // скушал свиток с эксп бонусом
{
    exp *= MIN(3, aff->modifier); // бонус макс тройной
}
```
Это не вписывается в общий механизм, нужно переделать чтобы вписывалось. Ввести какой-то стат "скорость набора экспы", и его модифицировать, скажем дефолтное значение 100%, и модификатор до +200%. А можно и в минус... :grin:

У безумия модификатор не используется, поэтому его нужно переделать в флаг, то есть APPLY_MADNESS убрать и добавить флаг AFF_MADNESS, и при касте проверять.

**Comment by il--ya** [comment]
> может это косяк dg_affect ?

Что - косяк? Эти два сообщения в логе на которые я завёл issue - по ним вполне понятно где косяк и как исправить, дойдут руки сделаю.

**Comment by Svjatovit** [comment]
Неоднократно были креши с спамными сообщениями о таких аффектах в логе. Вряд ли это совпадение.
