### ISSUE TITLE
нужен новый тип триггера

### ISSUE THREAD

**Issue by bylins** [bylins/mud#397]
Моб убил игрока, и чтоб был доступ к списку кого он убил

**Comment by lrdx** [comment]
К списку всех, кого он убил?

**Comment by bylins** [comment]
да

**Comment by lrdx** [comment]
Необходим ли порядок убийства при выводе? Необходимо ли включать все убийства одного игрока, или достаточно, чтобы каждый игрок был один раз в списке?

**Comment by bylins** [comment]
порядок пусть будет, а вот 2 раза одного и того же уже не надо

**Comment by lrdx** [comment]
Описание триггера для dg справочника.
Kill
Событие: Моб убил игрока
NArg: Вероятность (в процентах), что триггер будет запущен.
Argument: Не используется.
Возвращаемое значение: 1 - игрок будет добавлен в список убитых мобом игроков, 0 - не будет.
Локальные переменные:
actor UID идентефикатор убитого игрока
list строка список UID игроков, которых моб убил (исключая actor, если он не был убит ранее)

Примечание: в списке игроки сортированы по времени убийства (последний убитый - первый в списке). Если игрока убивают повторно он переносится в начало списка.
