### ISSUE TITLE
Ап волхва

### ISSUE THREAD

**Issue by bylins** [bylins/mud#402]
от Вадика (он же Арас, играл волхвом 9 лет) чтобы подтянуть профу к остальным надо:
1. чтобы добавлялась мана после 8 морта
2. дать возможность регенить ману в бою
3. чтобы фраг был сильнее удара палкой
а если есть желание апнуть волхва
то предлагаю объединять руны.
Пример.
имея кучу рун порядка в инвентаре
с них можно сделать одну,
а их таймеры и заряды суммируются.
Ну и пару заклов добавить ибо на
каждый лом должен быть противолом)
массовое истощение
снять сон
снять безсознанку

**Comment by bylins** [comment]
снять сон нет спела

**Comment by bylins** [comment]
от Полеля
https://docs.google.com/spreadsheets/d/1j-sVnkd-cZxLTXP__KH7ifIqJsuuj6S-2y0fc_WmjbU/edit#gid=0

**Comment by lrdx** [comment]
Вы апнуто его хотите или сделать незаменимым лидером группы? +200% опыта всей группе?? Трешей качать отличный скилл. В целом идея хорошая, но нахер на лидера вешать?
Завяжите скилл на время кд/действия, и как минимум опыт должен зависеть от реморта чара (не волхва).

**Comment by aryabenkiy** [comment]
когда бросается обкасты (груп сила) она завист от морта волша а не того на кого он кастит. почему тут должно быть по другому ?

**Comment by nickpoida** [comment]
День добрый. Поддерживаю Полеля в плане того, что не надо перевешивать скиллы других профессий на волхва по сути, не стоит из него делать недоколда. А вот новый скилл, это хорошо, это развитие, Опять же, хочется развеять сомнения уважаемого лдрх, относительно опыта, согласно моим расчетам, в среднем рандоме получается, удачное набрасывание опыта при 200 скилла(24 морта) удается раз в 68 часов, то есть хрен запланируешь. Бонус же в степи включить гораздо проще.

**Comment by lrdx** [comment]
Кулдаун | 12 часов/24 тика
-- | --
Аффект держится | 12 часов/24 тика

Не знаю про какие 68 часов идет речь, но я вижу кд и понимаю, что это должно работать постоянно. Для дуала это имба, имх. Не понимаю зачем это нужно вообще вводить, именно опыт нигде больше не задействован, зачем его трогать?

**Comment by nickpoida** [comment]
@ldrx вероятность выпадения и прохождения именно опыта составляет 0.08 при двухстах скилла. 
Вероятность повторного данного события подряд составляет уже 0.0064.
Где оно будет постоянно работать?

**Comment by lrdx** [comment]
))) и как я должен догадаться, что даётся рандом из предложенных вариантов )

**Comment by nickpoida** [comment]
Пардон. Но там именно так, просто видимо не правильно описано. Суть в том, что иммортал не выбирается. А просто выпадает рандомно.

**Comment by lrdx** [comment]
Ещё мне не нравится, что это раьотает, только когда волхв - лидер, зачем это?

**Comment by joopel** [comment]
Абсолютно против множителя опыта на группу. Что мешает волхву стоять спамить по кд на ренте подношение пока не выпадет опыт, в группе все равно большинство пассивные или боты. Выпадает жертва на опыт - пентится на маяка и зоним, да еще под свитками опыта...уф.
Опять же проблема выкача трешей. Опять же абьюз волхва, когда волхв афкает на ренте, но за ним следует куча живых уродов, которые получают халявный бонус на 24 тика.

По бонусам с формул тоже какой то овер выходит. Имеем 160 скила, даже если выпадет стойкость - это +32 на всю группу. А помимо этого у нас бонусы к сейвам нехилые теперь дают груп доблесть, внимательность и т.д - как то много с обкастов выходит.

Как вижу я, если делать - снижать кд до 8 тиков при макс раскачке, продолжительность на 4-6 тиков, бонусы по сейвам при 200% скила = 20. Как будет работать бонус на хп, как клич мощи богатырский? или типа надувки чернока?
------------------
Против волхва фрагующего. 

Давайте смотреть в сторону оборотничества. Код точно не помню, но мы можем же одеть на волхва какую-то шкуру, просто обрубать ему возможность каста, добавлять дамролы, дополнительные атаки.

Вообщим я за оборотничество. Могу попытаться привлечь Свентовита. И да, у него были интересные мысли о волхвах, попрошу его написать их здесь тоже.

**Comment by aryabenkiy** [comment]
Не переймайся. Некому так апать.

**Comment by bylins** [comment]
макс манны и реген манны
GET_REAL_WIS(ch))]+GET_REMORT(ch)*500
кап 9980
считаю нужным увеличить\изменить количество манны от мудры, уменьшить от морта (и так мудра при морте растет) и убрать или увеличить кап
int mana[] = { 0,		// Wiz= 0
			   100,			// Wiz= 1
			   250,			// Wiz= 2
			   500,			// Wiz= 3
			   750,			// Wiz= 4
			   1000,			// Wiz= 5
			   1250,			// Wiz= 6
			   1500,			// Wiz= 7
			   1750,			// Wiz= 8
			   2000,			// Wiz= 9
			   2250,			// Wiz=10
			   2500,			// Wiz=11
			   2750,			// Wiz=12
			   3000,			// Wiz=13
			   3250,			// Wiz=14
			   3500,			// Wiz=15
			   3650,			// Wiz=16
			   3900,			// Wiz=17
			   4000,			// Wiz=18
			   4300,			// Wiz=19
			   4600,			// Wiz=20
			   4900,			// Wiz=21
			   5200,			// Wiz=22
			   5500,			// Wiz=23
			   5800,			// Wiz=24
			   5920,			// Wiz=25
			   5930,			// Wiz=26
			   5940,			// Wiz=27
			   5950,			// Wiz=28
			   5960,			// Wiz=29
			   5970,			// Wiz=30
			   5980,			// Wiz=31
			   5990,			// Wiz=32
			   6000,			// Wiz=33
			   6000,			// Wiz=34
			   6000,			// Wiz=35
			   6000,			// Wiz=36
			   6000,			// Wiz=37
			   6000,			// Wiz=38
			   6000,			// Wiz=39
			   6000,			// Wiz=40
			   6000,			// Wiz=41
			   6000,			// Wiz=42
			   6000,			// Wiz=43
			   6000,			// Wiz=44
			   6000,			// Wiz=45
			   6000,			// Wiz=46
			   6000,			// Wiz=47
			   6000,			// Wiz=48
			   6000,			// Wiz=49
			   6000			// Wiz=50
			 };

// Количество гейн маны волхва в секунду в зависимости от инты
int mana_gain_cs[] = { 2,	// Int= 0
					   3,			// Int= 1
					   3,			// Int= 2
					   4,			// Int= 3
					   4,			// Int= 4
					   5,			// Int= 5
					   5,			// Int= 6
					   6,			// Int= 7
					   6,			// Int= 8
					   7,			// Int= 9
					   7,			// Int=10
					   8,			// Int=11
					   8,			// Int=12
					   9,			// Int=13
					   9,			// Int=14
					   10,			// Int=15
					   11,			// Int=16
					   12,			// Int=17
					   13,			// Int=18
					   14,			// Int=19
					   15,			// Int=20
					   16,			// Int=21
					   17,			// Int=22
					   18,			// Int=23
					   19,			// Int=24
					   20,			// Int=25
					   22,			// Int=26
					   24,			// Int=27
					   26,			// Int=28
					   27,			// Int=29
					   29,			// Int=30
					   31,			// Int=31
					   33,			// Int=32
					   35,			// Int=33
					   37,			// Int=34
					   39,			// Int=35
					   41,			// Int=36
					   44,			// Int=37
					   47,			// Int=38
					   50,			// Int=39
					   53,			// Int=40
					   56,			// Int=41
					   59,			// Int=42
					   62,			// Int=43
					   65,			// Int=44
					   68,			// Int=45
					   71,			// Int=46
					   74,			// Int=47
					   77,			// Int=48
					   80,			// Int=49
					   83			// Int=50
					 };

**Comment by pilaty** [comment]
предлагаю 1 мудра стоит 500 маны
в голого чара нуба будет 18 мудры 9к маны
в 50 мудры будет 25к маны
и долой проверки на морты
одел стаф - качайся
сабж

**Comment by pilaty** [comment]
по поводу файлика моего с апом волхва 
ссылка
https://docs.google.com/spreadsheets/d/1t1VZUTlExI2NUgj9VZ3MBudCp3Lp3miY3Bd4VSnmhe8/edit#gid=0


я не имею ввиду дамаг как у колда нивкеом случае
содрать со школ чтоб ничего не придумывать. поставить зтычки на морты
будет антуражно
дамаг пофиксить

**Comment by bylins** [comment]
т.е. морты  убираю из формулы, как и кап?

**Comment by bylins** [comment]
нужна функция ch->has_skill() или ch->get_skill()

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/56304024-da9ef900-6145-11e9-95d6-9acd3529daba.png)

**Comment by bylins** [comment]
#220
;Владыка морей в ПЦ
33316 10  250

**Comment by bylins** [comment]
косяк в школах магии, шмотка с магией земли дает сразу 3 сферы например

**Comment by Svjatovit** [comment]
Планку с мудры сняли, а общеабстрактные рассуждения "чего бы такого сделать" - на форум.
