### ISSUE TITLE
Проблема билдерам найти нужный триггер

### ISSUE THREAD

**Issue by bylins** [bylins/mud#404]
Просят команду что-то типа "vnum trig номершмотки"   чтоб найти в каком триггере она грузится.
Реализацию предложил Квирунд, при загрузке мада создать новую структуру, которую по этой команде выводить
----------------------------------------
Ага.
Там сейчас что-то типа

s = read_line(f);
trig_commands.push_back(s);
Вот добавить глобальный индекс (рядом со списком триггеров) типа std::unordered_map<object_id_t, trigger_id_t> index;
А при загрузке строки проверять, команда ли это загрузки шмотки и добавлять в индекс.
Типа
if (parse_command(s, object_id))
{
  index[object_id].push_back(trigger_id);
}
С типом индекса ошибся. Их же несколько для одного ID может быть.
Поэтому:
std::unordered_map<object_id_t, std::list<trigger_id_t>> index;
Ну а потом команда, типа "триггеры объект <ID>"
А в обработчике:
auto i = index.find(object_id);
if (i != index.end())
{
}
В скобках:
for (auto j = i.begin(); j != i.end(); j++)
{
  send_to_char("%d", *j);
}
Как-то так.

**Comment by bylins** [comment]
Regex ОЧЕНЬ тормозной.
Особенно, если его использовать не верно.
А он используется не верно в патче.
Его надо компилировать заранее, а не на каждый триггер.
Т. е. вот строчка, где он создаётся: std::regex(...)
Это его компиляция.
Но на это тратится дофига времени.
Поэтому надо вводить переменную, существующую пока грузятся триггеры.
Инициплизировать её один раз перед загрузкой первого триггера.
Затем использовать её одну для каждого триггера.
Затем, после загрузки последнего уничтожать.
Я пока не перед компом. Поэтому не могу сказать точнее.
ок, я ему перекину твое
щас переоткрою задачу
Ага.
Вообще, там, возможно, можно и без regex обойтись.
Но если правильно использовать regex, возможно, ещё быстрее окажется.

**Comment by bylins** [comment]
загрузка триггеров стала 22 минуты, надо править

**Comment by lrdx** [comment]
А чё он какой тупой этот компилятор ))) привык к RegexOptions.Compiled в .net ))))) другие даже не испольщовал никогда))))

**Comment by lrdx** [comment]
Добавлю static, всех устроит?))

**Comment by kvirund** [comment]
Нет. На самом деле я уже закоммитил исправление. Правда, я не проверял: это на Стрибоге.

**Comment by bylins** [comment]
стало сильно быстрее
May 23 10:01:16 :: Loading triggers and generating index.
May 23 10:01:16 :: Index booting 5
May 23 10:01:24 :: ERROR: Script with VNUM 49999 has attach_type 49911. Read from line '49911 - завершение квеста, если мастер согласен поручиться (метки 49901'.
May 23 10:01:31 :: Loading rooms.
15 секунд вместо 20 минут

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/58963912-adbaaa00-87b6-11e9-9c67-7465f624c5c7.png)
![image](https://user-images.githubusercontent.com/42086238/58963936-b57a4e80-87b6-11e9-8dd2-44901e3143ca.png)
работает криво

**Comment by Svjatovit** [comment]
Реализовано, работает нормально.
