### ISSUE TITLE
[17-02-19 12:09:47][ SCRIPT LOG (Mob: 'часовой рыцарь', VNum: 86102, trig: 86105): mdamage: bad syntax ]

### ISSUE THREAD

**Issue by bylins** [bylins/mud#406]
```
Name: 'баттл триг часового (для моба)',  VNum: [86105], RNum: [ 8192]
Trigger Intended Assignment: Mobiles
Trigger Type: Fight, Numeric Arg: 80, Arg list: None
Commands:
   mecho Град стрел и арбалетных болтов сыпется на Вас из недоступных бойниц. 
   wait 1s
   foreach target %self.pc%   
     if (%random.100% < 51)
       msend %target% Что-то острое пробило доспехи, и Вы почувствовали, как кровь хлынула из раны.
       eval dmg %random.70%+30
       mdamage %target% %dmg%
     else 
       msend %target%   Вы всеми способами уворачиваетесь от стрел, но долго Вам так не простоять! 
     end
   done
```

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/52912262-15a8bb80-32c0-11e9-96b4-1d2e56325c1a.png)
msend %target% Что-то острое пробило доспехи, и Вы почувствовали, как кровь хлынула из раны.
не ругается что нет %target% получается что %dmg% нет?
повторябельно.......

**Comment by bylins** [comment]
тестировали
Адена сказала вам : 'последний и предпоследний Что-то острое пробило доспехи, и Вы почувствовали, как кровь хлынула из раны.'
т.е. %target% существует

**Comment by bylins** [comment]
ошибка появляется после флика, во время боя все ок

**Comment by bodrich** [comment]
Файл dg_scripts.cpp. Функция int process_foreach_begin(const char* cond, void *go, SCRIPT_DATA * sc, TRIG_DATA * trig, int type)
Чар сбежал. Вызвался цикл. А точнее строка в цикле foreach target %self.pc%   
Проблема в том, что если в руме нет чаров, то вот это выражение отрабатывает некорректно
`eval_expr(p, list_str, go, sc, trig, type);
	p = list_str;

	if (!p || !*p)
	{
		return 0;
	}`

в list_str находится пустая строка с двумя пробелами '  ', потому что, после %self.pc% находится два пробела. Фикс это в функции void eval_expr(const char *line, char *result, void *go, SCRIPT_DATA * sc, TRIG_DATA * trig, int type)
Добавить в конце трим на result, и если строка пустая, то result = null

**Comment by kvirund** [comment]
А почему "после %self.pc% находится два пробела"?

**Comment by kvirund** [comment]
Как я понимаю, пробелы были в самом скрипте после `%self.pc%`. В этом случае это ошибка в самом триггере. По крайней мере, до тех пор, пока в документации по DG Script не говорится, что аргументы `foreach`'а должны триммиться.

Если добавить тримм - то автоматом исчезнет возможность эти пробелы вставлся не только таким случайным образом, но и специально, как часть некоторого выражения, например.

Поэтому, ИМХО, надо править скрипты и просто в будущем аккуратнее их писать. А код трогать не следует.

**Comment by bylins** [comment]
Билдер не видит лишние пробелы в конце, так что такие ошибки будут бесконечно.
Почему не захардкодить обрезание незначащих ничего пробелов?

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/52931864-09277000-335f-11e9-9901-7c789a7c6c4e.png)
это под юнихами видно, блокнот фар и остальные редакторы пробелы не высчечивают

**Comment by bylins** [comment]
поставили трим
