### ISSUE TITLE
Правка мигалки

### ISSUE THREAD

**Issue by bylins** [bylins/mud#407]
а нельзя сделать чтоб мигалка со стафа давала 5%, а мигалка кастом 5%+1% за каждый морт волшебника/волхва? Будет смысл их мортить.

**Comment by lrdx** [comment]
Имхо, это слишком сильно изменится баланс, 20% на 20 морте это прям дохера

**Comment by bylins** [comment]
так сейчас 20% от любой шмотки закла, я же порезал до 5%, И где ты видел волхва или волша 20 мортов?
но ты прав формулу будем переделывать

**Comment by bylins** [comment]
мне не понравилась моя реализация, чот как-то корявенько выглядит, щас скомпилится залью
