### ISSUE TITLE
Непонятки с напитками

### ISSUE THREAD

**Issue by bylins** [bylins/mud#409]
![image](https://user-images.githubusercontent.com/42086238/53173695-3c852b80-35f9-11e9-81b1-4854a7cf7280.png)

**Comment by bylins** [comment]
в пфайле нормально
![image](https://user-images.githubusercontent.com/42086238/53173756-59216380-35f9-11e9-9cc8-c8b792844769.png)
портится явно при загрузке мада

**Comment by bylins** [comment]
void name_from_drinkcon(OBJ_DATA * obj)
		obj->set_PName(c, new_name);
почему изменения попадают в прототип?

**Comment by bylins** [comment]
OBJ_DATA::shared_ptr WorldObjects::create_from_prototype_by_rnum(obj_rnum rnum)
вот тут вызывается, но опять же правится объект а не прототип

**Comment by Svjatovit** [comment]
А эту багу еще наблюдал кто-то? Было когда-то такое, пофиксили давно. Сейчас по стату нет кривых горшков с напитками.

**Comment by bylins** [comment]
в олц исправили билдеры, они знают как
