### ISSUE TITLE
Макс умения по морту в тригах

### ISSUE THREAD

**Issue by Avseek** [bylins/mud#413]
У нас во многих триггерах похоже максимум умения по морту рассчитывается как 80+5*морты. Это верно для небольших мортов, но становится неверным на больших мортах (по формуле выходит больше 200), и из-за этого триггеры отрабатывают неправильно, часто не выдавая альтернативную награду. 

Примеры:
1. Велес. Там апают бтру молот, если максимум апов уже достигнут то выдают 3к кун. Но если у тебя максимум скилла по морту, посчитанный по формуле 80+5*морты, больше 185 (там апают на +15 сверх морта), то триггер пытается апнуть тебе умение и вываливается заглушка из кода: "Ваше умение осталось неизменным".

```
Берегиня начала бросаться на шею ко всем подряд, пытаясь поделиться своей радостью.
1486H 279M 90900994о Зауч:0 Кл:6 Яр:2 26L 215617G Вых:v> 
- Нелегок был путь твой , но выполнил ты просьбу мою...
- За это награжу я тебя от всего сердца и поклонюсь в ноги.
Берегиня поклонилась до земли.
1486H 279M 90900994о Зауч:0 Кл:6 Яр:2 26L 215617G Вых:v> 
А вот и награда твоя..
Ваше умение осталось неизменным 'богатырский молот '.
```

2. Более плохой пример. В р1 бтру по квесту апают молот (не помню на сколько конкретно, никогда там не апал по сути). Если молот достаточно проапан, то выдают глуш. Но если у тебя родной скилл может быть больше 200, то глуш не выдают, т.к. пытаются апать молот.

Думаю таких триггеров очень много. Из критичного исправить бы р1 хотя бы, а то 18 морченному бтру спопить глуш проще чем 24 морченному, что очень странно.

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/54213062-d7846d80-44f4-11e9-96c1-f28d3731fc3e.png)
код править не надо, хотя все таки макс кап бы ввести в коде, так как всеж планировали раздвигать максумение до 350

**Comment by Avseek** [comment]
Это сейчас такой код там в триггере? Тогда пардон, я по памяти где-то годовой давности писал, просто вспомнил, что давно хотел это зарепортить, и даже не проверял с последнего раза.

**Comment by bylins** [comment]
это я исправил, но откатил изменения, решил править расчет skl в начале тригга через введение %actor.get_trained_skill%

**Comment by bylins** [comment]
хотя get_trained_skill возвращает значение текущего скилла, где вычисляется кап на морте\левеле пока не нашел (позже поищу как время будет)

**Comment by bylins** [comment]
ch->set_morphed_skill(skill_no, (trained_skill + number(1, 2)));
ch->set_morphed_skill(skill_no, (MIN(MAX_EXP_PERCENT + GET_REMORT(ch) * 5, ch->get_trained_skill(skill_no))));
не нахожу обрезание на 200, ведь тут может быть 199+2

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/54284024-4672cc80-45b0-11e9-9c63-1e232d4b0072.png)
пока я сделал так (в 912 зоне) можно и везде поставить заглушку в триггах, но мне всеж хотелось разобраться где режется до 200

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/54284412-f0525900-45b0-11e9-936f-2864d027a5f5.png)
```
int normalize_skill(int percent)
{
	const static int KMinSkillPercent = 0;
	const static int KMaxSkillPercent = 200;

	if (percent < KMinSkillPercent)
		percent = KMinSkillPercent;
	else if (percent > KMaxSkillPercent)
		percent = KMaxSkillPercent;

	return percent;
}

```
типа нашел

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/54287698-39a5a700-45b7-11e9-89d4-bc5ee7f49ddb.png)
![image](https://user-images.githubusercontent.com/42086238/54287726-46c29600-45b7-11e9-8df7-2e9c0df4d8c8.png)
11 морт
типа все норм, вношу в справку по DG

**Comment by bylins** [comment]
правлю теперь так
eval skl %actor.maxskill%
и тыпы
