### ISSUE TITLE
ошибка в поиске персхрана

### ISSUE THREAD

**Issue by bylins** [bylins/mud#418]
Думная гридня [49819]
[  330] Волшебный сундук так и манит к себе... ..блестит!
...
х Аинт Озапя
Выборка: ЗАПЯСТЬЕ интеллект 
клеймо дурака *Переруг* [35 кун]
красный дубовый лист *Инта+2* [150 кун]
четки из слоновой кости *Хакуна* ..голубая аура! ..желтая аура! [125 кун]

х х 2.Хакуна

Характеристики предмета: 2.Хакуна
Вы узнали следующее:
Предмет "четки из слоновой кости", тип : ОРУЖИЕ
Принадлежит к классу "иное оружие".
Вес: 5, Цена: 400, Рента: 275(250)
Материал : КОСТЬ
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: магический,благословлен
Наносимые повреждения '3D3' среднее 6.0.
Накладывает на вас аффекты: проклятие
Дополнительные свойства :
   попадание ухудшает на 4
   повреждение улучшает на 4
   здоровье улучшает на 10
   телосложение улучшает на 2
За информацию о предмете с вашего банковского счета сняли 110 кун

вз 2.хакун сунд

Вы взяли четки из слоновой кости из волшебного сундука.

х Аинт Озапя

Выборка: ЗАПЯСТЬЕ интеллект 
клеймо дурака *Переруг* [35 кун]
красный дубовый лист *Инта+2* [150 кун]

Вы зачитали свиток познания, который рассыпался в прах.

Вы узнали следующее:
Предмет "четки из слоновой кости", тип : ОРУЖИЕ
Принадлежит к классу "иное оружие".
Вес: 5, Цена: 400, Рента: 275(250)
Материал : КОСТЬ
Неудобен : ничего
Недоступен : ничего
Имеет экстрафлаги: магический,благословлен
Наносимые повреждения '3D3' среднее 6.0.
Накладывает на вас аффекты: проклятие
Дополнительные свойства :
   попадание ухудшает на 4
   повреждение улучшает на 4
   здоровье улучшает на 10
   телосложение улучшает на 2
 
[system] Лог закрыт: 'bag.txt'.
Былины - 25 Апр 2019, 20:43:49
Лог закрыт.

Предмет
[10306] четки из слоновой кости  <великолепно> ..голубая аура!
Сейчас у Зимун

опозн четки
Вы узнали следующее:
UID: 127043445, Предмет "четки из слоновой кости", тип : ОРУЖИЕ
Принадлежит к классу "иное оружие".
Материал : КОСТЬ
Таймер : 19132
Прочность : 93\93
Накладывает на вас аффекты: проклятие
Имеет экстрафлаги: магический,благословлен,таймер запущен,изменен кодом
Недоступен : ничего
Неудобен : ничего
Вес: 5, Цена: 400, Рента: 275(250)
Наносимые повреждения '3D3' среднее 6.0.
Дополнительные свойства :
   попадание ухудшает на 4
   повреждение улучшает на 4
   здоровье улучшает на 10
   телосложение улучшает на 2

**Comment by Svjatovit** [comment]
Правильно понял, четки выводятся по фильтру на интеллект, хотя на них его нет?

**Comment by bylins** [comment]
их энчатят колды, наверное просто не ту взяли для опознания, я постоянно так ошибался, теперь после взятия опознаю на всяк
