### ISSUE TITLE
Защита от света/тьмы[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#42]
*Originally reported by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

Предлагаю при наличии на персонажах данных афектов давать 10 % шанс поглотить магию противоположной школы и 20% уменьшение повреждения.

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/42

**Comment by Svjatovit** [comment]
Не нужно костылей в игровой системе. Даже в такой кривой, как у нас сейчас. Есть резисты, у них есть общая механика. Если "защита от тьмы/света" имеет другую механику - лучше как-то иначе это и называть, не резистами.
