### ISSUE TITLE
Ап ангела

### ISSUE THREAD

**Issue by bylins** [bylins/mud#426]

**Comment by bylins** [comment]
пиши, а то я ангелом мало пользовался, все больше печать бот

**Comment by bylins** [comment]
ну и хранов можно побольше градаций

**Comment by ladon3434** [comment]
Храны в другой задаче. Не надо их смешивать. Это ап ангела.

Концепция - Ангел защитный закл. Повышает возможность выживания волшебника. Спасает от прямого физического урона, не спадает от всякой ваты. Почти не наносит урон. Хилит. Не забивает напрочь мем.

Живучесть ангела - ангелы живучие, очень живучие, но не бессмертные.
1. Хп - база 1000. +100 за морт, +50 за харю выше 16. 
2. Санк - база
3. Щит - выше 26 хари. ( считай встроенное с 10 морта )
4. Острожка - база 50%. +10% за морт, +2 % за харю выше 16. ( 230 на 15 морте )
5. Веер - база 50%, +5% за морт, +5% за харю выше 16 ( 200 на 15 морте )
6. Дышит - 1d1 всегда, 1 атака. ( что бы щитами не убивало ) 
7. Хил - никаких критов, База 1, +1 за морт, +1 за каждые 3 хари выше 16. ( 21 на 15 морте )
8. Время жизни - 10 минут база. +15 секунд за морт, +15 секунд за харю выше 16 ( 17.5 минут на 15 морте )

Живучесть волша
1. Реск ангела - база 50%, +5% за каждый реморт.
2. Хил от ангела - ангел хиляет на желтом. Что себя что волша.
3. Жизнь за соратника - если волша или союзника все таки убили жертвует собой.

Мем
1. Время запоминания - 45 секунд
2. Фейлы - 50% база. -1% за морт, -2% за харю выше 16. (5% фейла на 15 морте ). Минимальный фейл 5%

Варианты применения :
1. Солозонинг - хороший танк, есть не просит, спасает, не дает сдохнуть. Можно умереть на толпе мобов, пока ангел рескает, можно словить фраг на всю банку, стабы прилетают.
2. Напарники - хороший танк, но не спасает напарника, переключающиеся мобы будут мешать.
3. Груп - как танк никакой, волша быстрее сольют чем он отрескает. Спасает союзников от рипа. Может успеть отхилить волша от суда/гнева/землетряса.
4. Пк - надо или ваншотнуть волша, или истощить ангела, или зарескать волша. Впринципе пару чаров без проблем держат волша в лаге и пилят.

**Comment by ladon3434** [comment]
Все цифры примерные, будут вынесены в отдельный файл настройки. Опции тоже.

**Comment by ladon3434** [comment]
@bylins  ну если возражений по большому счету нет то буду делать

**Comment by bylins** [comment]
апай, но ты не добавил что 25% ангел может воскресить убитого, мб от морта это тоже поднять, но свен очень против плюшек завязанных на морты
