### ISSUE TITLE
[11-05-19 15:02:02][ SCRIPT LOG (Mob: 'седой отшельник', VNum: 79449, trig: 79446): mskilladd: воительница skill/recipe not found ]

### ISSUE THREAD

**Issue by bylins** [bylins/mud#447]
```
     eval maxskl %actor.remort%*5+90
     if %actor.skill(опохмелиться)% < %maxskl%
       mskilladd %actor.name% опохмелиться 10
     else
       дум %actor.name%
       г Извини, я уже ничему новому тебя не научу...
       вздох
     end
```
что-то я не понял actor.skill не ругается (правда я его правил) а вот mskilladd  косячит

**Comment by bylins** [comment]
вообще срефакторить бы
```
	if (!MOB_OR_IMPL(ch))
	{
		send_to_char("Чаво?\r\n", ch);
		return;
	}

	if (AFF_FLAGGED(ch, EAffectFlag::AFF_CHARM))
	{
		return;
	}

	if (ch->desc && (GET_LEVEL(ch->desc->original) < LVL_IMPL))
	{
		return;
	}

```
поднять наверх

**Comment by bylins** [comment]
```
[	if ((skillnum = fix_name_and_find_skill_num(skillname)) > 0 && skillnum <= MAX_SKILL_NUM)
	{
		isSkill = true;
	}
	else if ((recipenum = im_get_recipe_by_name(skillname)) < 0)
	{
		sprintf(buf, "mskilladd: %s skill/recipe not found", skillname);
		mob_log(ch, buf);
		return;
	}
]
```
в самый низ и убрать переменную isSkill

**Comment by bylins** [comment]
будет меньше текста и читабельнее, но почему ругается я всеж не понял

**Comment by bylins** [comment]
походу нашел
ESkill find_skill_num(const char *name)   классу не доступен этот скилл и он уходит в SKILL_INVALID
ошибка в триггере, нет проверки на классы, но в мудлог не должно такого дурного сообщения слаться, что "не найдено". Короче порефакторить и добавить мессагу что попытка добавить проставить умение недоступное классу.

**Comment by bylins** [comment]
May 11 15:02:01 :: <Шеер, 787309> {79447} [приказ всем г от пьянки]
купа приказал чармисам, а проверка на чармиса почему-то ниже

**Comment by lrdx** [comment]
Это ошибка в триггере, а не в коде. Использование команд по имени запрещено.
Правильная строчка: mskilladd %actor% опохмелиться 10

**Comment by bylins** [comment]
с какого перепугу и ошибка не эта!
```
	if (*name == UID_CHAR)
	{
		if (!(victim = get_char(name)))
		{
			sprintf(buf, "mskilladd: victim (%s) UID does not exist", name + 1);
			mob_log(ch, buf);
			return;
		}
	}
	else if (!(victim = get_char_vis(ch, name, FIND_CHAR_WORLD)))
	{
		sprintf(buf, "mskilladd: victim (%s) does not exist", name);
		mob_log(ch, buf);
		return;
	};


```

**Comment by lrdx** [comment]
Это вообще другой кусок кода и он не имеет отношения к этой ошибке (даже сообщение в нем другое). На самом деле все просто, этот чарм имеет два слова в имени (странствующая воительница), а код всегда считает третье слово названием скидка.
Т.е. мы имеем следующую строку после замены: mskilladd странствующая воительница опохмелиться 10
И пытаемся проставить скилл воительница чару странствующая и такой скил не находится. Именно поэтому обращение к actor.name когда мы говорим о команде должно быть табу, иначе глючить будут все триггера на чармах/мобах. Использование здесь %actor% устраняет все ошибки.

**Comment by bylins** [comment]
ладно завтра поправлю тригг и закрою
