### ISSUE TITLE
Купец

### ISSUE THREAD

**Issue by bylins** [bylins/mud#451]
при наеме учитывается харя при стоимости моба в час, а вот если рассчитать, возвращает полную сумму, без учета хари, получается нанял за 100к кун, а рассчитал за лям

**Comment by pilaty** [comment]
У вас на руках 245062 куны и 805 гривен (и еще 181933063 куны припрятано в лежне).
<< нан дет
% Захмелевший детина сказал вам : "Один час моих услуг стоит 2792 куны".
оделся в интухарю
<< нан детин
% Захмелевший детина сказал вам : "Один час моих услуг стоит 101 куну".
<< нан детин 100
% Захмелевший детина начал следовать за вами.
Захмелевший детина сказал вам : "Приказывай, хозяин!"
У вас на руках 234962 куны и 805 гривен (и еще 181933063 куны припрятано в лежне).

<< рассч детин
% Вы рассчитали захмелевшего детину.
Захмелевший детина прекратил следовать за вами.

У вас на руках 1234862 куны и 805 гривен (и еще 181933063 куны припрятано в лежне).
