### ISSUE TITLE
разобраться с чармом

### ISSUE THREAD

**Issue by bylins** [bylins/mud#453]
else if (!IS_IMMORTAL(ch) && general_savingthrow(ch, victim, SAVING_WILL, (GET_REAL_CHA(ch) - 10) * 4 + GET_REMORT(ch) * 3))
		send_to_char("Ваша магия потерпела неудачу.\r\n", ch);

**Comment by pilaty** [comment]
убрать проверку на резисты при применении заклинания !починить разум!, оставить только проверку на харю

**Comment by bylins** [comment]
формула вверху... что убираем?

**Comment by Svjatovit** [comment]
Собственно, а в чем баг? Чарм у нас не 100% успешное заклинание, его можно и сфейлить и огрести по шее. Так почему спасбросок не должен учитываться? Резистов в формуле выше я вообще не вижу. В сотый раз повторяю, не надо путать резисты и спас-броски. Это разные параметры с разной механикой.

**Comment by Svjatovit** [comment]
Ошибки нет, закрыто.
