### ISSUE TITLE
Баф силы бесполезен татям и охотам

### ISSUE THREAD

**Issue by bylins** [bylins/mud#465]
у них из-за перка ловкий удар и ловкий выстрел сила не учитывается в расчетах, предлагаю в этом случае считать как буд-то добавили ловкость (костыль конечно, но не хочется вводить еще один закл баф ловкости)

**Comment by bylins** [comment]
нашел кучу багов в отображении дамаги, первый патч

**Comment by lrdx** [comment]
Баф силы на то он и баф силы, и дело тут не а дамаге ) можно и баф ловкости добавить, только уже не магу например )

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/59010359-9ec90b80-8839-11e9-8ff0-ce000876e038.png)
![image](https://user-images.githubusercontent.com/42086238/59010378-adafbe00-8839-11e9-91d3-048e6c4adfef.png)
там полный бардак, почему снял хитролы а атака выросла, тем более где хитролы от ловкого удара

**Comment by bylins** [comment]
стрелка походу не туда :) если оружие тяжелое то хитролы идут от силы, зачем тогда нужен этот перк, он наоборот вреден татю охоту
```
	if (can_use_feat(ch, WEAPON_FINESSE_FEAT))
	{
		if (weapon && GET_OBJ_WEIGHT(weapon) > 20)
		{
			hr += str_bonus(GET_REAL_STR(ch), STR_TO_HIT);
		}
		else
		{
			hr += str_bonus(GET_REAL_DEX(ch), STR_TO_HIT);
		}

```

**Comment by vredomir** [comment]
Что касается перков, "ловкий выстрел" влияет на урон, "ловкий удар" только на хитролы, так что татям/наемам этот фит практически бесполезен. Можно просто дать проверку на наличие фита где докидываются дамы хантам.

**Comment by vredomir** [comment]
А насчёт бафа +ловкости, проще всего повесить этот бонус на ускор, он сейчас дает копейки реакции, вместо можно сделать дексу.
