### ISSUE TITLE
Зависимость кастов от скилла магии

### ISSUE THREAD

**Issue by bylins** [bylins/mud#466]
```
// зависимость длительности закла от скила магии
float func_koef_duration(int spellnum, int percent)
{
switch (spellnum)
{
case SPELL_STRENGTH:
return 1 + percent / 400;

default:
return 1;
}
}
ниже

 const int koef_duration = func_koef_duration(spellnum, ch->get_skill(get_magic_skill_number_by_spell(spellnum)));
```
флоат получаем 1.5 макс, при превращении в int получаем 1, короче вообще не работает

**Comment by bylins** [comment]
https://bitbucket.org/bylins/mud/commits/ca726fe5befed5f6a900414cfb9c69605895009b#chg-src/magic.cpp
вот этот коммит

**Comment by bylins** [comment]
для силы:
af[0].modifier = (уровеньигрока + 14) / 15 + koef_modifier + GET_REMORT(ch) / 5;
может уберем уровниморты поставим от скилла магии?

**Comment by bylins** [comment]
koef_modifier  тут всегда равен 1 так как return 1 + скиллмагии / 400

**Comment by bylins** [comment]
если уберем зависимость от мортов и лева сделаем что-то типа скиллмагии/ 30 то при скилле 30 силу кастовать будет +1 при 200 +6, ну понятна формула надеюсь

**Comment by vredomir** [comment]
Как быть с потолком в 200 скилла, плюс некоторые сеты дают бонус на скилл? Сейчас кастеры по 20+ мортов не редкость. Если сделать скилл/30, то волшу выше 20 морта нет смысла дальше мортаться.

**Comment by bylins** [comment]
А щас есть смысл качать далее? В принципе именно для школ магии можно раздвинуть, он не используется в формулах расчета прохождении вероятности, только в допплюшках, но все таки не хочется линейную зависимость

**Comment by bylins** [comment]
делать сразу 1000 к 50 морту, не думаю что кто-то выше сможет всеж прокачаться

**Comment by Svjatovit** [comment]
Поскольку планируется изменение игровой системы и я надеюсь хотя бы шкелет таковых изменений заложить, то тему закрою. Учет скиллов магии там задуман.
