### ISSUE TITLE
Идея по кудесам[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#47]
*Originally reported by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

Создать 2 ветки развития проффеси  
1 - усиление чармиса в группе
2 - увеличение выживаемости в соло.
для каждой ветки свои способности, заклинания, афекты

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/47

**Comment by Svjatovit** [comment]
Идеи лучше в другим месте обсуждать, а тут держать готовые таски к выполнению.
