### ISSUE TITLE
Идеи по витязю[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#48]
*Originally reported by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

Создать 2 ветки проффесий  
1 усиление файтера (точка, пинок, возможно ошелоить)
2 усиление магии.
Каждой професии свои способности и заклинания

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/48

**Comment by Svjatovit** [comment]
Счастья всем, даром. и чтоб ни один обиженный не ушел!
