### ISSUE TITLE
хозяин может агрить своего чармиса по части алиаса

### ISSUE THREAD

**Issue by ladon3434** [bylins/mud#486]
[21:38] Полазник : 'купы просят чтобы агрить чара мождно было только если прописать полностью'
[21:38] Полазник : 'посмотри эту правку плз'
[21:38] Полазник : 'своего чармиса'
[21:39] Полазник : 'ну хотят пнуть призрака медведя допустим'
[21:40] Полазник : 'при чармиса призрак замка'
[21:40] Полазник : 'пишут пнут пр'
[21:40] Полазник : 'и пинают своего'

[22:05] Тикен заметил : 'раз 10 умирал от лиха, 3-5 от воилки, от всяких других не меньше'
[22:05] Тикен заметил : 'вообще не парюсь'

имхо бага, надо поправить

**Comment by ladon3434** [comment]
в общем дело тут

```
bool need_full_alias(CHAR_DATA * ch, CHAR_DATA * opponent)
{
	// Потенциальная жертва приведет к ПК?
	if (IS_NPC(opponent)
		&& (!opponent->has_master()
			|| IS_NPC(opponent->get_master())
>>>>>>		|| opponent->get_master() == ch))
	{
		return false;
	}

```
если убрать эту строчку - будем агрить своих только по полному имени.
мнения игроков разделились - ктото говорит уберите, ктото хочет оставить.
решайте господа имморталы

**Comment by Kaynur** [comment]
Вообще я за то, что бы ввести эту тему, сам недавно убился об свою очару, а там шансов нет ее пережить, тем более под глушем. Для тех кто против, если мнения разделились, мы можем сделать новый режим?  "Режим свои" - если режим включен, то своих очар только при полном написании, если вырублен, всё как и было. Так же хотелось бы что бы это распространялось на всяких коней и жеребцов. На лоулеве в жеребца вписался, так или долго ковырять или фликать надо, а стаф !флик поди найди на себе или рекол. - дискомфорт. Режим бы помог.

**Comment by ladon3434** [comment]
Автовыходы    : ON       Краткий режим : ON       Сжатый режим  : OFF 
 Повтор команд : YES      Обращения     : ON       Цвет          : обычный 
 Кто-то        : можно    Болтать       : ON       Орать         : ON  
 Аукцион       : ON       Базар         : ON       Автозаучивание: ON  
 Призыв        : OFF      Автозавершение: ON       Группа (вид)  : краткий 
 Без двойников : OFF      Автодележ     : ON       Автограбеж    : OFF     
 Брать куны    : OFF      Арена         : ON       Трусость      : нет 
 Ширина экрана : 80       Высота экрана : 50       Сжатие        : MCCPv2 
 Новости (вид) : лента    Доски         : ON       Хранилище     : полный    
 Пклист        : ON       Политика      : OFF      Пкформат      : полный    
 Соклановцы    : ON       Оффтоп        : ON       Потеря связи  : OFF 
 Ингредиенты   : OFF      Вспомнить     : 30       Уведомления   : Нет 
 Карта         : ON       Вход в зону   : ON       Магщиты (вид) : краткий
 Автопризыв    : ON       Маппер        : ON       Контроль IP   : OFF

больше режимов богу режимов?
@bylins  - так что делаем что-нибудь? или закрываем и забываем?
