### ISSUE TITLE
Проблема Ошеломить VS ЗБ

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#490]
Я один наблюдаю проблему? Когда ошеломляется моб скастящий ЗБ, он в бессознанке болтается под ЗБ и ЗБ с него не слетает, иногда слетает, иногда приходится уводить группу, потому как терпения не хватает ждать. - надо что бы ЗБ слетало как положено, даже если жертва в бессознанке.

**Comment by bylins** [comment]
похожая бага еще и с кругом пустоты, моб не обсчитывается помойму в этом положении, надо править

**Comment by ladon3434** [comment]
окей, ща посмотрю че там

**Comment by bylins** [comment]
залил коммит тестируем

**Comment by ladon3434** [comment]
@bylins  оттестили? можно закрывать?

**Comment by bylins** [comment]
а чо намудрили с GET_POS(vict) = POS_INCAP
что моб отвечает атакой?
Противник снежная баба: скилл == 238, итоговыйрасчетскилла == 314, бонус == 86, сэйвыпротивника == -10,
модификаторпротивника == 0
Мощным ударом вы ошеломили снежную бабу!
Регуляр дамаг = 162
Вы НЕВЫНОСИМО БОЛЬНО пырнули снежную бабу.
Применен урон = 182
2703H 329M 5209154о Зауч:11:03 Из:0 Ош:1 [Пилатий:Невредим] [снежная баба:Слегка ранена] >

Регуляр дамаг = 160
Вы БОЛЬНО пырнули снежную бабу.
Применен урон = 80
Снежная баба попыталась ударить вас, но не рассчитала и промахнулась.
2703H 330M 5209154о Зауч:11:03 Из:0 Ош:1 [Пилатий:Невредим] [снежная баба:Слегка ранена] >
почему баба отвечает?

**Comment by ladon3434** [comment]
Раньше каждый тик боя чармиса выпинывали из боя, поэтому у нее не отрабатывали снимания боевых эффктов. Гдето не хватает проверки на позицию, проверял то что неотвечает иммом. Окей попробую тестером и сделаю что не отвечает.

**Comment by ladon3434** [comment]
Ладон порылся в МУДе.
Ладон создал чармиса двадцать седьмого уровня!

580H 276M 4006711о Зауч:0 Вых:ВЮЗ> 
ошелом чарм
Мощным ударом вы ошеломили чармиса двадцать седьмого уровня!
Вы очень сильно резанули чармиса двадцать седьмого уровня.
Чармис двадцать седьмого уровня дамаг без сознания и медленно умирает. Помогите же ему.

580H 276M 4006485о Зауч:0 [Лукарь:Невредим] [чармис двадцать седьмого уровня дамаг:Слегка ранен] > 

Вы сильно резанули чармиса двадцать седьмого уровня.
Чармис двадцать седьмого уровня дамаг без сознания и медленно умирает. Помогите же ему.

580H 276M 4006307о Зауч:0 [Лукарь:Невредим] [чармис двадцать седьмого уровня дамаг:Слегка ранен] > 

Вы сильно резанули чармиса двадцать седьмого уровня.
Чармис двадцать седьмого уровня дамаг без сознания и медленно умирает. Помогите же ему.

580H 276M 4006162о Зауч:0 [Лукарь:Невредим] [чармис двадцать седьмого уровня дамаг:Слегка ранен] > 

Вы резанули чармиса двадцать седьмого уровня.
Чармис двадцать седьмого уровня дамаг сильно ударил вас.
Меткое попадание чармиса двадцать седьмого уровня тяжело ранило вас.
Чармис двадцать седьмого уровня дамаг БОЛЬНО ударил вас.
Чармис двадцать седьмого уровня дамаг сильно ударил вас.

444H 276M 4006027о Зауч:0 [Лукарь:Легко ранен] [чармис двадцать седьмого уровня дамаг:Легко ранен] > 

Чармис двадцать седьмого уровня дамаг ударил вас.
Чармис двадцать седьмого уровня дамаг очень сильно ударил вас.
Чармис двадцать седьмого уровня дамаг сильно ударил вас.
Вы попытались резануть чармиса двадцать седьмого уровня, но ваш удар не достиг цели.

**Comment by ladon3434** [comment]
тест с зб
Ладон взглянул на чармиса двадцать седьмого уровня и произнес : 'Живый в помощи Вышняго'.

533H 276M 4009480о Зауч:0 Вых:ВЮЗ> 
ошелом чарм
Мощным ударом вы ошеломили чармиса двадцать седьмого уровня!
Магический кокон вокруг чармиса двадцать седьмого уровня полностью поглотил ваш удар.

542H 276M 4009480о Зауч:0 [Лукарь:Слегка ранен] [чармис двадцать седьмого уровня дамаг:Невредим] > 

Магический кокон вокруг чармиса двадцать седьмого уровня полностью поглотил ваш удар.

542H 276M 4009480о Зауч:0 [Лукарь:Слегка ранен] [чармис двадцать седьмого уровня дамаг:Невредим] > 

Вы слегка резанули чармиса двадцать седьмого уровня.
Чармис двадцать седьмого уровня дамаг без сознания и медленно умирает. Помогите же ему.

544H 276M 4009432о Зауч:0 [Лукарь:Слегка ранен] [чармис двадцать седьмого уровня дамаг:Слегка ранен] > 

Вы слегка резанули чармиса двадцать седьмого уровня.
Чармис двадцать седьмого уровня дамаг сильно ударил вас.
Чармис двадцать седьмого уровня дамаг очень сильно ударил вас.
Чармис двадцать седьмого уровня дамаг очень сильно ударил вас.
