### ISSUE TITLE
почему прототип выводится дважды

### ISSUE THREAD

**Issue by bylins** [bylins/mud#491]
![image](https://user-images.githubusercontent.com/42086238/62411440-66586a80-b5fb-11e9-8adf-f54a04e9157e.png)

**Comment by bylins** [comment]
do_stat_object
![image](https://user-images.githubusercontent.com/42086238/62412027-f8b13c00-b604-11e9-800b-ee830e90f5b7.png)

**Comment by bylins** [comment]
```
		if ((i = real_object(GET_OBJ_VAL(j, 1))) >= 0)
		{
			sprintf(buf, "прототип %s%s%s.\r\n",
				CCICYN(ch, C_NRM), obj_proto[i]->get_PName(0).c_str(), CCNRM(ch, C_NRM));
			send_to_char(buf, ch);
		}
		break;

```
нету цикла

**Comment by ladon3434** [comment]
ага, ща залью фикс

**Comment by ladon3434** [comment]
![Jaba MUD Client  local  2019-08-05 03 23 31](https://user-images.githubusercontent.com/53003956/62431478-7d4ca900-b730-11e9-9103-2f00fc4775d9.png)

**Comment by ladon3434** [comment]
там как раз в этом месте не пушится игроку, а пишется в буфер и потом , в конце кидается в игрока.
