### ISSUE TITLE
Ассист глушащего чармиса

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#492]
Считаю, что будет адекватным озвучить. Чармис купца - лагающий, с приличной задержкой впрягается за танка, после смерти первой цели, так как ждет пока пролагается от глуша своего. Чарм дама и так не в почете и еще 2 раунда чармис стоит дрочит, пока пролагается - не справедливо. 

Я не говорю, что лаг от глуша надо убрать, можно сделать так, что бы на чарм дамагу он начинал отсчет после того как очара впряглась в следующю цель? 

Тогда очара будет полноценно участвовать в бою и лаги от глуша будут проходить так же, только немного изменив последовательность.

**Comment by bylins** [comment]
отрубить автоассист и сделать чтоб он вписывался по команде, лага не будет

**Comment by bylins** [comment]
+ надо назначить ответственных за профу
мои профы волш охот друж витя, я в них понимаю механику

**Comment by Kaynur** [comment]
Я за купца буду отвечать. Давайте лаг уберем его.

**Comment by ladon3434** [comment]
у кузи такой же лаг

**Comment by Kaynur** [comment]
ну не сравнивай чармера с кузей, по ДМЕ посмотри его дамаг и дамаг чармера и сравни, он гараздо меньше, по сему и прошу убрать лаг при переключении на моба, что бы немного исправить статистику.  Кузя даже если стоит, возглавляет топ дамаги, а очара и хотела бы потягаться, но так же стоит, хотя и денег стоит! )

**Comment by ladon3434** [comment]
К сожалению в лаге не написано что он от глуша, теоретически можно снимать лаг с чармиса при окончании боя, но тогда он все лаги будет сбрасывать. Если такая реализация норм - можно сделать.

**Comment by ladon3434** [comment]
по дме средний у кузи 250, макс который изредка выдается это 2000

**Comment by Kaynur** [comment]
чармиса при окончании боя, но тогда он все лаги будет сбрасывать. - давайте потестируем?

**Comment by ladon3434** [comment]
@bylins  махни платочком делаем - не делаем?

**Comment by bylins** [comment]
давай попробуем, ревертнем если что

**Comment by ladon3434** [comment]
в общем понятно что непонятно чем помочь купцам. как разберетесь - на меня переводите :)

**Comment by Kaynur** [comment]
Да все так же и осталось, чармис  отработал моба и стоишь спамишь пом, пока он не отдуплится от глуша своего, в то время как все нонстопом рубят цель.

**Comment by bylins** [comment]
Так коммитов на эту тему нет еще

**Comment by lrdx** [comment]
Да сделайте возможность начинать бой чармисом со скила, чтобы было как у Кузей/бтров , а то сбрасывать имово как то

**Comment by Svjatovit** [comment]
Думаю, с введением системы КД ussue неактуально. Глушить конечно чармис не может, пока глуш на КД, но вписаться в бой - вполне.
