### ISSUE TITLE
Чармисная батла

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#493]
Так же хочу  сделать акцент на то, что морты идут, экспы все меньше и меньше, чармисы те же, мобы те же.  Становится грустно. Предлагаю дать 10% батлы от чармиса хозяину, начиная с мортов, где начинают резать экспу. 

Файтеры жрут и батлу и прибыток, чармер должен то же иметь с общего пирога немного батлы!

**Comment by bylins** [comment]
а можно все это делать в 1 ветку а не плодить, я согласен батлу чармерам надо, раньше была другая схема, чармис набирал батлу, и ты его убивая забирал с него эту экспу. Но в году так 2004 это переделали, так как прокачивали нубов на чужом чармисе сразу уровня до 15

**Comment by Kaynur** [comment]
Перетащите пожалуйста темы про очар в одну тему, я не умею.
Вот для того что бы не было качаловок, экспа должна равномерно течь чармеру  и не кому больше. 10, а лучше 15%, я думаю было бы норм.

**Comment by ladon3434** [comment]
Всего получено опыта: 538,611,931, за удары: 16,654,009 (3.09%)

**Comment by ladon3434** [comment]
наши 3% незаметны на общем фоне

**Comment by Kaynur** [comment]
но они есть! нам то же нужно )

**Comment by ladon3434** [comment]
а у купцов чармис есть, кузям тоже надо! :))))

**Comment by bylins** [comment]
Всего получено опыта: 839,786,133, за удары: 17,223,583 (2.05%)   лохот
так что идею поддерживаю, но не 10% а 3%

**Comment by ladon3434** [comment]
Всю батлу кидаю в хозяина, цифры такие же как у файтеров.

**Comment by Kaynur** [comment]
супер!

**Comment by Kaynur** [comment]
Экспа теперь копится на очаре?  Это хрень, чармиса могут убить мобы и экспа в заднцу, плюс больше капа съесть ее нельзя. Батла должна идти к хозяину равномерно в момент убийства моба.

**Comment by ladon3434** [comment]
Батла идет в хозяина равномерно, каждый тик боя. Со всех чармисов. И с хранов где ее 3 копейки, и с ангела, где ее 1 копейка, и с всех всех остальных.

**Comment by Kaynur** [comment]
Принял, понаблюдаю. Спасибо.
