### ISSUE TITLE
АП Купца

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#495]
К обсуждению апдейт купца.
Чармеров не берут в гопу, потому как чармис обуза и от купца в целом, кроме групп защиты и групп доблы в гопе толку нет - ну еще может накормить, идти на автопоме это вообще блевота, а если лидить, то это стоишь рядом с боем и слушаешь скан. 

Для того, что бы заинтересовать лидеров брать купца, предлагаю дать купцу несколько групповых заклов.
1. Групп мигалка
2. Групп затуманка
3. Групповая насторожка
4. Групповая ловкость
5. Групп проклятье
6. Групп слепь
7. Новй закл  "сердец отвага" - повышает инициативу и реакцию группы
8. Новый закл "купеческое слово" - повышает удачу и иммунитет группы

Так же хотелось бы добавить купе хоть один фраг - например вопль, вполне бы подошел.
Так же было бы не лишним дать купцу умение лечить.

Не нужно быть через чур критичными, купцов не апапали и мы от этого страдаем и чахнем )

Про металку отдельная будет тема, пока не оттестил до адекватной консолидации информации. 

Update (Svjatovit): Умение "метнуть" переработано, к нему реализована пачка усиливающих и слегка видоизменяющих фитов. Надо протетсировать, откалибровать шансы прохождения и т.п.

**Comment by ladon3434** [comment]
давайте без груп слепи а? есть же масс слепь :)
можно клич дать какой нибудь купцу, например "свободная касса" :)
или на скидку

**Comment by Kaynur** [comment]
Ну я масс слепь и имел в виду, купа должен че нить уметь поднасрать в групп пк или в зонинге, кроме как палку какую нить заюзать, он таки кастер.

Кто возьмется реализовать ? Ну вон где я заклы новые писал, пусть это будут кличи, но заклы то же нужны!

**Comment by ladon3434** [comment]
ловкость можно не давать, купцы они про другое же.
лучше им сделать свой закл, на тело или на мудрость. на мувы там.

**Comment by ladon3434** [comment]
а груп обкастеры вроде волши же

**Comment by Kaynur** [comment]
ну надо или делить их обкасты на всех или добавить уникальные полезные, что бы у купца был шанс попасть в гопу

**Comment by joopel** [comment]
поддерживаю
1) Групп мигалка
2) Групп затуманка
3) Групповая насторожка

И предлагаю еще следующее, так как купцы это не рядовые лидеры, а настоящие караванщики - выдать перк полководец, который они смогу получить на 20 морте, и лидерстве выше 180%.  Я про тот перк, который расширяет группу до 14 человек. Сделать его уникальным только для хай морт купцов, квест бы я написал.

**Comment by ladon3434** [comment]
низя на 20 морт, просто низя, давай лучше сделаем 2 перка.
полководец, на лидерке 100+ дает в группу +1 чара
великий полководец на лидерке 130+ дает в группу еще +1
надо постепенно вводить.

**Comment by ladon3434** [comment]
а для 20 мортных, на лидерке 180+ можно дать уже и 3й перк - незаменимый соратник.
+1 персонажам любого лидера группы, но только 1 раз. что бы не бегал караван их 20+ купцов

**Comment by bylins** [comment]
т.е. подводим итог
Групп мигалка
Групп затуманка
Групповая насторожка
добавляю?
Полководец у нас сейчас аффект а не перк, но логично бы сделать от лидерки добавлять челов в группе, а то слишком мало плюшек она дает.
Что еще делаем?

**Comment by Kaynur** [comment]
Я предлагаю 150 180 200 вот так распределить. Потому как будут лепить ватокупцов, что бы таскать ими хороводы на пк, не более того.  А от 150 уже, какой ни какой, а зародыш купца. Там уже можно доверить +1.   Групп заклы, которые Серега озвучил, примем с удовольствием. Но реально хотелось бы что то вредное, типа масс  прокли или масс слепи или масс молчи может, что бы участвовать в замесе. Есть еще такой закл как лихорадка, вот мб масс лихорадка и масс сеть сделать? "ловчий невод".

**Comment by bylins** [comment]
ну хороводы на пк то не водят, там же засадные группы, но я согласен, пусть мортят водят и качают лидерку, которая не совсем просто качается

**Comment by Kaynur** [comment]
а долго это будет реализовываться?

**Comment by lrdx** [comment]
Абсолютно против введения доп.персов в группу купцу, очередной перекос в лидерство опеделенными классами, зачем это? Лидить должен мочь любой

**Comment by lrdx** [comment]
В 1 сообщении идёт речь о минусах купца и возможных вариантах, как вы переехали на какое то лидерство? При чем тут оно?

**Comment by Kaynur** [comment]
Мы в целом АП купца тут обсуждаем.  Купцы народ скупой, но в данном случае могу согласиться, что лидак нужно развить на все профы, скажем всем профам +1 от 180 скила и купцам +3, как я и говорил раньше 150 180 200. Способности (переговорщик, дипломат, вождь).

**Comment by ladon3434** [comment]
нет конкретики, @bylins  дай отмашку что делаем

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/62758195-540c7f80-ba86-11e9-871f-bd60d0dca611.png)

**Comment by Kaynur** [comment]
> т.е. подводим итог 
> Групп мигалка 
> Групп затуманка 
> Групповая насторожка 
> добавляю? 
> Половец у нас сейчас есть эффект и не перк, но логично было бы сделать так, чтобы лидерство пригласило парней в группу, что слишком мало плюшек она дает. 
> Что еще делаем?

За групп заклы спасибо, дайте один масс дебаф! масс медлу или что нибудь, что бы можно было кастить в бою на группу! Ну и добавить от лидака слоты на людей, хотя бы один, что бы купец имел место в гопе!

**Comment by Kaynur** [comment]
Возвращаю внимание к теме.  Заклы хорошо, но чарм дамагу не берут в гопу! Педлагаю дать дополнытельный слот в гопу под чарм дамагу онли.  Народ отзовитесь, купец не может тащить гопу в топ зону, приходится выгонять кастеров, что бы добавить контролеров, либо купца не берут, если лидит не сам купец. Это бесит и класс вымирает. Не дайте пропасть.

**Comment by Kaynur** [comment]
Так же прошу рассмотреть предложение по добавлению способности напарник для купца после 20 морта.  Вату катать соло можно, но вата есть вата и с нее чар многомортовый не покачается, в гопу не берут, а куда посерьезнее идти - нужен напарник, а экспу и так режут мама не горюй. Дайте напарника, считаю это адекватная мысль.

**Comment by Kaynur** [comment]
Не буду плодить другие темы.

Вопрос по очаре купеческой.  Достойного чармиса, как у чернока у нас нет, а надо бы  -  есть попытки это сделать - зеленая птица и ледяной воин в пзп.  Ледяной  уныл - не дамажит, птица ну что то пыхтит, но в 2-3 раунда при нормальном замесе ложится.  
Ледяного война для начала надо пересадить может в башню к огнезмею? Чего он сидит ледяной среди ледяных?  Ну и апнуть его, что бы физик был не хуже фурии. - ее легче чармить, чем потратить время будет пройти до огнезмея. Мне не лень будет сплавать за ним даже через реку смородину, был бы смысл. Ну и как бы огонь пленил лед. - нормально.
Птицу, добавить ей дамаги и хитей, что бы она жить могла и как раз ее запереть на месте ледяного война. - она правда сейчас говно, но и посадили ее на почарм на входе в пзп - это халява.  Пусть сидит нормальный бризер в ледяной тюрьме и от туда его и вызволять, но опять же должен быть не хуже зари.

Вы если не хотите делать нормальных чармисов купцу, опускайте зарю и фурию.
Чернок - надуется, затрясет, КП!, массов куча и еще и очары у него топовые. У купца нету таких ништяков, + он бабки теряет на наем + надо стаф одеть на очару , где то его добыть и удержать и не маловажно, мне его црить надо, в то время, как чернок может забить болт и добыть новый труп. Считаю, что справедливо будет сделать нам 2 нормальных чармиса с разным типом атак и достойным дамагом.

**Comment by Svjatovit** [comment]
https://docs.google.com/document/d/1ZXmuEENwqbVJ4eY4UPbfKB_cFXl42HtRqhNfbgPEz3g/edit

Здесь обсуждение фишек для купцов.

По чармисам предлагаю сделать так. При найме с моба удаляется его экипировка. Взамен генерируется и надевается на моба стандартная экипировка. Параметры зависят от параметров нанимателя. Можно, кстати, сделать фишку, чтобы за чуть более высокую плату экипировка была чуть лучше. Естественно, что эти предметы не продаются и не рентятся. Кроме того, чармисы купцов больше не выполняют команды типа надеть-снять. С одной стороны антуражно, наемник нанимается со своим снаряжением. С другой - снимает с купцов необходимость таскать комплекты на чармисов. Правда взамен придется таскать свитки или зелья, чтобы кидать на чармиса аффекты. Но это на мой взгляд плюс, потому что поднимет полезность варки зелий и крафта свитков, который тоже планировался.

**Comment by Svjatovit** [comment]
В общем, подведу итог:
- Меток переработан и вроде получилось неплохо.
- Вводить кличи купам сейчас не хочется, потому что их навыдавали всем подряд.
- Переделать чарм куп, как описано выше, можно, но это другая задача.

Так что пока тему закроем. В дальнейшем прошу не создавать тем вида "ап-моей-профы". Или не вашей, а какой угодно. Иссуе, повторюсь, для багов и конкретно сформулированных задач. Для обсуждений "чего бы такого сделать хорошего" есть форум.
