### ISSUE TITLE
Коряво выводится текущая ревизия сборки

### ISSUE THREAD

**Issue by bylins** [bylins/mud#499]
i5 630H 179M ??? Зауч:0 34L 110752387G Вых:Ю> ver
МПМ Былины, версия от Jul 16 2019 16:51:40, ревизия: e6b03b19 (Release)

![image](https://user-images.githubusercontent.com/42086238/62423544-5b204000-b6ca-11e9-826b-a42617f76e4a.png)

**Comment by ladon3434** [comment]
у мну норм
ver
МПМ Былины, версия от Aug  6 2019 22:01:16, ревизия: df6695b (Release)
