### ISSUE TITLE
Топ заклы за много гривен

### ISSUE THREAD

**Issue by bylins** [bylins/mud#501]
Поступило предложение:
!разбитые оковы!,!ледяной щит!,!каменное проклятье!,!круг пустоты! ну и подобные
выложить в магазы допустим за 5к, так как процент мизерный и оч долго снимаются.
Сделать возможность ложить гривны кланхран и ввести новый ранг "Казначей" который может тратить в кланхрана а не из своего кошелька.

**Comment by joopel** [comment]
Против заклов за гривны, в вышке есть свитки с временными заклами этими, там с ценами бага не знаю с чем связано. Поправим ее и пусть пользуют, пока не спопят постоянные заклинания.

Если вводить казначея, то обязательно с налогом на вложение гривен в казну.  Кладет 100, в казну отправляется 70. Объясню почему. 

Во-первых чтоб избежать когда каждый член клана скидывается крохами по 40-50 гривен, а таких крох на чарах копится очень много и затем берут сообща сразу сет. Это просто абуз с передачей гривен будет, так как гривны скопились на чаре, но сет по факту этому чару и не собирались никогда покупать.

Во-вторых, будет так что чар уходит в отпуск/бросает мад и т.д, гривны сдаются в хран. Ну уж нет, хотите сет - пусть перед отпуском добьет 300 гривен и покупает.

Если вводить казначея, налог 30%.

**Comment by Anden-Farik** [comment]
ну для гривен это наверно большой таки налог, ведь у них таймер раз в сутки сбор если примерно 200 собирать в день то в казну только 140, и клан налог 20% но куны без таймера сколько хочешь столько руби, может с гривноналогом какнить понежнее поступить ? а из мада уходят очень редко и еще трешсбор гривен исключен ибо гривны на акаунт привязанны, тоесть грабительский очень налог

**Comment by Kaynur** [comment]
Я таки думаю, что не надо за гривны буки продавать. Жупел прав, перебиться можно на свитках, если быть уверенным в том, что ты не будешь снимать и задрачивать клан, а тупо пойдешь купишь закл, уничтожает романтику. И опять же, пока один клан дрочит буку, второй идет свободную зону и мир движется за счет идущих ног.

**Comment by bylins** [comment]
ну или добавить места лоадов в альтернативных местах

**Comment by Kaynur** [comment]
+

**Comment by Anden-Farik** [comment]
> ну или добавить места лоадов в альтернативных местах

+(плюс)

**Comment by Svjatovit** [comment]
Что именно продавать в магазинах за альтернативные валюты и по каким ценам - отдельный вопрос и собственно к  коду он прямого отношения не имеет. Закрываю.
