### ISSUE TITLE
Ювелирное дело - улучшение и в частности огранка.

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#504]
Коллеги, есть мнение. 
Кузнецы регулярно портят вещи, когда плавят камни. Согласитесь, что грубые (кривые) руки кузнецов не приспособлены к работе с тонкими материями. Заточить - могут, укрепить - легко, сковать - хуйня вопрос. Но когда дело встает - "вплавить" блять - плавильщики - "хуевы", тут слово "ювелир" и "сука-вплавил", и вплавил слово реже используется, чаще - сука. Предлагаю, забрать у кузнецов, сей тонкий скил. Передать его купцам. Мы более бережно отнесемся к драг.материалам:
+ место для обработки камней
+ обработка камней
+ обработка металлов(материалов)
+ обработка заготовок
+ ингридиенты для обработки и материалов и заготовок
+ чертежи изделий
+ мастера для для обогащения руды и минералов
+ выпуск ЮВЕЛИРНЫХ изделий
+ выпуск УНИКАЛЬНЫХ предметов
+ котировка слова ЮВЕЛИР

Потому как щас -  рандом, воткнуть говна в говно, ну скуно же?  Кузнец, ну что он? Ну дырку нарезать в железке? Ну в каменном стволе увидеть щель и "вплавить".

**Comment by Kaynur** [comment]
> Коллеги, есть мнение.
> Кузнецы регулярно портят вещи, когда плавят камни. Согласитесь, что грубые (кривые) руки кузнецов не приспособлены к работе с тонкими материями. Заточить - могут, укрепить - легко, сковать - хуйня вопрос. Но когда дело встает - "вплавить" блять - плавильщики - "хуевы", тут слово "ювелир" и "сука-вплавил", и вплавил слово реже используется, чаще - сука. Предлагаю, забрать у кузнецов, сей тонкий скил. Передать его купцам. Мы более бережно отнесемся к драг.материалам:
> 
> * место для обработки камней
> * обработка камней
> * обработка металлов(материалов)
> * обработка заготовок
> * ингридиенты для обработки и материалов и заготовок
> * чертежи изделий
> * мастера для для обогащения руды и минералов
> * выпуск ЮВЕЛИРНЫХ изделий
> * выпуск УНИКАЛЬНЫХ предметов
> * котировка слова ЮВЕЛИР
> 
> Потому как щас - рандом, воткнуть говна в говно, ну скуно же? Кузнец, ну что он? Ну дырку нарезать в железке? Ну в каменном стволе увидеть щель и "вплавить".

**Comment by ladon3434** [comment]
И пришли сладкоголосые купцы, где подкупом где угрозами решили они обидеть честных куцнецов. Но сделали кузнецы свой ход, сказали - Руки прочь от вплавки! Лучше огранкой займитесь!

**Comment by ladon3434** [comment]
Огранка - превращение камня с рандомными статами в определенные.

**Comment by Kaynur** [comment]
У нас и так все камни определенные.  Купцы будут из различных материалов делать бижу, кузнецы дырки резать, купец будет драги вставлять в бижу.

**Comment by vredomir** [comment]
> 
> 
> У нас и так все камни определенные. 
Нет не определенные, тот же желтый дает 2 рандомных стата, полагаю, Рома говорит о фиксации стата на подобных камнях. Типа погранил камень и он даст точно 2 хари, а не бесполезные 2 силы/ловки/мудры.

**Comment by Kaynur** [comment]
Давайте начинать уже,  огранка это страт, меня интересует ювелирка как таковая. Я хочу что бы купы могли делать топовую бижу и не хуже чем из крутых зон, при наличии крутых ингров и рецепта.

**Comment by ladon3434** [comment]
предлагаю сделать бижу на 1-2 слота и расширить камни, и пущай извращаются.

**Comment by Kaynur** [comment]
Бижу на 1-2-3 слота, в зависимости от рецепта. 1 рецепт = 1 бижа. Соответственно бижу можно скрафтить из определенных ингров, ну и скил огранка что бы наделать камней и вплавить их в нее.

**Comment by Svjatovit** [comment]
Вообще есть ТЗ на новую систему крафта и даже частично код по ней. Но хз когда и у кого руки до него дойдут. А тут нужно ТЗ по огранке.

**Comment by Svjatovit** [comment]
В общем, с крафтом конечно что-то делать нужно, но не так.
