### ISSUE TITLE
Боль Кудеса

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#505]
Коллеги, ко мне обратился топ кудес с просьбой увеличения лимита хари. 
Сейчас потолок 50. Представитель кудесников просит рассмотреть увеличение потолка хари начиная с 18 морта на +3 хари с шагом в 3 морта к следующему увеличению(21, 24, 27) с итоговым потолком в 70 хари. С условием. Что если кудес берет чармиса на 50+ хари, второго он взять не может.

**Comment by Svjatovit** [comment]
Планки надо со всех статов снимать постепенно... И для всех классов.
