### ISSUE TITLE
Луки[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#51]
*Originally reported by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

По всеобщим взываниям охотников - создаем ветку для луков и их крафту.

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/51

=======COMMENTS=======

Date: 2017-09-03T12:01:58Z

*Original comment by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

какие проблемы предстоить решить
1. среднее по лукам.
2 разнообразие луков большое. что будем переносить.

**Comment by Svjatovit** [comment]
Не создаем. Есть система крафта, кто хочет заниматься крафтом - давайте ее допиливать. Там можно и луки крафтить, и черта в ступе.
