### ISSUE TITLE
Расширение формулы чарма

### ISSUE THREAD

**Issue by joopel** [bylins/mud#510]
Предлагается апнуть чармдамагу в зависимости от количества мортов, а также снять планку в 75 мудрости у черноков для чарма, суммарного стата у купцов для чарма и (кудесов? хз какая там у кудесов формула если у них кап 50, может их не стоит трогать либо также им увеличить кап по стату).
Отправная точка 54 мудры у чернока это умертвие трактрищка, самый стандартный чармис для лоумортов, с него несколько снижаем подъем значение чармис выставляя его в 140, а не 180 и тп как было раньше.
При 75 мудрости получаем примерно старое значение в 14000 как и было раньше, 140 составляет 1% от этого значения. За каждый реморт сверх 9-го добавляется по 1% к значению этого параметра начиная от 75 мудрости. 
Предлагаемая формула расчета новое значение Charms*(1+(количество мортов-9)/100)
Итого на 12 мортах и 75-76 мудрости чернок выходит на текущее значение. 
Дальше идет увеличение данного параметра, при 21 морте и 90 мудрости бонус составляет 1,25  к старому значению.
При 75 мудрости и 21 морте бонус 1,08 к старому значению.
При этом изменении появится смысл одевать чармеров свыше стандартных значений на чармисов, а также вводить новых чармисов для реморченых персонажей.
можно добавить что также изменен параметр Dam_to_hit_rate в тестовом варианте, было до 90 мудрости 9 начиная с 72, установлено постепенное увеличение до 6 на 90 мудрости. Это под вопросом надо тестить.

Залить отдельным бранчем, для теста на зеркале. Таблица в аттаче
[Charmis.xlsx](https://github.com/bylins/mud/files/3480533/Charmis.xlsx)

**Comment by bylins** [comment]
я в чармисах нифига не шарю, с меня помощь будет только в тестировании (запуске зеркала)

**Comment by lrdx** [comment]
Смысла нет, по сути весь чарм все равно сводится к тому, сто придумают билдеры, ибо взять мобов из реально существующей зоны не представляется возможным - у них слишком много хп. Так что если и увеличивать что-то, то делать это с добавлением новых чармоа и проработкой.

з.ы. ну если ты конечно не хочешь тупо сделать имбалансов с 2-3 ЗАРЯМИ/ФУРИЯМИ

**Comment by joopel** [comment]
Летий, таблицу СМОТРИ ВНИМАТЕЛЬНО чернок на 21 морте с 90 мудры будет иметь 17612, против текущего обрубка в 14150. Это не сильный ап, он нужен чтобы развивать чармисов дальше. 

И да я планирую заниматься их проработкой и даже крафтинг сделать со временем. Но скорее всего не в этом году.

**Comment by lrdx** [comment]
Да я понимаю все, просто хотел сказать что чарм все же больше от билдеров зависит, чем от формул и порогов к сожалению )

**Comment by bylins** [comment]
Одна из причин, почему я хочу из чернока сделать повелителем зомбаков, а не очередного чармера, у которого сила зависит от моба

**Comment by joopel** [comment]
[CHRM.txt](https://github.com/bylins/mud/files/3483257/CHRM.txt)

**Comment by ladon3434** [comment]
залил реквест, потестите с ветки. новые значения для файла Ярило вон приложил.

**Comment by joopel** [comment]
По чарму, формулу вместо 
	r_hp *= MAX( 1.0, 1.0 + ((float)ch->get_remort()-9.0)/100.0) ;
делаем такую, то есть добавочный кэф от морта не 1% будет, а 1.2%

	r_hp *= MAX( 1.0, 1.0 + (((float)ch->get_remort()-9.0)*1.2)/100.0) ;

Кап кудесам на харю делаем 60, очень много тестили так как кудесы одевают чармисов, если им расширять кап еще, надо вводить капы на одевания самого чармиса. И все, можно релизить.

**Comment by ladon3434** [comment]
последний фикс не залит, надо или залить или закрыть нафиг @Stribog1

**Comment by bylins** [comment]
так там формулу же надо переделать

**Comment by joopel** [comment]
так залито или нет? r_hp *= MAX( 1.0, 1.0 + (((float)ch->get_remort()-9.0)*1.2)/100.0) ; 

Если залито, закрываем.

**Comment by bylins** [comment]
https://github.com/bylins/mud/commit/0eb1a8097cdcf00bf3f0dd1ef827666b489f02d5
закрываю

**Comment by ladon3434** [comment]
окей, не залито, так что у чамодамаги 1% за реморт. тестите, если будет совсем мало бум раширять горизонты
