### ISSUE TITLE
большое неудобство в цр перековки - нубо сетов

### ISSUE THREAD

**Issue by ladon3434** [bylins/mud#515]
Сейчас нельзя даже взять такой шмот, очень неудобно црить таких чаров.
Поэтому делаем возможность брать такие вещи, и доабвляем проверки на одевание что бы не одевали не свое.

**Comment by vredomir** [comment]
Поднимается нормально, но при попытке одеть, шмотка падает на землю. Имхо должно просто жечь и не давать одеть. Лог ниже.

од шлем
Вас обожгло при попытке использовать шлем.
1935H 227M 155221948о Зауч:0 Кл:3 Яр:1 28L 5226G Вых:СВЮЗv> 
од ш
Вы водрузили шишак с клеймом Китовраса себе на голову.
Клеймо Китовраса вспыхнуло и вы почувствовали небывалый прилив сил.
1935H 228M 155221948о Зауч:0 Кл:3 Яр:1 28L 5226G Вых:СВЮЗv> 
дать шле .кол
У вас нет 'шле'.
1935H 230M 155221948о Зауч:0 Кл:3 Яр:1 28L 5226G Вых:СВЮЗv> 
см
Покои [40616]
Просторный покой. У западной стены - широкие палатья, покрытое простым 
цветастым покрывалом. У противоположной стены большая широкая скамья, с 
высокой спинкой и парой подушек, около нее несколько полок с книжками. 
В левом углу стоит не большой сундук с замком.
[ Exits: n e s w d ]
Шлем лежит здесь.
