### ISSUE TITLE
Дружи в группе

### ISSUE THREAD

**Issue by vredomir** [bylins/mud#517]
С учётом изменений экспы чармдамаги, я предлгаю либо дать бонус дружу на экспу, если он состоит в группе и в стиле, либо дать ему возможность дамагать в веере/блоке, например наносить контратаки с 50% уроном при каждом отраженном ударе, но повторюсь только в группе и в осторожке, дабы исключить абьюзы.

**Comment by Kaynur** [comment]
+

**Comment by Kaynur** [comment]
Ошеломить надо у всех отнять и дать дружу, пусть шеломит в щит моде щитом. Витязь точить умеет, охоту дайте стрелу злую.

**Comment by vredomir** [comment]
Как вариант дать врождённый фит 'опытный воин', и пусть получает допэкспу всегда. Например базу 10% и по 1% за каждые 3 морта начиная с 9.

**Comment by Svjatovit** [comment]
Опять треп в общем и целом... Дружу бы какой-нибудь ДД спек дать, чтоб он мог и подамажить. Ну и механику танкования надо менять. Иссуе закрываю.
