### ISSUE TITLE
Мигание татей

### ISSUE THREAD

**Issue by vredomir** [bylins/mud#518]
У татя врождённая плюшка автомигание, но при этом она не учитывает морты и работает так же как автомигалка на стафе, несправедливо как-то.

**Comment by ladon3434** [comment]
осуждая предлагай, давай рассчеты, у татя еще и уклон есть

**Comment by vredomir** [comment]
Уклон != мигание, т.к. в лаге от стаба не работает. И в случае если тать не танчит моба 2+ раунда, он бесполезен от слова совсем, а такое происходит крайне редко.
Сейчас волш вешает шанс такой:
(5 + GET_REMORT(ch) * 2 / 3)
21+ морт волш вешает мигалку на час+, поэтому делать шанс меньше имх бессмысленено.
Можно дать изначально выше шанс, например:
(10 + GET_REMORT(ch) * 2 / 3)
что даст топтатю 27% шанс мигнуть, вместо 22% с каста волша
Можно завязать на уклон, чтобы поднять его полезность:
(5 + (ch->get_skill(SKILL_DEVIATE) / 20) + GET_REMORT(ch) * 2 / 3)

**Comment by bylins** [comment]
лучше на скилл татя

**Comment by bylins** [comment]
сделал пока так
![image](https://user-images.githubusercontent.com/42086238/63101382-9bf93e00-bf81-11e9-9821-76b02c6a818a.png)
так как уровень макскилла все равно равно реморту, не логично его цеплять на скилл уклона, который качается моментально.
Но что меня смущает, ведь в данном случае вероятности складываются, если он обкастован волшем будет далеко не 32% у хайморт татя

**Comment by bylins** [comment]
скорее сделать надо так
![image](https://user-images.githubusercontent.com/42086238/63101614-13c76880-bf82-11e9-834a-3a2d190cf684.png)

**Comment by bylins** [comment]
и вообще мне кажется что
if (AFF_FLAGGED(victim, EAffectFlag::AFF_SPELL_BLINK) && number(1, 100) <=  (5 + GET_REMORT(ch) * 2 / 3))
надо перевести на морты волша, а не на морты чара, типа волш более крутой более лучшую мигалку вешает

**Comment by lrdx** [comment]
Надо на меньший Морт между кастующем и на кого кастуют сделать, чтобы для прокачки не имбово было

**Comment by bylins** [comment]
ну раньше мигалка жестко 25% была, и никто не багрепортил что имбово

**Comment by lrdx** [comment]
Ты думаешь хоть кто-то рерортит имбу?)))

**Comment by bylins** [comment]
ну мигалка в моих интересах, так как у охота тоже есть уклон, я же делаю онли тать!
совесть имею

**Comment by vredomir** [comment]
Вроде всё обсудили, надо внедрять)

**Comment by bylins** [comment]
сделаю

**Comment by Svjatovit** [comment]
А на самом деле автоаффекты на стафе - зло. Они лишают смысла свитки и зелья, а частично и касты.

**Comment by bylins** [comment]
короче у татя мигалка +5% всегда, вливаю
