### ISSUE TITLE
Горное дело

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#519]
Господа, не нашел тему про горное дело.

Поясните пожалуйста как рассчитывается успех рытья?  Роем роем, а как то непонятно, как увеличить шанс добычи желтого драга? 

Может быть стоит добавить еще один камень, "сердце горы" - редкий, но 3 статовый + рандомный аффект какой нить начиная от зеркала, заканчивая щитом?

**Comment by ladon3434** [comment]
кидается рандом от 1 до 100, если этот рандом > чем % горного дела / 3 то фейл копа.
т.е. на 100% горного дела 66% фейла вникуда, камня нет.
1 из 3 камней стекло всегда.
потом кидается рандом от 1 до мин ( % горного дела , 100)  и выбирается какой камень выпал. если >= 99 то самый крутой камень.  если меньше то более фиговый.

итого на 100% горного дела шанс +2 камня = 0.33 * 0.33 * 0.01 = 0.001089 = 0.1089% за коп.

с 1000 копов по статистке бывает от 0 до 3 камней. а 1000 копов это 2000 секунд примерно, около получаса

**Comment by ladon3434** [comment]
горное дело выше 100% не учитывается никак, удача никак, инта мудрость никак, реморты никак.

**Comment by Kaynur** [comment]
я думаю, если в мире появится огранка, то пусть так и остается, не должно быть избытка материала для огранки.

**Comment by vredomir** [comment]
Только нужно будет пересмотреть статы камней, т.к. шанс получения камней одинаков. Например 3 хитрола или дамрола вот никак не уравновесят 2 стата. Я готов проработать концепт, если дадите добро.

**Comment by ladon3434** [comment]
сначала проверяется будет ли камень, потом выбирается камень с разной вероятностью, потом 30% камней превращается в стекло. т..е. щанс +2 камня 1 % а 3 хитрола процентов 40%

**Comment by Kaynur** [comment]
Надо делать

**Comment by Svjatovit** [comment]
Ну так создайте отдельное Issue под огранку. Тему закрываю.
