### ISSUE TITLE
Поглощение

### ISSUE THREAD

**Issue by bylins** [bylins/mud#523]
шанс 10%
dam -= GET_ABSORBE(victim) / 2;
т.е. параметр поглоты просто вычитается из дамаги
капа в 50 нет
предлагаю сделать шанс 10% + реморт
ну и дам вычитать в % а не числом. Правда 200 поглоты будет полный иммун с определенным шансом, но чар просядет по другим параметрам одев столько поглоты.

**Comment by bylins** [comment]
мобам поставить кап 50 чтоб не изменить баланс зон

**Comment by bylins** [comment]
можно ввести кап и у игроков, но напялив 100 поглоты ты жутко просядешь по остальным статам

**Comment by joopel** [comment]
> предлагаю сделать шанс 10% + реморт
лучше 10%+ реморт/2, если чисто реморт даже 20 мортов будет давать уже очень высокий шанс = 30%

Также надо учитывать, что у нас есть такие предметы как кольцо из чешуи ламии, браслет из чешуи ламии, каждый дает по 20 поглоты. Да и еще много предметов таких.

То есть какой нибудь охотник в сете, одетый в 80 поглоты  только с этими 4 предметами, уже становится трудно пробиваем с мигалкой и уклоном )

а если одеть на батыра, у которого ярость на 3 тика дает 70 поглоты получается 150, докинуть еще пару шмоток, которые не занимают сетовые слоты и батыр 30 мортов получит иммун 40% к дамагу ) имба

Предлагаю сделать кап на поглоту, чтоб максимум 100-120 работало. Либо базовый кап 80, а дальше расширяем его 80+ реморт*2, то есть кап на 25 морте будет 80+50=120
