### ISSUE TITLE
Подъем лохотов

### ISSUE THREAD

**Issue by bylins** [bylins/mud#527]
Так как неизвестно когда заработают колчаны предложение:
ввести кличи
+опыт на группу
+удача
+физдамага

**Comment by Chadomir** [comment]
еще можно + броня, вроде ничем не дублируется. К опыту на группу  надо ввести какие-то требования -чтобы трешей не таскали - ограничение по морту (6?)

**Comment by bylins** [comment]
кличи такое не умеют, в смысле ограничение по морту

**Comment by bylins** [comment]
кстати опыт на группу, хрен ты лоулевел поводишь, там режется дико
