### ISSUE TITLE
вплавить кузнеца дает разные опции при ручном и рандомном плавлении

### ISSUE THREAD

**Issue by ladon3434** [bylins/mud#528]
Вы взяли зеленовато-голубой камушек [инфра, свет, +20 защита +5 реакция + 5 стойкость, попадание +1, водохождение] из переметной сумы.

1190H 247M 18M Зауч:0 23L 14773G Вых:Зv> вплав каму меч вава
Будучи искусным ювелиром, вы можете выбрать, какого эффекта вы желаете добиться: 
 настороженность
 защита.от.света
 защита.от.тьмы
 инфравидение

сам лично плавил камни в обруч и опознавал что получилось из рандома, а ручное плавление дает другие выборы вообще. может сделать так чтоб они были равны?
убрать из кода вообще рандомы и брать их по списку из insert_wanted.lst

**Comment by joopel** [comment]
против, будут плавить по желанию санки. Санк обесценится в разы. Рандом так задуман и был, хочешь нужный аффект - помучайся с плавкой

**Comment by ladon3434** [comment]
не, я имел в виду убираем полностью систему из кода с рандомом статов. 

if (GET_OBJ_VNUM(gemobj) == dig_vars.stone1_vnum)
				switch (number(1, 6))
				{
				case 1:
					set_obj_aff(itemobj, EAffectFlag::AFF_DETECT_INVIS);
					break;
				case 2:
					set_obj_aff(itemobj, EAffectFlag::AFF_DETECT_MAGIC);
					break;
				case 3:
					set_obj_aff(itemobj, EAffectFlag::AFF_DETECT_ALIGN);
					break;
				case 4:
					set_obj_aff(itemobj, EAffectFlag::AFF_BLESS);
					break;
				case 5:
					set_obj_aff(itemobj, EAffectFlag::AFF_HASTE);
					break;

				case 6:
					set_obj_eff(itemobj, APPLY_HITROLL, -1);
					break;

и для простой вплавки иоспользовать рандом по тем же аффектам что описаны в insert_wanted.lst что какие камни дают, сколько дают.

**Comment by ladon3434** [comment]
неактально, уже приравняли
