### ISSUE TITLE
Саммоны чернокнижнику, обсуждение

### ISSUE THREAD

**Issue by joopel** [bylins/mud#529]
Демний попросил запостить заготовку, обсуждает с ладоном реализацию

> Берем параметр чармиса, из него вычитаем базовые значения для чармиса на текущем морте, все остальное кидаем в дамаг которое кубики.
> Базовые статы чармисов.
> Лучник - макс дамаг, облако стрел, базовые хп 500 + 50 за морт, базовая сила 20, 30 хитролов, 10 дамролов.
> 4 атаки.
> Воин - танк, физ дамаг, базовые хп 1000+100 за мортв, базовая сила 30, 10 хитролов, 10 дамролов.
> Дракон бризер, 3 атаки, базовые 700хп+70 за морт, базовая сила 20, 20 хитролов, 10 дамролов, мудрость =мудра чернока/1,5 , какой тип дыхания установить не знаю, предлагаю тьмы, соответственно дать чарму магию тьмы от текущий магии чернока/2.
> Лич-кастер - хп 300+100 за морт, базовая сила 30, 0 дамролов, 0 хитролов, кубики можно поставить 1д1, 1 атаку чтобы сильно не дамажил. Даем шанс каста в раунд одного из заклов, метеоритный дождь, камнепад, масспроклу, массмолчу, вопль.
> Выдаем мудру = мудра чернока /1,5, каст = каст чернока - минус 50. Магии выдаем по аналогии с бризером, только отталкиваемся от магии тьмы, то есть магия тьмы/2.
> Чернок может таскать только 1 из чармисов, можно поставить два но будет геморно в расчетах.
> Для выбора какого из чармисов поднимать чернок зажимает в руке определенный ингр - сердце(воин), когти (лучник), чешуя( дракон), прядь волос (лич).
> Дополнительно при определенных уровнях мудрости добавляем чармисам зеркало и щиты.
> Зеркало предлагаю сделать с 65 мудрости, щиты с 75.
> Воину - огненный, личу - воздух, лучнику - ледяной, бризеру - ледяной.

**Comment by joopel** [comment]
Я без проблем сделаю прототипы типа костяных гончих, драконов. Остальное **хардкодить**. Перед тем как кодить, от товарища Чернокнижника хочу была таблица с закладками по расчетам, как эти чармисы будут выглядеть на промежуточных мортах, при разной мудрости вплоть до капа.

Чтобы я мог по этим расчетам сделать пару прототипов и потестить все это дело в живую. Прежде чем начать кодить. 

Сначало считаем, потом делаем

**Comment by ladon3434** [comment]
прототипы надо делать без учета количества кубиков дамаги, только размер кубиков.

**Comment by Zolfik** [comment]
Основные мысли изложены выше, ап чарма от мортов заработал.
Предлагаю пока ввести черноку 2 базовых чармисов лучника и танка, прототипы готовы.
Параметры лучника - 4 атаки, базовые хп 500+50 за морт, сила 15, хитролы 30, дамролы 10, облако стрел. Размер кубика ставим 20, количество бросков округляем в меньшую сторону в зависимости от параметра чармс за вычетом параметров выше.
Воин аналогично только хп база 1000+100 за морт, сила 15 хитролы 30 дамролы 10, размер кубика д20, остаток параметра чарм делим на 1.5 и добавляем в количество бросков кубика.
Чернок может одновременно призывать тлько 1 чармиса.
Бризера и лича предлагаю сделать после теста этих чармисов.

**Comment by ladon3434** [comment]
736H 142M 1о Зауч:0 Вых:СВ> 

Чармис тридцать девятого уровня дамаг БОЛЬНО ударил лича.
Чармис тридцать девятого уровня дамаг ОЧЕНЬ БОЛЬНО ударил лича.
От удара чармиса тридцатого уровня лич отправился в мир теней.
Лич вспыхнул и рассыпался в прах.
Кровушка стынет в жилах от предсмертного крика лича.
Лич прекратил следовать за вами.

736H 142M 1о Зауч:0 Вых:СВ> 
осм чар

Ничего необычного в чармисе тридцатого уровня вы не заметили.
Чармис тридцать девятого уровня дамаг смертельно ранен, стоит.

**Comment by ladon3434** [comment]
35 чармиса лич забодал с пол хп

**Comment by ladon3434** [comment]
Ветка залита, надо тестить на зеркале.

**Comment by ladon3434** [comment]
@bylins @Zolfik  проведите тесты, подкрутите статы прототипам.
