### ISSUE TITLE
Ап Витязя

### ISSUE THREAD

**Issue by Kaynur** [bylins/mud#532]
Прошу рассмотреть предложения играющего Витязя.

В связи с тем, что витязи объективно профа достаточно узкоспециализированная и довольно сильно отстающая в абсолютном большинстве зон по боевой эффективности и нужности, прошу рассмотреть следующие варианты небольших улучшений:
1.    Проблема в соло откаче даже со слабыми мобами, имеющими навык парирования или уклонения.  У витязя мало атак и точка просто не срабатывает из-за того, что мобы постоянно избегают атак активными навыками. Приходится долго и уныло пинать по 20 раундов, там, где кузнец/бтр убивает за 2 глуша.  Если возможно – сделать так, чтобы,  прокнувшая на атаку точка, пробивала парирование/уклонение. 
2.    Вариативность оружия. С двуруча (как и с перка «двойной выстрел» )40% возможность прохождения дополнительной атаки, что делает практически безальтернативным использование любого другого оружия кроме класса «двуручники» из за их веса и дополнительной атаки.  Однако, обидно, что пропадает возможность точить с луков с перком "двойной выстрел", имеющимся у витязя. Предлагается сделать учет веса лука на точку как 4/5 от веса оружия (т.е. лук 50 веса будет рассчитываться на точку как оружие 40 веса), но при этом  прохождение второй атаки с двойным выстрелом предлагается поднять до 75%). Соответственно у витязя появится выбор – точить реже, но сильно, чуть чаще, но средне, или еще чаще (атака левой рукой в дуале 95%) но послабее.
3.    Магия витязя. Предлагается придать хоть немного смысла заклинаниям витязя, которые (кроме дисмолчи и в минигопах санки) совершенно невостребованны. Для этих целей, чтобы витязь было более полезен в групповом зонинге дать витязю «снять оцепенение», «снять слепоту», «снять глухоту», «призматическая аура». В результате витязь сможет служить хорошим дополнительным дебаффером, на случай, если клера залагали или убили. Призмааура позволит витязю уверенней себя чувствовать в минигопах и не использовать вместо своей санки кастом – шмотки на санку (так как шмотку в отличии от каста можно в любой момент снять). Дать также уникальное заклинание которое вешает аффект !не сбежать.
4.    Повысить кап применения удачи витязя с 50 до 50+1 за каждый морт. Тогда витязю 20 мортов (кап 70) будет вполне осмысленно одеваться в удачу выше 50. Сейчас «лишняя» удача просто висит балластом.

**Comment by pilaty** [comment]
1.против холявного откача для витязя, причина следующая: мы уже видим нашествие ботов скриптеров в виде кузей наемов, если сделаем халявный откач для витязя будут в топе витязи-скриптеры, этот долгий откач сдерживает хоть эту профу от скриптодрочерства, ибо это уныло долго пинать мобов, ничего... если я привык в говностафе выходить из морта 3-4 сутки, значит в этом проблемы не вижу
относительно игнора точкой парировать и уклона. тоже против. тогда теряет смысл в таких скиллах как уклон и парировать против витязя, а если попадешь на моба кооторый точит то чара ничего н е спасет. в том же 4с
2. против луков витязя. витязь не лучник. и это работало. потом пофиксили чтобы вес лука резался в полтора, ибо слишком жирно было. но как бонус али вторую атаку пасивным перком для двуруча. да не всегда проходит. хотите 2 атаки - юзайте дуал. у меня все на этот пункт
3.за любые заклы диспелы, есть еще куча заклов которые доступны мобам а не доступны профам вообще предлагаю их повешать на витязя. а то у меня слотов валом по 30штук. а заучиваю доблести
4.удача. за. но тогда надо балансить все профы это сложно тошно и никому ненужно
5. отсебятина. как апнуть витязя? мой вариант: добавляем атаку щитом, если человек с башмоде, чтобы у него было 2 атаки. но щитом можно было рандомно оглушить соперника в ступор на 1 раунд, чтобы глуш не давал лаг на точку. скажите чит. хз.
увеличить дамаг от баша, именно от баша (помоему там было константа, а надо повешать от мортов силы), а не по сбитому сопернику, тут как раз итак есть коэф.
4.

**Comment by Nimrok** [comment]
В идеях написал про именного коня за славу, но почитав такую великолепную тему как "ап витязя" решил немного сузить рамки идеи. Предлагаю витязя теснее привязать к коню. Что меня натолкнуло на это: 1) картина "витязь на распутье", ролеплей; 2) в днд у паладинов есть способность призвать себе коня. Конечно и паладины и днд тут вообще не в почете, но зато опыт отработанный; 3) говорят, что у витязя нет сказки - хороший повод ее написать и заполнить выбором своего боевого коня витязя, призыв заклинанием, статы коня зависят от мортов, или от статов хозяина или еще от чего-нибудь. Качается витязь - растет и крепнет его жеребенок. 
   По поводу вышесказанного: все файтеры жестко подсели на двуручники, разве это нормально? Луки, дуал, башмод - подтянуть что угодно лишь бы могло конкурировать с двуручами хотя бы у некоторых классов. А витязь по боевому стилю довольно сильно отличается от других, значит и приоритет ему.

**Comment by LdanDSS** [comment]
Кстати, интересная тема с конями. Двуручи как стиль довольно неинтересная штука (итак конкуренция между ними бешеная из-за засилья кузнецов и бтров, которым они нужны). Прикольно бы сделать из витязя именно конного копейщика с щитом. Коняга давала бы веса оружию витязя , компенсируя легкость одноручного копья с таким расчетом чтобы раскачанная верховая езда, прокачанный свой конь давали бы до +30 к весу оружия и + к дамагу для расчета точки, если это копье , которое используется на лошади.  Можно даже ввести новый скилл "таранный удар" или что-то вроде, чтобы пассивно накидывал для копья дамролов, хитролов, веса при использовании на коне.

**Comment by bylins** [comment]
Проблема в соло откаче даже со слабыми мобами, имеющими навык парирования или уклонения. У витязя мало атак и точка просто не срабатывает из-за того, что мобы постоянно избегают атак активными навыками. Приходится долго и уныло пинать по 20 раундов, там, где кузнец/бтр убивает за 2 глуша. Если возможно – сделать так, чтобы, прокнувшая на атаку точка, пробивала парирование/уклонение.

предлагаю ввести способность игнора парри, и туда же перевесить двойной удар с двуруча

**Comment by Nimrok** [comment]
Действительно, меня в лирику понесло когда есть насущные проблемы. Ковыряние слабых мобов со всякого рода уклонениями одна из проблем откача с точкой. Витязи воины мудрые и умные, будут не против даже и умения, которое введет вторую атаку с возможностью сточить при промахе. Или того жесче - атаку со 100% попаданием, но это вроде механика метких попаданий. Да и точное попадание по определению меткое. В любом случае, согласен с предложением предыдущего оратора. А если вероятность прока второй атаки привяжут к умению владения двуручами, как это написано в справке (спр любимоеоружиедвуруч) то появится еще и стимул делать морты и повышать свой уровень мастерства.

**Comment by LdanDSS** [comment]
По-моему отличная идея с новой способностью и она давно назрела (клер с луком и облаком стрел быстрее парирующих сносит нежели витязь), но раз таки слот  это займет мб сделать чуть выше процент прохождения второй атаки? При фул раскаче навыка оружия 50% вместо 40%.
Опять же, мб этой способностью навесить немного дамролов на двуручи. В целом это изменение более направлено на комфортную игру "маленьких" витязей, которым будет чуть более комфортнее ощущать себя дамагой (так как далеко не у всех сразу 200 точки и пушка на 50 веса), ибо витязь до 10 мортов мало чем от дружа отличается :)

**Comment by Svjatovit** [comment]
На форум с обсуждениями, плз. Тут только конкретные таски по уже принятым решениям или баги.
