### ISSUE TITLE
Бага в MSDP

### ISSUE THREAD

**Issue by bylins** [bylins/mud#538]
[1] 16:06 13-07-2017 (Ларион) :: [85540] msdp: experience и level

по msdp обе переменные и EXPERIENCE и LEVEL возвращают уровень в коде в обоих там макрос GET LEVEL проставлен
msdp.cpp: LevelReporter, ExperienceReporter

**Comment by ladon3434** [comment]
void LevelReporter::get(Variable::shared_ptr& response)
	{
		const auto level = std::to_string(GET_LEVEL(descriptor()->character));
		response = std::make_shared<Variable>(constants::LEVEL,
			std::make_shared<StringValue>(level));
	}

	void ExperienceReporter::get(Variable::shared_ptr& response)
	{
		const auto experience = std::to_string(GET_EXP(descriptor()->character));
		response = std::make_shared<Variable>(constants::EXPERIENCE,
			std::make_shared<StringValue>(experience));
	}

**Comment by ladon3434** [comment]
бага не обнаружена
