### ISSUE TITLE
Плюшки для хаймортов

### ISSUE THREAD

**Issue by bylins** [bylins/mud#541]
Предлагаю с 20+ морта давать +1 мр +1 фр за морт

**Comment by Svjatovit** [comment]
Предлагаю не давать.
А если серьезно, то это мертвому припарки. А также инъекции, томограммы и капельницы. Хотите, чтобы был смысл мортиться выше 30 - вводите топ-контент. Зоны, доп активости и так далее, доступные на хаймортах. Да, его делать надо, прикиньте. А не 1 строчку в код добавить. 
А это просто сделает перебафаных бегемотов еще бегемотистей.

**Comment by joopel** [comment]
Тоже самое хотел написать.  + любые плюшки должны быть после серьезной переделки системы существующих мортов. Мне идея прироста с кэфами главных и вторичных характеристик крайне понравилась.

**Comment by bylins** [comment]
это другая тема это раз, второе - мне не понравилось, мы 20 лет делали что все характеристики важны, и тут такое изменение, первичное вторичное третичное. Кто будет шмот и мир подстраивать?

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/63953793-abe94580-ca8a-11e9-8dd4-33effa4ef8de.png)
сделал пока так для МР

**Comment by Svjatovit** [comment]
> 
> 
> мы 20 лет делали что все характеристики важны, и тут такое изменение, первичное вторичное третичное. 

И каким образом из этого следует, что не все характеристики важны?

**Comment by joopel** [comment]
Все характеристики так и будут важны, Свент предлагает чтобы прирост от мортов был не +1 к каждому стату, а свой собственный, в зависимости от профы. Это разумно. И открывает дальнейшие пути развития для персонажей. Вижу от этого одни плюсы и появляются интересные варианты дальнейшего развития, для хаймортов. Сейчас все как штампованные

**Comment by bylins** [comment]
мр фр добавили, будут еще предложения?

**Comment by vredomir** [comment]
Первая идея довести до ума роды, т.к. в текущих реалиях бонусы смешны, поэтому почти все файтеры вятичи или древляне.

Файтеры
Северяне
Вместо аддиктивного бонуса в целых 2!!! дамрола, предлагается:
Добавление %силы от родной (например, при 50 родной силы, даем бонусом 20%, т.е. станет 60 родной дексы)
Пробивание физрестита в % от мортов (например 1% за каждый морт после 18)
Поляне
Вместо одной дексы и ускоренного регена мувов:
Добавление %ловковсти от родной (например при 50 родной ловки, даем бонусом 20%, т.е. станет 60 родной дексы)
Пробивание физрестита в % от мортов (например 1% за каждый морт после 18)
Древляне
Вместо аддиктивного бонуса в 5 удачи:
Добавление удачи от обаяния (например, 1 удача за каждые 3*20/(кол-во мортов) очка обаяния)
Бонусные сейвы от обояния (например, по 1 всех сейвов за каждые 3*20/(кол-во мортов) очка обаяния)

Кастеры
Веляне
Вместо аддитивного бонуса в 5 каста:
Добавление в % от одетого каста, с зависимостью от мортов (например на 9 морте имеем бонус в 5% к касту, на 18 10%, на 24 в 15% и т.д.)
Пробивание магрестиста по аналогии с физикой
Кривичи
Вместо аддиктивного бонуса в 25 мема:
Снижение стоимости заклинаний в % от мортов (например на 9 морте имеем снижение в 5%, на 18 10%, на 24 в 15% и т.д.)
Возможность кастить бафы и дебафы с удвоеной стоимостью и удвоеной эффективностью (напрмер групдоблесть дает 20 воли вместо 10 и длиться вдвое дольше, но при этом из мема уходит сразу 2 спелла)

Общее
Вятичи
Вместо одного тела и ускоренного регена хп
Добавление %тела от родного (например, при 50 родного тела, даем бонусом 20%, т.е. станет 60 родного тела)
Добавление всех резистов от мортов (например по 1 резисту за каждые 2 морта)

Всё кроме каста завязано на родные статы, с кастом ситуация шваховая, больше 180 каста сейчас одеть без славы смогут только несколько чаров, а в зонах типа пустошей и леса нужно минимум 200. 

Есть ещё идея ввести новый параметр, например устойчивость, и резать им весь дамаг. Соответственно выдавать пробой этого параметра только хаймортам, и во всех новых зонах использовать его.
Таким образом не будет задет текущий баланс, при этом билдеры смогут сильно затруднить жизнь нубасам.

**Comment by Svjatovit** [comment]
> "Таким образом не будет задет текущий баланс"

Ахахахоймяу. Простите, не удержался. 

> "При этом билдеры смогут сильно затруднить жизнь нубасам." 

А это актуальная задача? O, RLY? Усложнить жизнь "нубасам", а не бегемотам 20+, а то и 30+ мортов?

Извините. не хотел этого всего писать, но вынужден. Не вдаваясь в более мутные моменты, учитывайте, хотя бы, что большинство предлагаемых вами плюшек - процентные. И две трети параметров, к которым вы предлагаете их применить, имеют потолок значений. Или формулы, в которые плашки прямо не заложены, но подразумевается значение в некоторых разумных пределах. Т.е. еще десяток мортов 20+ (а такие персонажи _уже_ есть) и эти ваши статы с предлагаемыми нововведениями или вообще упрутся в планку, или приобретут значения, с которыми дальнейших их рост станет бессмысленным, потому что эффект роста будет неощутим. И мы получим ту же саму проблему на еще более высоком уровне, причем очень быстро. Доводя ситуация до абсурда, у нас будут персонажи, по которым невозможно попасть ничем, которые не получают никакого урона, даже если кто-то попасть все же умудрился, и которые сами в свою очередь чем угодно попадают по всему и убивают что угодно с одного касания.

Ладно, теперь мои предложения. Из числа тех, что _относительно_ просто реализовать, но все-таки не сводятся к добавлению (а то и удалению) 1-5 строчек кода.

1) Эрзац-престижклассы. Делается в следующем виде. На 20-21 морте у персонажа открывается выбор одной из минимум двух способностей. Способность открывает доступ к набору из 1-2 скиллов, пары спеллов и нескольких способностей, которые серьезно меняют геймплей. Подчеркиваю, это программа-минимум. При этом престиж-класс может блокировать какие-то старые фишки вообще. Чтобы новые скиллы со способностями и спеллами были востребованы, ввести новые типы дамага, спасов и резистов, которые будут только в новых зонах, и для взаимодействия с которыми и нужны будут новые абилки. Ну то есть, грубо говоря, вводим "сферу разрушения" и "сферу созидания" на выбор и стихии "изначального/конечного пламени". Нынешние спасы с резистами они не учитывают, потому заходить в зону, где мобы кидаются абилками с этими стихиями без новых фишек - прямое самоубийство. А с ними вполне нормально играется. Да, это потребует для каждого класса придумать эти престижки и воплотить. Но нужно учитывать, что скиллы/спеллы/способности можно комбинировать. Т..е. на 14 классов потребуется не 28 скиллов, а меньше, например, чернокнижникам и волхвам Велеса и Чернобога может быть доступен один и тот же скилл какой-нибудь темной магии, а различия в конкретном наборе способностей и спеллов. Доступ к новым фишкам открывается постепенно, с мортами выше 20.

2) Развить идею гривен. Для мортов выше 20 мало набрать "перевоплотиться", нужно купить право на реморт за спецвалюту, которая добывается в топ-зонах, с ивентов, турниров, из хайлевел сундуков и т.п. Можно также сделать автоквестер, которые будет такие квесты генерировать индивидуально. Без особых наворотов, просто давать задания на добывания этих валют в разных топ-зонах и на разных глобальных квестах.

3) ПвП контент для кланов. Поля боя, контроль дорог, городов и зон, то что я уже неоднократно предлагал. Подробно могу расписать, у меня где-то все это так и валяется. Ессно тоже открывать новые фишки на 20+мортах, чтоб был смысл туда стремиться.

4) Довести до ума турнирные/аренные бои с рейтингами и делением по мортам. Хочешь вонзаться в рейтингах с папками 20+ мортов - сделай эти морты.

5) Отвязать прокачку и успех работы скиллов от планки в 200 и снять планку. Ну и разумеется, проставить соответствующие резисты и спасы для актуальных на таких мортах мобов, чтоб для их пробивания нужны были скиллы 200+. Аналогично делать с базовыми статами. Поменять логику работы каста на 200+. Сейчас у нас стоит планка резистов в 300, кажется. Снять ее и сделать, что на значениях резиста выше планки, они полностью режут шанс каста и урон. А для того, чтобы поигнорировать эту жесть, нужны скиллы магии и каст 200+. 

6) Крафт. Допилить систему и в новых суперхайкомплексах выкладывать поменьше готового стафа и побольше материалов. Ну а доступ к актуальным рецептам, правильно, на 20+ мортах.

7) Ну и собсно нужны новые суперхайкомплексы, где все перечисленное будет актуально. На 20+ мортов, на 30+ мортов. Где смогут прописать по шее даже 30-мортовым бегемотам. А чтоб туда ходили - см. выше про валюты, рецепты, новые параметры.

Хватит, наверное.

**Comment by lrdx** [comment]
И уменьшить всем морты до 20 максимум!)

**Comment by vredomir** [comment]
Эрзац-престижклассы. Слишком навороченно, с учтом того что мы имеем некоторое количество нерабочих или очень труднодоступных спеллов реализовать подобное без нарушения баланса будет очень тяжело.

Покупка морта за любую валюту очень сомнительна, для хайморта добить право это уже достижение, а чтоб ещё находясь на нем что-то там добыть и не слиться это будет слишком сложно.

ПВП контент и арены. Были бы прикольны ивенты, например открывающие доступ в ту или иную локацию на неделю победившей в замесе стороне. Но с текущим дисбалансом по стафу и славе, это выглядит сомнительно. Конечно если не будет введен пвп шаблон, учитывающий только класс персонажа, которым и придется скилловать.

Автоквестеры это отличная мысль, причем давать недельные квесты в места гиблые и дневные в места попроще. Репутацию, если будет, надо привязывать на аккаунт, чтобы не приходилось каждым чаром перекачивать. И открывать продажу рецептов/реагентов/бук/напитков по достижению определенного уровня репутации.

Отвязать планку в 200 скилла это круто, но это подразумевает необходимость переделки всех апающих скиллы квестов и влияния мудры на макс скилл. И вообще почему почти у всех классов стоит ограничение на инту и мудру, хайморт файтер мог бы одевать 50+ интомудры и быстрее откачивать скиллы.

По крафту. Крафт должен быть сильным и управляемым, а не как сшить сейчас. Что из одних и тех же регов можно получить и овер и кучку говна. При этом ограничить количество экипируемых крафтов, например 3-4 стафины максимум. Причём сделать им флаг "становиться личным при одевании". Личные вещи, благодаря Ладону, теперь не проблема при црах.

По вообще стафу в зонах. 90% стафа тупо продается в магазин, ибо не нужно. Можно сделать скилл/спелл позволяющй получить реагенты для крафта, заодно это уменьшит количество мусора в магазинах и при этом не придется править старые зоны.

Суперкомплексы это конечно хорошо, но как правило, тот кто первый смог их обнести, другим жизни не даст. Тут был бы хорош опыт соседей, инстансы и создание зоны повышенной сложности. Правда, не уверен, что такое вообще можно реализовать на текущем движке.

Понимаю что кажеться тупо критикой, но пока нет конкретики, то и встречного предложения быть не может(

**Comment by Svjatovit** [comment]
1. Престиж-классы совершенно не наворочены. В плане реализации это одна из самых простых и нетребовательных идей. Могу расписать для пары классов, посмотрите. Да, конечно, для всех 14 классов кодить надо будет довольно много, но ничего принципиально нового кодить не потребуется, задача разбивается на элементарные задачки вида "добавить новый спелл". Причем тут "труднодоступные спеллы" непонятно вообще. 

2. Покупка мортов - Ок, предположим
3. ПвП ивенты, я чуток иное имел в виду, но да, это довольно мутная и навороченная задача.

4. Автоквестер _клановый_. Для кланов. И репутация (и теряется) набивается не персонажем, а кланом. 

5. Не подразумевает. Максимум в тех квестах, где нет проверки на верхнюю планку, ее надо будет добавить. Но я вообще против апания скилло выше планки на морт. Как вариант, я при переделке системы прокачки скиллов сделал бы возможность указывать замедляющуюся прокачку скилла. Т.е., прокачать скилл с 1 до 100 достаточно быстро, а вот со 100 до 120 - вдвое дольше. Хочешь - мучай мобов долго. Не хочешь - апай на квестах. Или книжки скупай.

6. По крафту у меня была своя система, на мой взгляд очень продуманная. Там именно гарантирован определенный результат, если ты добыл материал. Лучше этого результата можно получить при везении. Хуже -  нет. 

7. Инстансы да, хорошо бы, но это действительно сделать сложно и я сейчас не возьмусь. Но зоны все равно нужны. Не получится сказать "ахалай-махалай" и перекачанным чарам вдруг появится чем заняться без добавления нового контента.

**Comment by vredomir** [comment]
1. Смотри, есть спеллы круг и кампрокла, шанс добыть 2% с зоны с репопом в 90 минут и 6% с зоны с репопом 45, но там можно выхватить. Причём обладание ими, не даёт само по себе приимущества, так как надо много каста и много мудры чтобы они вообще имели смысл. Плюс есть куча заклов, типа навьих рук, зубов индрика и пр. , которые либо не дамагают, либо мемяться долго. Добавить еще пачку спеллов, которые либо будут попиться х3 где с мелким лоадом, либо будут просто бесполезны на фоне текущих, сомнительная затея.
4. Квестер должен быть для всех, сам по себе клан не приемущество, но плюшка.
5. Ок, сейчас есть куча квестов с планкой в 140-150% скилла, а то и меньше , причём требующая 29 левел, и смысл в них нулевой. Это надо приводить в соотвествие, я неоднократно говорил, что готов эти авдиевы конюшни почтистить. Но считаю важным привести все подобные квесты к единому шаблону, чтобы было удобно вносить изменения в случае подъема планки скилла.
6. Сейчас крафт реально уныл, да мышки колються, но одевают, ибо материалов много и рано или поздно выходит из говна конфетка. По мне лучше шанс залутать рецепт, который гарантирует получение статов, чем рулетка с инграми. Убил хайзону, получил рец на 4 хари на любой слот, радуйся и пляши, получил на 4 силы, плачь)
7. Я давно прошу, дайте мне зоны в которые никто не ходит, я готов их актуализировать. И ещё я за рандомстатовый стаф с квестов и мобов, чтобы условный пчёл или лёня не могли даже пытаться контролировать его.

**Comment by Svjatovit** [comment]
1. Ты упускаешь один момент. В новых суперхайлевел комплексах, как ты сам предложил, будут новые виды резистов и прочие механики, которые сделают новые абилки, включая спеллы, нужными для прохождения. Ну а чтобы они были действенными и полезными - надо соответственно их сбалансировать.
2. Еще раз, задание дается _дружине_. Не путай задание для отдельного персонажа и для дружины. Никто не мешает сделать автоквесты и для персонажей отдельно, но это уже другой вопрос.
3. Надо вообще квестовый фреймворк городить, но пока хотя бы добавить в ДГ вычисление (точней получение из кода) актуальной планки скилла на морт. И в квесты, соответственно, ее учет в квестах с апами скиллов.
4. Про крафт я уже все сказал, система, которую я предлагал, с нынешними реалиями никак не связана. Предполагалось ее вкодить, потом в ее рамках постепенно реализовывать разные виды крафта, а по мере реализации старые удалять. Но я считаю, что делать ставку на крафт, как основное занятие для хаймремов, как минимум странно.
5. Сложный разговор. Пиши в телеге - пообщаемся на эту тему.

**Comment by bylins** [comment]
3:
		else if (!str_cmp(field, "maxskill"))
		{
			sprintf(str, "%d", MIN(MAX_EXP_PERCENT + GET_REMORT(c) * 5, CAP_SKILLS));
		}

**Comment by Svjatovit** [comment]
Есть предложение пересмотреть пока врожденные фиты типа +2 дамрола и т.п., а может и некоторые изучаемые. По крайней мере те, у которых статы не имеют верхней планки. И добавить там учет мортов, потому что с мортами какие-нибудь пара дамролов или очков сейва погоду делать перестают. Раз уж нужны дешевые и сердитые плюшки от мортов.

**Comment by Svjatovit** [comment]
В общем. тему закрываю. Оюсжудение "чего бы такого сделать для хаймортов" предлагаю вести на форуме. Под доработку фитов, которые дают просто фикисрованный бонус, на хаймортах уже неощутимый, сделать отдельную задачу.
