### ISSUE TITLE
Бага в прикрыть?

### ISSUE THREAD

**Issue by bylins** [bylins/mud#546]
03-09-2019 18:55:26 Уфара дружине 'в раунд можешь прикрыть 1 раз'.
03-09-2019 18:55:37 Уфара дружине 'или прикрывать можешь от 1 моба'.
03-09-2019 18:55:41 Уфара дружине 'а не от 5 как тут'.
03-09-2019 18:55:42 Вы дружине 'а он разве больше прикрывает?'.
03-09-2019 18:55:47 Уфара дружине 'да он от всех прикрывает'.
03-09-2019 18:55:51 Уфара дружине 'бой идет заходят 5 мобов агро'.
03-09-2019 18:55:53 Вы дружине 'так это бага, 1 раз должен'.
03-09-2019 18:55:55 Уфара дружине '1 бтр от 5ых сразу прикрывает'.
03-09-2019 18:56:17 Вы дружине 'от одной атаки должен, ща посмотрю код, откуда такая фича'.
03-09-2019 18:56:24 Уфара дружине 'пока бтр не в лаге'.
03-09-2019 18:56:28 Уфара дружине 'прикрывает бесконечно'.
03-09-2019 18:56:31 Уфара дружине 'хоть 5к'.
03-09-2019 18:56:31 Тикен дружине 'от одной атаки 1 моба'.
03-09-2019 18:56:33 Уфара дружине 'мобов зайдет'.
03-09-2019 18:56:49 Тикен дружине 'зашла пачка все по одной атаке сделали батыр от всех прикрыл'.
03-09-2019 18:56:53 Тикен дружине 'по 1 атаке'.

**Comment by bylins** [comment]
if (protect)
			{
				send_to_char(vict, "Чьи-то широкие плечи помешали вам прикрыть %s.\r\n", GET_PAD(vict->get_protecting(), 3));
				continue;
			}
----
а это сообщение может существовать?

**Comment by bylins** [comment]
надо EAF_PROTECT снимать после первого попадания по прикрываемому, а не в конце раунда

**Comment by bylins** [comment]
там еще круче прикол, если не ошибаюсь прикрышка работает до конца смерти моба
void change_fighting(CHAR_DATA* ch, int need_stop)
тут чистится CLR_AF_BATTLE(k, EAF_PROTECT);

**Comment by bylins** [comment]
справка типа это подтверждает, а не абуз ли? Точнее непродуманность кода?

**Comment by vredomir** [comment]
Прикрывает до лага прикрывальщика, это не абуз, это норма, если батыры не будут прикрывать от всех желающих предъявить, то они стануть снова бесполезны.

**Comment by Nimrok** [comment]
То есть если 1 батыр перестанет в пк бою 12 на 12 снимать с колдуна(который уничтожает всех 12 за 2 раунда) по 2-3-4 файтера противника, то батыры станут снова бесполезны? Снять 1 башера/глушера с 1 кастера это уже неплохо пошатывает по-цельную тактику боя. Вводите больше активности, а то мы имеем топ ботов-батыров 26-34 мортов, которые пассивно вносят дизбаланс в бой.

**Comment by Nimrok** [comment]
В дополнение хочу сказать, что прикрыть должно вешать на богатыря агр. Это конечно очень интересная механика, когда батыр в фулсете даже цель себе не прописывает, потому что 100% уверен, что его протеже будут агрить, и он знает, что сет с него не спадет, потому что он не при делах, но надо же видеть рамки, вообще. Целенаправленное возведение одних профессий в статус мастхев и игнорирование других это не способ развития проекта.

**Comment by Svjatovit** [comment]
Частично зафикшено введением ГКД и вообще кулдаунов: тонущий в них богатырь прикрывать будет намного хуже. В принципе там еще по-хорошему сделать бы все не "на глазок", а по балансу посчитать, но это уж в рамках перебалансировки скиллов. Пока что задачу закрываю.
