### ISSUE TITLE
Мультиреск

### ISSUE THREAD

**Issue by bylins** [bylins/mud#549]
сделать чтоб при перке, и прокачанном скилле, чар рескал всех кто сагрил на согрупника

**Comment by vredomir** [comment]
Зачем перк, надо убрать вообще реск у всех кроме дружей.

**Comment by LdanDSS** [comment]
Оставить дружам (крутой со способностью), витязям (обычный как поддержка) и убрать у остальных. Кузи и охоты пусть дамагают, а бтр пусть прикрывает.
