### ISSUE TITLE
Баланс урона в группе

### ISSUE THREAD

**Issue by Nimrok** [bylins/mud#551]
Думал над темой апа витязей - чем они полезны в группе, почему их надо вообще поднимать если у них точки по 10+к и т.д. А потому что такие точки увидишь только в нескольких зонах из за пресса дамаги от группы (почти все мобы умирают раньше от кузнецов, колдунов и батыров, чем откатывается точка после вступления в бой). Вот и подошел к теме распределения урона в группе. Во первых лагеры - почему кузнецы и батыры, отвечающие за лаг мобов являются одними из первых еще и по дамаге(больше, конечно, про кузнецов)? Где в таком случае дамаг при баше, тоже ведь умение контроля. Во вторых колдуны - это вообще затычка в каждой дырке. Я хорошо представляю как легко колдуны умирают от малейшего чиха, но не слишком ли тяжелый этой проблеме сделан противовес? Не знаю как в других, но в нашей группе колдун это всегда топ1 дамаги. Ладно пве, а что происходит по кл пк: половина строчек это "%1 убит $koldun". И все это приправляется багнутой прикрышкой, которая опять же и в зонинге и в пк универсальна.
Витязь со своей точкой становится полезным в том случае, когда моба можно бить 3+ раундов. Несколько тем про чармисов тоже считаю вытекающей отсюда проблемой - ведь раньше чармисы составляли костяк дамаги. Что получается на данный момент: обязательные товарищи в группу: минимум 1 колдун, защищенный пачкой батыров, которые при этом неконтрящийся лаг всего и вся; пачка кузнецов, лагающие и уничтожающие глушами через раунд, каждый по силе как средняя точка; волш конечно без разговоров - баффы и мобильность группы; лекарь оно и понятно; кудесник нужен кинуть груп зеркало и гуляй вася. Нужны ли кому-нибудь остальные профы?) Ну берут конечно, раз уже потрачено время на раскачку. 
Урезать надо дамаги у колдунов и кузнецов, возвращать чармисам, дать мобам возможность доживать до смерти от точки.

**Comment by vredomir** [comment]
Почему все влажные мечты о любых фиксах начинаются с давайте уменьшим/отберем, где позитив? Давайте здравые предложение о том как поднять нужность классов, батыры не дамагают, их берут ради прикрышки, ок, нужны, волши накидывают обкаст, ок, нужны. Почему надо нерфить какие-то классы, вместо апа? Витязей занерфили в хлам, вот итог, бесконечное нытье про бесполезность и разрыв в 13 мортов в топе.

**Comment by Nimrok** [comment]
Как минимум потому, что нерф тех, кто выбивается позваоляет не выходить за рамки существующей системы и формул. По крайней мере мне так кажется со дна понимания этой системы и формул. Можно конечно поднимать отстающих, переписывать формулу для поднятых и так далее, но что мы имеем на данный момент - попытки поднять это введение воодушевления витязям, которое превратили в немного каста и дамролов на 1(один, one) раунд(ни в коем случае это не претензия, люди что-то делают я это ценю). Надо же быть реалистами. Привожу в пример витязей, потому что играю им.

**Comment by LdanDSS** [comment]
С учетом того что тут вовсю планируется "новый топ контент", а даже мутанты "бегемоты" вполне исправно дохнут на пзп, словенах2 , то нерфить , согласен, с vredomir не стоит. Стоит апать отстающих. Татей для группы (но не для соло!), витязей, кудесов, волхвов, дружей (чтобы у них была возможность не только танчить, но и какую то другую пользу приносить группе - например контролить входящих в клетку мобов, удерживая их от атаки, или выбивать в бой 1 на 1 запрещая кастить или триговать) и они нужны было более чем 1 штука на клан).

**Comment by Svjatovit** [comment]
Опять же, ребаланс урона конечно нужен. Но тут никакой конкретной задачи не имеется.
Народ, не пишите тут всякие абстрактные идеи и общий треп. Для этого форум "Былин" есть, в конце концов. Там и закрытый раздел для кодеров есть, куда можно доступ дать, если нужно. Issue - для конкретных задач по кодингу, не захламляйте их трепом, плз.
