### ISSUE TITLE
Смастерить диковинку[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#57]
*Originally reported by* **Polel (Bitbucket: [Polel](https://bitbucket.org/Polel), GitHub: [Polel](https://github.com/Polel))**

----------------------------------------

После обсуждения. начинаем пилить ветку смастерить диковинку  
Первая диконика - колчан  
Необходимые пункты  
1) добавить тип предмета - магический контейнер   
2) добавить возможность одевать магический контейрен под лук в свет  
3) Добавить счетчик атаки для чаров  
4) если счетчик будет атак будет достигать определенного количество должна   происходить маг атака с колчана  
5) Контейнеры изготавливают волхвы и кудесы  
6) стрелы охотник делает сам.  
7) магический урон на стрелы  
 а - из отваров  
 б - наносят маги  
 данное еще предстоить обсудить.

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/57

=======COMMENTS=======

Date: 2017-09-15T14:24:10Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

>2) добавить возможность одевать магический контейрен под лук в свет   
может всеж новый слот? за плечем?
Остальное мы вроде обсудили.

**Comment by Svjatovit** [comment]
Не пилим. Крафт - отдельная тема и по нему есть ТЗ. И даже частично код, хотя кажется автор немного неправильно меня понял и часть кода придется переделывать. Колчаны - то ладно, хотя мне идея и не нравится.
