### ISSUE TITLE
Изгнать нежить (умение)

### ISSUE THREAD

**Issue by LdanDSS** [bylins/mud#571]
Привести малоосмысленное умение "изгнать нежить" в нормальный вид.
 1 Вариант - оставить нынешний лаг от умения, но очень сильно увеличить урон (чтобы лупить им редко, но наповал). Т.е., чтобы был смысл, то урон должне быть в 3-4 раза покруче суда (с учетом задержки умения в несколько тиков).
 2 Вариант - оставить нынешний урон (или увеличить до среднего), но дать возможность спама как клич. Уникальная абилка витязя "изгоняющий нежить" тогда будет давать + к урону или более частое применение. 

Дополнительно увеличить шанс флика мобов-нежити с клетки как доп.аффект к урону. 
Провести ревизию мобов в новых зонах - зачастую мертвяки, призраки, ужасы, тени не являются нежитью - что как-то странно.

**Comment by Svjatovit** [comment]
Тень, положим, по антуражу не обязательно нежить. А в остальном да, абилка эта взята из DnD и там она может применяться эн раз в день, а при наличии фита - еще плюс сколько-то. Просто когда ее вводили не было возможности это реализовать.

**Comment by joopel** [comment]
Меня смущает наличие в маде абилки изгнать нежить, заклинаний силы света и изгнать зло. Может имеет смысл объединить это все дело в что-то одно, но юзабельное?

**Comment by LdanDSS** [comment]
Было бы неплохо, но проблема в том, что надо еще "зло" и "нежить" как то проставить монстрам у которых они не стоят.  Хорошая бы тема была наносить не только урон, но и выгонять подобных  мобов из клеток с хорошим шансом при хорошем раскаче умения. Например, применив на моба из группы, он получает урон и убегает из клетки если выживает, а остальные мобы в клетке просто получают урон.  Поможет в тошнильных зонах где надо долго ждать пока злодеи разойдутся сами.

**Comment by Svjatovit** [comment]
Взял "изгнать нежить" на переделку. Всякие там "изгнать зло" с прочими "силами светы" пусть пока лежат дальше.

**Comment by Svjatovit** [comment]
Переработал в первом приближении.
Теперь там "гашетка" с 3 зарядами, способность добавляет еще 1 заряд.
Урон изменен (и скорей всего я с ним сильно переборщил, но урезать несложно).
Кроме того, воткнуто ограничение на максимум 20 целей и суммарное количество наносимого урона (раньше было по уровню мобов).
Плюс, по приколу добавлены критфейл и критуспех. При критуспехе есть шанс убить на месте низкоуровневую нежить (уровнем ниже применяющего на 1d4), кроме того, такая цель "бесплатна", не учитывается в сумме "изгоняемых" хитов. Ну а критфейл приводит цель в ярость без нанесения урона.
