### ISSUE TITLE
новый флаг мобам !магик

### ISSUE THREAD

**Issue by joopel** [bylins/mud#572]
работает по тому же принципу как и в клетках !магик,  для разнообразия геймплея. Моб с флагом !магик, бегающий по маршруту это интересно.

Откроется множество вариантов, как с минибоссами, так и в целом, по усложнению проходных зон.

**Comment by bylins** [comment]
Можно немного костыльно
Entry триггер
eval room %self.room%
if %room.flag(нет магии)% == 1
%room.flag(-нет магии)% 
end
wait 1
eval room %self.room%
%room.flag(+нет магии)%
----------------
ну и при рипе моба снимать флаг с комнаты, сделать отладить триггер 1 раз и можно просто навешивать на нужных мобов один и тот же триггер.
Правда Свент писал что там где-то крешь зарыт, но это можно исправить, только отлаживать на зеркале.

**Comment by bylins** [comment]
проверен триггер признан рабочим
eval room %self.room%
%room.flag(-нет магии)%
wait 1
eval room %self.room%
%room.flag(+нет магии)%
