### ISSUE TITLE
при 2х неудачных попытках реализовать месть не сбрасывается флаг

### ISSUE THREAD

**Issue by ladon3434** [bylins/mud#581]
агрил клан чар на неклан чара.
мстил неклан чар дружиннику

**Comment by joopel** [comment]
Картозар до тебя добрался? ) Тестили? есть баг?

**Comment by Svjatovit** [comment]
Протестите плз, етсь баг или нет. Если есть - пофикшу.

**Comment by kartozar** [comment]
Сегодня на зеркале тестили. когда убиваю я некланового месть становится в 1 0 потом он агрил и было вначале 1 1 потом 2 1 и потом ещё третий раз он сагрил и месть была уже 3 1. тоесть не обнуляло, но при реконекте того кто агрил месть типа упала, уже не писало что я могу отомстить, а бд то ещё оставалось. но вторая попытка не обнуляла. логи должны быть на зеркале.

**Comment by kartozar** [comment]
Я б хотел показать лог, того как мести не обнулялись. лог я разместил тут:
https://pastebin.com/9GtN3cVG
тоесть было три попытки и писало уже 3 1.

**Comment by kartozar** [comment]
Так что мне ещё надо привести, чтоб данный баг поправить? Вроди б всё описал придельно точно, и доступно. Может ещё надо какие данные?

**Comment by kartozar** [comment]
Какая сетуация с фиксом бага по местям? какие данные ещё надо дать?

**Comment by bylins** [comment]
а никто не переживает кроме тебя из-а этой баги

**Comment by kartozar** [comment]
Но ведь в справке получается, что тогда написано неправдивую информацию, о том, что оно б должно обнуляться, а оно не обнуляется. Кроме того, логи собраны, информация собрана. Я ж видимо не просто собирал то всё?

**Comment by Svjatovit** [comment]
Исправлено.
