### ISSUE TITLE
Увеличение повышающего коэффициента для чармисов бризеров и изменение методика апа велета, дрекавеца и василиск

### ISSUE THREAD

**Issue by Zolfik** [bylins/mud#583]
Увеличить коэффициент расчет дамаги при чарме для бризеров с 1,1 до 1,3.
Здесь -https://github.com/bylins/mud/blob/6ce427a7758fced8809a8373c1a6260755ce7da8/src/handler.cpp
if (MOB_FLAGGED(victim, (MOB_FIREBREATH | MOB_GASBREATH | MOB_FROSTBREATH | MOB_ACIDBREATH | MOB_LIGHTBREATH)))
 	{
 		dam_per_round *= 1.1f;

Меняем принцип апа,
Велет 26-34 уровень трупа.
С 35+ уровня трупа рандомно или василиск или дрекавец.
Убираем проверку на морты при апе василиска.

**Comment by bylins** [comment]
dam_per_round *= 1.1f;  это сделал

**Comment by ladon3434** [comment]
залил реквест
