### ISSUE TITLE
лучшие прославленные

### ISSUE THREAD

**Issue by bylins** [bylins/mud#584]
показывает таблицу со старой временной славой

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/66371689-8f56fc00-e9ac-11e9-98e4-ae934010997e.png)

**Comment by bylins** [comment]
Надо бы еще скипать старых игроков, кто не входил год в игру не показывать

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/67018687-41589b80-f104-11e9-80cc-b8e5edf9ae6f.png)
надо брать имя по UID а не из конфига

**Comment by bylins** [comment]
недоделано

**Comment by ladon3434** [comment]
#604
