### ISSUE TITLE
Текущий рефакторинг

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#586]
Постоянно действующая ветка для текущего рефакторинга.
Т.е. для правок вида:
1. Неудачно названные функции, переменные и т.п.
2. Неудачная сигнатура функции.
3. Слишком большая функция, которую стоит разделить.
4. Замена макроса на функцию или переименование неудачного макроса.

И так далее. В общем, для относительно небольших правок, не меняющих логику работы в целом, но требующих нередко изменений по всему коду. Крупное переписывание целых модулей и классов стоит делать отдельными ветками.

Если что-то такое увидели и захотели поправить, исправили, смержили с мастером, потестили и залили в эту ветку. Иначе обычные коммиты уж очень захламляются такими исправлениями, а править все-таки надо.

**Comment by bylins** [comment]
Есть небольшая проблема в скакании по веткам, заново с нуля начинает пересобираться код, т.е. тратится много времени. Ветку можно завести, но и не лениться в своей ветке править.
Хотя.... кто мешает держать отдельный проект в отдельном каталоге для рефакторинга....
Так что заводим ветку

**Comment by Svjatovit** [comment]
Думаю, не лучшая была идея, лучше под рефакторинг конкретного модуля и т.п. октрывать отдельные ветки.
