### ISSUE TITLE
Спадение кличей охотов

### ISSUE THREAD

**Issue by vredomir** [bylins/mud#589]
Рандомно спадают кличи охота, пруфы:
![image](https://user-images.githubusercontent.com/51622971/65866640-d70ecf80-e37d-11e9-8e68-7d2bca699607.png)
![image](https://user-images.githubusercontent.com/51622971/65866648-daa25680-e37d-11e9-93e3-db745f4edf48.png)

**Comment by bylins** [comment]
Скрины отвратительные ничего не понятно

**Comment by vredomir** [comment]
Я фиг знает как их сделать нормальными, походу надо новые ловить, смысл такой:
1. Висит клич точности 4 часа
2. Коза кидает клич обучения, чекает афф висят 2 клича
3. Жмет груп, клич точности пропадает из аффектов

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/66138874-0df81600-e608-11e9-9831-e24eaa5c2b84.png)
![image](https://user-images.githubusercontent.com/42086238/66138901-1ea88c00-e608-11e9-9bf7-0c33013eeed0.png)

вроде все нормально

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/66139042-5f080a00-e608-11e9-8054-ceea1d203dae.png)
