### ISSUE TITLE
Предложение по "Мастеру оружия"

### ISSUE THREAD

**Issue by LdanDSS** [bylins/mud#590]
Предлагаю  придать востребованность применению разных оружейных навыков файтерами, через улучшение способности «мастер оружия» дополнительно к имеющимся сейчас бонусам:
1.	Мастер оружия двуручники. Дать шанс 1% за каждые 10% оружейного навыка совершить дополнительную атаку двуручником. Витязь, соответственно, получит либо третью дополнительную атаку (20% при 200 % навыка), либо улучшит шанс прохождения второй на указанный процент. 
2.	Мастер оружия длинные лезвия. Дать шанс 1% за каждые 2% оружейного навыка совершить парирование двух атак в раунд при применении навыка «парирование», либо отбить на 2 атаки больше при применении навыка «веерная защита». Применяется только в дуале, если хотябы одно оружие являеется длинным лезвием.
3.	Мастер оружия короткие лезвия. Дать шанс 1% за каждые 10% оружейного навыка совершить дополнительную атаку коротким лезвием. Если персонаж вооружен коротким лезвием в каждой руке, то данный шанс прокает два раза. (например при 200% коротких лезвий и 95% атаки левой рукой, мастер оружия короткие лезвия с двумя короткими может совершить 4 атаки : прайм , офф , 20% доп с прайма, 20% доп с оффа, если прошла атака с оффа).
4.	Мастер оружия копья и рогатины. Значительно увеличить шанс прохождения метких попаданий в зависимости от оружейного навыка.
5.	Мастер оружия палицы и дубины. В целях расчета успеха применений способностей «оглушение», «точный стиль» мастер оружия вооруженный указанным видом оружия, имеет +1 вес оружия за каждые 20% боевого навыка (т.е. дубина в руках мастера оружия с навыком палиц 200% будет иметь +10 к весу при расчете оглушения или точки с нее). 
6.	Мастер оружия проникающее. За каждые 20% оружейного навыка, атака проником не будет учитывать 5 поглощения и 5 брони цели, а также незначительно (но выше по сравнению с имеющимся шансом) увеличит шанс прохождения метких попаданий в зависимости от оружейного навыка.
7.	Мастер оружия топоры и секиры.  Увеличить на 1% за каждые 2% оружейного навыка урон от метких попаданий (но шанс прохождения метких попаданий остается неизменным).
8.	Мастер оружия луки.  За каждые 10% оружейного навыка, атака луком или самострелом, если его держат в обеих руках, не будет учитывать 1 физ.резист цели.
9.	Мастер оружия иное оружие. С шансом 1% за каждые 10% оружейного навыка атака иными оружием может дезориентировать офигевшую от того, что она атакована такой херней цель. Дезориентация на 1 раунд запрещает цели колдовать и бризить, и снижает на 50% урон от всех физ.атак в этом раунде.

10. Мастер оружия кулачный бой.  С шансом 1% за каждые 20% оружейного навыка атака сражающийся без оружия может попытаться обезоружить цель безлаговым эффектом попавшей по противнику атаки (цель резистит как от обезоруживания, равного 2/3 уровня оружейного навыка или полного навыка обезоруживания). Если противник не вооружен, то есть шанс сбить ее с ног (цель резиситит как от умения "сбить" равного 2/3 уровня оружейного навыка)

Возможно, стоит разрешить иметь персонажу только одного мастера оружия, а дружам двух.

**Comment by Svjatovit** [comment]
Мастеров конечно нужно переделывать, но предлагаемое не подойдет. 
Во-первых, почти все бонусы предлагаются в процентах. Т.е. при 200% скилла бонус в 1% шанса за 20% скилла упрется в планку 100%. А эти 200% достигаются уже на 24 мортах, что по нынешнем меркам не особо и много. Механики нужны совершенно иные.
Во-вторых, уже планируется серьезная переделка системы скиллов и фитов, и предлагаемое на запланированное ложится примерно никак.

За идею спасибо, но в таком виде, увы, не получится.
