### ISSUE TITLE
Составление списков персонажей для масскастов и т.п.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#594]
Пересмотреть логику работы масскастов, ареакастов, того же "изгнать нежить", групкастов и т.д. Сейчас в коде минимум четыре места (уверен, что если поискать - найдутся еще), где врукопашную составляется временный список персонажей, с которыми потом что-то делается. Каждый раз дублируется код на "это не имм", "мы (не) в одной группе" и так далее.

Привести все к одному знаменателю, вынести, куда это логичней всего.

**Comment by bylins** [comment]
Ага, еще и массивы сообщений масс ареа групп были разбиты на 3 функции, хотя выборка идет по номеру закла, я офигел когда очередной раз закл добавлял. Может конечно было сделано так как case когда-то максимум 127 штук можно было

**Comment by Svjatovit** [comment]
В первом приближении сделано.
По хорошему, там еще много чего можно напилить и допилить, но это про весь код можно сказать.
