### ISSUE TITLE
бага в описании способности

### ISSUE THREAD

**Issue by bylins** [bylins/mud#601]
![image](https://user-images.githubusercontent.com/42086238/66931601-03de0a80-f03f-11e9-85ba-3cae312f0a68.png)
а реально она на 8м слоту, опять пресловутая привычка, что в коде от 0 а в миру от 1

**Comment by Svjatovit** [comment]
Это не баг. Просто в файле нумерация идет с нуля, как и в коде. А игрокам показывается на слот выше, чтобы нумерация была с единицы.
