### ISSUE TITLE
Не спадает бой при агре в замке

### ISSUE THREAD

**Issue by vredomir** [bylins/mud#603]
Сварн сагрил Козьку в замке, после чего Сварна выкинуло из замка, а Коза остался в бою. Рекол не помогал, засумонили иммом на арену и там грохнули, это помогло)
![image](https://user-images.githubusercontent.com/51622971/67091254-d9ae5900-f1b4-11e9-8c4d-a5e17479181b.png)
![image](https://user-images.githubusercontent.com/51622971/67091266-dfa43a00-f1b4-11e9-996d-514b09d832e7.png)

**Comment by bylins** [comment]
я же вроде исправил это
