### ISSUE TITLE
Переключаемый точный стиль

### ISSUE THREAD

**Issue by Nimrok** [bylins/mud#607]
Дать возможность витязям переключать стили боя между Точным и, например, Боевым. Точный стиль концентрирует урон по одному мобу, а второй стиль будет бить по площади в клетке, но уже слабее. Почему это интересно - схожая механика заклинаний по площади появится у файтера, а не у очередного кастера. Почему это не читерство - потому что в отличие от заклинаний уничтожающих все живое Стиль работает очень рандомно, и ждать его можно десятки раундов.

**Comment by ReynirOddmarson** [comment]
Я правильно тебя понял -
в точном ты сконцентрирован на вывод из строя и крит поражении моба, а в боевом ты можешь начать махать двуручником над головой и отрубить 5 мобам руки?

**Comment by Svjatovit** [comment]
С идеями - на форум. Сюда только готовые таски.
