### ISSUE TITLE
Предложение по апу Волхвов

### ISSUE THREAD

**Issue by LdanDSS** [bylins/mud#608]
Волхв - это такой кастер, который в теории может много, но все это делает недостаточно хорошо, усугубляя тем, что ему кроме кастерской одежке нужен дополнительный геммор по рунам. 

Соответственно его роль саппортера прекрасно размывается другими кастерами (волш (обкаст, печать)+колд (пента, фраги), да к тому же он имеет ограниченный запас зарядов.

Предложение апнуть волхва следующим образом.
1. Ввести способность Мастер рун. Начиная с 3-го круга способностей волхв может выучив эту способность (к примеру будет награждать волхв за фул проход прадуба), выбрать одну руну, которую он исключает из применения каста, но при этом хотя бы одна руна в касте должна остаться (т.е. складываем руну А+В+С для каста и у нас есть Мастер рун на руну В и С, соответственно руна А у нас должна быть в инвентаре).  Это даст волхву более комфортную игру, а также сделает смысл в его мортах - больше способностей - больше усвоенных рун.

2. Ввести умение, которое пассивно режет дамаг от бриза. Это незанятая ниша и довольно востребовано в новых зонах, поэтому раскачанный волхв, который умеет снижать урон от бриза всей группе (например по 1% за каждые 2 % умения) заставит многих лидеров брать волхвов в зоны, где могут люто бризить.

**Comment by ReynirOddmarson** [comment]
Вот список моих способностей на 26 уровне (21 реморт)

спос
Вы обладаете следующими способностями :
 1 )       напарник
 2 )       тяжеловоз
 3 )       жонглер
 4 )       толкователь рун
 5 )       тайные руны
 6 )       заветные руны
 7 )       руны богов
 8 )       десяцкий
 9 )       [пусто]

Врожденные способности :
          выносливость
          быстрое заживление
          боевое колдовство
          знак чародея
          травник
          использование амулетов
          запасливость


к сожалению места у меня для новых способностей считай нет, надо думать что-то еще.
Я бы вообще как-то минимизировал то, что я ношу в руках (пока не знаю как).
По поводу скилла очень даже интересно.

**Comment by LdanDSS** [comment]
Новая способность        : за каждые 4 перевоплощения  сделать, например. 20 мортов +4 способности и -4 руны для самых используемых заклинаний уже неплохо.

**Comment by ReynirOddmarson** [comment]
Я даже согласен на квест, который бы вбивал определённую руну в память на весь морт что-то в этом роде.

**Comment by Svjatovit** [comment]
На форум, все на форум!
ЗЫ: волхвов тоже надо перерабатывать, идеи есть.
