### ISSUE TITLE
Воодушевление витязя

### ISSUE THREAD

**Issue by bylins** [bylins/mud#622]
сделать:
1) вылечивает ХП всей группе от 150 до 350
2) увеличивает сейвы (воля, реакция, стойкость, здоровье и так далее) в разбеге 5 - 25 (на пять раундов)
3) увеличивает поглоту/броню в разбеге 5/5 - 25/25 (на пять раундов)
4) увеличивает хитроллы/дамроллы с разбегом 5/5 - 20-20 (на пять раундов)
5) рандомно закрывает весь мем у случайного кастера в группе (включая витязя и купца)
6) увеличивает каст/мем у случайного кастера в группе (включая витязя и купца) (на три раунда)
7) увеличивает резист к школам  магии в разбеге 5 - 25 (на пять раундов)
цифры условные

**Comment by LdanDSS** [comment]
Прежде всего надо помнить, что воодушевление это эффект точки, а абсолютное большинство точек это как правило 5-7 раунд боя (3 раунда лаг от агра + ждать пока сработает). Следовательно:
1. Лечение хорошая тема. Действительно может на хай энде может вытащить группу, если что - то пошло не так и сложный бой затянулся. Для соло / малых групп витязь также будет намного более полезен.
2. Сейва выглядят сомнительно. Если группу нагибают, то сейва на 5-7 раунде боя, думаю, особо не помогут.
3. Аналогично п.2
4. Хорошая тема, но разве хитролы кому-то еще нужны ? Лучше + много дамов, либо снижение физ/маг резиста моба, к примеру. Тут еще надо помнить, что жирные и опасные мобы где нужны дамролы на группу, чтобы как можно быстрее его заковырять, как правило !точка, и эффект не будет иметь шанса сработать. Остальные мобы итак умирают быстрее 3-х раундов, либо убиваются без всяких дамролов теми же крит  точками.
5. Хорошо для минигоп без топ.стафа/мортов. Для хай энд контента - бесполезно.
6. Аналогично п.5.
7. Хорошо, если действительно резист будет мощный, такой чтобы перевернуть ход сложного боя. Перспективная тема может быть.

**Comment by LdanDSS** [comment]
Хорошим вариантом еще будет снятие дебафов с группы (слепоты, холдов итп)

**Comment by Dagomir1** [comment]
Снятие дебафов было в первой версии.
Ещё надо давать с точки облако стрел витязю

**Comment by bylins** [comment]
могу диспелл кастовать, можно прикрутить умение "лечить" только его перделать придется на без мессаг

**Comment by Dagomir1** [comment]
Диспелл с точки прикрутить к уровню скилла "лечить" + способность
Лечить 50% - воодушевление с шансом снимает дебаф у одного
Лечить 100% - снимает дебаф у всей группы
150% - снимает дебаф у группы + одного лечит
200% - снимает дебаф + гх

**Comment by bylins** [comment]
диспелл снимает не только дебафы но и бафы

**Comment by Dagomir1** [comment]
Бонус к урону от воодушевления привязать к способности мощная и улучшенная мощная атаки
Без способности - 20 урона
Мощная атака - 40 урона
Улучшенная мощная атака - 60 урона

**Comment by Dagomir1** [comment]
Сейвы от воодушевления
Выучил деревянную кожу - бонус от воодушевления к резистам
Выучил силу воли - бонус к воли
И так далее

**Comment by Dagomir1** [comment]
Подитог
1. Лечение/снятие дебафов
минимальный эффект - снятие дебафа с витязя
максимальный эффект - снятие дебафов со всей группы + ГХ

Скилл лечить - эффект
Нет лечить - снимает дебафф с витязя
Лечить 10% - снимает дебафф с витязя или с одного из согрупников + с одного из согрупников
Лечить 20% - снимает дебаф с витязя + с двух согрупников
Лечить 30% - снимает дебаф с витязя + с трёх согрупников
Лечить 40% - снимает дебаф с витязя + с четырёх согрупников
Лечить 50% - снимает дебаф с витязя + с пяти согрупников
Лечить 60% - снимает дебаф с витязя + с шести согрупников
Лечить 70% - снимает дебаф с витязя + с семи согрупников
Лечить 80% - снимает дебаф с витязя + с восьми согрупников
Лечить 90% - снимает дебаф с витязя + с девяти согрупников
Лечить 100% - снимает дебаф с витязя + с десяти согрупников + случайный ХИЛ на одного 
Лечить 110% - снимает со всей группы + хил на витязя + случайный ХИЛ на двух + снимает дебаф с чармисов
Лечить 120% - снимает со всей группы + хил на витязя + случайный ХИЛ на трёх + снимает дебаф с чармисов
Лечить 130% - снимает со всей группы + хил на витязя +случайный ХИЛ на четырёх + снимает дебаф с чармисов
Лечить 140% - снимает со всей группы + хил на витязя +случайный ХИЛ на пятерых + снимает дебаф с чармисов
Лечить 150% - снимает со всей группы + хил на витязя +случайный ХИЛ на шестерых + снимает дебаф с чармисов
Лечить 160% - снимает со всей группы + хил на витязя + случайный ХИЛ на семерых + снимает дебаф с чармисов
Лечить 170% - снимает со всей группы + хил на витязя +случайный ХИЛ на восьмерых + снимает дебаф с чармисов
Лечить 180% - снимает со всей группы + хил на витязя + случайный ХИЛ на девятерых + снимает дебаф с чармисов
Лечить 190% - снимает со всей группы + хил на витязя +случайный ХИЛ на десятерых + снимает дебаф с чармисов
Лечить 200% - снимает со всей группы + хил на витязя + ГХ + снимает дебаф с чармисов

дальше буду дополнять

увеличивает сейвы (воля, реакция, стойкость, здоровье и так далее) в разбеге 5 - 25 (на пять раундов)
увеличивает поглоту/броню в разбеге 5/5 - 25/25 (на пять раундов)
увеличивает хитроллы/дамроллы с разбегом 5/5 - 20-20 (на пять раундов)
рандомно закрывает весь мем у случайного кастера в группе (включая витязя и купца)
увеличивает каст/мем у случайного кастера в группе (включая витязя и купца) (на три раунда)
увеличивает резист к школам магии в разбеге 5 - 25 (на пять раундов)
цифры условные

**Comment by Dagomir1** [comment]
Увеличение сейвов всей группе
по умолчания + 10 на все сейвы
способность деревянная кожа - 10 на все сейвы + 20 к МР
выучил силу духа - 10 на все сейвы + 20 к воле
выучил мгновенную реакцию - 10 на все сейвы + 20 к реакции
-------------
деревянная кожа + сила духа + мгновенная реакция - 20 к МР + 20 к воле + 20 к реакции
точный стиль	- прибавка к резистам
10%	-	1
20%	-	3
30%	-	5
40%	-	7
50%	-	9
60%	-	11
70%	-	13
80%	-	15
90%	-	17
100%	-	19
110%	-	21
120%	-	23
130%	-	25
140%	-	27
150%	-	29
160%	-	31
170%	-	33
180%	-	35
190%	-	37
200%	-	39

**Comment by Dagomir1** [comment]
Увеличение урона у согрупников
без способностей		
точный стиль	-	прибавка к урону
10%	-	1
20%	-	2
30%	-	3
40%	-	4
50%	-	5
60%	-	6
70%	-	7
80%	-	8
90%	-	9
100%	-	10
110%	-	11
120%	-	12
130%	-	13
140%	-	14
150%	-	15
160%	-	16
170%	-	17
180%	-	18
190%	-	19
200%	-	20

Способность "мощная атака"
точный стиль	-	прибавка к урону
10%	-	1
20%	-	3
30%	-	5
40%	-	7
50%	-	9
60%	-	11
70%	-	13
80%	-	15
90%	-	17
100%	-	19
110%	-	21
120%	-	23
130%	-	25
140%	-	27
150%	-	29
160%	-	31
170%	-	33
180%	-	35
190%	-	37
200%	-	39

Способность улучшенная мощная атака
точный стиль	-	прибавка к урону
10%	-	1
20%	-	4
30%	-	7
40%	-	10
50%	-	13
60%	-	16
70%	-	19
80%	-	22
90%	-	25
100%	-	28
110%	-	31
120%	-	34
130%	-	37
140%	-	40
150%	-	43
160%	-	46
170%	-	49
180%	-	52
190%	-	55
200%	-	58

**Comment by Dagomir1** [comment]
Три направления бафов: хп/хил, урон, сейвы
Под каждое направление способсности/скиллы
Хп/хил – надо качать «лечение»
Урон – надо учить «мощная атака» и «улучшенная мощная атака»
Сейвы – нужны «деревянная кожа», сила духа, деревянная кожа, мгновенная реакция

Шанс срабатывания бафа зависит от уровня прокачки «точный стиль»
точный стиль	Шанс срабатывания
10%	1
20%	5
30%	9
40%	13
50%	17
60%	21
70%	25
80%	29
90%	33
100%	37
110%	41
120%	45
130%	49
140%	53
150%	57
160%	61
170%	65
180%	69
190%	73
200%	77

Дальше кидаем кубик и выбираем какой именно баф получим

ХИЛ
Считается по формуле: % точного стиля*базовая прибавка*лечить+базовая прибавка
=B5*C5*A5+B5

A	B	C	Итого
точный стиль	Базовая прибавка	Лечить	ХП
10%	50	5%	50,25
20%	75	10%	76,5
30%	100	15%	104,5
40%	125	20%	135
50%	150	25%	168,75
60%	175	30%	206,5
70%	200	35%	249
80%	225	40%	297
90%	250	45%	351,25
100%	275	50%	412,5
110%	300	55%	481,5
120%	325	60%	559
130%	350	65%	645,75
140%	375	70%	742,5
150%	400	75%	850
160%	425	80%	969
170%	450	85%	1100,25
180%	475	90%	1244,5
190%	500	95%	1402,5
200%	525	100%	1575

**Comment by Dagomir1** [comment]
Хил баф от воодушевления

Описание: при воодушевлении есть шанс излечить группу или случайного согрупника, если витязь бегает в соло, то "ГХ" меняем на "ХИЛ", а "ХИЛ" меняем на "крит.исцеление"

При срабатывании смотрим на уровень владения умением "точный стиль", далее смотрим на уровень владения умения "лечить", следом проверяем в откате или нет "лечить"
Если точка на уровне 200%, а лечить 100%, то выбираем строчку "среднее значение" 150%


точный 			стиль | Лечить | Среднее 			значение | Лечить 			в откате | Лечить не в откате
-- | -- | -- | -- | --
10% | 10% | 10% | Групповое 			легкое исцеление | Легкое исцеление
20% | 20% | 20% | Групповое 			легкое исцеление | Легкое исцеление
30% | 30% | 30% | Групповое 			легкое исцеление | Легкое исцеление
40% | 40% | 40% | Групповое 			легкое исцеление | Легкое исцеление
50% | 50% | 50% | Групповое 			легкое исцеление | Легкое исцеление
60% | 60% | 60% | Групповое 			серьёзное исцеление | серьёзное исцеление
70% | 70% | 70% | Групповое 			серьёзное исцеление | серьёзное исцеление
80% | 80% | 80% | Групповое 			серьёзное исцеление | серьёзное исцеление
90% | 90% | 90% | Групповое 			серьёзное исцеление | серьёзное исцеление
100% | 100% | 100% | Групповое 			серьёзное исцеление | серьёзное исцеление
110% | 110% | 110% | Групповое 			критическое исцеление | критическое исцеление
120% | 120% | 120% | Групповое 			критическое исцеление | критическое исцеление
130% | 130% | 130% | Групповое 			критическое исцеление | критическое исцеление
140% | 140% | 140% | Групповое 			критическое исцеление | критическое исцеление
150% | 150% | 150% | Групповое 			критическое исцеление | критическое исцеление
160% | 160% | 160% | Групповое 			критическое исцеление | критическое исцеление
170% | 170% | 170% | ГХ | ХИЛ
180% | 180% | 180% | ГХ | ХИЛ
190% | 190% | 190% | ГХ | ХИЛ
200% | 200% | 200% | ГХ | ХИЛ

**Comment by Dagomir1** [comment]
Баф на сейвы - длительность на пять боевых раундов (не тиков, а раундов)

Даёт бонус к ФР и МР, это позволит пережить массовые скиллы или самон

Если у витязя выучена способность, то баф даёт дополнительно:
Мгновенная реакция — баф даёт +20 к реакции
Сила духа — баф даёт + 20 к воле, стойкости и здоровью
Деревянная кожа — баф даёт +20 к защите от каждой школы магии
Боевой дух — баф даёт +20 к удаче и инициативе

Точный 			стиль | МР | ФР
-- | -- | --
10% | 1 | 1
20% | 2 | 3
30% | 3 | 5
40% | 4 | 7
50% | 5 | 9
60% | 6 | 11
70% | 7 | 13
80% | 8 | 15
90% | 9 | 17
100% | 10 | 19
110% | 11 | 21
120% | 12 | 23
130% | 13 | 25
140% | 14 | 27
150% | 15 | 29
160% | 16 | 31
170% | 17 | 33
180% | 18 | 35
190% | 19 | 37
200% | 20 | 39

**Comment by Dagomir1** [comment]
Баф на урон/каст — длительность три боевых раундов (не тиков, а раундов)

Даёт бонус к урону и касту

Если у витязя выучена и включена способность:
Мощная атака — длительность бафа увеличивается на один раунд и действует четыре боевых раунда
Улучшенная мощная атака — длительность бафа увеличивается на два раунд и действует пять боевых раундов


Точный 			стиль | УРОН | КАСТ
-- | -- | --
10% | 5 | 1
20% | 10 | 3
30% | 15 | 5
40% | 20 | 7
50% | 25 | 9
60% | 30 | 11
70% | 35 | 13
80% | 40 | 15
90% | 45 | 17
100% | 50 | 19
110% | 55 | 21
120% | 60 | 23
130% | 65 | 25
140% | 70 | 27
150% | 75 | 29
160% | 80 | 31
170% | 85 | 33
180% | 90 | 35
190% | 95 | 37
200% | 100 | 39

**Comment by ReynirOddmarson** [comment]
Я влезу, хоть и не витязь.
Вот скажите мне зачем СЕЙВЫ на уже заточканного моба?
Я бы добавил с воодушевления +МАГ.УРОН +ФИЗ.УРОН на группу.
Это и рпшней и всяко нужней и адекватней.

**Comment by ReynirOddmarson** [comment]
Представьте себе воодушевившуюся в бою группу получающую СЕЙВЫ - бред же;)
Воодушевление само по себе это порыв, стремление как можно быстрее надрать задницу Кощще-Великано-Змеям всяким.

**Comment by bylins** [comment]
у нас нет бонусов на магурон, я недавно сделал клич оозота, _ физурон, он есть, но это аналогично + дамролы почти

**Comment by bylins** [comment]
я согласен с выше пишущим, надо улучшать свои параметры, именно воодушевил, резисты тут не каким раком, и не надо приводить дружа с "кличами"

**Comment by bylins** [comment]
PS, дага выбор случайного из группы я сделал

**Comment by bylins** [comment]
Кстати, у нас так и умирают задачи, бред несут, потому никто не делает.................

**Comment by bylins** [comment]
Кто обобщит вышесказанное?
защиту от воодушевления: мне не нравится
жду список бонусов воодушевления, могу кидать на группу могу теперь на случайного чара в группе

**Comment by Dagomir1** [comment]
Так я же расписал три типа - урон, сейвы, хп. 
А что вы сейвы так критикуете? 
Я против кнопки "убить цель", воодушевление на сейвы должно сильно увеличивать выживаемость группы. 
И кстати не каждый моб после точки в ауте.

**Comment by ReynirOddmarson** [comment]
Андрей, но увеличение маг.урона же бывает на сетах? разве нельзя его к плюшкам прикрутить? про резисты совершенно согласен - воодушевление это боевой порыв - группа не защищается, а окрыляется и начинает наваливать еще сильней, чем до этого.

**Comment by LdanDSS** [comment]
Воодушевление на дамролы и на хилы норм. Остальное лишнее имхо.
Надо воодушевлялку отвязаться от прохождения точки как таковой. Витязя не берут, потому что половина зон с флагами !точка.  Ну сделаем воодушевление, но если из за флагов заточить не получится вообще, то какой в этом всем смысл ?

**Comment by Dagomir1** [comment]
Фишка с сейвами для того, чтобы группа могла несколько раундов выдохнуть.
Возможно ли для мобов !точка оставить точку, но убрать с неё урон? Чтобы воодушевление срабатывало

**Comment by Svjatovit** [comment]
ИМХО, вы _очень_ зря повесили это снова на точку, которая пассивный скилл. Тупо стоишь и ждешь, пока не выпадет. Витязю нужна какая-то дополнительная механика, можено и с таким эффектом.

**Comment by Dagomir1** [comment]
Моя цель - сделать воодушевление полезным.
Если эти бонусы вешать на активные скиллы, то получим очередную пачку "кличей"

**Comment by Dagomir1** [comment]
Под итог:
1. Воодушевление на урон
Прибавка идёт к урону в процентах, количество ремортов = процент прибавки
длительность 3 раунда

2. Каст/мем
Прибавка идёт к урону в процентах, количество ремортов = процент прибавки
Каст длительность 3 раунда
Мем длительность 10 раундов

3. ГХ

**Comment by LdanDSS** [comment]
И чтобы 

> Под итог:
> 
> 1. Воодушевление на урон
>    Прибавка идёт к урону в процентах, количество ремортов = процент прибавки
>    длительность 3 раунда
> 2. Каст/мем
>    Прибавка идёт к урону в процентах, количество ремортов = процент прибавки
>    Каст длительность 3 раунда
>    Мем длительность 10 раундов
> 3. ГХ

И , чтобы это работало, надо разобраться с флагом !точка, так, чтобы он запрещал прохождение спец аффектов (из строя, итп), крит урона, но не трогал воодушевление.

**Comment by bylins** [comment]
вообще-то флаг MOB_NOTKILLPUNCTUAL !убить.точным.стилем был введен против ваншота точным, потом его переделал кто-то вообще ан "не работает точка" но хорошо, переведу воодушевление выше проверки

**Comment by joopel** [comment]
Против пункта 3. ГХ - причина очевидна. Витязь сможет в соло зонить 99% зон тупо себя захиливая. Точка выводящая из строя срабатывает довольно часто, это станет зачастую заменой груп хила от клера. 

Если витязь в группе и члены группы стоят в одной клетке с ним вместо пункта 3. Давайте сделаем груп крит или рандомние применение умения лечить на согрупника. Что собственно и обсуждалось ранее. Откуда у вас ГХ взялся мне в принципе не понятно. Лекори чтоли?

**Comment by Dagomir1** [comment]
Заменой х Лера витязь в группе не станет никогда.
Сначала надо дождаться, когда выпадет точка - сколько там шанс? 
Дальше нужно, чтобы воодушевление прошло - два. 
И вишенка - только 30% шанс, что выпадет ГХ.
Считаем все проценты и выходит совсем маленький шанс. 
Это я как витязь говорю.

**Comment by bylins** [comment]
Баги:
если моб точит группу игроков, он ее воодушевляет каким-то раком

**Comment by joopel** [comment]
Воодушевление у витязя часто срабатывает даже если не было точки и даже по мобам с флагом !точка.

**Comment by bylins** [comment]
по мобам с фагом !точка сделано специально, корявые воодушевлялки (лишние) вроде исправил
