### ISSUE TITLE
Флаг "спамер" для игроков.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#633]
Проставляется имморталом, игроку не отображается.
При наличии флага сообщения, отправленные в каналы "орать/болтать/оффтоп" отображаются как обычно владельцу флага, со всеми сопутствующими эффектами, но другие пользователи не видят этих сообщений.

(Канал "кричать", считаю, трогать не нужно, его используют, чтобы проверить, есть ли кто в зоне и т.п.)

**Comment by bylins** [comment]
пока не снимут? или как муть - таймер?

**Comment by joopel** [comment]
давай как аналог mute

**Comment by Svjatovit** [comment]
Пока не снимут. Хотя бы потому что если делать "как муть" придется обходить показ наказания в счете игроку. А смысл именно в том чтоб игрок как можно дольше не знал об этом.

**Comment by joopel** [comment]
согласен, значит флагом

**Comment by bylins** [comment]
do_score_all написан так по дурацки, что ничего обходить не надо, чтоб увидеть наказание в нем, надо добавить секцию.
Но без таймера мне будет проще конечно писать :)

**Comment by lrdx** [comment]
а зачем это?

**Comment by bylins** [comment]
Ты не видел что творится в маде когда у "Могуты" сносит крышу, Почти все вежливо но хрень несет полную, и еще и нубам помогает, как "гуру" отвратными советами

**Comment by Svjatovit** [comment]
Реализовано, залито.
