### ISSUE TITLE
Добавить мобам защиту от магии тьмы.

### ISSUE THREAD

**Issue by joopel** [bylins/mud#643]
Добавлять по тому же принципу как проставлялись мобам резисты, у которых их раньше не было.

Прошу сюда написать формулу, не могу найти по которой проставлялось. Доработаю ее, лиибо напишу свою, если ее нет.

**Comment by bylins** [comment]
так я сделал вроде в олц это, проверь и закрой

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/70540017-8b468680-1b75-11ea-91b3-47c1a2cc6b61.png)
есть такое в коде

**Comment by joopel** [comment]
if (уровень моба>27 && !защита_магии_тьмы)
защита_магии_тьмы = (уровень_моба/2)

То есть моб 28 уровня будет иметь резист от магии тьмы 14, а моб 40 уровня 20.

**Comment by joopel** [comment]
После тестов на свежей локалки, пришел к выводу предыдущая формула даст сильный резист, что  убьет топ заклы, более мягкий вариант:

**if (уровень моба>30 && !защита_магии_тьмы)
защита_магии_тьмы = int((уровень_моба-30)/1.3)+5**

То есть моб 31 уровня будет иметь резист от магии тьмы 5, 
моб 38 уровн - 11, моб 44 уровня 16, а моб 50 уровня 20.
