### ISSUE TITLE
Ввести флаг "без номеров" для зоны - скрываем внумы клеток.

### ISSUE THREAD

**Issue by joopel** [bylins/mud#644]
Сделать возможность в OLC поставить флаг "без номеров" или "!маппер" или "лабиринт", название не принципиально. У игроков в зоне с этим флагом не должны отображаться номера клеток.

Реализовать думаю можно через тип зоны.

**Comment by bylins** [comment]
закрываю? дополнений не будет?

**Comment by bylins** [comment]
добавлений нет? закрываю
