### ISSUE TITLE
Таблица стандартных чармисов кудесам.

### ISSUE THREAD

**Issue by joopel** [bylins/mud#646]
Клонируем стандартных чармисов из городов и зон в зону 2010, в ней будет таблица стандартных чармисов, там где имя чармис типа лихо, предлагаю переименовать во что-то нейтральное. Также расширить таблицу новыми элитными чармисами, допустим с 40 внума.

Стандартных чармисов десантируем по городам, через тригер. 2-3 элитных также десантируем по городам, остальных раскидывем по топ зонам, в клетки мирка или !мобы.

https://github.com/bylins/mud/files/3480533/Charmis.xlsx - формула распределения "поднимаего веса" от хари и мортов, у черноков и кудесов они одинаковы

**Comment by Svjatovit** [comment]
А зачем в 2010? В двадцатой зоне уже есть чармисы куп. Можно последние 50 номеров отдать под чармисов кудесов. Или вообще начать с 2099, а там сколько понадобится. Вам 50 стандартных чармисов не хватит? Тогда со стандартом чет не так.

**Comment by Svjatovit** [comment]
Кудесов, конечно, переделывать надо, может и через стандартных чармисов в том числе, но это чет не то. Да и к кодингу отношения особо не имеет. Закрываю.
