### ISSUE TITLE
скиллы магии

### ISSUE THREAD

**Issue by bylins** [bylins/mud#660]
![image](https://user-images.githubusercontent.com/42086238/71762297-b4410980-2ede-11ea-947e-a2a352dcec2b.png)
и как они выше 200 стали?

**Comment by Svjatovit** [comment]
if ((trained_skill <= 0 || trained_skill >= CAP_SKILLS) && !is_magic_skill(skill_no))

А код не запрещает магические скиллы качать выше 200. У них потолок вообще в 1000 выставлен.

**Comment by Svjatovit** [comment]
В общем, это не баг. Надо ли все скиллы резать по планке в 200 — уже другой вопрос.
