### ISSUE TITLE
Ошибка с экспой при множественных рипах

### ISSUE THREAD

**Issue by bylins** [bylins/mud#665]
![image](https://user-images.githubusercontent.com/42086238/72960674-ac7ad380-3dbf-11ea-872b-4da2db034546.png)

**Comment by bylins** [comment]
походу просто расширить табличку

**Comment by bylins** [comment]
13 мортов
![image](https://user-images.githubusercontent.com/42086238/72977613-e9f25780-3de5-11ea-85bc-8291b6500e50.png)
вообще-то там
unsigned long long Exp_mob_this    как бы должно было хватить по любому

**Comment by lrdx** [comment]
поэтому и говорю, что ошибка - столько экспы невозможно потерять ) с другой стороны сейчас все равно уже не определить - число сохраняется полностью, скорее всего был баг в какой-то момент с начислением экспы

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/72984582-1a8dbd80-3df5-11ea-8909-c11b19d4894c.png)
вот скрин с примерно таким же количеством рипов все ок

**Comment by Svjatovit** [comment]
Кмк какой-то одиночный глюк, мб из-за кривого начисления опыта. Можно пока задачу закрыть, будет повторяться — открыть снова.
