### ISSUE TITLE
Ангел-хранитель

### ISSUE THREAD

**Issue by bylins** [bylins/mud#667]
![image](https://user-images.githubusercontent.com/42086238/72996211-621f4400-3e0b-11ea-9cb1-dcee6043a776.png)
почему 2 раза то?

**Comment by bylins** [comment]
любой чармис почему-то так
![image](https://user-images.githubusercontent.com/42086238/72997062-cdb5e100-3e0c-11ea-8664-fdf494449eb5.png)

**Comment by bylins** [comment]
if (affect->type == SPELL_CHARM && !charmed_msg && affect->duration == 1)
![image](https://user-images.githubusercontent.com/42086238/72999487-7f0a4600-3e10-11ea-89e6-fad22a68e89b.png)
исправилось почему не понимаю

**Comment by bylins** [comment]
чот мне подсказывает что это только у имма 2 раза кидает, проверяю

**Comment by bylins** [comment]
да, только у имма, а у него -1 
					affect->duration = -1;	// GODS - unlimited

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/73003091-16be6300-3e16-11ea-8499-dc65f0f6deac.png)
у мортала

**Comment by Svjatovit** [comment]
Так бага актуальна или нет? Если только у имма какие-то косяки, так и фиг с ним.
