### ISSUE TITLE
Обработка чармисов при агре

### ISSUE THREAD

**Issue by Timeofgod** [bylins/mud#678]
При метке(в частности, поскольку купа пока еще играющая профессия, и у нее именно этот закл все же полезен), синтаксис чармисов купца пересекается с именами мобов и невозможно сделать триггер на автометнуть по цели танка (даже взяв первые символы цели или обрезав последние).. например у тебя чармис словенский лесоруб, он отзывается на синтаксис сло или лес. Необходимо сделать проверку на чармисов, чтобы при условии, если это твой чармис, то нужно было бы указывать синоним целиком. Решено сделать отдельной процедурой и после каждого поиска цели проверять на чармиса(ну или встроить в поиск цели).

**Comment by bylins** [comment]
после 	CHAR_DATA* victim = findVictim(ch, argument);
добавлять:
```
if (victim && IS_CHARMICE(victim) && victim->get_master() && !IS_NPC(victim->get_master())) {
    if (!strcmp(GET_NAME(victim), argument)) {
      send_to_char(ch, "Это ваш или последователь группы, введите имя полностью.\r\n");
      return;
    }
 }
```

**Comment by bylins** [comment]
вот так правильно
<------>CHAR_DATA* victim = findVictim(ch, argument);
<------>skip_spaces(&argument);
<------>send_to_char(ch, "моб !%s!  аргумент !%s!.\r\n", GET_NAME(victim), argument);
<------>if (victim && IS_CHARMICE(victim) && victim->get_master() && !IS_NPC(victim->get_master())) {
<------><------>send_to_char(ch, "попытка метнуть в чармиса!!!!!!!!!!!!!!!!!!!!!!!!!.\r\n");
<------><------>if (strcmp(GET_NAME(victim), argument)) {
<------><------><------>send_to_char(ch, "Это ваш или последователь группы, введите имя полностью.\r\n");
<------><------><------>return;
<------><------>}.
<------><------>else {
<------><------><------>send_to_char(ch, "Имя чармиса введено полностью метаем в него!!!!!!!!!!!!!!!!!!!!!!!!!.\r\n");
<------><------>}
<------>}
