### ISSUE TITLE
Откуда у всех мобов скилл 0 берется

### ISSUE THREAD

**Issue by bylins** [bylins/mud#690]
![image](https://user-images.githubusercontent.com/42086238/77666307-dbfdb600-6f91-11ea-82bf-f8e7ce7d7d31.png)

**Comment by bylins** [comment]
переправил на внум
![image](https://user-images.githubusercontent.com/42086238/77667952-e1f49680-6f93-11ea-9713-1f7d412d1361.png)
откуда нули? я же недавно конвертил мобов из-за добавления резистов, а эти поля с 0 не читаются

**Comment by bylins** [comment]
CASE("Skill")
	{
		if (sscanf(value, "%d %d", t, t + 1) != 2)
		{
			log("SYSERROR : Excepted format <# #> for SKILL in MOB #%d", i);
			return;
		}
		if (t[0] > MAX_SKILL_NUM || t[0] < 1)
		{
			log("SYSERROR : Unknown skill No %d for MOB #%d", t[0], i);
			return;
		}
		t[1] = MIN(200, MAX(0, t[1]));
		(mob_proto + i)->set_skill(static_cast<ESkill>(t[0]), t[1]);
	}
и вообще везде i который rnum надо поменять на nr - который vnum

**Comment by Svjatovit** [comment]
Закрыл ибо дубль (да и пофикшено уже, в следующем патче будет).
