### ISSUE TITLE
хрень с скилами у мобов в мобфайле

### ISSUE THREAD

**Issue by bylins** [bylins/mud#691]
![image](https://user-images.githubusercontent.com/42086238/77772774-b89e3e00-7059-11ea-8bad-9add116bcd07.png)
удаляю руками, загружаю, все норма, делаю
medit save 205
опять появляются нулевые скиллы, нужен дебаггер

**Comment by bylins** [comment]
for (const auto c : AVAILABLE_SKILLS)
			{
				if (mob->get_skill(c))
				{
					fprintf(mob_file, "Skill: %d %d\n", c, mob->get_skill(c));
				}
			}

**Comment by bylins** [comment]
что-то свент намутил с кулдауном, надо разбираться и править

**Comment by Svjatovit** [comment]
Вроде бы исправил.
