### ISSUE TITLE
Неправильный вывод дамаги

### ISSUE THREAD

**Issue by bylins** [bylins/mud#707]
Вы УБИЙСТВЕННО пнули пьяного черниговского крестьянина. Теперь ему наложат гипс.
Применен урон = 461

Пилатий, [22.05.20 12:52]
|   УБИЙСТВЕННО        296..400                                                |
|   СМЕРТЕЛЬНО           400+

**Comment by bylins** [comment]
Ричер сказал вам : 'урон 800+ все равно убийственно'

**Comment by bylins** [comment]
Торговый смерд глубоко поклонился перед всеми.
1560H 382M 204173612о Зауч:0 ОЗ:0 Пз:0 Пх:0 Лч:0 Кл:5 29L 1497G Вых:ВЗ> 
пну см
Противник торговый смерд: скилл == 213, итоговыйрасчетскилла == 296, бонус == 89, сэйвыпротивника == -1, модификаторпротивника == -5
Сильно пнув в челюсть, вы заставили торгового смерда замолчать.
Вы УБИЙСТВЕННО пнули торгового смерда. Теперь ему наложат гипс.
Применен урон = 854
1560H 383M 204173072о Зауч:0 ОЗ:1 Пн:2 Пз:0 Пх:0 Лч:0 Кл:5 [Ричер:Невредим] [торговый смерд:О.тяжело ранен] >

**Comment by bylins** [comment]
переписал на С напрямую передавая дамаг - пофиг
void dam_message(CHAR_DATA* ch, CHAR_DATA* victim, int dam) 
![image](https://user-images.githubusercontent.com/42086238/82662595-cece1200-9c36-11ea-8ccd-9441ae92572f.png)

**Comment by bylins** [comment]
хаха
там используется другой вывод
const WeapForAct::kick_type_t WeapForAct::s_kick_type =

**Comment by lrdx** [comment]
Ну так может унифицировать, выделить дамаг в одну общую функцию и использовать ее ото всюду? А то опять копи-паст костыль в 10 местах.

**Comment by bylins** [comment]
там не все так просто
dam_message еще и на щиты что-то вякает, да и сообщение в клетку себе и другим дает, а пнуть сразу всем, короче я не разобрался, просто поправил опечатку
