### ISSUE TITLE
Силы зла

### ISSUE THREAD

**Issue by bylins** [bylins/mud#711]
Аффект не добавляется на кастера, только на мобов, поэтому нет мессаги о спадении

**Comment by bylins** [comment]
или просто сделать его рекастуемым на моба

**Comment by Bikbai** [comment]
> или просто сделать его рекастуемым на моба

Осталось понять, как это делать. Рекастуемое - тьфу и растереть. Мессага о спадении неролеплейно, умертвие то без мозгов.
