### ISSUE TITLE
новые фляги сыпятся по неизвесным причинам

### ISSUE THREAD

**Issue by kartozar** [bylins/mud#729]
22 июня купил новые фляги, а настойки перелил из старых. сегодня 24 июня, спустя два дня часть фляг просто сыпнулась.
По-скольку тут удобно писать вставляя отрывки логов, я процытирую с логами.
Процытирую именно то, что сыпнулось.
они ж не были в ужасе, и считаю, что сыпнулись по ошибке, или по багу, то уже как кому угодно.
Были такие фляги:
фляга с названием добла куплена 22 июня. метка клановая
1780H 274M ОЗ:0 Пх:0 Яр:4 Кл:6 Вых:ВЗ> нац клан фля добла
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:4 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:4 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием фиолетового колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:4 Кл:6 Вых:ВЗ> 
Вы положили флягу с фиолетовым колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:4 Кл:6 Вых:ВЗ> 
Вы бросили кожаную флягу.
1780H 274M ОЗ:0 Пх:0 Яр:4 Кл:6 Вых:ВЗ> 

фляга с названием проворства, метка клановая,
1780H 274M ОЗ:0 Пх:0 Яр:3 Кл:6 Вых:ВЗ> нац клан фля проворства
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:3 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:3 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием фиолетового колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:3 Кл:6 Вых:ВЗ> 
Вы положили флягу с фиолетовым колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:3 Кл:6 Вых:ВЗ> 
Вы бросили кожаную флягу.
1780H 274M ОЗ:0 Пх:0 Яр:3 Кл:6 Вых:ВЗ> инв
так как все куплено 22 июня и метки клановые я не буду повторяться.
фляга с названием тьма
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> нац клан фля тьма
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 
Вы положили флягу с колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 

фляга с названием развейка
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> нац клан фля развейка
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 
Вы положили флягу с колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 

фляга с названием снять проклу
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> нац клан фля снять проклу
Аукцион : лот 0(книга о лечении тяжелых ран), 1 куна, ДВА!!
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием серого колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 
Вы положили флягу с серым колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 

фляга с названием бесстрашия
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> нац клан фля бесстрашия
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 
Вы положили флягу с колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:2 Кл:6 Вых:ВЗ> 

фляга с названием брага
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> нац клан фля брага
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием белого колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 
Вы положили флягу с белым колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 

фляга с названием щит
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> нац клан фля щит
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 
Вы положили флягу с колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 

фляга с названием ловка
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> нац клан фля ловка
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 
Вы положили флягу с колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 

фляга с названием слух
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> нац клан фля слух
Вы покрыли флягу каракулями, понятными разве что вашим соратникам.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> лить фля земля
Вы опустошили флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> перелить 2.фля фля; пол фля сум; бр фля
Вы занялись переливанием колдовского зелья в флягу.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ> 
Вы положили флягу с колдовским зельем в жестяную банку из-под сгущенки.
1780H 274M ОЗ:0 Пх:0 Яр:1 Кл:6 Вых:ВЗ>

**Comment by bylins** [comment]
бред

**Comment by kartozar** [comment]
по какой причине закрыт топик? фляги ж посыпались, и то очевидно. причин закрытия топика нету.

**Comment by kartozar** [comment]
как простой игрок может проверить причины, если ж сислог ему недоступен..? прежде чем закрывать топик, думаю, что след разобраться, по каким причинам посыпались вещи которым было 2 дня.

**Comment by bylins** [comment]
Не сыпятся фляги, и это не багрепорт а рассуждение о возможной баге. покажи как повторить - топик не закрою

**Comment by kartozar** [comment]
это напоминает игру в почтальена печкина. Логи от меня я привел. назвал время, дату. повторюсь купил новые фляги 22 июня вечером, тоесть после 18 часов. посыпались 24 июня, опять вошел после 18 часов, и было сообщение, что они посыпались. Как повторить, опять-таки незнаю. система ведет логи, и у меня есть логи. что оно посыпалось, это факт, который есть очевидный. И отрецать его не реально хотя б по той причине, что логи всего есть у меня. Да, я согласен, что деталей у меня нету, потому что сислога нету. Но ведь в системе логи есть, и это уже надо разобраться вместе, выявить причину, и устранить поломку, или недочет. Сказать, что бред, и закрыть чисто по той причине, что нету желания разобраться, то оно ж проще всего. А вот как простой рядовой пользователь может повторить баг? Я припускаю, что вот чтоб не начислить славу, сделать пользователя крайним, топик и закрыт. Давайте не сориться, и вместе выявлять причины багов, устраняя их.

**Comment by bylins** [comment]
За 22 года работы мада фляги рассыпались только у тебя.
