### ISSUE TITLE
по вопросу issue №729

### ISSUE THREAD

**Issue by kartozar** [bylins/mud#731]
обращаюсь по вопросу поднятому в issue №729. Он был закрыт по причине, как сказал администратор, неполного багрепорта. От себя я дал отрывки логов. Что такое багрепорт? это полные логи, как с моей стороны, так и со стороны системы. Отрывки логов от себя я опубликовал. Как  по словам администратора, я б должен обосновать факт преждевременного рассыпания фляг?  Учитывая то, что логи от системы, а именно syslog,  мне недоступен, то по сути я описал то, что видел я. Чтоб видеть полную картину, в ответ на предоставленное мною, по идее, администратор бы предоставил отрывки сислога, чтоб видеть полную картину.
В ответ я получаю в первом комнте, слово бред.
И issue №729 закрывается.  А какую информацию от себя, чисто физически я б смог предоставить?
 Анализируя выше написанное, прошу открыть заново issue №729.
Наперед прошу извенений, если с моей стороны, что не так.

**Comment by bylins** [comment]
никогда больше не открывай задачи, ты несешь бред

**Comment by bylins** [comment]
У меня нет ресурсов править баги которые возникают раз в 5 лет, важно - найми программиста

**Comment by kartozar** [comment]
Не соглашусь с тем, что issue №729 и №731  закрыты. проблема есть, и логи я привел. другое дело в том, что сислоги недоступны, и неизвесно, что там было и как. Но в таком случае, задачу не след закрывать. Если вина на моей стороне, то тогда аналогично надо привести сислог, в том, что вина на моей стороне. Но в данном случае, я не согласен в том, что вина на моей стороне, так как я смотрел за состоянием фляг, купил новые, и они сыпнулись. 
В свою очередь от себя я логи привел, с которых видно, что фляги были куплены, и они ж через два дня сыпнулись. 
И если уже говорить по сути, то на флягах были метки, а когда они сыпнулись, и не было сказано, что именно сыпнулось.
Потому, по-моему мнению, задачу следует открыть, и хотя б внести правки, чтоб было видно, что именно сыпнулось, и чтоб так и писалось фляга с фиолетовым настоем (сила) рассыпалась. ну как-то так. а то при том, не говорится что именно сыпнулось. потом приходится все перебрать, чтоб выявить хотя б что сыпнулось.
В данном случае 6 фляг сыпнулось.
И вот взять и закрыть, потому что по-вашему мнению бред, я считаю не правильно. Для вас бред, для меня не бред. Настой с огнещитом, для меня не бред, и он сыпнулся.
Прошу открыть issue №731 і как-то по суті разобрать почему оно сыпнулось. Сразу ж прошу и учесть, что если и взять договориться с программистом, то он и скажет, а где логи, где задача, что править. А логов то и нету.
Аналогично, как и говорили про баг с местями, что его нету, а потом в результате он же был и исправлен.

**Comment by kartozar** [comment]
reopened this
