### ISSUE TITLE
Моб милион китайцев теперь бессмертный

### ISSUE THREAD

**Issue by ladon3434** [bylins/mud#732]
тригером китайцы убегают, а т.к. теперь можно убегать сразу то они убегают сразу, даже если сами агрят.
лагать его невозможно, ибо он !все похоже.

**Comment by Svjatovit** [comment]
Не надо на гитхаб писать баги с зонами, для этого есть доски в маде.
В крайнем случае, может и стоит отдельный багтрекер для багов зон завести, но гитхаб захламлять не надо.
