### ISSUE TITLE
Нацарапать

### ISSUE THREAD

**Issue by bylins** [bylins/mud#737]
После правки в олц у предмета слетают метки

**Comment by kartozar** [comment]
И кроме того, если скажем на предмете нацарапана метка, или личная, или клановая. например на фляге. фляга сыпется, и просто пишет,
Фляга с колдовским зельем рассыпалась от длительного использования.
Фляга с колдовским зельем рассыпалась от длительного использования.
Фляга с колдовским зельем рассыпалась от длительного использования.
Фляга рассыпалась от длительного использования.
Фляга с колдовским зельем рассыпалась от длительного использования.
Фляга с колдовским зельем рассыпалась от длительного использования.
Фляга с белым колдовским зельем рассыпалась от длительного использования.
Фляга с серым колдовским зельем рассыпалась от длительного использования.
Фляга с колдовским зельем рассыпалась от длительного использования.
Фляга с фиолетовым колдовским зельем рассыпалась от длительного использования.
Фляга с фиолетовым колдовским зельем рассыпалась от длительного использования.
Но ведь то ж на всех флягах стояли клановые метки, а что рассыпалось, потом сортируй разбирай.

**Comment by Bikbai** [comment]
> И кроме того, если скажем на предмете нацарапана метка, или личная, или клановая. например на фляге. фляга сыпется, и просто пишет,
> Но ведь то ж на всех флягах стояли клановые метки, а что рассыпалось, потом сортируй разбирай.

660H 285M 19433849о Зауч:0 ОЗ:0 Пз:0 Пх:0 29L 23124G Вых:СЗ>                                                                                        │
│[Персональное хранилище]: 'сверкающие поножи *бикбай*C* рассыпались в прах' 

В хране то пишет.
