### ISSUE TITLE
Смерть по триггеру засчитало за ДТ.

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#742]
Кхарн дружине: 'Оттолкнувшись сильно от берега, вы щучкой нырнули в озеро, и тут же напоролись головой на торчащий из дна острый кам
ень. Последней мыслью было: "И зачем я тут нырнул? Не мог найти лучше места что ли"?'.
Кхарн дружине: 'в статистики пишет что дт поймал, но опыт сняли.'.

Категория: "В гиблых местах:"

Не знаю, может оно так и задумывалось, но непохоже.

**Comment by bylins** [comment]
слоу дт похоже а там снимает

**Comment by Bikbai** [comment]
Слоу дт, трупис остался.

Специфический сценарий, ибо выглядит как обычное ДТ, но с потерей опыта. Чтобы выяснить - нужно залезть в код зоны, не особо и надо.
