### ISSUE TITLE
Метание копья не дает лага жертве

### ISSUE THREAD

**Issue by Vitaliy-Zlynya** [bylins/mud#743]
Тестовые параметры чара:
Ваши характеристики :
  Сила : 37(50)  Подв : 35(43)  Тело : 39(50)  Мудр : 29(29)  Ум   : 33(36)  Обаян: 36(43)
 метнуть                  (заоблачно) 180% 
магия тьмы               (возвышенно) 170% 
1038H 328M 53663605о Зауч:0:03 ОЗ:0 Пз:3 Пх:0 Зо:0 28L 366131G Вых:СВЮЗ> тен шабу
Рукоять оружия в вашей руке налилась неестественным холодом.
Попадание копья повалило Шабу наземь.
Шабу медленно появилась из пустоты.
Ваш меткий бросок надолго запомнится Шабу. (*)

[метну]
1040H 329M 53663605о Зауч:0:03 ОЗ:1 Пз:3 Пх:0 Зо:5 [Зурис:Слегка ранен] [Шабу:О.тяжело ранена] > 
Так и рука отвалится, нужно передохнуть.

Вы попытались пырнуть Шабу, но промахнулись.
Вы попытались уколоть Шабу, но промахнулись.
Шабу огрела вас.

1029H 331M 53663605о Зауч:0:02 ОЗ:1 Пз:3 Пх:0 Зо:5 [Зурис:Слегка ранен] [Шабу:О.тяжело ранена] > 
Шабу поднялась.

Тестовые параметры чара с капом инты:
Ваши характеристики :
  Сила : 37(50)  Подв : 35(43)  Тело : 39(42)  Мудр : 29(30)  Ум   : 33(50)  Обаян: 36(49)
 метнуть                  (заоблачно) 180% 
магия тьмы               (возвышенно) 170% 

1114H 331M 53663605о Зауч:0 ОЗ:0 Пз:0 Пх:0 Зо:0 28L 366131G Вых:СВЮЗ> тен шабу
Рукоять оружия в вашей руке налилась неестественным холодом.
Попадание копья повалило Шабу наземь.
Шабу медленно появилась из пустоты.
Ваш меткий бросок надолго запомнится Шабу. (*)

[метну]
1114H 331M 53663605о Зауч:0 ОЗ:1 Пз:0 Пх:0 Зо:5 [Зурис:Невредим] [Шабу:Ранена] > 
Так и рука отвалится, нужно передохнуть.

Шабу огрела вас.
Вы попытались пырнуть Шабу, но ваш удар не достиг цели.

1099H 331M 53663605о Зауч:0 ОЗ:1 Пз:0 Пх:0 Зо:4 [Зурис:Невредим] [Шабу:Ранена] > 
Шабу поднялась.

Молот метается лучше, лаг 3 раунда

**Comment by Svjatovit** [comment]
Не воспроизводится. Это старый глюк с обнулением лага на тике, видимо. То есть, тут не в метнуть дело, а в логике обработки лагов на тике в целом. Это конечно надо будет когда-нибудь переписать...
