### ISSUE TITLE
Ребаланс покровительства

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#755]
Щас там формула Уровень + Морты*2. Бонус от 1 до 110 хп для текущих игроков
Причем был еще (случайно) оверхил на (Уровень + Морты)*2. Бонус от 1 до 140 хп для текущих игроков

Надо, наверное, на скилл магии перевести.

**Comment by Svjatovit** [comment]
В оригинале  это было, вроде бы, вот это заклинание: 
**Божественная Мощь (Divine Power)**
Созидание
Уровень: Клк 4, Война 4
Компоненты: В, С, БФ
Время Сотворения: 1 действие 
Расстояние: Персональное	
Цель: Вы 
Длительность: 1 минута/уровень

Взывая к божественной силе вашего покровителя, вы наполняетесь мощью и боевым умением. Вы получаете базовый бонус атаки как у воина вашего общего уровня, бонус к Силе поднимает ее до 18 (если она уже не 18 или выше), и вы получаете временно 1 хит за уровень. 

Силу добавлять не стали, потому что и так есть заклинание "сила", а хитов изначально примерно столько же и добавлялось, плюс 1 за морт. Был сразу коэффициент *2 или нет, не помню. Но перевести на учет скилла - наверное правильная идея. Правда величины получаемых хитов, имхо, должны примерно соответствовать нынешним.
