### ISSUE TITLE
Сделать, чтобы многолапые мобы (и люди), сразу выдавали все атаки

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#757]
Сейчас код при старте боя выполняет одну атаку и ставит игрока в очередь на следующий раунд боя.
А можно сделать, чтобы сразу выдавало полный комплект. Возможные проблемы:
танк на большой группе не успеет врубить веер/блок и отъедет, только сожрать !ЗБ!
вломившися агро-моб выдаст со своих шести лап в кастера - реск не успеет, только прикрышка

**Comment by lrdx** [comment]
Не надо - ломает существущий баланс

**Comment by bylins** [comment]
вот тоже самое хотел написать, танку и так тяжело выжить первый раунд зачастую
