### ISSUE TITLE
Научиться уже открывать единтственную закрытую дверь

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#770]
В сенях [5102]
i34 755H 82M ??? Зауч:0 Вых:СВ(Ю)> откр две
Уже открыто!

Бесит, аж кушать не могу =)

**Comment by Svjatovit** [comment]
Почему бы и нет...

**Comment by hikopol** [comment]
тогда и отперать в ту же степь....

**Comment by Bikbai** [comment]
Готово, работает.
