### ISSUE TITLE
Вожака реализовать как спец.прогу моба

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#773]
В профиле игрока хранить всех знакомых купцу чармисов
Спец.программа выдает всех, с кем познакомился на текущем морте

**Comment by Svjatovit** [comment]
Дополню.
Купцу дать возможность просмотреть список запомненных наемников и удалить ненужных.
Спец-процедура у вожака выдает не просто список, а прайс с ценами.
Желательно конечно еще конфиг прайса у вожаков вынести в файл, не место ему в коде, но это уже по желанию.

**Comment by bylins** [comment]
У купы и так в профиле хранятся знакомые чармисы

**Comment by Svjatovit** [comment]
> 
> 
> У купы и так в профиле хранятся знакомые чармисы

Хранение чармисов в виде меток квестов -  костыль костыльный.
Можно конечно и так пока оставить.. Но как минимум, нужна возможность автоматически запоминать чармисов, редактировать и просматривать список.
