### ISSUE TITLE
Неправильная логика работы ЗБ.

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#780]
Зеркало возвращает урон, даже если в зб? Теоретически так можна убиться в ЗБ...
пример ниже, откуда видно что урон наноситься....
844H 108M 4037114о Зауч:0 Пз:0 Пх:0 [Кудояр:Невредим] [побирушка:Слегка ранен] [лукавый прелат:Ранен] >  

Магический кокон вокруг лукавого прелата полностью поглотил ваш удар.
Магический кокон вокруг лукавого прелата полностью поглотил удар побирушки.
Магический кокон вокруг лукавого прелата полностью поглотил удар побирушки.
Магический кокон вокруг лукавого прелата полностью поглотил удар побирушки.
Магический кокон вокруг лукавого прелата полностью поглотил удар побирушки.
Магический кокон вокруг лукавого прелата полностью поглотил удар побирушки.
Лукавый прелат зыркнул на вас и проревел : 'гнев божиа не минути'.
Ваше магическое зеркало отразило поражение лукавого прелата!
Лукавый прелат разгневанно взглянул на лукавого прелата, его окружило облако пара.
Лукавый прелат попытался сокрушить побирушку, но промахнулся.
Удар лукавого прелата прошел мимо побирушки.
Магический кокон вокруг лукавого прелата полностью поглотил удар ментальной тени.
844H 108M 4037114о Зауч:0 Пз:0 Пх:0 [Кудояр:Невредим] [побирушка:Слегка ранен] [лукавый прелат:Тяжело ранен] >

**Comment by Svjatovit** [comment]
Вроде бы исправлено, но надо понаблюдать.
