### ISSUE TITLE
Режим персональной подсветки/гэгов

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#785]
1. Общение разными цветами.
2. Подсветка применения скиллов
3. Подсветка атак разной силы
4. Подавление атак ниже определенного уровня урона + промахи
5. Подавление применения скиллов мобами

**Comment by bylins** [comment]
это делается хайлайтом в клиенте

**Comment by Bikbai** [comment]
ну а зачем хайлайты, когда можно раз и навсегда накорябать кодом, не сильно сложнее?)
