### ISSUE TITLE
Примастырить телеграм для теллов в офлайн

### ISSUE THREAD

**Issue by Bikbai** [bylins/mud#788]
Сделать режим доступности через телегу. 
РЕЖИМ ТЕЛЕГА ВКЛ, ВЫКЛ, ЗАБЫТЬ.
При первой активации необходимо зарегаться у чат-бота и вписать ид, который чат-бот вернёт, себе в профиль.
Сделать отдельную команду прогнать_телегу <имя> текст. Если у игрока активен режим, то через бота производится отправка текста в его телеграм, идентификатор хранить в профиле и подгружать отдельной процедурой для оптимизации, вне чар_дата. Теоретически этот ид юзера телеги суть атрибут аккаунта, но там всё непонятно.

**Comment by hikopol** [comment]
зачем это ? для упрощения жизни ботов?)

**Comment by bylins** [comment]
ты давно отстал от жизни, у КВ штатно из жабы общение через телегу плагином к жабе.
Но я в принципе против хардкорно это делать, это по сути интерес бикбая. сделаю по флагу устанавливаемым иммом. мне иногда надо вылавливать игроков которые нужны через соту.

**Comment by Bikbai** [comment]
> ты давно отстал от жизни, у КВ штатно из жабы общение через телегу плагином к жабе.
> Но я в принципе против хардкорно это делать, это по сути интерес бикбая. сделаю по флагу устанавливаемым иммом. мне иногда надо вылавливать игроков которые нужны через соту.

Ключевое отличие от жабы - передача сообщения офлайн-игроку. Имм-команда тут с трудом лезет, ибо надо чтобы игрок со своего телеграм-аккаунта чат-боту сообщение кинул.

**Comment by bylins** [comment]
а кто сказал что я этот коммит примиу?

**Comment by Bikbai** [comment]
> а кто сказал что я этот коммит примиу?

а где сказано, что код уже есть и его надо срочно заливать? =) Я лишь высказал идею про удобную опцию
