### ISSUE TITLE
Молот и размер... непонятки

### ISSUE THREAD

**Issue by hikopol** [bylins/mud#789]
https://github.com/bylins/mud/blob/master/src/skills.cpp#L1238
в формуле так : 
	case SKILL_MIGHTHIT: // богатырский молот
		{
		//victim_sav = GET_SAVE(vict, SAVING_STABILITY) - dex_bonus(GET_REAL_CON(vict));
		victim_sav = -GET_REAL_SAVING_STABILITY(vict);
		//bonus = size + dex_bonus(GET_REAL_STR(ch));
		bonus = size + dex_bonus(GET_REAL_STR(ch));

		if (IS_NPC(vict))
			victim_modi -= (size_app[GET_POS_SIZE(vict)].shocking) / 2;
		else
			victim_modi -= size_app[GET_POS_SIZE(vict)].shocking;
		break;
		}
Судя из этого полагаю что размер применяемого должен давать бонус к молоту, сответвсенно шмотки +размер должны повышать шанс. На практике имеем наоборот, одевая шмотку +размер "bonus" падает, а одевая -размер растет.

Вырезка из експерементов цель ментальная тень.
Голый чармис для чистоты експеремента:
П: оружейных дел мастер, Ц:  ментальная тень, Скилл: 4. Итог.скилл = 137, fail limit = 965, Morale = 9, Bonus == 31, Сейвы цели = -1, Моди.цели = -1
Ментальная тень содрогнулась от богатырского удара оружейных дел мастера.
// смотрим тут Bonus == 31
Предмет "сверкающий плащ", тип : БРОНЯ
Можно надеть на плечи.
Вес: 10, Цена: 500, Рента: 450(200)
Материал : КОЖА
Неудобен : ничего
Недоступен : ничего
Требует перевоплощений : 3
Имеет экстрафлаги: светится,!разыскать
защита (AC) : 5
броня       : 5
Накладывает на вас аффекты: ничего
Дополнительные свойства :
   телосложение улучшает на 2
   размер улучшает на 10 <==== + 10 размера
   защита улучшает на 5
   броня улучшает на 5
Оружейных дел мастер одет :
<на плечах>                 сверкающий плащ  <великолепно> ..блестит!

П: оружейных дел мастер, Ц:  ментальная тень, Скилл: 4. Итог.скилл = 136, fail limit = 965, Morale = 9, Bonus == 30, Сейвы цели = -1, Моди.цели = -1
Ментальная тень сумела избежать удара оружейных дел мастера.
// тут бонус уже 30  (соответсвенно +10 размера == -1 к бонусу ?)
// Дальше пялим -20 размера
Предмет "чешуйчатые прозрачные перчатки", тип : БРОНЯ
Можно надеть на кисти.
Вес: 8, Цена: 5000, Рента: 800(400)
Материал : КОЖА
Неудобен : ничего
Недоступен : ничего
Требует перевоплощений : 12
Имеет экстрафлаги: ничего
защита (AC) : 5
броня       : 5
Накладывает на вас аффекты: мигание
Дополнительные свойства :
   повреждение улучшает на 4
   воля улучшает на 8
   размер ухудшает на 20 <== -20 размера
   удача улучшает на 8
   макс.жизнь улучшает на 70

Оружейных дел мастер одет :
<на кистях>                 чешуйчатые прозрачные перчатки  <великолепно>

П: оружейных дел мастер, Ц:  ментальная тень, Скилл: 4. Итог.скилл = 0, fail limit = 978, Morale = 17, Bonus == 33, Сейвы цели = -1, Моди.цели = -1
Удар оружейных дел мастера прошел мимо ментальной тени.

// Вуаля бонус 33 .... (+2 изза -20 к размеру)
Как по мне работает криво...

**Comment by Svjatovit** [comment]
Ц:  веселый цыган, Скилл: 4. Итог.скилл = 152, fail limit = 961, Morale = 7, **Bonus == 19,** Сейвы цели = -13, Моди.цели = -1
Вы надели магический браслет вокруг правого запястья (+20 размер).
Ц:  веселый цыган, Скилл: 4. Итог.скилл = 172, fail limit = 961, Morale = 7, **Bonus == 39**, Сейвы цели = -13, Моди.цели = -1
Поменял на браслете бонус на -20
П: Вызга, Ц:  веселый цыган, Скилл: 4. Итог.скилл = 152, fail limit = 961, Morale = 7, **Bonus == 19**, Сейвы цели = -13, Моди.цели = -1

Ну, последнее понятно:, там размер меньше 50 не учитывается (что бред, но там вся функция состоит из бреда и костылей). В общем. все там правильно работает. А в приложенном тут логе бонус скачет, скорей всего, из-за других параметров.
