### ISSUE TITLE
иммкоманда glory имя ну или у мортала слава2 информация

### ISSUE THREAD

**Issue by bylins** [bylins/mud#799]
показывает сколько вложено и сколько свободно, сделать вывод сколько славы в количестве влито

**Comment by bylins** [comment]
calculate_glory_in_stats
есть такая функция

**Comment by bylins** [comment]
хрень какая-то
sprintf(buf+strlen(buf), "Свободных очков : %d, вложенно : %d\r\n", it->second->free_glory, it->second->tmp_spent_glory);
Свободных очков : 0, вложенно : -1094795586

**Comment by bylins** [comment]
и копипаст не помогает
[  0%] Building CXX object CMakeFiles/circle.library.dir/src/glory_const.cpp.o
/home/stribog/mud/src/glory_const.cpp: In function 'void GloryConst::print_glory(CHAR_DATA*, std::__debug::map<long int, std::shared_ptr<GloryConst::glory_node> >::iterator&)':
/home/stribog/mud/src/glory_const.cpp:236:94: error: 'calculate_glory_in_stats' was not declared in this scope
  sprintf(buf+strlen(buf), "Свободных очков : %d, вложено : %d\r\n", it->second->free_glory, calculate_glory_in_stats(it));

**Comment by bylins** [comment]
она же глобальная для этого файла

**Comment by bylins** [comment]
![image](https://user-images.githubusercontent.com/42086238/93711617-62b5d900-fb58-11ea-8162-3ec13acb202b.png)
хрень.....

**Comment by Svjatovit** [comment]
Я так понимаю, это уже сделано, просто опять задачу забыли закрыть.

**Comment by bylins** [comment]
Не полностью сделано, оно брешет, сумму вложено не вложено пишет некорректно

**Comment by bylins** [comment]
Информация о вложенных вами очках славы:
Макс.жизнь      : +600(12)
Успех.колдовства: +126(18)
Стойкость       : +60(4)
Реакция         : +135(9)
Запоминание     : +200(4)
Свободных очков: 21560. Вложено: 55400

13:13:30 14 Марта 2020 года :: Change const glory +50000 by Стрибог [мое]
10:16:19 26 Марта 2020 года :: Change const glory +2000 by Стрибог [тест]
09:19:00 16 Января 2020 года :: Change const glory +5000 by Стрибог [мое]
17:00:38 20 Января 2020 года :: Change const glory +20000 by Стрибог [мое]
18:10:50 20 Февраля 2019 года :: Change const glory +3200 by Стрибог [бонус за морт]
12:26:01 16 Сентября 2018 года :: Change const glory +2400 by Стрибог [патчи]
17:57:16 27 Сентября 2018 года :: remort from 9 to 10 [dest=1]
12:01:31 29 Сентября 2018 года :: Change const glory +10000 by Стрибог [куда-то подевалось 5к славы, надо разобраться в коде]
17:18:41  5 Июня 2018 года :: Change const glory +10000 by Стрибог [мое]
20:17:44 24 Июня 2014 года :: Change const glory +5000 by Стрибог [зоны]

**Comment by bylins** [comment]
т.е. как минимум 100к славы, а пишет белиберду
