### ISSUE TITLE
мобы группятся

### ISSUE THREAD

**Issue by maratakberdin** [bylins/mud#800]
Серая цапля пришла с запада.
Серая цапля пришла с запада.
Серая цапля пришла с запада.
Серая цапля пришла с запада.
Серая цапля пришла с запада.
Серая цапля пришла с запада.

Белохвостая сорока прилетела с юга.
Белохвостая сорока прилетела с юга.
Белохвостая сорока начала следовать за белохвостой сорокой.

собираются огромные толпы мобов.

есть подозрение что флаг !группа не работает.

**Comment by bylins** [comment]
я по идею знаю  где постараюсь сам

**Comment by maratakberdin** [comment]
женщина Птица MOB 'серая цапля' IDNum: [0] В комнате [99544] Текущий ID:[2077908] ЛАГ: [0]
Синонимы: серая цапля, VNum: [99505], RNum: [11807]
Падежи: серая цапля/серую цаплю/серой цапле/серую цаплю/серой цаплёй/серой цапле Титул: <Нет>
L-Des: Серая цапля важно выхаживает тут.
Роли NPC: нет, Уровень: [ 4], Опыт: [     32000], Наклонности: [   0]
Сейчас в мире : 18. Последний раз убит: никогда!
Сила: [7/7]  Инт : [4/4]  Мудр : [4/4] 
Ловк: [17/17]  Тело:[16/16]  Обаян:[4/4] Размер: [12/12]
Жизни :[174/174+20]  Энергии :[100/100+4]
Glory: [0], ConstGlory: [0], AC: [-40/-40(-100)], Броня: [0], Попадания: [ 5/ 5/3], Повреждения: [10/10/8]
Защитн.аффекты: [Para:0/Breath:0/Spell:0/Basic:0], Поглощ: [0], Стойк: [6], Реакц: [7], Воля: [-3]
Резисты: [Огонь:0/Воздух:0/Вода:0/Земля:0/Жизнь:0/Разум:0/Иммунитет:0/Тьма:0]
Защита от маг. аффектов : [0], Защита от маг. урона : [0], Защита от физ. урона : [0]
Запом: [0], УспехКолд: [0], ВоссЖиз: [0], ВоссСил: [0], Поглощ: [0], Удача: [2], Иниц: [0]
Положение: Стоит, Сражается: Нет, Экипирован в металл: Нет, Тип атаки: клюнул
Позиция по умолчанию: Стоит, Таймер отсоединения (тиков) [0]
MOB флаги: моб,трус,!очар,!призывать,!групится
NPC флаги: ничего
Количество атак: 2. Вероятность использования умений: 50%. Убить до начала замакса: 0
Умения:
Mob СпецПроц: Нет, NPC сила удара: 2d12
Несет - вес 0, предметов 0; (в инвентаре) : 0, (надето): 0
Ведущий: серая цапля, Ведомые:
Аффекты: состоит в группе

**Comment by bylins** [comment]
готово
