### ISSUE TITLE
Очень-очень редкая удача! Опыт повышен!

### ISSUE THREAD

**Issue by bylins** [bylins/mud#813]
Я отключил опыт, видимо мессага осталась

**Comment by Svjatovit** [comment]
А можно подробностей? Что за механика, что было, что отключено?

**Comment by bylins** [comment]
у нас есть список убийства мобов по времени, я его заюзал, но оказалось это список, который используется для поиска куда засунуть сет.
т.е. уникальные мобы, а не все. Списка всех мобов и когда его последний раз убили у нас нет.

**Comment by vkhanayev** [comment]
@bylins а что сделать надо - до конца все вырезать или вернуть механику (с добавлением статы по всем мобам)?
само сообщение было отключено в f7bf19479d71b4b7d694935a5fd011173f95906d

**Comment by bylins** [comment]
Тот список что я использовал, это мобы подбираемые дня расчета загрузить в них табличный сет.
Полного списка мобов нет. Сделать бы... но не по моим силам.
