### ISSUE TITLE
make[2]: *** No rule to make target '/usr/local/lib/libTgBot.a', needed by 'circle'.  Stop.

### ISSUE THREAD

**Issue by bylins** [bylins/mud#816]
Уже не используется, надо выпилить, а то мад  не собирается из коробки

**Comment by Bikbai** [comment]
чойта не используется, когда да.

https://github.com/reo7sp/tgbot-cpp

**Comment by Svjatovit** [comment]
А это актуально вообще еще? Вроде с телеграмом мад подружили.

**Comment by bylins** [comment]
я исправил
