### ISSUE TITLE
поправить stat иммов

### ISSUE THREAD

**Issue by bylins** [bylins/mud#817]
650H 179M ??? Зауч:0 34L 52787G Вых:Ю> vstat obj 68612
Название: 'фамильное кольцо',
Синонимы: 'фамильное кольцо',
VNum: [68612], RNum: [10073], UID: [0], ID: [2547254]
Расчет критерия: 1.280000, мортов: (13.000000) 
Тип: БРОНЯ, СпецПроцедура: Нет
L-Des: Фамильное кольцо Демидовых сверкает на свету.
Может быть надет : ВЗЯТЬ,ПАЛЬЦЫ
Материал : ДРАГ.КАМЕНЬ
Неудобства : ничего
Запреты : ничего
Устанавливает аффекты : ничего
Дополнительные флаги  : невидим
Вес: 1, Цена: 800, Рента(eq): 100, Рента(inv): 800, Таймер: 58800
Находится в комнате : нигде, В контейнере: Нет, В инвентаре: Нет, Надет: Нет
AC: [1]  Броня: [1]
Аффекты: -5 to реакция, +40 to макс.жизнь
Уровень (ilvl): 13.000000
Сейчас в мире : 3. На постое : 0. Макс в мире: 3
Script information:
  None.

не выводится прочность предмета

**Comment by bylins** [comment]
гыгы
MAT_DIAMOND  - алмаз, переведен у нас как драгоценный камень, ну ладно, но какого хрена он по прочности стоит ниже бумаги?

**Comment by bylins** [comment]
в опознать тоже добавить описание прочности и макспрочности

**Comment by Svjatovit** [comment]
> 
> 
> MAT_DIAMOND - алмаз, переведен у нас как драгоценный камень, ну ладно, но какого хрена он по прочности стоит ниже бумаги?

Прочность отражает способность материала противостоять ударам, т.к. она у нас в основном для доспехов. А алмаз в этом плане действительно как бы не хуже бумаги: это довольно хрупкий камень. В то время, как толстую пачку бумаги не вдруг проткнешь и тем более разрубишь. :)

**Comment by bylins** [comment]
Ага, и очень легко поддается фрагам :)

**Comment by bylins** [comment]
У нас кристал по табличке якобы прочнее алмаза, но не суть, эта таблица нигде не используется, просто тупо енум перечислений. А работает то что проставил билдер.
Менять название на алмаз не стал, оно в копке используется, а то у нас будут серобурокозюльчатого цвета алмазы.
пусть драг.камень, вывод в опознать прочности я добавил, несуразности будут репортить игроки теперь.
