### ISSUE TITLE
молитва или жерва[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#82]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Пересмотреть даваемые бонусы и сделать увеличение от мортов.

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/82

=======COMMENTS=======

Date: 2017-12-28T09:25:48Z

*Original comment by* **Александр Соловьев (Bitbucket: [dethman](https://bitbucket.org/dethman), GitHub: [dethman](https://github.com/dethman))**

----------------------------------------

Вот не согласен. но можно.

Date: 2017-12-06T21:54:42Z

*Original comment by* **Posvist (Bitbucket: [Posvist](https://bitbucket.org/Posvist), GitHub: [Posvist](https://github.com/Posvist))**

----------------------------------------

я предлагаю длительность действия аффекта от молитвы/жертвы рассчитывать не в зависимости от кол-ва молитв, а в зависимости от стоимости жертвуемого (например шмотка стоимостью в 10к повесит аффект на 1 час). Ну или зависимость и от первого и от второго. Смысл в том, чтобы дать игрокам возможность сливать куны, да и антуражненько это.

Date: 2017-11-24T16:23:53Z

*Original comment by* **Александр Соловьев (Bitbucket: [dethman](https://bitbucket.org/dethman), GitHub: [dethman](https://github.com/dethman))**

----------------------------------------

https://bitbucket.org/bylins/mud/wiki/pray

**Comment by Svjatovit** [comment]
Систему религий в принципе надо переделывать и развивать. А это место все-таки для конкретных тасков, а не для обсуждений "чего бы сделать хорошего". Потому закрываю.
