### ISSUE TITLE
Опять косяк с порчей памяти

### ISSUE THREAD

**Issue by bylins** [bylins/mud#829]
![image](https://user-images.githubusercontent.com/42086238/96864514-3819b180-1471-11eb-9088-7bedd4e5c0e4.png)

**Comment by bylins** [comment]
на чистом перегруженном маде все правильно
![image](https://user-images.githubusercontent.com/42086238/96864567-4a93eb00-1471-11eb-926f-371902de12f5.png)

**Comment by Svjatovit** [comment]
Это все та же задача #889. Причины там описаны в описании, это не порча памяти, как таковая.
