### ISSUE TITLE
Бонусы к резистам

### ISSUE THREAD

**Issue by bylins** [bylins/mud#832]
![image](https://user-images.githubusercontent.com/42086238/97406363-2b320d80-190a-11eb-86b3-86db16b63e79.png)
а походу должны плюсоваться

**Comment by Svjatovit** [comment]
Скорей всего не должны. Потому что это не резисты, а спас-броски (в стотыщпятьсотый раз повторяю, перестаньте их путать, это разные параметры). А спас-броски сделаны по принципу "чем меньше, тем лучше". Скорей всего, если ковырнуть, этот dex_bonus отрицательный.

**Comment by Svjatovit** [comment]
Посмотрел.

Суть вот в чем. Спас-бросок на предмете или спелле меньше нуля - _**улучшает**_  этот показатель. Больше нуля - ухудшает. Т.е. -5 реакции - это "улучшает реакцию на 5". Как правило, значения спас-бросокв у персонажей "хорошие", то есть - меньше нуля, значение отрицательное. dex_bonus положительный. При прибавлении к нему отрицательного числа получается плюс, т.е. общая сумма выше.

А везде, где этот макрос используется, он вызывается с минусом перед ним. Т.е. снова берется отрицательное значение, как и надо для спас-броска. Это, конечно, криво: минус, если по-хорошему, должен быть внутри макроса (а совсем по-хорошему не надо макросами пользоваться), но то уже другой вопрос. 

В общем, ошибки тут нет, просто неудобочитаемый код.
