### ISSUE TITLE
Странности с досками, зачем учитывается уровень игрока?

### ISSUE THREAD

**Issue by bylins** [bylins/mud#839]
[1] 16:14 16-11-2020 (Белун) :: [97300]

вас пишится с маленькой буквы в обоих случаях
i31 521H 157M ??? Зауч:0 Вых:ВЗ> 
очеп очис 1
У вас нет возможности удалить это сообщение.

**Comment by lrdx** [comment]
Из комментария:

> // для простых досок сверяем левела (для контроля иммов)

Видимо, чтобы младшие иммы не могли удалять сообщения старших иммов )

**Comment by Svjatovit** [comment]
Да, вероятно, именно поэтому. Зачем это отключать, мешает кому-то?
