### ISSUE TITLE
Первый удар от дышащих мобов[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#84]
*Originally reported by* **Kirill (Bitbucket: [lrdx](https://bitbucket.org/lrdx), GitHub: [lrdx](https://github.com/lrdx))**

----------------------------------------

Почему первый удар от дышащих мобов всегда физика (так по крайней мере кажется)?
И почему вообще мобы дышат без видимого урона? СМЕРТЕЛЬНО ДЫХНУЛ?

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/84

=======COMMENTS=======

Date: 2017-11-20T17:33:53Z

*Original comment by* **Sventovit (Bitbucket: [Sventovit](https://bitbucket.org/Sventovit), GitHub: [Sventovit](https://github.com/Sventovit))**

----------------------------------------

Потому что дыхания мобов - это спеллы. Так вот криво сделано, не было раньше такого понятия, как "тип урона". По-хорошему, всю систему бы переделать в этом плане.

**Comment by Bikbai** [comment]
Чинится легко, уже починил :)

Но назрел другой вопрос - почему мобы начинают бой с одной атаки, даже если у него их шесть?
И стоит ли это чинить, количество рипов возрастет..
