### ISSUE TITLE
APPLY_MOVEREG

### ISSUE THREAD

**Issue by bylins** [bylins/mud#843]
не работает, нет обработки в коде

**Comment by Svjatovit** [comment]
limits.cpp:349 - int move_gain(CHAR_DATA* ch)
Все там есть. В void affect_modify(CHAR_DATA * ch, byte loc, int mod, const EAffectFlag bitv, bool add) наложенный APPLY_MOVEREG плюсуется к родному, как и должен. Почему решили, что нет обработки?
