### ISSUE TITLE
К чему приводят опечатки

### ISSUE THREAD

**Issue by bylins** [bylins/mud#845]
2021.zon
-------------
#10
Системная зона 2021 -- новый 2021 год~
#50 0 1
202199 1 0 0 *.
S
$
обратите внимание  на первую строку #10 
все бы нормально но попытка отредактировать trigedit любой триггер в 2021 зоне дает лаг и какую-то кашу в 10.trg чуть ли не на пол мада всяких левых триггеров, файл разрастается до 5 мег

**Comment by Svjatovit** [comment]
Нужна какая-то проверка, чтобы кривой файл зоны не приводил к подобным апокалипсисам.
