### ISSUE TITLE
Убрать ограничение по уровню при применении переместиться

### ISSUE THREAD

**Issue by Anarch-mud** [bylins/mud#856]
Нужно убрать ограничение на уровень персонажа (если состоите в группе или у него включен режим призыв) при применении способности переместиться. Чтобы работало как переход и призвать, вне зависимости от уровня того кто применяет.

**Comment by Svjatovit** [comment]
В общем-то это было сделано, чтобы не подводили к врагам трешей и не пуфались на них. Сейчас войн и ПК толком нет, потому неактуально, но может и снова стать актуальным. Так что думайте, точно ли надо снимать ограничение.

**Comment by bylins** [comment]
Лучше снять, больше мороки в игре чем бонусов

**Comment by Svjatovit** [comment]
Сделано.
