### ISSUE TITLE
Косяки с пуржем, если коротко спуржил иммом сумку потом пришлось пуржить содержимое с земли

### ISSUE THREAD

**Issue by bylins** [bylins/mud#880]
987H 179M ??? Зауч:0 34L 5064757G Вых:СВЮv> purge
Мир стал немного чище.

987H 179M ??? Зауч:0 34L 5064757G Вых:СВЮv> см

[  100] Тронный зал [внутри;нет магии;арена;телепортация из комнаты запрещена;внепогодная;не переместиться;всегда светло]
   Величественные мраморные колонны уходят ввысь, подпирая самое небо. На стенах, отделанных редчайшими сортами мрамора красуются барельефы, изображающие
бытие обитателей замка - охоту на Жар-Птицу, воскрешение Змея Горыныча, зверски
изрубленного Ильей Муромцем после очередной попойки, пленение Змея Тугарина и
многое другое. В центре зала - огромный дубовый стол, покрытый
скатертью-самобранкой.  
[ Exits: n E s d ]
[  723] У ваших ног лежит глиняная плошка.
[  712] Немного отрубей просыпано здесь.
[  724] Лужица дождевой воды разлита у ваших ног.
[75939] Берестяной свиток пылится на полу тут. [4]

**Comment by Svjatovit** [comment]
Это не ошибка. Пурж просто удаляет предметы и мобов из комнаты. А удаление контейнера именно так и выглядит - удаляется сам контейнер, а его содержимое перемещается в комнату или на руки державшему сумку. Можно, конечно, сделать рекурсивное удаление контейнеров вместе с содержимым, но нужно ли?
