### ISSUE TITLE
режим призвать

### ISSUE THREAD

**Issue by pilaty** [bylins/mud#884]
доработка режима призвать на: реж призвать да и реж призвать нет
+добавление строчки в табличке группы у кого режим включен/выключен

**Comment by bylins** [comment]
поставь всем триггер на счет все
Вы можете быть призваны.
чтоб отвечали в гг

**Comment by Svjatovit** [comment]
Вот делать нечего, только еще ботоводам жизнь облегчать...  Давайте тогда уж сразу онлайн-игрушку для программистов сделаем, состязание ботов.
