### ISSUE TITLE
Ошибка в работе vnum t

### ISSUE THREAD

**Issue by vredomir** [bylins/mud#889]
Если несколько мест лоада, то vnum t показывает не правильные тригеры, например ищем книгу небес:

vnum tri 546
  1. [76107] медведь принимает квест
  2. [90061] Tree <Вернулись к принцессе>
  3. [90136] Tree <Вернулись к принцессе>

По факту лоадят всего 2 тригера 76110 и 90065

**Comment by Svjatovit** [comment]
Структура, хранившая список соответствия триггеров и загружаемых объектов, хранила rnum триггеров вместо vnum, Но rnum - это индекс экземпляров, а не прототипов. Триггеров с одним внумом может быть более одного, на разных мобах, на разных комнатах и так далее, каждый будет получать свой rnum. Поэтому при старте мада команда будет работать нормально, но после нескольких перезагрузок зон с таким использованием триггеров индексы "сползут" и команда начнет показывать какие попало триггера, чаще соседние или из соседних зон. Заменил все на использование vnum, который уникален для прототипа.

Нужно отметить, что это полумеры, потому что структура заполняется парсингом триггеров на старте мада и не хранит ни новые триггера, ни триггера, где номер загружаемого объекта не написан явно, а подставляется из переменной (типа wload obj %var%). По-хорошему, нужны нормальные таблицы загрузки для квестов, мобов и контейнеров и уже из них подобная команда должна брать информацию. Тогда все будет работать как надо. Однако это довольно сложная задача...

Пофиксил, залил. После после теста, если все нормально, задачу закрыть.

**Comment by Svjatovit** [comment]
Вроде бы исправлено.
