### ISSUE TITLE
Дописать новые суффиксы форматирования в справку по DG.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#901]
В справке по DG Script не отражены все суффиксы, которые можно использовать для форматирования строк 
Функция:
void perform_act(const char *orig, CHAR_DATA * ch, const OBJ_DATA* obj, const void *vict_obj, CHAR_DATA * to, const int arena, const std::string& kick_type)
(comm.cpp: 3819)

Нужно дописать их описание в справку.

**Comment by bylins** [comment]
добавил в описание dg

char.r | строка | ым/ой/ыми | Суффикс
char.x | строка | ое/ой/ая/ие | Суффикс
