### ISSUE TITLE
Следование мобов с прописанным путём

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#917]
Если у мобов прописан пересекающийся путь, и не слишком отличаются наклонности, они начинают следовать друг за другом. Это мешает прописывать мобам пути без натыкивания везде флагов !моб. По идее этому должен препятствовать флаг !вступает_в_группу но мобы его почему-то игнорируют. Надо исправить.

**Comment by bylins** [comment]
у нас еще есть флаг орда, надо посмотреть как работает

**Comment by bylins** [comment]
Сделали по другому, только орда группится
