### ISSUE TITLE
Проверить, насколько реально снять кап в 200 с оружейных умений.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#928]
Собственно субж. Подозреваю, что главная пробелма будет с прокачкой, которая зачем-то, кажется. учитывает макспроцент. Если можно снять без переписывания половины механики скиллов, то сделать.

**Comment by bylins** [comment]
проблема не в прокачке а в том что в формулах фигурирует max_percent
тот же глуш, молот виды прохождения умелки зависят от него
тот кто двинул ползунок до 200 оригинален, max_percent и формулы оставил старые

**Comment by bylins** [comment]
вообще во всех формулах прохождения даже в тех в которых действие одно, все равно бросок на прохождение учитывает max_percent
а вот на кач никак он не влияет, увеличь переменную CAP_SKILLS и будет тебе счастье

**Comment by Svjatovit** [comment]
> 
> 
> а вот на кач никак он не влияет, увеличь переменную CAP_SKILLS и будет тебе счастье

Я пока хочу снять кап только с оружейных скиллов.

**Comment by bylins** [comment]
в skillo введи поле капскилла

**Comment by Svjatovit** [comment]
Сделано. Попутно проторена дорожка к возможности снять капы с остальных скиллов.
