### ISSUE TITLE
Для пустых ёмкостей отображать состояние, аналогично контейнерам.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#931]
i31 927H 330M ??? Зауч:0 34L 100000G Вых:СВЮv> лить бочонок земля
Вы опустошили бочонок с квасом.

i31 927H 330M ??? Зауч:0 34L 100000G Вых:СВЮv> ин
Вы несете:
бочонок  <великолепно>

Сделать что-то типа бочонок  <великолепно> (пуст)

**Comment by bylins** [comment]
взять за основу
			}
		} else    // item must be a fountain or drink container
		{
			if (GET_OBJ_VAL(obj, 1) <= 0)
				send_to_char("Пусто.\r\n", ch);
			else {
				if (GET_OBJ_VAL(obj, 0) <= 0 || GET_OBJ_VAL(obj, 1) > GET_OBJ_VAL(obj, 0)) {
					sprintf(buf, "Заполнен%s вакуумом?!\r\n", GET_OBJ_SUF_6(obj));    // BUG
				} else {
					const char *msg = AFF_FLAGGED(ch, EAffectFlag::AFF_DETECT_POISON)
										  && obj->get_val(3) == 1 ? "(отравленной)" : "";
					amt = (GET_OBJ_VAL(obj, 1) * 5) / GET_OBJ_VAL(obj, 0);
					sprinttype(GET_OBJ_VAL(obj, 2), color_liquid, buf2);
					snprintf(buf,
							 MAX_STRING_LENGTH,
							 "Наполнен%s %s%s%s жидкостью.\r\n",
							 GET_OBJ_SUF_6(obj),
							 fullness[amt],
							 buf2,
							 msg);
				}
				send_to_char(buf, ch);
			}
		}
