### ISSUE TITLE
Затирание !рунной метки! согрупника.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#933]
Убрать установку БД при таком затирании.

**Comment by bylins** [comment]
по идее там штатное пк вызывается, ну влеплю проверку на группу

**Comment by bylins** [comment]
//Ищем кастера по миру
				caster = find_char(aff->caster_id);
				//Если кастер онлайн - выдаем деятелю БД как за воровство
				if (caster)
				{
					pk_thiefs_action(ch, caster);
					sprintf(buf, "Послышался далекий звук лопнувшей струны, и перед вами промельнул призрачный облик %s.\r\n", GET_PAD(ch, 1));
					send_to_char(buf, caster);
				}
поменять проверку на:
if (caster && !same_group(ch, caster))

**Comment by bylins** [comment]
можно добавить конечно и чармисов конечно проверять, 
if (caster && !same_group(ch->get_master(), caster))
