### ISSUE TITLE
Исправить несколько мелких ошибок.

### ISSUE THREAD

**Issue by Svjatovit** [bylins/mud#941]
1. Команда "мсписок" доступна смертным - непорядок. 
^ исправлено
2. При пинке с коня не учитывается пол, всегда "если он выживет".
^ исправлено
3. "Сражение верхом" сбрасывается при каждом реморте, а не при  #каждом третьем.
^ исправлено
4. У купцов способность "знаток" почему-то не уменьшает время перезарядки опознания (возможно, перекрывается какими-то купеческими - сначала проверить).

**Comment by bylins** [comment]
p3 уже исправлен 
class.cpp 2062

**Comment by bylins** [comment]
р4
	if (!IS_IMMORTAL(ch))
	{
		timed.skill = SKILL_IDENTIFY;
		timed.time = MAX((can_use_feat(ch, CONNOISEUR_FEAT) ? getModifier(CONNOISEUR_FEAT, FEAT_TIMER) : 12) - ((GET_SKILL(ch, SKILL_IDENTIFY) - 25) / 25),1); //12..5 or 8..1
		timed_to_char(ch, &timed);
	}
вот тут уменьшается, как бы другие перки не учитываются
