### ISSUE TITLE
Show zones

### ISSUE THREAD

**Issue by bylins** [bylins/mud#944]
i5 987H 179M ??? Зауч:0 ОЗ:0 34L 0G Вых:СВЮv> show zones 830
830 Княжья псарня                                                Средний уровень мобов: 29; Type: village             ; Age:   0; 
Reset:  45 (1)(1)
    Top: 83099    ; ResetIdle: N; Занято: N; Активность: 2.18; Группа:  2; Автор: Не известен., посещено после ребута: 2150
^^^^ это не с ребута

**Comment by bylins** [comment]
во первых поправить топ, теперь get_zone_rooms указывает диапазон клеток правильно исключая виртуалку
ну и посмотреть почему счетчик посещаемости брешет

**Comment by vkhanayev** [comment]
Поправил текст (счетчик посещений сохраняется между ребутами).
Добавил вывод количества репопов зоны с перезагрузки (уже было в статистике, чтоб новых полей не плодить).

**Comment by bylins** [comment]
А как почистить счетчик посещений?

**Comment by vkhanayev** [comment]
нашел только "зоныстат очистить", но оно все удалит.
можно добавить параметром номер зоны для очистки, например - "зоныстат очистить 830"

**Comment by bylins** [comment]
ага делай

**Comment by bylins** [comment]
стоп не получится - дата же изменится только для одной зоны, а она не пишется, так что не надо
