### ISSUE TITLE
Сокращение вертикального текста

### ISSUE THREAD

**Issue by bylins** [bylins/mud#960]
![image](https://user-images.githubusercontent.com/42086238/119513203-ac586280-bd7c-11eb-968e-98a10a08b6bc.png)

**Comment by bylins** [comment]
сделать режим, нет титула
сделать режим, сокращение аур писать правее имени 
ну и тыпы

**Comment by bylins** [comment]
чистая аура - много боков, (ЧА)
Окружен ледяным щитом (ЛЩ)
это как пример

**Comment by yuraigle** [comment]
Мы старались, выдумывали титулы. Мальчиш-Плохиш сражается, сидя на коне.
Пожалуйста не надо это менять на 
"Никас (ДНЗ) бьет моба1 (ЛЩ, ЧА)"

**Comment by dr-hools** [comment]
Ну и покрасить ледщит - не просто ЛЩ 
Можно ЛедЩит и цветами синеголубыми

**Comment by Svjatovit** [comment]
> 
> 
> Мы старались, выдумывали титулы. Мальчиш-Плохиш сражается, сидя на коне. Красиво и по-русски.
> Пожалуйста не надо это менять на
> "Никас (ДНЗ) бьет моба1 (ЛЩ, ЧА)"

Поддерживаю. Не надо первращать мад в калькулятор.
Ладно еще сделать отображение щитов не текстом, а звездочками например, как в бою.
С аурами тоже что-то в этом роже придумать.
Но антуражные названия и титулы убирать не нужно.

**Comment by bylins** [comment]
оки, все против закрываю
