### ISSUE TITLE
	{"forcetime", POS_DEAD, do_forcetime, LVL_IMPL, 0, 0},

### ISSUE THREAD

**Issue by bylins** [bylins/mud#971]
выкинуть нафиг, опасная команда и не нужная от слова совсем

**Comment by Svjatovit** [comment]
Не надо ее выкидывать. Она и так доступна только 34, а иногда пригождается. Например, когда нужно проверить, что какой-то код или триггер корректно отработает в течение 15, скажем, минут. Каждый раз 15 минут ждать или менять константы, определяющие скорость течения внутриигрового времени?

**Comment by bylins** [comment]
ок, хотя я константы меняю :)
