### ISSUE TITLE
корявый парсер[BitBucket]

### ISSUE THREAD

**Issue by bodrich** [bylins/mud#99]
*Originally reported by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

i25 3308H 179M ??? Зауч:0 34L 9741963G Вых:Ю> экип прав.рука  
На вас надето:  
<правый указательный палец> [  160] обручальное кольцо  <великолепно>  
<левый указательный палец>  [  160] обручальное кольцо  <великолепно>  
<в левой руке>              [  110] длинный нож  <очень хорошо>

----------------------------------------
- Bitbucket: https://bitbucket.org/bylins/mud/issue/99

=======COMMENTS=======

Date: 2017-12-23T09:15:47Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

хелп по dg_scripts  
char.eq(pos) UID
Получение предмета экипировки.
pos – позиция (текст или номер
позиции)  
пришлось делать по номеру позиции, так как правая.рука не работает.  И функционал есть в коде, там парсится текст.

Date: 2017-12-22T19:00:10Z

*Original comment by* **Oleksiy Sadovy (Bitbucket: [osadovy](https://bitbucket.org/osadovy), GitHub: [osadovy](https://github.com/osadovy))**

----------------------------------------

А у нас никогда небыло такого функционала, чтобы командой "эк" посмотреть
одетую на определенном слоту шмотку. Есть только `эк` и `эк все`.

Date: 2017-12-22T11:15:46Z

*Original comment by* **Andrey Serdiukov (Bitbucket: [Stribog_](https://bitbucket.org/Stribog_), GitHub: Unknown)**

----------------------------------------

Хотел однако увидеть, что у меня в правой руке. Для игрока это не существенно, а вот в триггерах когда надо проверить что на какой месте одето важно.

Date: 2017-12-22T10:53:44Z

*Original comment by* **Posvist (Bitbucket: [Posvist](https://bitbucket.org/Posvist), GitHub: [Posvist](https://github.com/Posvist))**

----------------------------------------

Можно в описание добавить ожидаемый результат выполнения команды?

**Comment by Svjatovit** [comment]
И в чем проблема посмотреть по номеру позиции?

**Comment by Svjatovit** [comment]
В общем, закрываю. Совершенно никакой надобности смотреть по имени позицию нет. Даже если какой-то дикий изврат с обработкой вводимой игроком команды, не такая проблема перевести ее в номер,
